using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class LivingLedgerRecord
    {
        public int Schema { get; set; }
        public long Sequence { get; set; }
        public string Utc { get; set; }
        public string Event { get; set; }
        public string Subject { get; set; }
        public string Detail { get; set; }
        public string VersionFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public string PrevHash { get; set; }
        public string EntryHash { get; set; }
        public override string ToString() { return Sequence.ToString("000000", CultureInfo.InvariantCulture) + "   ·   " + (Utc ?? "") + "   ·   " + (Event ?? "EVENT") + "   ·   " + (Subject ?? "") + "   ·   " + LivingDocumentKernel.Short(EntryHash); }
    }

    internal sealed class LivingDocumentStore
    {
        public int Schema { get; set; }
        public int Revision { get; set; }
        public string UpdatedUtc { get; set; }
        public List<LivingDocument> Documents { get; set; }
        public List<LivingProjectionReceipt> Projections { get; set; }
        public List<LivingImpactReport> Impacts { get; set; }
        public List<LivingBaseline> Baselines { get; set; }
        public List<LivingPublicationSeal> Seals { get; set; }
        public LivingDocumentStore() { Schema = 1; Documents = new List<LivingDocument>(); Projections = new List<LivingProjectionReceipt>(); Impacts = new List<LivingImpactReport>(); Baselines = new List<LivingBaseline>(); Seals = new List<LivingPublicationSeal>(); }
    }

    internal static class LivingDocumentIntelligenceFactory
    {
        private static readonly object Gate = new object();
        private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = Int32.MaxValue, RecursionLimit = 256 };
        private static readonly Brush Bg = B("#090A0F"), Surface = B("#121722"), Raised = B("#1A2432"), Border = B("#32465D"), Text = B("#F5F7FB"), Muted = B("#98A8BA"), Accent = B("#F2C86B"), Green = B("#70E0A3"), Amber = B("#FFD166"), Danger = B("#FF7A8D"), Violet = B("#C7A5FF"), Cyan = B("#78DDF7");
        private static LivingDocumentStore Store;
        private static string LoadedRoot;
        private const int MaxLedgerRead = 65536;
        private const int MaxDocuments = 128;
        private const int MaxVersionsPerDocument = 96;

        public static void Open(Window owner, DeepSystemsContext ctx)
        {
            if (ctx == null) return; Ensure(ctx); if (Store.Documents.Count == 0) SeedStarter(ctx);
            Window w = W(owner, "YOMI · DEV13.37.26 · LIVING DOCUMENT & INTELLIGENCE FACTORY", 1560, 960);
            DockPanel root = Shell("LIVING DOCUMENT & INTELLIGENCE FACTORY", "Build reports, manuals, research dossiers and specifications whose visible prose remains attached to the evidence, calculations, models, assumptions, objections, requirements and earlier versions underneath it.");
            int versions = Store.Documents.Sum(x => x.Versions == null ? 0 : x.Versions.Count);
            TextBlock status = new TextBlock { Text = "DOCΩ   ·   DEV13.37.26   ·   " + Store.Documents.Count + " documents   ·   " + versions + " immutable versions   ·   " + Store.Projections.Count + " source projections   ·   " + Store.Seals.Count + " publication seals   ·   Ctrl+Alt+L", Foreground = Accent, FontWeight = FontWeights.Bold, Margin = new Thickness(20, 0, 20, 14) }; DockPanel.SetDock(status, Dock.Top); root.Children.Add(status);
            ScrollViewer scroll = new ScrollViewer { VerticalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled }; WrapPanel chambers = new WrapPanel { Margin = new Thickness(12) };

            Portal(chambers, "REG", "DOCUMENT REGISTRY", "Open every retained living report/manual/dossier/specification and descend through its immutable version lineage.", delegate { OpenDocuments(w, ctx); });
            Portal(chambers, "NEW", "NEW INTELLIGENCE WORK", "Create a new provenance-native document with a genesis version, evidence spine and auditable thesis paragraph.", delegate { NewDocument(w, ctx); });
            Portal(chambers, "OUT", "OUTLINE / SECTION ARCHITECTURE", "See the ordered section skeleton and paragraph membership of the active version.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { OpenCollection(w, "OUTLINE · " + d.Title, v.Sections.OrderBy(x => x.Order).Cast<object>().ToList(), "Sections point to stable paragraph identities."); }); });
            Portal(chambers, "WRITE", "PARAGRAPH FORGE", "Add a paragraph by creating a new immutable version. The previous version remains intact and traversable.", delegate { AddParagraph(w, ctx); });
            Portal(chambers, "MICRO", "PARAGRAPH MICROSCOPE", "Choose a paragraph and expose every attached claim, evidence anchor, calculation, model, objection and dependency.", delegate { ParagraphMicroscope(w); });
            Portal(chambers, "CLAIM", "CLAIM GRAPH", "Inspect explicit propositions, support edges, parent claims, assumptions, confidence and challenge links.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { OpenCollection(w, "CLAIM GRAPH · " + d.Title, v.Claims.Cast<object>().ToList(), "Claims are graph nodes, not invisible rhetoric."); }); });
            Portal(chambers, "EVID", "EVIDENCE SPINE", "Content-addressed source anchors preserve civilization, source identity, source fingerprint, locator and confidence.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { OpenCollection(w, "EVIDENCE SPINE · " + d.Title, v.Evidence.Cast<object>().ToList(), "A citation is a locator plus retained source identity/fingerprint; its existence is not proof of truth."); }); });
            Portal(chambers, "INBOX", "SOURCE PROJECTION INBOX", "Evidence receipts arriving from every preceding civilization, held separately until deliberately bound into prose.", delegate { OpenCollection(w, "SOURCE PROJECTION INBOX", Store.Projections.Cast<object>().ToList(), "Projection preserves upstream identity and never transfers authority."); });
            Portal(chambers, "BIND", "BIND SOURCE INTO DOCUMENT", "Attach a projected civilization object to a fresh document version as a fingerprinted evidence anchor.", delegate { BindProjection(w, ctx); });
            Portal(chambers, "CALC", "CALCULATION WORKBENCH", "Retain expression, inputs, output, units, explanation and evidence dependencies next to the prose that uses them.", delegate { AddCalculation(w, ctx); });
            Portal(chambers, "MODEL", "MODEL BINDING VAULT", "Attach models with source fingerprint, assumptions, outputs and limitations rather than flattening them into prose.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { OpenCollection(w, "MODEL BINDINGS · " + d.Title, v.Models.Cast<object>().ToList(), "Model outputs remain distinct from observed evidence."); }); });
            Portal(chambers, "ASM", "ASSUMPTION REGISTRY", "Make hidden premises explicit, status-bearing and evidence-linked.", delegate { AddAssumption(w, ctx); });
            Portal(chambers, "OBJ", "OBJECTION / COUNTERARGUMENT CHAMBER", "Retain the strongest challenge beside the claim it attacks, including status, evidence and resolution.", delegate { AddObjection(w, ctx); });
            Portal(chambers, "REQ", "REQUIREMENT TRACEABILITY", "Specifications keep SHALL/SHOULD requirements connected to claims, evidence and verification links.", delegate { AddRequirement(w, ctx); });
            Portal(chambers, "ADR", "DECISION RECORDS", "Preserve decisions, alternatives considered and the claim/evidence chain that justified the choice at that time.", delegate { AddDecision(w, ctx); });
            Portal(chambers, "DEF", "DEFINITION / GLOSSARY GRAPH", "Pin important terms to stable definitions and their evidence anchors to prevent semantic drift across versions.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { OpenCollection(w, "DEFINITIONS · " + d.Title, v.Definitions.Cast<object>().ToList(), "Definitions are versioned artifacts."); }); });
            Portal(chambers, "DEP", "PARAGRAPH DEPENDENCY CONSTELLATION", "Traverse paragraph-to-paragraph dependencies and find prose whose meaning inherits from upstream sections.", delegate { DependencyConstellation(w); });
            Portal(chambers, "STALE", "STALENESS PROPAGATION ENGINE", "When an upstream source fingerprint changes, create a new version and mark all directly/transitively dependent paragraphs stale.", delegate { StalenessView(w); });
            Portal(chambers, "REV", "SOURCE REVISION RADAR", "Compare repeated projections of the same upstream source and expose fingerprint changes that can invalidate prose.", delegate { SourceRevisionRadar(w); });
            Portal(chambers, "IMPACT", "CHANGE IMPACT TELESCOPE", "Select an evidence/calculation/model/claim and trace the exact claims and paragraphs downstream of it.", delegate { ImpactTelescope(w, ctx); });
            Portal(chambers, "COV", "TRACE COVERAGE HEATMAP", "Quantify supported claims, challenged claims, paragraph claim-trace, freshness and requirement verification.", delegate { Coverage(w); });
            Portal(chambers, "UNSUP", "UNSUPPORTED CLAIM RADAR", "Find assertive claims with no explicit evidence, calculation or model dependency.", delegate { ValidationSubset(w, "UNSUPPORTED CLAIM RADAR", "UNSUPPORTED_CLAIM"); });
            Portal(chambers, "ORPH", "ORPHAN EVIDENCE RADAR", "Find evidence anchors not referenced by any claim or paragraph so the source spine does not silently rot.", delegate { OrphanEvidence(w); });
            Portal(chambers, "OPEN", "OPEN OBJECTION RADAR", "Surface unresolved challenges before they disappear under polished prose.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { OpenCollection(w, "OPEN OBJECTIONS · " + d.Title, v.Objections.Where(x => String.Equals(x.Status, "OPEN", StringComparison.OrdinalIgnoreCase)).Cast<object>().ToList(), "Open objections are retained as first-class intelligence debt."); }); });
            Portal(chambers, "VALID", "CONSISTENCY / TRACE VALIDATOR", "Check broken references, unsupported claims, unverified requirements, model provenance, dependency cycles and fingerprint drift.", delegate { Validate(w); });
            Portal(chambers, "TIME", "VERSION TIME MACHINE", "Every mutation creates a new version; earlier prose and evidence topology remain inspectable instead of overwritten.", delegate { VersionTimeline(w); });
            Portal(chambers, "GEN", "PARAGRAPH GENEALOGY", "Follow a paragraph identity and predecessor link through version history.", delegate { ParagraphGenealogy(w); });
            Portal(chambers, "DIFF", "VERSION DIFF REACTOR", "Compare paragraph/claim additions, removals and fingerprint changes between any two retained versions.", delegate { VersionDiff(w); });
            Portal(chambers, "FORK", "BRANCH / FORK LAB", "Fork an immutable version onto a named branch without mutating the source branch.", delegate { ForkBranch(w, ctx); });
            Portal(chambers, "CHECK", "CHECKPOINT VERSION", "Create a no-content-change snapshot with a reason, giving an investigation a durable resume point.", delegate { Checkpoint(w, ctx); });
            Portal(chambers, "BASE", "IMMUTABLE BASELINES", "Freeze document/version identity and root fingerprint as a named comparison anchor.", delegate { Baseline(w, ctx); });
            Portal(chambers, "FREEZE", "PUBLICATION FREEZE", "Freeze the active version only after structural validation, preserving exactly what was reviewed.", delegate { FreezeVersion(w, ctx); });
            Portal(chambers, "SEAL", "PUBLICATION SEAL", "Bind validated graph fingerprint to rendered artifact fingerprint with warning/error counts and a certificate hash.", delegate { SealPublication(w, ctx); });
            Portal(chambers, "RENDER", "CANONICAL RENDERER", "Render Markdown while embedding paragraph identity, fingerprint and trace metadata beneath the visible prose.", delegate { RenderPreview(w); });
            Portal(chambers, "EXPORT", "REPRODUCIBLE PUBLICATION PACKAGE", "Write Markdown plus a JSON manifest into YOMI data with document/version/source fingerprints and validation results.", delegate { ExportPackage(w, ctx); });
            Portal(chambers, "CERT", "PROVENANCE CERTIFICATE VAULT", "Collect document roots, evidence certificates, baselines, impact reports and publication seals in one addressable surface.", delegate { Certificates(w); });
            Portal(chambers, "LEDGER", "TAMPER-EVIDENT DOCUMENT LEDGER", "Append-only SHA-256 previous-hash chain for document creation, projections, mutations, staleness, baselines and seals.", delegate { Ledger(w, ctx); });
            Portal(chambers, "BRANCH", "BRANCH MAP", "Inspect retained version parentage and branch labels across every document.", delegate { BranchMap(w); });
            Portal(chambers, "SRC", "SOURCE FINGERPRINT ATLAS", "Group upstream source identities and fingerprints across projections and bound evidence.", delegate { SourceFingerprintAtlas(w); });
            Portal(chambers, "REPRO", "REPRODUCIBILITY CAPSULE", "Show the exact graph roots, source fingerprints, calculations, models and validation state required to reproduce a publication review.", delegate { ReproducibilityCapsule(w); });
            Portal(chambers, "REPORT", "REPORT MODE", "Lens for executive findings, evidence density, decisions and unresolved objections.", delegate { ModeLens(w, "REPORT"); });
            Portal(chambers, "MAN", "MANUAL MODE", "Lens for ordered procedures, assumptions, definitions, requirements and evidence-backed operating notes.", delegate { ModeLens(w, "MANUAL"); });
            Portal(chambers, "DOS", "RESEARCH DOSSIER MODE", "Lens for hypotheses/claims, evidence, models, calculations, uncertainty and objections.", delegate { ModeLens(w, "RESEARCH_DOSSIER"); });
            Portal(chambers, "SPEC", "SPECIFICATION MODE", "Lens for requirements, definitions, verification links, decisions and source baselines.", delegate { ModeLens(w, "SPECIFICATION"); });
            Portal(chambers, "EXEC", "EXECUTIVE SUMMARY LENS", "Extract executive-role paragraphs plus thesis claims without severing their underlying trace graph.", delegate { ExecutiveLens(w); });
            Portal(chambers, "MATRIX", "OBJECTION MATRIX", "Claims × objections surface showing where the document has been stress-tested and where it has not.", delegate { ObjectionMatrix(w); });
            Portal(chambers, "KLINE", "CALCULATION LINEAGE", "Calculation → evidence → claim → paragraph descent without treating an arithmetic output as self-justifying.", delegate { CalculationLineage(w); });
            Portal(chambers, "LIMIT", "MODEL LIMITATION RADAR", "Models with missing or thin limitation sets are surfaced before polished prose overstates them.", delegate { ModelLimitationRadar(w); });
            Portal(chambers, "VERIFY", "REQUIREMENT VERIFICATION CROSSWALK", "Requirement → claim → evidence → verification-link crosswalk for specs and manuals.", delegate { RequirementCrosswalk(w); });
            Portal(chambers, "HADAL", "HADAL DOCUMENT DESCENT", "Choose one paragraph and descend through every retained dependency until prose becomes source evidence and lineage.", delegate { HadalDescent(w); });
            Portal(chambers, "DATAΩ", "DATA FOUNDRY WORMHOLE", "Project the active document version as structured traceability data without flattening away its source fingerprints.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { DataFoundry.OpenFromLivingDocumentVersion(w, ctx, d, v); }); });
            Portal(chambers, "GENOMEΩ", "SOFTWARE GENOME WORMHOLE", "Project a specification/report version into software-change context as requirements and documentary evidence, never executable code.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { SoftwareGenomeObservatory.OpenFromLivingDocumentVersion(w, ctx, d, v); }); });
            Portal(chambers, "EXPΩ", "GRAND UNIFIED EXPEDITION COMMAND", "Capture the active document version into a durable cross-civilization mission worldline without flattening its provenance graph.", delegate { WithVersion(w, delegate(LivingDocument d, LivingVersion v) { GrandUnifiedExpeditionCommand.OpenFromLivingDocumentVersion(w, ctx, d, v); }); });
            Portal(chambers, "WORM", "RETURN WORMHOLES", "Cross directly into every preceding civilization while the living document and its version graph remain retained.", delegate { OpenReturnWormholes(w, ctx); });
            Portal(chambers, "ATLAS", "DEEP SYSTEMS ATLAS", "Return to the recursive civilization lattice without closing the intelligence factory.", delegate { DeepSystems.OpenAtlasFromContext(w); });

            scroll.Content = chambers; root.Children.Add(scroll); w.Content = root; w.Show();
        }

        public static void OpenFromWorldNode(Window owner, DeepSystemsContext ctx, WorldIndex index, string nodeId) { if (index == null || String.IsNullOrWhiteSpace(nodeId)) { Open(owner, ctx); return; } WorldNode source; if (!index.Nodes.TryGetValue(nodeId, out source)) { Open(owner, ctx); return; } Project(owner, ctx, "WORLD", source, nodeId, "World object supplied as source context for evidence-backed prose."); }
        public static void OpenFromCivilResolution(Window owner, DeepSystemsContext ctx, WorldIndex index, CivilResolution source) { Project(owner, ctx, "CIVILIZATION", source, ReadId(source), "Governance resolution supplied as a citable institutional source."); }
        public static void OpenFromLogicTheory(Window owner, DeepSystemsContext ctx, WorldIndex index, LogicTheory source) { Project(owner, ctx, "EPISTEMIC_LOGIC", source, ReadId(source), "Theory supplied as explicit assumptions, propositions and epistemic context."); }
        public static void OpenFromVerificationModel(Window owner, DeepSystemsContext ctx, WorldIndex index, VerificationModel source) { Project(owner, ctx, "VERIFICATION", source, ReadId(source), "Verification model supplied as behavioral and proof evidence."); }
        public static void OpenFromStrategyModel(Window owner, DeepSystemsContext ctx, WorldIndex index, StrategyModel source) { Project(owner, ctx, "STRATEGY", source, ReadId(source), "Counterfactual strategy supplied as decision/model context."); }
        public static void OpenFromDiscoveryProtocol(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol source) { Project(owner, ctx, "SCIENTIFIC_DISCOVERY", source, ReadId(source), "Discovery protocol supplied as preregistered research evidence."); }
        public static void OpenFromEngineeringArchitecture(Window owner, DeepSystemsContext ctx, WorldIndex index, EngineeringArchitecture source) { Project(owner, ctx, "SYSTEMS_ENGINEERING", source, ReadId(source), "Engineering architecture supplied as requirements/design evidence."); }
        public static void OpenFromCyberneticTwin(Window owner, DeepSystemsContext ctx, WorldIndex index, CyberTwinModel source) { Project(owner, ctx, "CYBERNETIC_TWIN", source, ReadId(source), "Digital twin supplied as model evidence with control/runtime assumptions."); }
        public static void OpenFromComplexSystem(Window owner, DeepSystemsContext ctx, WorldIndex index, ComplexSystemModel source) { Project(owner, ctx, "COMPLEX_SYSTEMS", source, ReadId(source), "Complex-system model supplied as emergence/simulation evidence."); }
        public static void OpenFromOperationsResearchModel(Window owner, DeepSystemsContext ctx, WorldIndex index, OperationsResearchModel source) { Project(owner, ctx, "OPERATIONS_RESEARCH", source, ReadId(source), "Optimization model supplied as calculation/model evidence."); }
        public static void OpenFromEconomicModel(Window owner, DeepSystemsContext ctx, WorldIndex index, EconomicModel source) { Project(owner, ctx, "ECONOMIC_CIVILIZATION", source, ReadId(source), "Economic model supplied as domain/model evidence."); }
        public static void OpenFromSpatialWorld(Window owner, DeepSystemsContext ctx, WorldIndex index, SpatialWorldModel source) { Project(owner, ctx, "SPATIAL_CARTOGRAPHY", source, ReadId(source), "Spatial world supplied as topology/geographic evidence."); }
        public static void OpenFromDistributedSystem(Window owner, DeepSystemsContext ctx, WorldIndex index, DistributedSystemModel source) { Project(owner, ctx, "DISTRIBUTED_SYSTEMS", source, ReadId(source), "Distributed-system model supplied as service/consistency/failure evidence."); }
        public static void OpenFromSecurityModel(Window owner, DeepSystemsContext ctx, WorldIndex index, SecurityModel source) { Project(owner, ctx, "ADVERSARIAL_SECURITY", source, ReadId(source), "Defensive-security model supplied as trust/control/risk evidence."); }
        public static void OpenFromDataDataset(Window owner, DeepSystemsContext ctx, DataDataset source) { Project(owner, ctx, "DATA_FOUNDRY", source, ReadId(source), "Dataset supplied as provenance-bound empirical evidence."); }
        public static void OpenFromSoftwareGenomeSnapshot(Window owner, DeepSystemsContext ctx, GenomeSnapshot source) { Project(owner, ctx, "SOFTWARE_GENOME", source, ReadId(source), "Codebase genome supplied as static architecture/change evidence."); }
        public static void OpenFromExpeditionMission(Window owner, DeepSystemsContext ctx, ExpeditionMission source) { Project(owner, ctx, "GRAND_UNIFIED_EXPEDITION", source, source == null ? "UNKNOWN" : source.Id, "Expedition mission supplied as provenance-bound synthesis source with retained branches, crossings, findings, contradictions and checkpoints."); }

        private static void Project(Window owner, DeepSystemsContext ctx, string civilization, object source, string sourceId, string rule)
        {
            if (ctx == null || source == null) return; ExpeditionWorkspace.Visit(ctx, "documents", civilization + " projection", rule); Ensure(ctx); string fp = HashObject(source); string sid = String.IsNullOrWhiteSpace(sourceId) ? "UNKNOWN" : sourceId;
            LivingProjectionReceipt prior = Store.Projections.FirstOrDefault(x => String.Equals(x.Civilization, civilization, StringComparison.OrdinalIgnoreCase) && String.Equals(x.SourceId, sid, StringComparison.OrdinalIgnoreCase));
            LivingProjectionReceipt r = new LivingProjectionReceipt { Id = LivingDocumentKernel.NewId("PROJ"), Civilization = civilization, SourceId = sid, SourceFingerprint = fp, Rule = rule }; r.CertificateHash = LivingDocumentKernel.HashText(r.Civilization + "|" + r.SourceId + "|" + r.SourceFingerprint + "|" + r.Rule); Store.Projections.Insert(0, r); Trim(Store.Projections, 4096);
            int stale = 0; if (prior != null && !String.Equals(prior.SourceFingerprint, fp, StringComparison.OrdinalIgnoreCase)) stale = PropagateSourceRevision(civilization, sid, prior.SourceFingerprint, fp);
            Save(ctx); AppendLedger(ctx, "PROJECTION", sid, civilization + " → DOCΩ" + (stale > 0 ? "; " + stale + " paragraphs marked stale in new versions" : ""), "", r.CertificateHash); Open(owner, ctx);
        }

        private static int PropagateSourceRevision(string civilization, string sourceId, string oldFp, string newFp)
        {
            int total = 0; foreach (LivingDocument d in Store.Documents.ToList()) { LivingVersion current = LivingDocumentKernel.Current(d); if (current == null) continue; bool references = current.Evidence.Any(x => String.Equals(x.SourceCivilization, civilization, StringComparison.OrdinalIgnoreCase) && String.Equals(x.SourceId, sourceId, StringComparison.OrdinalIgnoreCase) && String.Equals(x.SourceFingerprint, oldFp, StringComparison.OrdinalIgnoreCase)); if (!references) continue; LivingVersion next = CloneVersion(d, current, "Upstream source fingerprint changed: " + civilization + "/" + sourceId, current.Branch); int changed = LivingDocumentKernel.MarkSourceFingerprintChanged(next, civilization, sourceId, oldFp, newFp); if (changed > 0) { CommitVersion(d, next); total += changed; } }
            return total;
        }

        private static void OpenDocuments(Window owner, DeepSystemsContext ctx)
        {
            Ensure(ctx); Window w = W(owner, "YOMI · LIVING DOCUMENT REGISTRY", 1420, 860); DockPanel root = Shell("LIVING DOCUMENT REGISTRY", "Double-click a document to inspect its current version and complete lineage."); ListBox list = List(); list.ItemsSource = Store.Documents; list.MouseDoubleClick += delegate { LivingDocument d = list.SelectedItem as LivingDocument; if (d != null) OpenDocument(w, ctx, d); }; root.Children.Add(list); w.Content = root; w.Show();
        }

        private static void OpenDocument(Window owner, DeepSystemsContext ctx, LivingDocument d)
        {
            LivingVersion v = LivingDocumentKernel.Current(d); if (v == null) return; Window w = W(owner, "YOMI · DOCΩ · " + d.Title, 1480, 900); DockPanel root = Shell(d.Title, (d.Kind ?? "DOCUMENT") + "   ·   " + (d.Objective ?? "")); TextBlock meta = new TextBlock { Text = "document " + d.Id + "   ·   current v" + v.Number + "   ·   " + v.Branch + "   ·   fp " + LivingDocumentKernel.Short(v.RootFingerprint) + "   ·   " + v.Paragraphs.Count + " paragraphs   ·   " + v.Claims.Count + " claims   ·   " + v.Evidence.Count + " evidence anchors", Foreground = Accent, Margin = new Thickness(20, 0, 20, 10), TextWrapping = TextWrapping.Wrap }; DockPanel.SetDock(meta, Dock.Top); root.Children.Add(meta); WrapPanel p = new WrapPanel { Margin = new Thickness(14) };
            SmallPortal(p, "PARAGRAPHS", delegate { OpenCollection(w, "PARAGRAPHS · " + d.Title, v.Paragraphs.Cast<object>().ToList(), "Visible prose surface."); }); SmallPortal(p, "CLAIMS", delegate { OpenCollection(w, "CLAIMS · " + d.Title, v.Claims.Cast<object>().ToList(), "Explicit proposition graph."); }); SmallPortal(p, "EVIDENCE", delegate { OpenCollection(w, "EVIDENCE · " + d.Title, v.Evidence.Cast<object>().ToList(), "Content-addressed source spine."); }); SmallPortal(p, "VERSIONS", delegate { OpenCollection(w, "VERSIONS · " + d.Title, d.Versions.OrderByDescending(x => x.Number).Cast<object>().ToList(), "Immutable history."); }); SmallPortal(p, "VALIDATE", delegate { OpenCollection(w, "VALIDATION · " + d.Title, LivingDocumentKernel.Validate(v).Cast<object>().ToList(), "Current graph integrity."); }); SmallPortal(p, "RENDER", delegate { TextView(w, "CANONICAL RENDER · " + d.Title, LivingDocumentKernel.RenderMarkdown(d, v)); }); SmallPortal(p, "WORLD SPINE", delegate { WorldPassportSpine.CaptureAndOpen(w, ctx, d.Title + " · v" + v.Number.ToString(CultureInfo.InvariantCulture), "LIVING_DOCUMENT_VERSION", "DOCΩ", "documents", v.Id, v, "", "$document/" + d.Id + "/version/" + v.Id); });
            root.Children.Add(new ScrollViewer { Content = p, VerticalScrollBarVisibility = ScrollBarVisibility.Auto }); w.Content = root; w.Show();
        }

        private static void NewDocument(Window owner, DeepSystemsContext ctx)
        {
            string title = Prompt(owner, "NEW INTELLIGENCE WORK", "Document title:", "Untitled intelligence dossier"); if (title == null) return; string kind = Prompt(owner, "DOCUMENT KIND", "REPORT, MANUAL, RESEARCH_DOSSIER or SPECIFICATION:", "RESEARCH_DOSSIER"); if (kind == null) return; LivingDocument d = LivingDocumentKernel.Starter(title, kind); Store.Documents.Insert(0, d); Trim(Store.Documents, MaxDocuments); Save(ctx); LivingVersion v = LivingDocumentKernel.Current(d); AppendLedger(ctx, "DOCUMENT_GENESIS", d.Id, d.Title + " · " + d.Kind, v == null ? "" : v.RootFingerprint, ""); OpenDocument(owner, ctx, d);
        }

        private static void AddParagraph(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null || cur.Frozen) { MessageBox.Show(owner, "The active version is frozen. Fork/checkpoint first.", "YOMI · DOCΩ", MessageBoxButton.OK, MessageBoxImage.Information); return; }
            string heading = Prompt(owner, "PARAGRAPH FORGE", "Paragraph heading:", "New finding"); if (heading == null) return; string text = Prompt(owner, "PARAGRAPH FORGE", "Paragraph text:", ""); if (text == null) return; LivingVersion next = CloneVersion(d, cur, "Add paragraph: " + heading, cur.Branch); LivingParagraph p = new LivingParagraph { Id = LivingDocumentKernel.NewId("PARA"), Heading = heading, Text = text, Role = "BODY" };
            if (next.Evidence.Count > 0) p.EvidenceIds.Add(next.Evidence[0].Id); LivingClaim c = new LivingClaim { Id = LivingDocumentKernel.NewId("CLAIM"), Text = text, Kind = "ASSERTION", Confidence = next.Evidence.Count > 0 ? 0.65 : 0.35 }; if (next.Evidence.Count > 0) c.EvidenceIds.Add(next.Evidence[0].Id); c.CertificateHash = LivingDocumentKernel.FingerprintClaim(c); next.Claims.Add(c); p.ClaimIds.Add(c.Id); p.CertificateHash = LivingDocumentKernel.FingerprintParagraph(p); next.Paragraphs.Add(p); LivingSection s = next.Sections.OrderBy(x => x.Order).LastOrDefault(); if (s == null) { s = new LivingSection { Id = LivingDocumentKernel.NewId("SEC"), Title = "Body", Order = 1 }; next.Sections.Add(s); } s.ParagraphIds.Add(p.Id); next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "PARAGRAPH_ADD", p.Id, d.Title + " v" + next.Number + " · " + heading, next.RootFingerprint, p.CertificateHash); OpenDocument(owner, ctx, d);
        }

        private static void BindProjection(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null || Store.Projections.Count == 0) return; LivingProjectionReceipt r = Choose<LivingProjectionReceipt>(owner, "Choose source projection", Store.Projections); if (r == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null || cur.Frozen) return; LivingVersion next = CloneVersion(d, cur, "Bind source projection " + r.Civilization + "/" + r.SourceId, cur.Branch); LivingEvidenceAnchor e = new LivingEvidenceAnchor { Id = LivingDocumentKernel.NewId("EVID"), SourceCivilization = r.Civilization, SourceId = r.SourceId, SourceFingerprint = r.SourceFingerprint, Locator = "projection://" + r.Civilization + "/" + r.SourceId, Label = r.Civilization + " · " + r.SourceId, Excerpt = r.Rule, Authority = "UPSTREAM_PROJECTION", Confidence = 1.0 }; e.CertificateHash = LivingDocumentKernel.HashText(e.Id + "|" + e.SourceCivilization + "|" + e.SourceId + "|" + e.SourceFingerprint + "|" + e.Excerpt); next.Evidence.Insert(0, e); next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "EVIDENCE_BIND", e.Id, d.Title + " ← " + r.Civilization + "/" + r.SourceId, next.RootFingerprint, e.CertificateHash); OpenCollection(owner, "SOURCE BOUND", new List<object> { e }, "A new document version now contains the fingerprinted source anchor.");
        }

        private static void AddCalculation(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null || cur.Frozen) return; string name = Prompt(owner, "CALCULATION", "Name:", "Derived measure"); if (name == null) return; string expression = Prompt(owner, "CALCULATION", "Expression (retained text; not executed):", "a / b"); if (expression == null) return; string output = Prompt(owner, "CALCULATION", "Recorded output:", ""); if (output == null) return; LivingVersion next = CloneVersion(d, cur, "Add calculation: " + name, cur.Branch); LivingCalculation c = new LivingCalculation { Id = LivingDocumentKernel.NewId("CALC"), Name = name, Expression = expression, Output = output, Explanation = "User-recorded calculation artifact. DOCΩ retains lineage but does not execute arbitrary expressions." }; if (next.Evidence.Count > 0) c.EvidenceIds.Add(next.Evidence[0].Id); c.CertificateHash = LivingDocumentKernel.HashText(c.Id + "|" + c.Name + "|" + c.Expression + "|" + c.Output + "|" + String.Join(",", c.EvidenceIds.ToArray())); next.Calculations.Insert(0, c); next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "CALCULATION_ADD", c.Id, d.Title + " · " + c.Name, next.RootFingerprint, c.CertificateHash); OpenCollection(owner, "CALCULATION CREATED", new List<object> { c }, "Expression is retained as evidence; arbitrary code is never evaluated.");
        }

        private static void AddAssumption(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null || cur.Frozen) return; string text = Prompt(owner, "ASSUMPTION", "Assumption:", ""); if (text == null) return; LivingVersion next = CloneVersion(d, cur, "Add assumption", cur.Branch); LivingAssumption a = new LivingAssumption { Id = LivingDocumentKernel.NewId("ASM"), Text = text, Status = "OPEN", Rationale = "Explicitly retained premise" }; if (next.Evidence.Count > 0) a.EvidenceIds.Add(next.Evidence[0].Id); a.CertificateHash = LivingDocumentKernel.HashText(a.Id + "|" + a.Text + "|" + String.Join(",", a.EvidenceIds.ToArray())); next.Assumptions.Insert(0, a); next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "ASSUMPTION_ADD", a.Id, a.Text, next.RootFingerprint, a.CertificateHash);
        }

        private static void AddObjection(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null || cur.Claims.Count == 0 || cur.Frozen) return; LivingClaim selected = Choose<LivingClaim>(owner, "Choose challenged claim", cur.Claims); if (selected == null) return; string text = Prompt(owner, "OBJECTION", "Strongest objection/counterargument:", ""); if (text == null) return; LivingVersion next = CloneVersion(d, cur, "Add objection to " + selected.Id, cur.Branch); LivingClaim c = next.Claims.First(x => x.Id == selected.Id); LivingObjection o = new LivingObjection { Id = LivingDocumentKernel.NewId("OBJ"), TargetClaimId = c.Id, Position = text, Severity = "MATERIAL", Status = "OPEN" }; if (next.Evidence.Count > 0) o.EvidenceIds.Add(next.Evidence[0].Id); o.CertificateHash = LivingDocumentKernel.HashText(o.Id + "|" + o.TargetClaimId + "|" + o.Position + "|" + String.Join(",", o.EvidenceIds.ToArray())); next.Objections.Insert(0, o); if (!c.ObjectionIds.Contains(o.Id)) c.ObjectionIds.Add(o.Id); c.CertificateHash = LivingDocumentKernel.FingerprintClaim(c); next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "OBJECTION_ADD", o.Id, "claim " + c.Id, next.RootFingerprint, o.CertificateHash);
        }

        private static void AddRequirement(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null || cur.Frozen) return; string text = Prompt(owner, "REQUIREMENT", "Requirement:", "The system SHALL "); if (text == null) return; LivingVersion next = CloneVersion(d, cur, "Add requirement", cur.Branch); LivingRequirement q = new LivingRequirement { Id = LivingDocumentKernel.NewId("REQ"), Text = text, Level = "SHALL", Status = "OPEN" }; if (next.Evidence.Count > 0) q.EvidenceIds.Add(next.Evidence[0].Id); if (next.Claims.Count > 0) q.ClaimIds.Add(next.Claims[0].Id); q.CertificateHash = LivingDocumentKernel.HashText(q.Id + "|" + q.Text + "|" + String.Join(",", q.ClaimIds.ToArray()) + "|" + String.Join(",", q.EvidenceIds.ToArray())); next.Requirements.Insert(0, q); next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "REQUIREMENT_ADD", q.Id, q.Text, next.RootFingerprint, q.CertificateHash);
        }

        private static void AddDecision(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null || cur.Frozen) return; string title = Prompt(owner, "DECISION RECORD", "Decision title:", "Decision"); if (title == null) return; string decision = Prompt(owner, "DECISION RECORD", "Decision:", ""); if (decision == null) return; LivingVersion next = CloneVersion(d, cur, "Add decision record: " + title, cur.Branch); LivingDecisionRecord a = new LivingDecisionRecord { Id = LivingDocumentKernel.NewId("ADR"), Title = title, Decision = decision }; if (next.Claims.Count > 0) a.ClaimIds.Add(next.Claims[0].Id); if (next.Evidence.Count > 0) a.EvidenceIds.Add(next.Evidence[0].Id); a.CertificateHash = LivingDocumentKernel.HashText(a.Id + "|" + a.Title + "|" + a.Decision + "|" + String.Join(",", a.ClaimIds.ToArray())); next.Decisions.Insert(0, a); next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "DECISION_ADD", a.Id, a.Title, next.RootFingerprint, a.CertificateHash);
        }

        private static void ParagraphMicroscope(Window owner)
        {
            WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { LivingParagraph p = Choose<LivingParagraph>(owner, "Choose paragraph", v.Paragraphs); if (p == null) return; List<object> rows = new List<object> { p }; rows.AddRange(v.Claims.Where(x => p.ClaimIds.Contains(x.Id)).Cast<object>()); rows.AddRange(v.Evidence.Where(x => p.EvidenceIds.Contains(x.Id) || v.Claims.Where(c => p.ClaimIds.Contains(c.Id)).Any(c => c.EvidenceIds.Contains(x.Id))).Cast<object>()); rows.AddRange(v.Calculations.Where(x => p.CalculationIds.Contains(x.Id) || v.Claims.Where(c => p.ClaimIds.Contains(c.Id)).Any(c => c.CalculationIds.Contains(x.Id))).Cast<object>()); rows.AddRange(v.Models.Where(x => p.ModelIds.Contains(x.Id) || v.Claims.Where(c => p.ClaimIds.Contains(c.Id)).Any(c => c.ModelIds.Contains(x.Id))).Cast<object>()); rows.AddRange(v.Objections.Where(x => p.ObjectionIds.Contains(x.Id) || v.Claims.Where(c => p.ClaimIds.Contains(c.Id)).Any(c => c.ObjectionIds.Contains(x.Id))).Cast<object>()); OpenCollection(owner, "PARAGRAPH MICROSCOPE · " + p.Heading, rows, "Visible prose first, then every retained dependency beneath it."); });
        }

        private static void DependencyConstellation(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = new List<object>(); foreach (LivingParagraph p in v.Paragraphs) foreach (string dep in p.DependsOnParagraphIds) rows.Add(p.Id + "   →   " + dep + "   ·   " + p.Heading); OpenCollection(owner, "PARAGRAPH DEPENDENCIES · " + d.Title, rows, "Explicit dependency edges only."); }); }
        private static void StalenessView(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { OpenCollection(owner, "STALE PARAGRAPHS · " + d.Title, v.Paragraphs.Where(x => x.Stale).Cast<object>().ToList(), "Staleness is propagated from changed bound source fingerprints and explicit paragraph dependencies."); }); }
        private static void SourceRevisionRadar(Window owner) { List<object> rows = new List<object>(); foreach (IGrouping<string,LivingProjectionReceipt> g in Store.Projections.GroupBy(x => (x.Civilization ?? "") + "|" + (x.SourceId ?? ""), StringComparer.OrdinalIgnoreCase)) { List<LivingProjectionReceipt> xs = g.OrderByDescending(x => x.CreatedUtc).ToList(); if (xs.Select(x => x.SourceFingerprint).Distinct(StringComparer.OrdinalIgnoreCase).Count() > 1) rows.Add(g.Key + "   ·   " + xs.Count + " projections   ·   " + xs.Select(x => LivingDocumentKernel.Short(x.SourceFingerprint)).Distinct().Count() + " fingerprints"); } OpenCollection(owner, "SOURCE REVISION RADAR", rows, "Repeated source identity with changed fingerprints is a first-class change signal."); }

        private static void ImpactTelescope(Window owner, DeepSystemsContext ctx)
        {
            WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { if (v.Evidence.Count == 0) return; LivingEvidenceAnchor e = Choose<LivingEvidenceAnchor>(owner, "Choose evidence source", v.Evidence); if (e == null) return; LivingImpactReport r = LivingDocumentKernel.Impact(v, "EVIDENCE", e.Id); Store.Impacts.Insert(0, r); Trim(Store.Impacts, 4096); Save(ctx); AppendLedger(ctx, "IMPACT", r.Id, d.Title + " · evidence " + e.Id, v.RootFingerprint, r.CertificateHash); List<object> rows = new List<object> { r }; rows.AddRange(r.Claims.Cast<object>()); rows.AddRange(r.Paragraphs.Cast<object>()); rows.AddRange(r.Reasons.Cast<object>()); OpenCollection(owner, "CHANGE IMPACT · " + e.Label, rows, "Exact explicit dependency cone."); });
        }

        private static void Coverage(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = LivingDocumentKernel.Coverage(v).OrderBy(x => x.Key).Select(x => (object)(x.Key + "   ·   " + x.Value.ToString("P1", CultureInfo.InvariantCulture))).ToList(); OpenCollection(owner, "TRACE COVERAGE · " + d.Title, rows, "Coverage measures explicit graph linkage, not truth or writing quality."); }); }
        private static void ValidationSubset(Window owner, string title, string kind) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { OpenCollection(owner, title + " · " + d.Title, LivingDocumentKernel.Validate(v).Where(x => String.Equals(x.Kind, kind, StringComparison.OrdinalIgnoreCase)).Cast<object>().ToList(), "Structural validation subset."); }); }
        private static void OrphanEvidence(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { HashSet<string> used = new HashSet<string>(v.Paragraphs.SelectMany(x => x.EvidenceIds).Concat(v.Claims.SelectMany(x => x.EvidenceIds)).Concat(v.Calculations.SelectMany(x => x.EvidenceIds)).Concat(v.Assumptions.SelectMany(x => x.EvidenceIds)).Concat(v.Objections.SelectMany(x => x.EvidenceIds)).Concat(v.Requirements.SelectMany(x => x.EvidenceIds)), StringComparer.Ordinal); OpenCollection(owner, "ORPHAN EVIDENCE · " + d.Title, v.Evidence.Where(x => !used.Contains(x.Id)).Cast<object>().ToList(), "Unused evidence is not deleted automatically."); }); }
        private static void Validate(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { OpenCollection(owner, "VALIDATION · " + d.Title, LivingDocumentKernel.Validate(v).Cast<object>().ToList(), "Validator checks graph integrity and provenance hygiene; it does not declare prose true."); }); }
        private static void VersionTimeline(Window owner) { LivingDocument d = ChooseDocument(owner); if (d != null) OpenCollection(owner, "VERSION TIME MACHINE · " + d.Title, d.Versions.OrderByDescending(x => x.Number).Cast<object>().ToList(), "Earlier versions are immutable retained states."); }

        private static void ParagraphGenealogy(Window owner) { LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion v = LivingDocumentKernel.Current(d); if (v == null || v.Paragraphs.Count == 0) return; LivingParagraph p = Choose<LivingParagraph>(owner, "Choose paragraph", v.Paragraphs); if (p != null) OpenCollection(owner, "PARAGRAPH GENEALOGY · " + p.Heading, LivingDocumentKernel.ParagraphGenealogy(d, p.Id).Cast<object>().ToList(), "Identity/predecessor chain across versions."); }
        private static void VersionDiff(Window owner) { LivingDocument d = ChooseDocument(owner); if (d == null || d.Versions.Count < 2) return; LivingVersion a = Choose<LivingVersion>(owner, "Choose earlier version", d.Versions.OrderBy(x => x.Number).ToList()); if (a == null) return; LivingVersion b = Choose<LivingVersion>(owner, "Choose later version", d.Versions.OrderBy(x => x.Number).ToList()); if (b == null) return; LivingVersionDiff diff = LivingDocumentKernel.Diff(a, b); List<object> rows = new List<object> { diff }; rows.AddRange(diff.AddedParagraphs.Select(x => (object)("+ PARAGRAPH " + x))); rows.AddRange(diff.RemovedParagraphs.Select(x => (object)("- PARAGRAPH " + x))); rows.AddRange(diff.ChangedParagraphs.Select(x => (object)("~ PARAGRAPH " + x))); rows.AddRange(diff.AddedClaims.Select(x => (object)("+ CLAIM " + x))); rows.AddRange(diff.RemovedClaims.Select(x => (object)("- CLAIM " + x))); rows.AddRange(diff.ChangedClaims.Select(x => (object)("~ CLAIM " + x))); OpenCollection(owner, "VERSION DIFF · " + d.Title, rows, "Identity-aware graph diff."); }

        private static void ForkBranch(Window owner, DeepSystemsContext ctx) { LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null) return; string branch = Prompt(owner, "BRANCH / FORK", "New branch name:", "analysis-branch"); if (branch == null) return; LivingVersion next = CloneVersion(d, cur, "Fork branch " + branch, branch); CommitVersion(d, next); d.ActiveBranch = branch; Save(ctx); AppendLedger(ctx, "BRANCH_FORK", next.Id, d.Title + " · " + cur.Id + " → " + branch, next.RootFingerprint, ""); }
        private static void Checkpoint(Window owner, DeepSystemsContext ctx) { LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null) return; string note = Prompt(owner, "CHECKPOINT VERSION", "Checkpoint reason:", "Investigation checkpoint"); if (note == null) return; LivingVersion next = CloneVersion(d, cur, note, cur.Branch); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "CHECKPOINT", next.Id, d.Title + " · " + note, next.RootFingerprint, ""); }

        private static void Baseline(Window owner, DeepSystemsContext ctx) { LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion v = LivingDocumentKernel.Current(d); if (v == null) return; LivingBaseline b = new LivingBaseline { Id = LivingDocumentKernel.NewId("BASE"), DocumentId = d.Id, VersionId = v.Id, VersionFingerprint = v.RootFingerprint, Name = d.Title + " · v" + v.Number, CreatedUtc = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture) }; b.CertificateHash = LivingDocumentKernel.HashText(b.DocumentId + "|" + b.VersionId + "|" + b.VersionFingerprint + "|" + b.Name); Store.Baselines.Insert(0, b); Trim(Store.Baselines, 2048); Save(ctx); AppendLedger(ctx, "BASELINE", b.Id, b.Name, v.RootFingerprint, b.CertificateHash); OpenCollection(owner, "BASELINE CREATED", new List<object> { b }, "Immutable comparison anchor."); }
        private static void FreezeVersion(Window owner, DeepSystemsContext ctx) { LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion cur = LivingDocumentKernel.Current(d); if (cur == null) return; List<LivingValidationFinding> findings = LivingDocumentKernel.Validate(cur); int errors = findings.Count(x => String.Equals(x.Severity, "ERROR", StringComparison.OrdinalIgnoreCase)); if (errors > 0) { OpenCollection(owner, "FREEZE REFUSED · VALIDATION ERRORS", findings.Cast<object>().ToList(), "Resolve structural errors before publication freeze."); return; } if (cur.Frozen) return; LivingVersion next = CloneVersion(d, cur, "Publication freeze", cur.Branch); next.Frozen = true; next.RootFingerprint = LivingDocumentKernel.Fingerprint(next); CommitVersion(d, next); Save(ctx); AppendLedger(ctx, "FREEZE", next.Id, d.Title + " v" + next.Number, next.RootFingerprint, ""); }
        private static void SealPublication(Window owner, DeepSystemsContext ctx) { LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion v = LivingDocumentKernel.Current(d); if (v == null) return; List<LivingValidationFinding> findings = LivingDocumentKernel.Validate(v); int errors = findings.Count(x => String.Equals(x.Severity, "ERROR", StringComparison.OrdinalIgnoreCase)); int warnings = findings.Count(x => String.Equals(x.Severity, "WARN", StringComparison.OrdinalIgnoreCase)); if (errors > 0) { OpenCollection(owner, "SEAL REFUSED", findings.Cast<object>().ToList(), "Publication seal requires zero structural errors."); return; } string rendered = LivingDocumentKernel.RenderMarkdown(d, v); LivingPublicationSeal s = new LivingPublicationSeal { Id = LivingDocumentKernel.NewId("SEAL"), DocumentId = d.Id, VersionId = v.Id, VersionFingerprint = v.RootFingerprint, RenderedFingerprint = LivingDocumentKernel.HashText(rendered), WarningCount = warnings, ErrorCount = errors, CreatedUtc = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture) }; s.CertificateHash = LivingDocumentKernel.HashText(s.DocumentId + "|" + s.VersionId + "|" + s.VersionFingerprint + "|" + s.RenderedFingerprint + "|" + s.WarningCount + "|" + s.ErrorCount); Store.Seals.Insert(0, s); Trim(Store.Seals, 2048); Save(ctx); AppendLedger(ctx, "PUBLICATION_SEAL", s.Id, d.Title + " v" + v.Number, v.RootFingerprint, s.CertificateHash); OpenCollection(owner, "PUBLICATION SEALED", new List<object> { s }, "Graph fingerprint and rendered artifact fingerprint are bound together."); }

        private static void RenderPreview(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { TextView(owner, "CANONICAL RENDER · " + d.Title, LivingDocumentKernel.RenderMarkdown(d, v)); }); }
        private static void ExportPackage(Window owner, DeepSystemsContext ctx)
        {
            LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion v = LivingDocumentKernel.Current(d); if (v == null) return; string root = Path.Combine(ctx.DataRoot, "deep-systems", "living-document-exports"); Directory.CreateDirectory(root); string stem = SafeName(d.Title) + "-v" + v.Number + "-" + DateTime.UtcNow.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture); string md = Path.Combine(root, stem + ".md"), manifest = Path.Combine(root, stem + ".manifest.json"); string rendered = LivingDocumentKernel.RenderMarkdown(d, v); File.WriteAllText(md, rendered, new UTF8Encoding(false)); var m = new { schema = 1, product = "YOMI", civilization = "DEV13.37.26", document_id = d.Id, version_id = v.Id, version = v.Number, branch = v.Branch, version_fingerprint = v.RootFingerprint, rendered_sha256 = LivingDocumentKernel.HashText(rendered), source_fingerprints = v.Evidence.Select(x => new { civilization = x.SourceCivilization, source_id = x.SourceId, fingerprint = x.SourceFingerprint, certificate = x.CertificateHash }).ToList(), validation = LivingDocumentKernel.Validate(v).Select(x => new { severity = x.Severity, kind = x.Kind, subject = x.SubjectId, message = x.Message }).ToList() }; File.WriteAllText(manifest, Json.Serialize(m), new UTF8Encoding(false)); AppendLedger(ctx, "EXPORT_PACKAGE", v.Id, md, v.RootFingerprint, LivingDocumentKernel.HashText(File.ReadAllText(manifest, Encoding.UTF8))); try { Clipboard.SetText(md + Environment.NewLine + manifest); } catch { } MessageBox.Show(owner, "Publication package written inside YOMI data and both paths copied to the clipboard.\n\n" + md + "\n" + manifest, "YOMI · DOCΩ Export", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        private static void Certificates(Window owner) { List<object> rows = new List<object>(); foreach (LivingDocument d in Store.Documents) foreach (LivingVersion v in d.Versions) rows.Add("VERSION   ·   " + d.Title + " v" + v.Number + "   ·   " + v.RootFingerprint); rows.AddRange(Store.Baselines.Select(x => (object)x)); rows.AddRange(Store.Impacts.Select(x => (object)x)); rows.AddRange(Store.Seals.Select(x => (object)x)); OpenCollection(owner, "PROVENANCE CERTIFICATE VAULT", rows, "Addressable roots for document graph, impacts, baselines and rendered publications."); }
        private static void Ledger(Window owner, DeepSystemsContext ctx) { List<LivingLedgerRecord> rows = ReadLedger(ctx); OpenCollection(owner, "DOCUMENT LEDGER", rows.Cast<object>().ToList(), VerifyLedger(rows) ? "HASH CHAIN: VERIFIED over retained ledger window." : "HASH CHAIN: ATTENTION — retained window does not verify."); }
        private static void BranchMap(Window owner) { LivingDocument d = ChooseDocument(owner); if (d == null) return; OpenCollection(owner, "BRANCH MAP · " + d.Title, d.Versions.OrderBy(x => x.Number).Select(x => (object)("v" + x.Number + "   ·   " + x.Id + "   ·   parent " + (x.ParentVersionId ?? "∅") + "   ·   branch " + x.Branch + "   ·   fp " + LivingDocumentKernel.Short(x.RootFingerprint))).ToList(), "Version parentage is explicit; branch labels do not rewrite history."); }
        private static void SourceFingerprintAtlas(Window owner) { List<object> rows = new List<object>(); foreach (LivingProjectionReceipt p in Store.Projections) rows.Add("INBOX   ·   " + p); foreach (LivingDocument d in Store.Documents) { LivingVersion v = LivingDocumentKernel.Current(d); if (v == null) continue; foreach (LivingEvidenceAnchor e in v.Evidence) rows.Add("BOUND   ·   " + d.Title + "   ·   " + e); } OpenCollection(owner, "SOURCE FINGERPRINT ATLAS", rows, "Upstream identity and document-bound evidence in one view."); }
        private static void ReproducibilityCapsule(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = new List<object> { "DOCUMENT " + d.Id, "VERSION " + v.Id, "ROOT " + v.RootFingerprint, "RENDER " + LivingDocumentKernel.HashText(LivingDocumentKernel.RenderMarkdown(d, v)) }; rows.AddRange(v.Evidence.Select(x => (object)("SOURCE " + x.SourceCivilization + "/" + x.SourceId + " " + x.SourceFingerprint))); rows.AddRange(v.Calculations.Cast<object>()); rows.AddRange(v.Models.Cast<object>()); rows.AddRange(LivingDocumentKernel.Validate(v).Cast<object>()); OpenCollection(owner, "REPRODUCIBILITY CAPSULE · " + d.Title, rows, "Everything needed to reconstruct the review surface from retained graph state."); }); }
        private static void ModeLens(Window owner, string kind) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = new List<object> { "MODE   ·   " + kind, "DOCUMENT KIND   ·   " + d.Kind, "OBJECTIVE   ·   " + d.Objective }; if (kind == "SPECIFICATION" || kind == "MANUAL") rows.AddRange(v.Requirements.Cast<object>()); if (kind == "RESEARCH_DOSSIER" || kind == "REPORT") rows.AddRange(v.Claims.Cast<object>()); rows.AddRange(v.Objections.Where(x => x.Status == "OPEN").Cast<object>()); OpenCollection(owner, kind + " LENS · " + d.Title, rows, "Lens changes what is foregrounded; it does not mutate the document graph."); }); }
        private static void ExecutiveLens(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = v.Paragraphs.Where(x => String.Equals(x.Role, "EXECUTIVE", StringComparison.OrdinalIgnoreCase)).Cast<object>().ToList(); rows.AddRange(v.Claims.Where(x => String.Equals(x.Kind, "THESIS", StringComparison.OrdinalIgnoreCase)).Cast<object>()); OpenCollection(owner, "EXECUTIVE SUMMARY LENS · " + d.Title, rows, "Summary surface remains linked to full trace graph."); }); }
        private static void ObjectionMatrix(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = new List<object>(); foreach (LivingClaim c in v.Claims) rows.Add(c.Id + "   ·   objections " + c.ObjectionIds.Count + "   ·   " + c.Text); OpenCollection(owner, "OBJECTION MATRIX · " + d.Title, rows, "Zero objections is a signal to inspect, not automatic proof of weakness."); }); }
        private static void CalculationLineage(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = new List<object>(); foreach (LivingCalculation c in v.Calculations) { rows.Add(c); rows.AddRange(v.Evidence.Where(x => c.EvidenceIds.Contains(x.Id)).Cast<object>()); rows.AddRange(v.Claims.Where(x => x.CalculationIds.Contains(c.Id)).Cast<object>()); rows.AddRange(v.Paragraphs.Where(x => x.CalculationIds.Contains(c.Id) || v.Claims.Where(q => q.CalculationIds.Contains(c.Id)).Any(q => x.ClaimIds.Contains(q.Id))).Cast<object>()); } OpenCollection(owner, "CALCULATION LINEAGE · " + d.Title, rows, "Arithmetic artifact to prose consequence."); }); }
        private static void ModelLimitationRadar(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { OpenCollection(owner, "MODEL LIMITATION RADAR · " + d.Title, v.Models.Where(x => x.Limitations == null || x.Limitations.Count < 1).Cast<object>().ToList(), "A model without retained limitations is publication risk."); }); }
        private static void RequirementCrosswalk(Window owner) { WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { List<object> rows = new List<object>(); foreach (LivingRequirement q in v.Requirements) { rows.Add(q); rows.AddRange(v.Claims.Where(x => q.ClaimIds.Contains(x.Id)).Cast<object>()); rows.AddRange(v.Evidence.Where(x => q.EvidenceIds.Contains(x.Id)).Cast<object>()); rows.AddRange(q.VerificationLinks.Cast<object>()); } OpenCollection(owner, "REQUIREMENT VERIFICATION CROSSWALK · " + d.Title, rows, "Requirement descent retains evidence and verification references."); }); }

        private static void HadalDescent(Window owner)
        {
            WithVersion(owner, delegate(LivingDocument d, LivingVersion v) { LivingParagraph p = Choose<LivingParagraph>(owner, "Choose paragraph for hadal descent", v.Paragraphs); if (p == null) return; List<object> rows = new List<object> { d, v, p }; HashSet<string> claims = new HashSet<string>(p.ClaimIds, StringComparer.Ordinal); rows.AddRange(v.Claims.Where(x => claims.Contains(x.Id)).Cast<object>()); HashSet<string> evidence = new HashSet<string>(p.EvidenceIds.Concat(v.Claims.Where(x => claims.Contains(x.Id)).SelectMany(x => x.EvidenceIds)), StringComparer.Ordinal); rows.AddRange(v.Evidence.Where(x => evidence.Contains(x.Id)).Cast<object>()); HashSet<string> calcs = new HashSet<string>(p.CalculationIds.Concat(v.Claims.Where(x => claims.Contains(x.Id)).SelectMany(x => x.CalculationIds)), StringComparer.Ordinal); rows.AddRange(v.Calculations.Where(x => calcs.Contains(x.Id)).Cast<object>()); HashSet<string> models = new HashSet<string>(p.ModelIds.Concat(v.Claims.Where(x => claims.Contains(x.Id)).SelectMany(x => x.ModelIds)), StringComparer.Ordinal); rows.AddRange(v.Models.Where(x => models.Contains(x.Id)).Cast<object>()); HashSet<string> objs = new HashSet<string>(p.ObjectionIds.Concat(v.Claims.Where(x => claims.Contains(x.Id)).SelectMany(x => x.ObjectionIds)), StringComparer.Ordinal); rows.AddRange(v.Objections.Where(x => objs.Contains(x.Id)).Cast<object>()); rows.AddRange(LivingDocumentKernel.ParagraphGenealogy(d, p.Id).Cast<object>()); OpenCollection(owner, "HADAL DOCUMENT DESCENT · " + p.Heading, rows, "Paragraph → claim → evidence/calculation/model/objection → version genealogy."); });
        }

        private static void OpenReturnWormholes(Window owner, DeepSystemsContext ctx)
        {
            Window w = W(owner, "YOMI · DOCΩ RETURN WORMHOLES", 1220, 820); DockPanel root = Shell("RETURN WORMHOLES", "The living-document graph remains retained while you cross into another civilization."); WrapPanel p = new WrapPanel { Margin = new Thickness(14) };
            SmallPortal(p, "WORLD KERNEL", delegate { WorldKernel.Open(w, ctx); }); SmallPortal(p, "CIVILIZATION LAYER", delegate { CivilizationLayer.Open(w, ctx); }); SmallPortal(p, "EPISTEMIC LOGIC", delegate { EpistemicLogicFoundry.Open(w, ctx); }); SmallPortal(p, "VERIFICATION REACTOR", delegate { AxiomaticVerificationReactor.Open(w, ctx); }); SmallPortal(p, "COUNTERFACTUAL STRATEGY", delegate { CounterfactualStrategySuperstructure.Open(w, ctx); }); SmallPortal(p, "SCIENTIFIC DISCOVERY", delegate { ScientificDiscoveryHyperstructure.Open(w, ctx); }); SmallPortal(p, "SYSTEMS ENGINEERING", delegate { DysonSystemsEngineeringMegastructure.Open(w, ctx); }); SmallPortal(p, "CYBERNETIC TWIN", delegate { CyberneticDigitalTwinMetastructure.Open(w, ctx); }); SmallPortal(p, "COMPLEX SYSTEMS", delegate { ComplexSystemsLaboratory.Open(w, ctx); }); SmallPortal(p, "OPERATIONS RESEARCH", delegate { OperationsResearchEmpire.Open(w, ctx); }); SmallPortal(p, "ECONOMIC CIVILIZATION", delegate { EconomicCivilization.Open(w, ctx); }); SmallPortal(p, "SPATIAL CARTOGRAPHY", delegate { SpatialWorldCartography.Open(w, ctx); }); SmallPortal(p, "DISTRIBUTED SYSTEMS", delegate { DistributedSystemsPlanetarium.Open(w, ctx); }); SmallPortal(p, "SECURITY FORTRESS", delegate { AdversarialSecurityFortress.Open(w, ctx); }); SmallPortal(p, "DATA FOUNDRY", delegate { DataFoundry.Open(w, ctx); }); SmallPortal(p, "SOFTWARE GENOME", delegate { SoftwareGenomeObservatory.Open(w, ctx); });
            root.Children.Add(new ScrollViewer { Content = p, VerticalScrollBarVisibility = ScrollBarVisibility.Auto }); w.Content = root; w.Show();
        }

        private static void SeedStarter(DeepSystemsContext ctx) { LivingDocument d = LivingDocumentKernel.Starter("Atlas Intelligence Dossier", "RESEARCH_DOSSIER"); Store.Documents.Add(d); Save(ctx); LivingVersion v = LivingDocumentKernel.Current(d); AppendLedger(ctx, "GENESIS", d.Id, "DOCΩ starter living dossier", v == null ? "" : v.RootFingerprint, ""); }
        private static LivingDocument ChooseDocument(Window owner) { EnsureLoaded(); return Store.Documents.Count == 0 ? null : Choose<LivingDocument>(owner, "Choose living document", Store.Documents); }
        private static void WithVersion(Window owner, Action<LivingDocument,LivingVersion> action) { LivingDocument d = ChooseDocument(owner); if (d == null) return; LivingVersion v = LivingDocumentKernel.Current(d); if (v != null) action(d, v); }

        private static LivingVersion CloneVersion(LivingDocument d, LivingVersion source, string note, string branch)
        {
            LivingVersion v = Json.Deserialize<LivingVersion>(Json.Serialize(source)); v.Id = LivingDocumentKernel.NewId("VER"); v.DocumentId = d.Id; v.Number = d.Versions.Count == 0 ? 1 : d.Versions.Max(x => x.Number) + 1; v.ParentVersionId = source.Id; v.Branch = String.IsNullOrWhiteSpace(branch) ? source.Branch : branch; v.CreatedUtc = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture); v.ChangeNote = note; v.Frozen = false; v.RootFingerprint = LivingDocumentKernel.Fingerprint(v); return v;
        }
        private static void CommitVersion(LivingDocument d, LivingVersion v) { v.RootFingerprint = LivingDocumentKernel.Fingerprint(v); d.Versions.Add(v); while (d.Versions.Count > MaxVersionsPerDocument) d.Versions.RemoveAt(0); d.CurrentVersionId = v.Id; d.ActiveBranch = v.Branch; }

        private static void Ensure(DeepSystemsContext ctx) { lock (Gate) { string root = ctx.DataRoot ?? ""; if (Store != null && String.Equals(LoadedRoot, root, StringComparison.OrdinalIgnoreCase)) return; LoadedRoot = root; Store = Load(ctx); } }
        private static void EnsureLoaded() { if (Store == null) Store = new LivingDocumentStore(); }
        private static string StorePath(DeepSystemsContext ctx) { string d = Path.Combine(ctx.DataRoot, "deep-systems"); Directory.CreateDirectory(d); return Path.Combine(d, "controller-living-document-factory.json"); }
        private static string LedgerPath(DeepSystemsContext ctx) { string d = Path.Combine(ctx.DataRoot, "deep-systems"); Directory.CreateDirectory(d); return Path.Combine(d, "controller-living-document-ledger.jsonl"); }
        private static LivingDocumentStore Load(DeepSystemsContext ctx) { string p = StorePath(ctx), prev = p + ".previous"; foreach (string q in new[] { p, prev }) { if (!File.Exists(q)) continue; try { LivingDocumentStore s = Json.Deserialize<LivingDocumentStore>(File.ReadAllText(q, Encoding.UTF8)); if (s != null && s.Schema <= 1) { Normalize(s); return s; } } catch { try { File.Copy(q, q + ".corrupt-" + DateTime.UtcNow.ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture), true); } catch { } } } return new LivingDocumentStore(); }
        private static void Normalize(LivingDocumentStore s) { if (s.Documents == null) s.Documents = new List<LivingDocument>(); if (s.Projections == null) s.Projections = new List<LivingProjectionReceipt>(); if (s.Impacts == null) s.Impacts = new List<LivingImpactReport>(); if (s.Baselines == null) s.Baselines = new List<LivingBaseline>(); if (s.Seals == null) s.Seals = new List<LivingPublicationSeal>(); foreach (LivingDocument d in s.Documents) { if (d.Versions == null) d.Versions = new List<LivingVersion>(); foreach (LivingVersion v in d.Versions) NormalizeVersion(v); } }
        private static void NormalizeVersion(LivingVersion v) { if (v.Sections == null) v.Sections = new List<LivingSection>(); if (v.Paragraphs == null) v.Paragraphs = new List<LivingParagraph>(); if (v.Claims == null) v.Claims = new List<LivingClaim>(); if (v.Evidence == null) v.Evidence = new List<LivingEvidenceAnchor>(); if (v.Calculations == null) v.Calculations = new List<LivingCalculation>(); if (v.Models == null) v.Models = new List<LivingModelBinding>(); if (v.Assumptions == null) v.Assumptions = new List<LivingAssumption>(); if (v.Objections == null) v.Objections = new List<LivingObjection>(); if (v.Decisions == null) v.Decisions = new List<LivingDecisionRecord>(); if (v.Requirements == null) v.Requirements = new List<LivingRequirement>(); if (v.Definitions == null) v.Definitions = new List<LivingDefinition>(); }
        private static void Save(DeepSystemsContext ctx) { lock (Gate) { Normalize(Store); Store.Revision++; Store.UpdatedUtc = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture); Trim(Store.Documents, MaxDocuments); string p = StorePath(ctx), next = p + ".next", prev = p + ".previous"; File.WriteAllText(next, Json.Serialize(Store), new UTF8Encoding(false)); if (File.Exists(p)) { try { File.Copy(p, prev, true); } catch { } } if (File.Exists(p)) File.Delete(p); File.Move(next, p); } }
        private static void Trim<T>(List<T> xs, int n) { if (xs == null) return; while (xs.Count > n) xs.RemoveAt(xs.Count - 1); }

        private static void AppendLedger(DeepSystemsContext ctx, string ev, string subject, string detail, string versionFp, string cert)
        {
            lock (Gate) { List<LivingLedgerRecord> old = ReadLedger(ctx); long seq = old.Count == 0 ? 1 : old[old.Count - 1].Sequence + 1; string prev = old.Count == 0 ? new string('0', 64) : old[old.Count - 1].EntryHash; LivingLedgerRecord r = new LivingLedgerRecord { Schema = 1, Sequence = seq, Utc = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture), Event = ev, Subject = subject, Detail = detail, VersionFingerprint = versionFp, CertificateHash = cert, PrevHash = prev }; r.EntryHash = LivingDocumentKernel.HashText(r.Schema + "|" + r.Sequence + "|" + r.Utc + "|" + r.Event + "|" + r.Subject + "|" + r.Detail + "|" + r.VersionFingerprint + "|" + r.CertificateHash + "|" + r.PrevHash); File.AppendAllText(LedgerPath(ctx), Json.Serialize(r) + Environment.NewLine, new UTF8Encoding(false)); }
        }
        private static List<LivingLedgerRecord> ReadLedger(DeepSystemsContext ctx) { List<LivingLedgerRecord> r = new List<LivingLedgerRecord>(); string p = LedgerPath(ctx); if (!File.Exists(p)) return r; Queue<string> q = new Queue<string>(); foreach (string line in File.ReadLines(p)) { q.Enqueue(line); if (q.Count > MaxLedgerRead) q.Dequeue(); } foreach (string line in q) { if (String.IsNullOrWhiteSpace(line)) continue; try { LivingLedgerRecord x = Json.Deserialize<LivingLedgerRecord>(line); if (x != null) r.Add(x); } catch { } } return r; }
        private static bool VerifyLedger(List<LivingLedgerRecord> xs) { if (xs == null || xs.Count == 0) return true; for (int i = 0; i < xs.Count; i++) { LivingLedgerRecord r = xs[i]; if (i > 0 && !String.Equals(r.PrevHash, xs[i - 1].EntryHash, StringComparison.OrdinalIgnoreCase)) return false; string h = LivingDocumentKernel.HashText(r.Schema + "|" + r.Sequence + "|" + r.Utc + "|" + r.Event + "|" + r.Subject + "|" + r.Detail + "|" + r.VersionFingerprint + "|" + r.CertificateHash + "|" + r.PrevHash); if (!String.Equals(h, r.EntryHash, StringComparison.OrdinalIgnoreCase)) return false; } return true; }

        private static string HashObject(object source) { try { return LivingDocumentKernel.HashText(Json.Serialize(source)); } catch { return LivingDocumentKernel.HashText(source == null ? "" : source.ToString()); } }
        private static string ReadId(object source) { if (source == null) return "UNKNOWN"; try { PropertyInfo p = source.GetType().GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase); object v = p == null ? null : p.GetValue(source, null); return v == null ? source.GetType().Name : Convert.ToString(v, CultureInfo.InvariantCulture); } catch { return source.GetType().Name; } }
        private static string SafeName(string s) { if (String.IsNullOrWhiteSpace(s)) return "document"; StringBuilder b = new StringBuilder(); foreach (char c in s) b.Append(Char.IsLetterOrDigit(c) ? c : '-'); string x = b.ToString().Trim('-'); while (x.Contains("--")) x = x.Replace("--", "-"); return x.Length > 80 ? x.Substring(0, 80) : x; }

        private static T Choose<T>(Window owner, string title, IList<T> items) where T : class { Window w = W(owner, "YOMI · " + title.ToUpperInvariant(), 1000, 700); DockPanel root = Shell(title.ToUpperInvariant(), "Double-click to select."); ListBox list = List(); list.ItemsSource = items; T selected = null; list.MouseDoubleClick += delegate { selected = list.SelectedItem as T; w.DialogResult = selected != null; w.Close(); }; root.Children.Add(list); w.Content = root; bool? r = w.ShowDialog(); return r == true ? selected : null; }
        private static Window W(Window owner, string title, double width, double height) { return new Window { Title = title, Width = width, Height = height, Background = Bg, Foreground = Text, WindowStartupLocation = owner == null ? WindowStartupLocation.CenterScreen : WindowStartupLocation.CenterOwner, Owner = owner }; }
        private static DockPanel Shell(string title, string subtitle) { DockPanel root = new DockPanel { Background = Bg }; StackPanel head = new StackPanel { Margin = new Thickness(20, 18, 20, 10) }; head.Children.Add(new TextBlock { Text = title, Foreground = Text, FontSize = 25, FontWeight = FontWeights.Bold }); head.Children.Add(new TextBlock { Text = subtitle ?? "", Foreground = Muted, FontSize = 13, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 5, 0, 0) }); DockPanel.SetDock(head, Dock.Top); root.Children.Add(head); return root; }
        private static void Portal(WrapPanel panel, string badge, string title, string detail, RoutedEventHandler click) { Button b = new Button { Width = 285, MinHeight = 118, Margin = new Thickness(7), Padding = new Thickness(14), Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), HorizontalContentAlignment = HorizontalAlignment.Stretch }; StackPanel p = new StackPanel(); p.Children.Add(new TextBlock { Text = badge + "   " + title, Foreground = Accent, FontWeight = FontWeights.Bold, FontSize = 13, TextWrapping = TextWrapping.Wrap }); p.Children.Add(new TextBlock { Text = detail, Foreground = Muted, FontSize = 12, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 7, 0, 0) }); b.Content = p; b.Click += click; panel.Children.Add(b); }
        private static void SmallPortal(Panel p, string title, RoutedEventHandler click) { Button b = new Button { Content = title, Margin = new Thickness(5), Padding = new Thickness(11, 7, 11, 7), Background = Raised, Foreground = Accent, BorderBrush = Border }; b.Click += click; p.Children.Add(b); }
        private static ListBox List() { return new ListBox { Margin = new Thickness(18), Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), FontFamily = new FontFamily("Consolas"), FontSize = 12 }; }
        private static void OpenCollection(Window owner, string title, IList<object> items, string note) { Window w = W(owner, "YOMI · " + title, 1360, 840); DockPanel root = Shell(title, note + "   ·   " + (items == null ? 0 : items.Count) + " retained rows"); ListBox list = List(); list.ItemsSource = items ?? new List<object>(); root.Children.Add(list); w.Content = root; w.Show(); }
        private static void TextView(Window owner, string title, string text) { Window w = W(owner, "YOMI · " + title, 1360, 860); DockPanel root = Shell(title, "Read-only canonical text view."); TextBox box = new TextBox { Text = text ?? "", Margin = new Thickness(18), Background = Surface, Foreground = Text, BorderBrush = Border, FontFamily = new FontFamily("Consolas"), FontSize = 13, IsReadOnly = true, AcceptsReturn = true, AcceptsTab = true, TextWrapping = TextWrapping.Wrap, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollBarVisibility = ScrollBarVisibility.Auto }; root.Children.Add(box); w.Content = root; w.Show(); }
        private static string Prompt(Window owner, string title, string label, string initial) { Window w = W(owner, "YOMI · " + title, 760, 300); DockPanel root = Shell(title, label); TextBox box = new TextBox { Text = initial ?? "", Margin = new Thickness(20, 6, 20, 10), Padding = new Thickness(8), Background = Surface, Foreground = Text, BorderBrush = Border, AcceptsReturn = true, TextWrapping = TextWrapping.Wrap, MinHeight = 80, VerticalScrollBarVisibility = ScrollBarVisibility.Auto }; DockPanel.SetDock(box, Dock.Top); root.Children.Add(box); StackPanel buttons = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(20) }; Button ok = new Button { Content = "COMMIT", Padding = new Thickness(18, 7, 18, 7), Margin = new Thickness(6), Background = Raised, Foreground = Green, BorderBrush = Border }; Button cancel = new Button { Content = "CANCEL", Padding = new Thickness(18, 7, 18, 7), Margin = new Thickness(6), Background = Raised, Foreground = Muted, BorderBrush = Border }; string value = null; ok.Click += delegate { value = box.Text; w.DialogResult = true; w.Close(); }; cancel.Click += delegate { w.DialogResult = false; w.Close(); }; buttons.Children.Add(cancel); buttons.Children.Add(ok); root.Children.Add(buttons); w.Content = root; bool? r = w.ShowDialog(); return r == true ? value : null; }
        private static Brush B(string hex) { return (Brush)new BrushConverter().ConvertFromString(hex); }
    }
}
