using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class CyberTwinAnalysisRecord
    {
        public string Id { get; set; }
        public string TwinId { get; set; }
        public string CreatedUtc { get; set; }
        public string TwinFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public CyberStructuralAnalysis Structure { get; set; }
        public CyberControllerSynthesis Lqr { get; set; }
        public CyberControllerSynthesis Pid { get; set; }
        public CyberMpcResult Mpc { get; set; }
        public CyberReachabilityResult Reachability { get; set; }
        public CyberRobustnessEnvelope Robustness { get; set; }
        public CyberSensorSelection Sensors { get; set; }
        public List<string> Audit { get; set; }
        public CyberTwinAnalysisRecord() { Audit = new List<string>(); }
        public override string ToString() { return (CreatedUtc ?? "") + "   ·   " + (Structure == null ? "STRUCTURE —" : Structure.ToString()) + "   ·   " + (Lqr == null ? "LQR —" : "closed ρ " + Lqr.ClosedLoopSpectralRadius.ToString("0.000000", CultureInfo.InvariantCulture)) + "   ·   cert " + Short(CertificateHash); }
        private static string Short(string value) { return String.IsNullOrWhiteSpace(value) ? "∅" : value.Substring(0, Math.Min(16, value.Length)); }
    }

    internal sealed class CyberTelemetryFrame
    {
        public string Id { get; set; }
        public string TwinId { get; set; }
        public long Sequence { get; set; }
        public string CapturedUtc { get; set; }
        public string EffectiveTime { get; set; }
        public string SourceKind { get; set; }
        public string SourceReference { get; set; }
        public string TwinFingerprint { get; set; }
        public double[] Input { get; set; }
        public double[] Output { get; set; }
        public double[] EstimatedState { get; set; }
        public double[] Innovation { get; set; }
        public double InnovationMahalanobis { get; set; }
        public CyberTelemetryFrame() { SourceKind = "MANUAL_DECLARATION"; Input = new double[0]; Output = new double[0]; EstimatedState = new double[0]; Innovation = new double[0]; }
        public override string ToString() { return Sequence.ToString(CultureInfo.InvariantCulture).PadLeft(7) + "   ·   " + (EffectiveTime ?? CapturedUtc ?? "") + "   ·   y=[" + Join(Output) + "]   ·   x̂=[" + Join(EstimatedState) + "]   ·   χ² " + InnovationMahalanobis.ToString("0.######", CultureInfo.InvariantCulture) + "   ·   " + (SourceKind ?? "DECLARED"); }
        private static string Join(IEnumerable<double> values) { return String.Join(", ", (values ?? Enumerable.Empty<double>()).Select(x => x.ToString("0.######", CultureInfo.InvariantCulture)).ToArray()); }
    }

    internal sealed class CyberTwinSnapshot
    {
        public string Id { get; set; }
        public string TwinId { get; set; }
        public string Name { get; set; }
        public string CapturedUtc { get; set; }
        public string TwinFingerprint { get; set; }
        public string SourceTelemetryFrameId { get; set; }
        public double[] EstimatedState { get; set; }
        public double[] LastInput { get; set; }
        public double[] LastOutput { get; set; }
        public string CertificateHash { get; set; }
        public List<string> Assumptions { get; set; }
        public CyberTwinSnapshot() { EstimatedState = new double[0]; LastInput = new double[0]; LastOutput = new double[0]; Assumptions = new List<string>(); }
        public override string ToString() { return (Name ?? Id ?? "SNAPSHOT") + "   ·   " + (CapturedUtc ?? "") + "   ·   x̂=[" + String.Join(", ", EstimatedState.Select(x => x.ToString("0.######", CultureInfo.InvariantCulture)).ToArray()) + "]   ·   cert " + Short(CertificateHash); }
        private static string Short(string value) { return String.IsNullOrWhiteSpace(value) ? "∅" : value.Substring(0, Math.Min(16, value.Length)); }
    }

    internal sealed class CyberTwinBaseline
    {
        public string Id { get; set; }
        public string TwinId { get; set; }
        public string ParentBaselineId { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string FrozenUtc { get; set; }
        public string Reason { get; set; }
        public string TwinFingerprint { get; set; }
        public string SnapshotJson { get; set; }
        public string BaselineFingerprint { get; set; }
        public override string ToString() { return (Status ?? "FROZEN") + "   ·   " + (Name ?? Id ?? "BASELINE") + "   ·   " + (FrozenUtc ?? "") + "   ·   " + Short(BaselineFingerprint); }
        private static string Short(string value) { return String.IsNullOrWhiteSpace(value) ? "∅" : value.Substring(0, Math.Min(16, value.Length)); }
    }

    internal sealed class CyberControlDossier
    {
        public string Id { get; set; }
        public string TwinId { get; set; }
        public string AnalysisId { get; set; }
        public string BaselineId { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string CreatedUtc { get; set; }
        public string UpdatedUtc { get; set; }
        public string Decision { get; set; }
        public string AuthorityBoundary { get; set; }
        public string TwinFingerprint { get; set; }
        public string AnalysisCertificate { get; set; }
        public List<string> Assumptions { get; set; }
        public List<string> Risks { get; set; }
        public List<string> Dissent { get; set; }
        public List<string> EvidenceNodeIds { get; set; }
        public CyberControlDossier() { Status = "DRAFT"; Assumptions = new List<string>(); Risks = new List<string>(); Dissent = new List<string>(); EvidenceNodeIds = new List<string>(); AuthorityBoundary = "DESIGN-ONLY · no live sensor, process, scheduler, actuator, deployment or autonomous execution authority."; }
        public override string ToString() { return (Status ?? "DRAFT") + "   ·   " + (Title ?? "CONTROL DOSSIER") + "   ·   " + (UpdatedUtc ?? CreatedUtc ?? "") + "   ·   analysis " + Short(AnalysisCertificate); }
        private static string Short(string value) { return String.IsNullOrWhiteSpace(value) ? "∅" : value.Substring(0, Math.Min(16, value.Length)); }
    }

    internal sealed class CyberTwinLedgerRecord
    {
        public int Schema { get; set; }
        public long Sequence { get; set; }
        public string Utc { get; set; }
        public string Event { get; set; }
        public string Subject { get; set; }
        public string Detail { get; set; }
        public string CorrelationId { get; set; }
        public string TwinFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public string PrevHash { get; set; }
        public string EntryHash { get; set; }
        public override string ToString() { return Sequence.ToString(CultureInfo.InvariantCulture).PadLeft(7) + "   " + (Utc ?? "") + "   " + (Event ?? "") + "   ·   " + (Subject ?? "∅") + "   ·   " + (Detail ?? ""); }
    }

    internal sealed class CyberneticTwinStore
    {
        public int Schema { get; set; }
        public long Revision { get; set; }
        public string UpdatedUtc { get; set; }
        public string LastCommitId { get; set; }
        public List<CyberTwinModel> Twins { get; set; }
        public List<CyberTwinAnalysisRecord> Analyses { get; set; }
        public List<CyberTelemetryFrame> Telemetry { get; set; }
        public List<CyberTwinSnapshot> Snapshots { get; set; }
        public List<CyberTwinBaseline> Baselines { get; set; }
        public List<CyberControlDossier> Dossiers { get; set; }
        public List<string> RecentQuestions { get; set; }
        public CyberneticTwinStore() { Schema = 1; Twins = new List<CyberTwinModel>(); Analyses = new List<CyberTwinAnalysisRecord>(); Telemetry = new List<CyberTelemetryFrame>(); Snapshots = new List<CyberTwinSnapshot>(); Baselines = new List<CyberTwinBaseline>(); Dossiers = new List<CyberControlDossier>(); RecentQuestions = new List<string>(); }
    }

    internal static class CyberneticDigitalTwinMetastructure
    {
        private static readonly Brush Bg = B("#03070B");
        private static readonly Brush Surface = B("#08141B");
        private static readonly Brush Raised = B("#102733");
        private static readonly Brush Border = B("#2B6074");
        private static readonly Brush Text = B("#F2FCFF");
        private static readonly Brush Muted = B("#9ABBC6");
        private static readonly Brush Accent = B("#6EF2D0");
        private static readonly Brush Blue = B("#64C8FF");
        private static readonly Brush Amber = B("#FFD46A");
        private static readonly Brush Violet = B("#C5A5FF");
        private static readonly Brush Danger = B("#FF7F95");
        private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = Int32.MaxValue, RecursionLimit = 256 };
        private static readonly object Gate = new object();
        private static CyberneticTwinStore Store;
        private static string LoadedRoot;
        private const int MaxTwins = 256;
        private const int MaxAnalyses = 512;
        private const int MaxTelemetry = 32768;
        private const int MaxSnapshots = 2048;
        private const int MaxBaselines = 1024;
        private const int MaxDossiers = 1024;
        private const int MaxStates = 128;
        private const int MaxInputs = 64;
        private const int MaxOutputs = 128;
        private const int MaxConstraints = 1024;
        private const int MaxFaults = 512;
        private const int MaxEvidence = 1024;
        private const int MaxShortText = 2048;
        private const int MaxLongText = 65536;

        public static void Open(Window owner, DeepSystemsContext ctx) { if (ctx == null) return; Load(ctx); OpenHub(owner, ctx, WorldKernel.ExternalIndex(ctx, false)); }

        public static void OpenFromWorldNode(Window owner, DeepSystemsContext ctx, WorldIndex index, string nodeId)
        {
            if (ctx == null || index == null || String.IsNullOrWhiteSpace(nodeId)) return; WorldNode node; if (!index.Nodes.TryGetValue(nodeId, out node)) { Open(owner, ctx); return; }
            string fingerprint = HashText((node.Id ?? "") + "|" + (node.Kind ?? "") + "|" + (node.Label ?? "") + "|" + (node.Fingerprint ?? ""));
            OpenProjection(owner, ctx, index, "WORLD", node.Id, fingerprint, delegate { CyberTwinModel t = StarterTwin("Cybernetic passport · " + (node.Label ?? node.Kind ?? "World node"), "Bounded digital-twin projection of a Universal World Kernel passport. Identity and provenance remain evidence; the projection grants no runtime authority."); t.EvidenceNodeIds.Add(node.Id); t.States[0].EvidenceNodeIds.Add(node.Id); return t; });
        }

        public static void OpenFromCivilResolution(Window owner, DeepSystemsContext ctx, WorldIndex index, CivilResolution resolution)
        {
            if (ctx == null || resolution == null) return; string fingerprint = HashText((resolution.Id ?? "") + "|" + (resolution.Title ?? "") + "|" + (resolution.Proposition ?? "") + "|" + (resolution.Status ?? "") + "|" + String.Join("|", (resolution.EvidenceNodeIds ?? new List<string>()).OrderBy(x => x).ToArray()));
            OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "CIVILIZATION", resolution.Id, fingerprint, delegate { CyberTwinModel t = StarterTwin("Institutional dynamics · " + (resolution.Title ?? "Resolution"), "A declared cybernetic abstraction of an institutional resolution. Adoption is stakeholder evidence, never an automatic control law."); t.Charter += "\n\nResolution proposition: " + (resolution.Proposition ?? ""); t.EvidenceNodeIds.AddRange(resolution.EvidenceNodeIds ?? new List<string>()); return t; });
        }

        public static void OpenFromLogicTheory(Window owner, DeepSystemsContext ctx, WorldIndex index, LogicTheory theory)
        {
            if (ctx == null || theory == null) return; Dictionary<string, string> truth = EpistemicLogicFoundry.ExternalTheoryTruth(ctx, theory); string fingerprint = HashText((theory.Id ?? "") + "|" + (theory.Name ?? "") + "|" + String.Join("|", truth.OrderBy(x => x.Key).Select(x => x.Key + "=" + x.Value).ToArray()));
            OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "LOGIC", theory.Id, fingerprint, delegate { CyberTwinModel t = StarterTwin("Epistemic observer · " + (theory.Name ?? "Theory"), "Observer-state projection of a frozen paraconsistent theory. Truth spectra become declared estimation coordinates, not physical measurements."); t.Assumptions.Add("Frozen theory spectrum: " + String.Join(", ", truth.Take(32).Select(x => x.Key + "=" + x.Value).ToArray())); return t; });
        }

        public static void OpenFromVerificationModel(Window owner, DeepSystemsContext ctx, WorldIndex index, VerificationModel model)
        {
            if (ctx == null || model == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "VERIFICATION", model.Id, VerificationKernel.Fingerprint(model), delegate { return ProjectVerification(model); });
        }

        public static void OpenFromStrategyModel(Window owner, DeepSystemsContext ctx, WorldIndex index, StrategyModel model)
        {
            if (ctx == null || model == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "STRATEGY", model.Id, CounterfactualStrategyKernel.Fingerprint(model), delegate { return ProjectStrategy(model); });
        }

        public static void OpenFromDiscoveryProtocol(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol protocol)
        {
            if (ctx == null || protocol == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "DISCOVERY", protocol.Id, ExperimentalDesignKernel.ProtocolFingerprint(protocol), delegate { return ProjectDiscovery(protocol); });
        }

        public static void OpenFromEngineeringArchitecture(Window owner, DeepSystemsContext ctx, WorldIndex index, EngineeringArchitecture architecture)
        {
            if (ctx == null || architecture == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "ENGINEERING", architecture.Id, SystemsEngineeringKernel.Fingerprint(architecture), delegate { return ProjectEngineering(architecture); });
        }

        private static void OpenProjection(Window owner, DeepSystemsContext ctx, WorldIndex index, string sourceKind, string sourceId, string fingerprint, Func<CyberTwinModel> factory)
        {
            Load(ctx); List<CyberTwinModel> existing = Store.Twins.Where(x => Eq(x.SourceKind, sourceKind) && Eq(x.SourceId, sourceId)).OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).ToList(); CyberTwinModel exact = existing.FirstOrDefault(x => Eq(x.SourceFingerprint, fingerprint)); if (exact != null) { OpenTwin(owner, ctx, index, exact); return; }
            if (existing.Count > 0)
            {
                MessageBoxResult drift = MessageBox.Show(owner, "The source fingerprint has changed since the latest projection.\n\nYES · create a traceable child revision\nNO · open the historical projection\nCANCEL · leave unchanged", "YOMI · SOURCE DRIFT BOUNDARY", MessageBoxButton.YesNoCancel, MessageBoxImage.Warning); if (drift == MessageBoxResult.No) { OpenTwin(owner, ctx, index, existing[0]); return; } if (drift != MessageBoxResult.Yes) return;
            }
            CyberTwinModel twin = factory == null ? StarterTwin("Untitled digital twin", "Declared cybernetic abstraction.") : factory(); if (twin == null) return; twin.Id = Id("twin"); twin.ParentTwinId = existing.Count == 0 ? null : existing[0].Id; twin.SourceKind = sourceKind; twin.SourceId = sourceId; twin.SourceFingerprint = fingerprint; twin.CreatedUtc = Now(); twin.UpdatedUtc = twin.CreatedUtc; twin.Revision = existing.Count == 0 ? 1 : Math.Max(1, existing[0].Revision) + 1; Store.Twins.Insert(0, twin); Save(ctx); AppendLedger(ctx, "TWIN_PROJECTED", twin.Id, sourceKind + ":" + sourceId + (existing.Count == 0 ? "" : " · source drift child of " + existing[0].Id), CyberneticsKernel.Fingerprint(twin), ""); OpenTwin(owner, ctx, index, twin);
        }

        private static void OpenHub(Window owner, DeepSystemsContext ctx, WorldIndex index)
        {
            Load(ctx); Window w = W(owner, "YOMI · CYBERNETIC DIGITAL TWIN METASTRUCTURE", 1320, 900); DockPanel root = Shell("CYBERNETIC DIGITAL TWIN METASTRUCTURE", "DEV13.37.17 · state estimation, control synthesis, constrained prediction, reachability, robustness and fault isolation · design authority only"); root.Children.Add(T(CensusLine(), 12, Blue, FontWeights.SemiBold)); WrapPanel cards = new WrapPanel { Margin = new Thickness(0, 12, 0, 0) };
            Portal(cards, "Σ", "TWIN REGISTRY", "Inspect versioned state-space twins and source-fingerprint branches.", delegate { OpenRegistry(w, ctx, index); });
            Portal(cards, "ẋ=Ax+Bu", "STATE-SPACE FORGE", "Create a bounded discrete or continuous linear cybernetic abstraction.", delegate { CreateTwin(w, ctx, index); });
            Portal(cards, "rank", "STRUCTURAL TRIBUNAL", "Controllability, observability, finite Gramians, conditioning and weak modes.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenRows(w, "STRUCTURAL TRIBUNAL", CyberneticsKernel.AnalyzeStructure(t), "Numerical structure of the declared linear abstraction"); }); });
            Portal(cards, "ρ(A)", "SPECTRAL STABILITY", "Approximate discrete pole magnitudes and open/closed-loop stability margins.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { CyberStructuralAnalysis s = CyberneticsKernel.AnalyzeStructure(t); CyberControllerSynthesis l = CyberneticsKernel.SynthesizeLqr(t, 2048, 1e-11); OpenRows(w, "SPECTRAL STABILITY", new object[] { s, l }, "Open-loop and synthesized closed-loop spectral envelopes"); }); });
            Portal(cards, "x[k+1]", "SIMULATION CHAMBER", "Deterministic bounded propagation with declared costs and constraint witnesses.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenSimulation(w, t); }); });
            Portal(cards, "Kₖ", "KALMAN OBSERVATORY", "Manual telemetry ingestion, innovation statistics and covariance-aware state estimates.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenTelemetry(w, ctx, t); }); });
            Portal(cards, "DARE", "RICCATI / LQR FOUNDRY", "Finite-iteration discrete Riccati synthesis with residual and spectral certificate.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenRows(w, "RICCATI / LQR", CyberneticsKernel.SynthesizeLqr(t, 4096, 1e-12), "Model-bound controller design artifact; no actuation authority"); }); });
            Portal(cards, "argmin J", "MPC HORIZON", "Projected-gradient constrained prediction respecting input and slew boxes.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { CyberMpcResult r = CyberneticsKernel.SolveMpc(t, null, 24, 768); OpenRows(w, "CONSTRAINED MPC", new object[] { r }.Concat(r.Prediction == null ? Enumerable.Empty<object>() : r.Prediction.Steps.Cast<object>()).ToArray(), "Prediction only · no plant execution"); }); });
            Portal(cards, "PID", "PID RESPONSE FOUNDRY", "FOPDT response identification and IMC-style proportional-integral-derivative tuning.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenRows(w, "PID RESPONSE FOUNDRY", CyberneticsKernel.TunePid(t, 0, 0, 256), "Declared channel approximation; independently validate any implementation"); }); });
            Portal(cards, "Xₖ", "REACHABILITY / VIABILITY", "Interval-box propagation and first unsafe envelope witness.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { CyberReachabilityResult r = CyberneticsKernel.AnalyzeReachability(t, 96); OpenRows(w, "REACHABILITY / VIABILITY", new object[] { r }.Concat(r.Steps.Cast<object>()).ToArray(), "Conservative interval over-approximation"); }); });
            Portal(cards, "Ω", "ROBUSTNESS MANIFOLD", "Halton stress worlds over declared model and initial-condition uncertainty.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { CyberRobustnessEnvelope r = CyberneticsKernel.AnalyzeRobustness(t, 512, 48, 1337); OpenRows(w, "ROBUSTNESS MANIFOLD", new object[] { r }.Concat(r.RetainedCases.Cast<object>()).ToArray(), "Deterministic stress coordinates, not calibrated probabilities"); }); });
            Portal(cards, "I(x;y)", "SENSOR PORTFOLIO", "Greedy cost-constrained output selection maximizing rank then information log-determinant.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenSensorSelection(w, t); }); });
            Portal(cards, "B†", "ACTUATOR ALLOCATION", "Bounded regularized least squares for desired one-step state displacement.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenAllocation(w, t); }); });
            Portal(cards, "r=y−ŷ", "RESIDUAL FAULT ISOLATION", "Gaussian residual signatures, diagonal covariance and normalized fault posteriors.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenFaultIsolation(w, t); }); });
            Portal(cards, "◇", "SNAPSHOT VAULT", "Capture estimator state and telemetry provenance under a SHA-256 certificate.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenSnapshots(w, ctx, t); }); });
            Portal(cards, "▣", "IMMUTABLE BASELINES", "Freeze full model JSON, parent lineage, reason and independently recomputable fingerprint.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenBaselines(w, ctx, t); }); });
            Portal(cards, "CERT", "CONTROL DOSSIERS", "Bind decisions to model fingerprints, analysis certificates, assumptions, risks and dissent.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenDossiers(w, ctx, t); }); });
            Portal(cards, "AUDIT", "MODEL AUDITOR", "Dimension, range, covariance, reference, rank and authority-boundary findings.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OpenRows(w, "MODEL AUDITOR", CyberneticsKernel.Audit(t).Cast<object>().ToArray(), "Internal coherence audit of the declared twin"); }); });
            Portal(cards, "⛓", "INTEGRITY LEDGER", "Verify the append-only SHA-256 chain across twin mutations and certificates.", delegate { OpenLedger(w, ctx); });
            Portal(cards, "DYSON", "SYSTEMS ENGINEERING", "Return to requirements, interfaces, reliability, trades, safety cases and configuration control.", delegate { DysonSystemsEngineeringMegastructure.Open(w, ctx); });
            Portal(cards, "A=K", "AXIOMATIC VERIFICATION", "Return to explicit state machines, invariants, fixed points and counterexample witnesses.", delegate { AxiomaticVerificationReactor.Open(w, ctx); });
            Portal(cards, "do(X)", "COUNTERFACTUAL STRATEGY", "Return to interventions, policies, uncertainty and minimax-regret decisions.", delegate { CounterfactualStrategySuperstructure.Open(w, ctx); });
            Portal(cards, "I(H;Y)", "SCIENTIFIC DISCOVERY", "Return to preregistered measurement and empirical calibration boundaries.", delegate { ScientificDiscoveryHyperstructure.Open(w, ctx); });
            Portal(cards, "ΣPOP", "COMPLEX SYSTEMS LABORATORY", "Project a linear state-space twin into a nonlinear interacting population for emergent feedback, cascade, attractor, resilience and finite-size phase analysis.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { ComplexSystemsLaboratory.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "ORΩ", "OPERATIONS RESEARCH EMPIRE", "Project twin states, controls, outputs and constraints into explicit allocation, schedule, network-flow and robust recourse models without granting plant authority.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { OperationsResearchEmpire.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "ECONΩ", "ECONOMIC CIVILIZATION", "Project twin states, controls and resource constraints into an economic shock and institution layer without replacing control-theoretic guarantees or granting plant authority.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { EconomicCivilization.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "GEOΩ", "SPATIAL WORLD CARTOGRAPHY", "Project twin sensors, actuators, states and dependencies into explicit coverage, placement and movement geography without replacing control guarantees.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { SpatialWorldCartography.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "DISTΩ", "DISTRIBUTED SYSTEMS PLANETARIUM", "Project a control twin into networked sensors, estimators, controllers and delayed channels while preserving upstream stability and estimation claims.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { DistributedSystemsPlanetarium.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "SECΩ", "ADVERSARIAL SECURITY FORTRESS", "Project a control twin into cyber-physical assets, trust boundaries, defensive loops and recovery assurance without live authority.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { AdversarialSecurityFortress.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "DATAΩ", "DATA FOUNDRY", "Project twin state, model metadata and evidence structure into immutable bounded data provenance.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { DataFoundry.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "GENOMEΩ", "SOFTWARE GENOME", "Project runtime/control assumptions into static source architecture context.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { SoftwareGenomeObservatory.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "DOCΩ", "LIVING DOCUMENT", "Project twin assumptions, estimates and control evidence into an auditable technical dossier.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { LivingDocumentIntelligenceFactory.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "EXPΩ", "EXPEDITION COMMAND", "Capture the active twin as a fingerprinted mission crossing with estimates, controls and dynamic evidence retained.", delegate { WithTwin(w, ctx, delegate(CyberTwinModel t) { GrandUnifiedExpeditionCommand.OpenFromCyberneticTwin(w, ctx, index, t); }); });
            Portal(cards, "HADAL", "HADAL DESCENT", "Descend into twins, analyses, telemetry, snapshots, baselines, dossiers and integrity records.", delegate { AbyssalKnowledgeEngine.DescendFromExternal(w, ctx, "Cybernetic Digital Twin Metastructure", Store, StorePath(ctx), "$cybernetic-twins", "CYBERNETIC TWIN"); });
            root.Children.Add(new ScrollViewer { Content = cards, VerticalScrollBarVisibility = ScrollBarVisibility.Auto }); w.Content = root; w.Show();
        }

        private static string CensusLine() { return Store.Twins.Count(x => Active(x.Status)).ToString(CultureInfo.InvariantCulture) + " active twins · " + Store.Twins.Sum(x => x.States.Count).ToString(CultureInfo.InvariantCulture) + " states · " + Store.Twins.Sum(x => x.Inputs.Count).ToString(CultureInfo.InvariantCulture) + " inputs · " + Store.Twins.Sum(x => x.Outputs.Count).ToString(CultureInfo.InvariantCulture) + " outputs · " + Store.Analyses.Count.ToString(CultureInfo.InvariantCulture) + " analyses · " + Store.Telemetry.Count.ToString(CultureInfo.InvariantCulture) + " telemetry frames · " + Store.Baselines.Count.ToString(CultureInfo.InvariantCulture) + " baselines"; }

        private static CyberTwinModel StarterTwin(string name, string charter)
        {
            CyberTwinModel t = new CyberTwinModel { Id = Id("twin"), Name = Short(name, 240), Charter = Short(charter, MaxLongText), Status = "CONCEPT", DynamicsKind = "DISCRETE", SamplePeriod = 1, ParameterUncertaintyFraction = 0.05, CreatedUtc = Now(), UpdatedUtc = Now(), Revision = 1 };
            t.States.AddRange(new[] { X("inventory", "Stored potential", "normalized", 0.45, 0, 1, 0.001, 1.0), X("throughput", "Delivered throughput", "normalized", 0.40, 0, 1, 0.002, 1.5), X("thermal", "Constraint pressure", "normalized", 0.20, 0, 1, 0.003, 2.5) });
            t.Inputs.AddRange(new[] { U("drive", "Drive allocation", "normalized", -0.4, 0.4, -0.08, 0.08, 0.15), U("cool", "Constraint relief", "normalized", 0, 0.35, -0.05, 0.05, 0.12) });
            t.Outputs.AddRange(new[] { Y("delivery", "Delivered capability", "normalized", 0.65, 0, 1, 0.01, 2, 2), Y("pressure", "Constraint pressure", "normalized", 0.20, 0, 1, 0.015, 3, 1) });
            t.A = M(new[] { 0.92, 0.03, 0.00 }, new[] { 0.08, 0.86, -0.03 }, new[] { 0.02, 0.12, 0.88 }); t.B = M(new[] { 0.10, 0.00 }, new[] { 0.16, 0.01 }, new[] { 0.08, -0.18 }); t.C = M(new[] { 0.00, 1.00, 0.00 }, new[] { 0.00, 0.00, 1.00 }); t.D = M(new[] { 0.00, 0.00 }, new[] { 0.00, 0.00 });
            t.Constraints.Add(new CyberConstraint { Id = "constraint-pressure", VariableKind = "OUTPUT", VariableId = "pressure", Name = "Pressure containment", Status = "ACTIVE", Minimum = 0, Maximum = 0.85, Hard = true, Penalty = 5000 });
            CyberFaultSignature nominal = new CyberFaultSignature { Id = "fault-nominal", Name = "Nominal residual field", Description = "Residuals remain centered on zero.", PriorWeight = 8 }, driveFault = new CyberFaultSignature { Id = "fault-drive-loss", Name = "Drive effectiveness loss", Description = "Delivery residual trends negative while pressure remains near nominal.", PriorWeight = 1 }, sensorBias = new CyberFaultSignature { Id = "fault-pressure-bias", Name = "Pressure sensor positive bias", Description = "Pressure residual trends positive.", PriorWeight = 1 }; foreach (CyberMeasuredOutput y in t.Outputs) { nominal.ResidualMeans[y.Id] = 0; nominal.ResidualVariances[y.Id] = y.MeasurementNoiseVariance; driveFault.ResidualMeans[y.Id] = Eq(y.Id, "delivery") ? -0.18 : 0; driveFault.ResidualVariances[y.Id] = y.MeasurementNoiseVariance * 2; sensorBias.ResidualMeans[y.Id] = Eq(y.Id, "pressure") ? 0.22 : 0; sensorBias.ResidualVariances[y.Id] = y.MeasurementNoiseVariance * 1.5; } t.FaultSignatures.AddRange(new[] { nominal, driveFault, sensorBias });
            t.Assumptions.Add("Starter coefficients, bounds, covariances, weights and signatures are editable declarations, not calibrated physical facts."); t.Assumptions.Add("This subsystem computes design artifacts and never acquires live telemetry or commands an actuator."); return t;
        }

        private static CyberTwinModel ProjectEngineering(EngineeringArchitecture architecture)
        {
            List<EngineeringComponent> components = (architecture.Components ?? new List<EngineeringComponent>()).Where(x => Active(x.Status)).Take(32).ToList(); if (components.Count == 0) return StarterTwin("Engineering twin · " + (architecture.Name ?? "Architecture"), architecture.Charter);
            CyberTwinModel t = NewProjected("Engineering twin · " + (architecture.Name ?? "Architecture"), "Linear reliability/capacity projection of a systems-engineering architecture. Component and interface declarations become a design abstraction only."); Dictionary<string, int> map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase); for (int i = 0; i < components.Count; i++) { EngineeringComponent component = components[i]; map[component.Id] = i; double rateSum = Math.Max(0, component.FailureRatePerHour) + Math.Max(0, component.RepairRatePerHour), declaredAvailability = rateSum > 0 ? Math.Max(0, component.RepairRatePerHour) / rateSum : 0.95, initial = Math.Max(0.05, Math.Min(1, declaredAvailability)); t.States.Add(X("component-" + component.Id, component.Name, "availability", initial, 0, 1, Math.Max(1e-8, component.FailureRatePerHour), Math.Max(0.1, component.Capacity))); t.States[i].EvidenceNodeIds.AddRange(component.EvidenceNodeIds ?? new List<string>()); }
            double[][] a = Z(components.Count, components.Count); for (int i = 0; i < components.Count; i++) a[i][i] = Math.Max(0.70, Math.Min(0.9999, 1 - Math.Max(0, components[i].FailureRatePerHour) * Math.Max(1, t.SamplePeriod))); foreach (EngineeringInterface edge in (architecture.Interfaces ?? new List<EngineeringInterface>()).Where(x => Active(x.Status))) { int from, to; if (!map.TryGetValue(edge.FromComponentId ?? "", out from) || !map.TryGetValue(edge.ToComponentId ?? "", out to)) continue; a[to][from] += Math.Min(0.06, 0.005 + Math.Abs(edge.Capacity) / (10000 + Math.Abs(edge.Capacity))); a[to][to] = Math.Max(0.60, a[to][to] - 0.005); } t.A = a;
            List<EngineeringComponent> controlComponents = components.Where(x => Eq(x.Kind, "CONTROL") || Eq(x.Kind, "BOUNDARY")).Take(8).ToList(); if (controlComponents.Count == 0) controlComponents.Add(components[0]); t.B = Z(components.Count, controlComponents.Count); for (int j = 0; j < controlComponents.Count; j++) { int i = map[controlComponents[j].Id]; t.Inputs.Add(U("control-" + controlComponents[j].Id, "Allocation · " + controlComponents[j].Name, "normalized", -0.2, 0.2, -0.04, 0.04, 0.2)); t.B[i][j] = 0.08; }
            List<EngineeringComponent> observed = components.Take(16).ToList(); t.C = Z(observed.Count, components.Count); t.D = Z(observed.Count, controlComponents.Count); for (int i = 0; i < observed.Count; i++) { int state = map[observed[i].Id]; t.Outputs.Add(Y("observe-" + observed[i].Id, "Observed · " + observed[i].Name, "availability", t.States[state].InitialValue, 0, 1, 0.0025, 1, 1)); t.C[i][state] = 1; }
            foreach (EngineeringFailureMode failure in (architecture.FailureModes ?? new List<EngineeringFailureMode>()).Where(x => Active(x.Status)).Take(MaxFaults)) { CyberFaultSignature f = new CyberFaultSignature { Id = "engineering-" + failure.Id, Name = failure.Name, Description = failure.Cause + " · " + failure.Effect, PriorWeight = Math.Max(1e-6, failure.Probability) }; foreach (CyberMeasuredOutput y in t.Outputs) { f.ResidualMeans[y.Id] = y.Id.EndsWith(failure.ComponentId ?? "", StringComparison.OrdinalIgnoreCase) ? -Math.Min(0.8, 0.05 + failure.Severity * 0.05) : 0; f.ResidualVariances[y.Id] = y.MeasurementNoiseVariance * 2; } f.EvidenceNodeIds.AddRange(failure.EvidenceNodeIds ?? new List<string>()); t.FaultSignatures.Add(f); } t.Assumptions.AddRange(architecture.Assumptions ?? new List<string>()); t.Assumptions.Add("Projected from engineering fingerprint " + SystemsEngineeringKernel.Fingerprint(architecture) + "; reliability and capacity coefficients require empirical calibration."); t.EvidenceNodeIds.AddRange(architecture.EvidenceNodeIds ?? new List<string>()); return t;
        }

        private static CyberTwinModel ProjectVerification(VerificationModel model)
        {
            List<VerificationState> states = (model.States ?? new List<VerificationState>()).Where(x => Active(x.Status)).Take(32).ToList(); if (states.Count == 0) return StarterTwin("Verification twin · " + (model.Name ?? "Model"), model.Description); CyberTwinModel t = NewProjected("Verification occupancy twin · " + (model.Name ?? "Model"), "Linear occupancy-flow abstraction projected from a formal transition system. It does not replace exact model checking."); Dictionary<string, int> map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase); for (int i = 0; i < states.Count; i++) { map[states[i].Id] = i; t.States.Add(X("formal-" + states[i].Id, states[i].Name, "occupancy", (model.InitialStateIds ?? new List<string>()).Contains(states[i].Id) ? 1 : 0, 0, 1, 0.0001, 1)); t.States[i].EvidenceNodeIds.AddRange(states[i].EvidenceNodeIds ?? new List<string>()); }
            t.A = Z(states.Count, states.Count); int[] outgoing = new int[states.Count]; foreach (VerificationTransition edge in (model.Transitions ?? new List<VerificationTransition>()).Where(x => Active(x.Status))) { int from, to; if (map.TryGetValue(edge.FromStateId ?? "", out from) && map.TryGetValue(edge.ToStateId ?? "", out to)) outgoing[from]++; } for (int i = 0; i < states.Count; i++) if (outgoing[i] == 0) t.A[i][i] = 0.98; foreach (VerificationTransition edge in (model.Transitions ?? new List<VerificationTransition>()).Where(x => Active(x.Status))) { int from, to; if (map.TryGetValue(edge.FromStateId ?? "", out from) && map.TryGetValue(edge.ToStateId ?? "", out to)) t.A[to][from] += 0.98 / Math.Max(1, outgoing[from]); }
            t.Inputs.Add(U("formal-perturbation", "Declared transition perturbation", "normalized", -0.1, 0.1, -0.02, 0.02, 0.5)); t.B = Z(states.Count, 1); t.B[0][0] = 0.02; int observed = Math.Min(16, states.Count); t.C = Z(observed, states.Count); t.D = Z(observed, 1); for (int i = 0; i < observed; i++) { t.Outputs.Add(Y("formal-observe-" + states[i].Id, "Occupancy · " + states[i].Name, "occupancy", t.States[i].InitialValue, 0, 1, 0.0001, 1, 1)); t.C[i][i] = 1; } t.Assumptions.Add("Linear occupancy projection is an analytic lens; exact temporal properties remain owned by the Axiomatic Verification Reactor."); t.EvidenceNodeIds.AddRange(model.EvidenceNodeIds ?? new List<string>()); return t;
        }

        private static CyberTwinModel ProjectStrategy(StrategyModel model)
        {
            List<StrategyVariable> variables = (model.Variables ?? new List<StrategyVariable>()).Where(x => Active(x.Status)).Take(32).ToList(); if (variables.Count == 0) return StarterTwin("Strategy twin · " + (model.Name ?? "Model"), model.Charter); CyberTwinModel t = NewProjected("Strategy dynamics twin · " + (model.Name ?? "Model"), "Linear dynamic projection of a structural causal strategy model. Causal coefficients remain hypotheses and do not become actuator gains."); Dictionary<string, int> map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase); for (int i = 0; i < variables.Count; i++) { StrategyVariable v = variables[i]; map[v.Id] = i; t.States.Add(X("strategy-" + v.Id, v.Name, v.Unit, v.Baseline, v.Minimum, v.Maximum, v.Uncertain ? 0.01 : 0.0001, 1)); t.States[i].EvidenceNodeIds.AddRange(v.EvidenceNodeIds ?? new List<string>()); } t.A = Z(variables.Count, variables.Count); for (int i = 0; i < variables.Count; i++) t.A[i][i] = 0.82; foreach (StrategyEdge edge in (model.Edges ?? new List<StrategyEdge>()).Where(x => Active(x.Status))) { int from, to; if (map.TryGetValue(edge.FromVariableId ?? "", out from) && map.TryGetValue(edge.ToVariableId ?? "", out to)) t.A[to][from] += Math.Max(-0.15, Math.Min(0.15, edge.Coefficient * 0.05)); }
            List<StrategyVariable> decisions = variables.Where(x => Eq(x.Kind, "DECISION")).Take(8).ToList(); if (decisions.Count == 0) decisions.Add(variables[0]); t.B = Z(variables.Count, decisions.Count); for (int j = 0; j < decisions.Count; j++) { int i = map[decisions[j].Id]; double span = Math.Max(1e-6, decisions[j].Maximum - decisions[j].Minimum); t.Inputs.Add(U("do-" + decisions[j].Id, "do(" + decisions[j].Name + ")", decisions[j].Unit, -span * 0.1, span * 0.1, -span * 0.02, span * 0.02, 0.2)); t.B[i][j] = 0.25; }
            List<StrategyVariable> outcomes = variables.Where(x => Eq(x.Kind, "OUTCOME")).Take(16).ToList(); if (outcomes.Count == 0) outcomes = variables.Take(16).ToList(); t.C = Z(outcomes.Count, variables.Count); t.D = Z(outcomes.Count, decisions.Count); for (int i = 0; i < outcomes.Count; i++) { int state = map[outcomes[i].Id]; t.Outputs.Add(Y("outcome-" + outcomes[i].Id, outcomes[i].Name, outcomes[i].Unit, outcomes[i].Baseline, outcomes[i].Minimum, outcomes[i].Maximum, outcomes[i].Uncertain ? 0.01 : 0.001, 1, 1)); t.C[i][state] = 1; } foreach (StrategyConstraint constraint in model.Constraints ?? new List<StrategyConstraint>()) if (Active(constraint.Status) && map.ContainsKey(constraint.VariableId ?? "")) t.Constraints.Add(new CyberConstraint { Id = "strategy-" + constraint.Id, VariableKind = "STATE", VariableId = "strategy-" + constraint.VariableId, Name = constraint.Name, Status = "ACTIVE", Minimum = Eq(constraint.Operator, ">=") ? constraint.Threshold : variables[map[constraint.VariableId]].Minimum, Maximum = Eq(constraint.Operator, "<=") ? constraint.Threshold : variables[map[constraint.VariableId]].Maximum, Hard = Eq(constraint.Severity, "HARD"), Penalty = constraint.Penalty }); t.Assumptions.AddRange(model.Assumptions ?? new List<string>()); t.Assumptions.Add("Projected from strategy fingerprint " + CounterfactualStrategyKernel.Fingerprint(model) + "; causal identification and transportability remain unresolved."); t.EvidenceNodeIds.AddRange(model.EvidenceNodeIds ?? new List<string>()); return t;
        }

        private static CyberTwinModel ProjectDiscovery(DiscoveryProtocol protocol)
        {
            List<DiscoveryOutcome> outcomes = (protocol.Outcomes ?? new List<DiscoveryOutcome>()).Where(x => Active(x.Status)).Take(32).ToList(); if (outcomes.Count == 0) return StarterTwin("Discovery twin · " + (protocol.Name ?? "Protocol"), protocol.Charter); CyberTwinModel t = NewProjected("Discovery response twin · " + (protocol.Name ?? "Protocol"), "Linear response-state projection of a preregistered discovery protocol. Design priors do not become observations."); for (int i = 0; i < outcomes.Count; i++) { DiscoveryOutcome o = outcomes[i]; double span = Math.Max(1, Math.Abs(o.RelevantEffect) * 10); t.States.Add(X("outcome-" + o.Id, o.Name, o.Unit, 0, -span, span, Math.Max(1e-8, o.NoiseSigma * o.NoiseSigma), 1)); } t.A = Z(outcomes.Count, outcomes.Count); for (int i = 0; i < outcomes.Count; i++) t.A[i][i] = 0.90;
            List<DiscoveryFactor> factors = (protocol.Factors ?? new List<DiscoveryFactor>()).Where(x => Active(x.Status) && x.Controllable).Take(16).ToList(); if (factors.Count == 0) factors.Add(new DiscoveryFactor { Id = "declared-factor", Name = "Declared factor", Minimum = -1, Maximum = 1, Controllable = true }); t.B = Z(outcomes.Count, factors.Count); for (int j = 0; j < factors.Count; j++) { DiscoveryFactor f = factors[j]; double span = Math.Max(1e-6, f.Maximum - f.Minimum); t.Inputs.Add(U("factor-" + f.Id, f.Name, f.Unit, f.Minimum, f.Maximum, -span * 0.25, span * 0.25, 0.1)); for (int i = 0; i < outcomes.Count; i++) t.B[i][j] = 0.02 * (1 + ((i + j) % 3)); }
            t.C = Z(outcomes.Count, outcomes.Count); t.D = Z(outcomes.Count, factors.Count); for (int i = 0; i < outcomes.Count; i++) { DiscoveryOutcome o = outcomes[i]; t.Outputs.Add(Y("measure-" + o.Id, o.Name, o.Unit, 0, t.States[i].Minimum, t.States[i].Maximum, Math.Max(1e-8, o.NoiseSigma * o.NoiseSigma), 1, 1)); t.C[i][i] = 1; } t.Assumptions.AddRange(protocol.Assumptions ?? new List<string>()); t.Assumptions.Add("Projected from preregistration fingerprint " + ExperimentalDesignKernel.ProtocolFingerprint(protocol) + "; coefficients are placeholders until observations are imported manually."); t.EvidenceNodeIds.AddRange(protocol.EvidenceNodeIds ?? new List<string>()); return t;
        }

        private static CyberTwinModel NewProjected(string name, string charter) { return new CyberTwinModel { Name = Short(name, 240), Charter = Short(charter, MaxLongText), Status = "CONCEPT", DynamicsKind = "DISCRETE", SamplePeriod = 1, ParameterUncertaintyFraction = 0.08, CreatedUtc = Now(), UpdatedUtc = Now(), Revision = 1 }; }

        private static void OpenRegistry(Window owner, DeepSystemsContext ctx, WorldIndex index) { Window w = W(owner, "YOMI · TWIN REGISTRY", 1200, 800); DockPanel root = Shell("TWIN REGISTRY", CensusLine()); ListBox list = List(); list.ItemsSource = Store.Twins.OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).ToList(); list.MouseDoubleClick += delegate { CyberTwinModel t = list.SelectedItem as CyberTwinModel; if (t != null) OpenTwin(w, ctx, index, t); }; WrapPanel actions = new WrapPanel(); actions.Children.Add(Btn("OPEN", delegate { CyberTwinModel t = list.SelectedItem as CyberTwinModel; if (t != null) OpenTwin(w, ctx, index, t); })); actions.Children.Add(Btn("NEW TWIN", delegate { CreateTwin(w, ctx, index); })); DockPanel.SetDock(actions, Dock.Bottom); root.Children.Add(actions); root.Children.Add(list); w.Content = root; w.Show(); }

        private static void CreateTwin(Window owner, DeepSystemsContext ctx, WorldIndex index) { string name = Prompt(owner, "STATE-SPACE FORGE", "Twin name", "Untitled cybernetic twin"); if (String.IsNullOrWhiteSpace(name)) return; string charter = PromptLarge(owner, "STATE-SPACE FORGE", "Charter and authority boundary", "Declare the system boundary, state meaning, observation assumptions, admissible controls and prohibited authority."); if (charter == null) return; CyberTwinModel t = StarterTwin(name, charter); Store.Twins.Insert(0, t); Save(ctx); AppendLedger(ctx, "TWIN_CREATED", t.Id, t.Name, CyberneticsKernel.Fingerprint(t), ""); OpenTwin(owner, ctx, index, t); }

        private static void OpenTwin(Window owner, DeepSystemsContext ctx, WorldIndex index, CyberTwinModel twin)
        {
            if (twin == null) return; Window w = W(owner, "YOMI · " + (twin.Name ?? "DIGITAL TWIN"), 1320, 860); DockPanel root = Shell(twin.Name ?? "DIGITAL TWIN", twin.ToString() + "\n" + (twin.Charter ?? "")); WrapPanel actions = new WrapPanel { Margin = new Thickness(0, 4, 0, 8) };
            actions.Children.Add(Btn("FULL ANALYSIS", delegate { RunFullAnalysis(w, ctx, twin); })); actions.Children.Add(Btn("TELEMETRY", delegate { OpenTelemetry(w, ctx, twin); })); actions.Children.Add(Btn("SIMULATE", delegate { OpenSimulation(w, twin); })); actions.Children.Add(Btn("COMPLEX POPULATION", delegate { ComplexSystemsLaboratory.OpenFromCyberneticTwin(w, ctx, index, twin); })); actions.Children.Add(Btn("RESOURCE OPTIMIZATION", delegate { OperationsResearchEmpire.OpenFromCyberneticTwin(w, ctx, index, twin); })); actions.Children.Add(Btn("SNAPSHOT", delegate { CaptureSnapshot(w, ctx, twin); })); actions.Children.Add(Btn("FREEZE BASELINE", delegate { FreezeBaseline(w, ctx, twin); })); actions.Children.Add(Btn("DOSSIER", delegate { OpenDossiers(w, ctx, twin); })); actions.Children.Add(Btn("AUDIT", delegate { OpenRows(w, "MODEL AUDITOR", CyberneticsKernel.Audit(twin).Cast<object>().ToArray(), CyberneticsKernel.Fingerprint(twin)); })); actions.Children.Add(Btn("EDIT CHARTER", delegate { string value = PromptLarge(w, "TWIN CHARTER", "Charter", twin.Charter); if (value != null) { twin.Charter = Short(value, MaxLongText); Touch(twin); Save(ctx); AppendLedger(ctx, "CHARTER_CHANGED", twin.Id, "charter updated", CyberneticsKernel.Fingerprint(twin), ""); } })); DockPanel.SetDock(actions, Dock.Top); root.Children.Add(actions);
            Grid grid = new Grid(); grid.ColumnDefinitions.Add(new ColumnDefinition()); grid.ColumnDefinitions.Add(new ColumnDefinition()); grid.RowDefinitions.Add(new RowDefinition()); grid.RowDefinitions.Add(new RowDefinition()); ListBox states = List(), io = List(), assumptions = List(), analyses = List(); states.ItemsSource = twin.States.Cast<object>().Concat(twin.Constraints.Cast<object>()).ToList(); io.ItemsSource = twin.Inputs.Cast<object>().Concat(twin.Outputs.Cast<object>()).Concat(twin.FaultSignatures.Cast<object>()).ToList(); assumptions.ItemsSource = new object[] { "FINGERPRINT · " + CyberneticsKernel.Fingerprint(twin), "SOURCE · " + (twin.SourceKind ?? "LOCAL") + ":" + (twin.SourceId ?? twin.Id), "SOURCE FINGERPRINT · " + (twin.SourceFingerprint ?? "∅") }.Concat(twin.Assumptions.Cast<object>()).ToList(); analyses.ItemsSource = Store.Analyses.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.CreatedUtc).ToList(); AddGrid(grid, states, 0, 0); AddGrid(grid, io, 0, 1); AddGrid(grid, assumptions, 1, 0); AddGrid(grid, analyses, 1, 1); root.Children.Add(grid); w.Content = root; w.Show();
        }

        private static void RunFullAnalysis(Window owner, DeepSystemsContext ctx, CyberTwinModel twin)
        {
            string fingerprint = CyberneticsKernel.Fingerprint(twin); CyberTwinAnalysisRecord r = new CyberTwinAnalysisRecord { Id = Id("analysis"), TwinId = twin.Id, CreatedUtc = Now(), TwinFingerprint = fingerprint }; r.Structure = CyberneticsKernel.AnalyzeStructure(twin); r.Lqr = CyberneticsKernel.SynthesizeLqr(twin, 4096, 1e-12); r.Pid = CyberneticsKernel.TunePid(twin, 0, 0, 256); r.Mpc = CyberneticsKernel.SolveMpc(twin, null, 24, 768); r.Reachability = CyberneticsKernel.AnalyzeReachability(twin, 96); r.Robustness = CyberneticsKernel.AnalyzeRobustness(twin, 512, 48, 1337); r.Sensors = CyberneticsKernel.SelectSensors(twin, twin.Outputs.Sum(x => Math.Max(0, x.SensorCost)) * 0.6); r.Audit = CyberneticsKernel.Audit(twin); r.CertificateHash = HashText(fingerprint + "|" + r.CreatedUtc + "|" + Json.Serialize(r.Structure) + "|" + Json.Serialize(r.Lqr) + "|" + Json.Serialize(r.Pid) + "|" + Json.Serialize(r.Mpc) + "|" + Json.Serialize(r.Reachability) + "|" + Json.Serialize(r.Robustness) + "|" + Json.Serialize(r.Sensors) + "|" + String.Join("|", r.Audit.ToArray())); Store.Analyses.Insert(0, r); Save(ctx); AppendLedger(ctx, "ANALYSIS_CERTIFIED", twin.Id, r.Id, fingerprint, r.CertificateHash); OpenRows(owner, "CYBERNETIC ANALYSIS CERTIFICATE", new object[] { r, r.Structure, r.Lqr, r.Pid, r.Mpc, r.Reachability, r.Robustness, r.Sensors }.Concat(r.Audit.Cast<object>()).ToArray(), r.CertificateHash);
        }

        private static void OpenSimulation(Window owner, CyberTwinModel twin) { string raw = Prompt(owner, "SIMULATION CHAMBER", "Horizon (1–512)", "48"); if (raw == null) return; int horizon = Math.Max(1, Math.Min(512, (int)Number(raw, 48))); CyberControllerSynthesis lqr = CyberneticsKernel.SynthesizeLqr(twin, 2048, 1e-11); double[][] controls = Enumerable.Range(0, horizon).Select(k => new double[twin.Inputs.Count]).ToArray(); CyberSimulationResult r = CyberneticsKernel.Simulate(twin, null, controls); r.ControllerKind = "ZERO_INPUT_DECLARED_BASELINE"; OpenRows(owner, "SIMULATION CHAMBER", new object[] { r, lqr }.Concat(r.Steps.Cast<object>()).ToArray(), "Deterministic propagation only · no live plant, process or actuator"); }

        private static void OpenTelemetry(Window owner, DeepSystemsContext ctx, CyberTwinModel twin)
        {
            Window w = W(owner, "YOMI · KALMAN OBSERVATORY", 1200, 780); DockPanel root = Shell("KALMAN OBSERVATORY · " + twin.Name, "Manual declarations only · expected input order: " + String.Join(", ", twin.Inputs.Select(x => x.Id).ToArray()) + " · output order: " + String.Join(", ", twin.Outputs.Select(x => x.Id).ToArray())); ListBox list = List(); Action refresh = delegate { list.ItemsSource = Store.Telemetry.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.Sequence).Take(4096).ToList(); }; refresh(); WrapPanel buttons = new WrapPanel(); buttons.Children.Add(Btn("APPEND FRAME", delegate { string inputRaw = Prompt(w, "MANUAL TELEMETRY", "Input vector, comma-separated", String.Join(",", Enumerable.Repeat("0", twin.Inputs.Count).ToArray())); if (inputRaw == null) return; string outputRaw = Prompt(w, "MANUAL TELEMETRY", "Observed output vector, comma-separated", String.Join(",", twin.Outputs.Select(x => x.Target.ToString("R", CultureInfo.InvariantCulture)).ToArray())); if (outputRaw == null) return; string effective = Prompt(w, "MANUAL TELEMETRY", "Effective time or external sequence label (provenance text)", Now()); if (effective == null) return; AppendTelemetry(ctx, twin, Vector(inputRaw, twin.Inputs.Count), Vector(outputRaw, twin.Outputs.Count), effective); refresh(); })); buttons.Children.Add(Btn("ESTIMATOR TRACE", delegate { List<CyberTelemetryFrame> frames = Store.Telemetry.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.Sequence).Take(4096).OrderBy(x => x.Sequence).ToList(); CyberKalmanResult r = CyberneticsKernel.Estimate(twin, frames.Select(x => x.Input).ToList(), frames.Select(x => x.Output).ToList(), null, 1); OpenRows(w, "KALMAN ESTIMATOR TRACE", new object[] { r }.Concat(r.Steps.Cast<object>()).ToArray(), "Manual telemetry provenance · no sensor acquisition"); })); buttons.Children.Add(Btn("CAPTURE SNAPSHOT", delegate { CaptureSnapshot(w, ctx, twin); })); DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(list); w.Content = root; w.Show();
        }

        private static void AppendTelemetry(DeepSystemsContext ctx, CyberTwinModel twin, double[] input, double[] output, string effective)
        {
            List<CyberTelemetryFrame> prior = Store.Telemetry.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.Sequence).Take(4096).OrderBy(x => x.Sequence).ToList(); List<double[]> controls = prior.Select(x => x.Input).Concat(new[] { input }).ToList(), observations = prior.Select(x => x.Output).Concat(new[] { output }).ToList(); CyberKalmanResult estimate = CyberneticsKernel.Estimate(twin, controls, observations, null, 1); CyberKalmanStep last = estimate.Steps.LastOrDefault(); CyberTelemetryFrame frame = new CyberTelemetryFrame { Id = Id("telemetry"), TwinId = twin.Id, Sequence = prior.Count == 0 ? 1 : prior.Max(x => x.Sequence) + 1, CapturedUtc = Now(), EffectiveTime = Short(effective, 512), SourceKind = "MANUAL_DECLARATION", SourceReference = "operator-entered vector", TwinFingerprint = CyberneticsKernel.Fingerprint(twin), Input = input, Output = output, EstimatedState = last == null ? twin.States.Select(x => x.InitialValue).ToArray() : last.PosteriorState, Innovation = last == null ? new double[twin.Outputs.Count] : last.Innovation, InnovationMahalanobis = last == null ? 0 : last.InnovationMahalanobis }; Store.Telemetry.Insert(0, frame); Save(ctx); AppendLedger(ctx, "TELEMETRY_DECLARED", twin.Id, "frame " + frame.Sequence + " · manual source", frame.TwinFingerprint, "");
        }

        private static void OpenSnapshots(Window owner, DeepSystemsContext ctx, CyberTwinModel twin) { Window w = W(owner, "YOMI · SNAPSHOT VAULT", 1100, 720); DockPanel root = Shell("SNAPSHOT VAULT · " + twin.Name, "Estimator-state certificates bound to manual telemetry and a model fingerprint"); ListBox list = List(); Action refresh = delegate { list.ItemsSource = Store.Snapshots.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.CapturedUtc).ToList(); }; refresh(); Button capture = Btn("CAPTURE", delegate { CaptureSnapshot(w, ctx, twin); refresh(); }); DockPanel.SetDock(capture, Dock.Bottom); root.Children.Add(capture); root.Children.Add(list); w.Content = root; w.Show(); }
        private static void CaptureSnapshot(Window owner, DeepSystemsContext ctx, CyberTwinModel twin) { string name = Prompt(owner, "CAPTURE SNAPSHOT", "Snapshot name", "Estimator snapshot · " + Now()); if (String.IsNullOrWhiteSpace(name)) return; CyberTelemetryFrame frame = Store.Telemetry.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.Sequence).FirstOrDefault(); CyberTwinSnapshot s = new CyberTwinSnapshot { Id = Id("snapshot"), TwinId = twin.Id, Name = Short(name, 240), CapturedUtc = Now(), TwinFingerprint = CyberneticsKernel.Fingerprint(twin), SourceTelemetryFrameId = frame == null ? null : frame.Id, EstimatedState = frame == null ? twin.States.Select(x => x.InitialValue).ToArray() : (double[])frame.EstimatedState.Clone(), LastInput = frame == null ? new double[twin.Inputs.Count] : (double[])frame.Input.Clone(), LastOutput = frame == null ? new double[twin.Outputs.Count] : (double[])frame.Output.Clone() }; s.Assumptions.Add(frame == null ? "No telemetry frame existed; snapshot uses declared initial state." : "State estimate derives exclusively from manually declared telemetry through the model-bound estimator."); s.CertificateHash = HashText(s.Id + "|" + s.TwinId + "|" + s.Name + "|" + s.CapturedUtc + "|" + s.TwinFingerprint + "|" + s.SourceTelemetryFrameId + "|" + Join(s.EstimatedState) + "|" + Join(s.LastInput) + "|" + Join(s.LastOutput) + "|" + String.Join("|", s.Assumptions.ToArray())); Store.Snapshots.Insert(0, s); Save(ctx); AppendLedger(ctx, "SNAPSHOT_CERTIFIED", twin.Id, s.Id, s.TwinFingerprint, s.CertificateHash); }

        private static void OpenBaselines(Window owner, DeepSystemsContext ctx, CyberTwinModel twin) { Window w = W(owner, "YOMI · IMMUTABLE TWIN BASELINES", 1100, 720); DockPanel root = Shell("IMMUTABLE TWIN BASELINES · " + twin.Name, "Full model JSON, lineage, reason and recomputable SHA-256 fingerprint"); ListBox list = List(); Action refresh = delegate { list.ItemsSource = Store.Baselines.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.FrozenUtc).ToList(); }; refresh(); WrapPanel buttons = new WrapPanel(); buttons.Children.Add(Btn("FREEZE", delegate { FreezeBaseline(w, ctx, twin); refresh(); })); buttons.Children.Add(Btn("VERIFY", delegate { CyberTwinBaseline b = list.SelectedItem as CyberTwinBaseline; if (b != null) MessageBox.Show(w, Eq(b.BaselineFingerprint, BaselineHash(b)) ? "BASELINE VERIFIED\n" + b.BaselineFingerprint : "BASELINE FINGERPRINT MISMATCH", "YOMI · BASELINE INTEGRITY", MessageBoxButton.OK, Eq(b.BaselineFingerprint, BaselineHash(b)) ? MessageBoxImage.Information : MessageBoxImage.Error); })); DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(list); w.Content = root; w.Show(); }
        private static void FreezeBaseline(Window owner, DeepSystemsContext ctx, CyberTwinModel twin) { string name = Prompt(owner, "FREEZE TWIN BASELINE", "Immutable baseline name", (twin.Name ?? "Twin") + " · r" + twin.Revision); if (String.IsNullOrWhiteSpace(name)) return; string reason = PromptLarge(owner, "FREEZE TWIN BASELINE", "Reason, boundary and known limitations", "Freeze the declared model for traceable analysis and review. This baseline grants no runtime or actuator authority."); if (reason == null) return; CyberTwinBaseline parent = Store.Baselines.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.FrozenUtc).FirstOrDefault(); CyberTwinBaseline b = new CyberTwinBaseline { Id = Id("baseline"), TwinId = twin.Id, ParentBaselineId = parent == null ? null : parent.Id, Name = Short(name, 240), Status = "FROZEN", FrozenUtc = Now(), Reason = Short(reason, MaxLongText), TwinFingerprint = CyberneticsKernel.Fingerprint(twin), SnapshotJson = Json.Serialize(twin) }; b.BaselineFingerprint = BaselineHash(b); Store.Baselines.Insert(0, b); Save(ctx); AppendLedger(ctx, "BASELINE_FROZEN", twin.Id, b.Id + " · " + b.Name, b.TwinFingerprint, b.BaselineFingerprint); }
        private static string BaselineHash(CyberTwinBaseline b) { return b == null ? HashText("NULL_BASELINE") : HashText("CYBER_BASELINE_V1|" + b.Id + "|" + b.TwinId + "|" + b.ParentBaselineId + "|" + b.Name + "|" + b.Status + "|" + b.FrozenUtc + "|" + b.Reason + "|" + b.TwinFingerprint + "|" + b.SnapshotJson); }

        private static void OpenDossiers(Window owner, DeepSystemsContext ctx, CyberTwinModel twin) { Window w = W(owner, "YOMI · CONTROL DOSSIERS", 1140, 760); DockPanel root = Shell("CONTROL DOSSIERS · " + twin.Name, "Decision provenance with explicit assumptions, risks, dissent and prohibited authority"); ListBox list = List(); Action refresh = delegate { list.ItemsSource = Store.Dossiers.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).ToList(); }; refresh(); WrapPanel buttons = new WrapPanel(); buttons.Children.Add(Btn("NEW DOSSIER", delegate { CyberTwinAnalysisRecord analysis = Store.Analyses.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.CreatedUtc).FirstOrDefault(); CyberTwinBaseline baseline = Store.Baselines.Where(x => Eq(x.TwinId, twin.Id)).OrderByDescending(x => x.FrozenUtc).FirstOrDefault(); string title = Prompt(w, "CONTROL DOSSIER", "Decision title", "Control design review · " + twin.Name); if (String.IsNullOrWhiteSpace(title)) return; string decision = PromptLarge(w, "CONTROL DOSSIER", "Decision, rationale and rejected alternatives", "Document the bounded design decision. Do not represent model output as deployment authorization."); if (decision == null) return; CyberControlDossier d = new CyberControlDossier { Id = Id("dossier"), TwinId = twin.Id, AnalysisId = analysis == null ? null : analysis.Id, BaselineId = baseline == null ? null : baseline.Id, Title = Short(title, 240), CreatedUtc = Now(), UpdatedUtc = Now(), Decision = Short(decision, MaxLongText), TwinFingerprint = CyberneticsKernel.Fingerprint(twin), AnalysisCertificate = analysis == null ? null : analysis.CertificateHash }; d.Assumptions.AddRange(twin.Assumptions); if (analysis == null) d.Risks.Add("No certified cybernetic analysis is attached."); if (baseline == null) d.Risks.Add("No immutable twin baseline is attached."); d.Dissent.Add("Unrecorded dissent is not evidence of consensus."); Store.Dossiers.Insert(0, d); Save(ctx); AppendLedger(ctx, "DOSSIER_CREATED", twin.Id, d.Id, d.TwinFingerprint, d.AnalysisCertificate); refresh(); })); buttons.Children.Add(Btn("OPEN", delegate { CyberControlDossier d = list.SelectedItem as CyberControlDossier; if (d != null) OpenRows(w, "CONTROL DOSSIER", new object[] { d, "DECISION · " + d.Decision, "AUTHORITY · " + d.AuthorityBoundary }.Concat(d.Assumptions.Select(x => (object)("ASSUMPTION · " + x))).Concat(d.Risks.Select(x => (object)("RISK · " + x))).Concat(d.Dissent.Select(x => (object)("DISSENT · " + x))).ToArray(), d.TwinFingerprint); })); DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(list); w.Content = root; w.Show(); }

        private static void OpenSensorSelection(Window owner, CyberTwinModel twin) { string raw = Prompt(owner, "SENSOR PORTFOLIO", "Sensor budget", twin.Outputs.Sum(x => Math.Max(0, x.SensorCost)).ToString("R", CultureInfo.InvariantCulture)); if (raw == null) return; CyberSensorSelection r = CyberneticsKernel.SelectSensors(twin, Number(raw, 0)); OpenRows(owner, "SENSOR PORTFOLIO", new object[] { r }.Concat(r.MarginalTrace.Cast<object>()).ToArray(), "Rank-first, information-second greedy design portfolio"); }
        private static void OpenAllocation(Window owner, CyberTwinModel twin) { string raw = Prompt(owner, "ACTUATOR ALLOCATION", "Desired state delta, comma-separated · " + String.Join(", ", twin.States.Select(x => x.Id).ToArray()), String.Join(",", Enumerable.Repeat("0", twin.States.Count).ToArray())); if (raw == null) return; CyberActuatorAllocation r = CyberneticsKernel.AllocateActuators(twin, Vector(raw, twin.States.Count), 2048); OpenRows(owner, "ACTUATOR ALLOCATION", new object[] { r }.Concat(r.Audit.Cast<object>()).ToArray(), "Bounded least-squares design calculation · sends no command"); }
        private static void OpenFaultIsolation(Window owner, CyberTwinModel twin) { string raw = Prompt(owner, "RESIDUAL FAULT ISOLATION", "Residuals as outputId=value, comma-separated", String.Join(",", twin.Outputs.Select(x => x.Id + "=0").ToArray())); if (raw == null) return; Dictionary<string, double> residuals = Pairs(raw); CyberFaultDiagnosis r = CyberneticsKernel.DiagnoseFault(twin, residuals); OpenRows(owner, "RESIDUAL FAULT ISOLATION", new object[] { r }.Concat(r.Scores.Cast<object>()).Concat(r.Audit.Cast<object>()).ToArray(), "Conditional posterior over declared signatures only"); }

        private static void OpenLedger(Window owner, DeepSystemsContext ctx) { List<CyberTwinLedgerRecord> rows = ReadLedger(ctx, 16384); OpenRows(owner, "CYBERNETIC INTEGRITY LEDGER", new object[] { VerifyLedger(rows) }.Concat(rows.OrderByDescending(x => x.Sequence).Cast<object>()).ToArray(), "Append-only SHA-256 chain · " + LedgerPath(ctx)); }

        private static void WithTwin(Window owner, DeepSystemsContext ctx, Action<CyberTwinModel> action) { CyberTwinModel twin = ChooseObject(owner, "SELECT DIGITAL TWIN", "Choose an active cybernetic boundary", Store.Twins.Where(x => Active(x.Status)).OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).Cast<object>().ToList()) as CyberTwinModel; if (twin != null && action != null) action(twin); }

        private static void Load(DeepSystemsContext ctx) { lock (Gate) { if (Store != null && Eq(LoadedRoot, ctx.StateRoot)) return; LoadedRoot = ctx.StateRoot; Store = null; string path = StorePath(ctx); if (File.Exists(path)) try { Store = Json.Deserialize<CyberneticTwinStore>(File.ReadAllText(path, Encoding.UTF8)); } catch { PreserveCorrupt(path); } if (Store == null && File.Exists(path + ".previous")) try { Store = Json.Deserialize<CyberneticTwinStore>(File.ReadAllText(path + ".previous", Encoding.UTF8)); } catch { } if (Store == null) Store = new CyberneticTwinStore(); NormalizeStore(); } }
        private static void NormalizeStore() { if (Store == null) Store = new CyberneticTwinStore(); Store.Schema = 1; Store.Twins = Store.Twins ?? new List<CyberTwinModel>(); Store.Analyses = Store.Analyses ?? new List<CyberTwinAnalysisRecord>(); Store.Telemetry = Store.Telemetry ?? new List<CyberTelemetryFrame>(); Store.Snapshots = Store.Snapshots ?? new List<CyberTwinSnapshot>(); Store.Baselines = Store.Baselines ?? new List<CyberTwinBaseline>(); Store.Dossiers = Store.Dossiers ?? new List<CyberControlDossier>(); Store.RecentQuestions = Store.RecentQuestions ?? new List<string>(); foreach (CyberTwinModel t in Store.Twins) { t.States = (t.States ?? new List<CyberStateVariable>()).Take(MaxStates).ToList(); t.Inputs = (t.Inputs ?? new List<CyberControlInput>()).Take(MaxInputs).ToList(); t.Outputs = (t.Outputs ?? new List<CyberMeasuredOutput>()).Take(MaxOutputs).ToList(); t.Constraints = (t.Constraints ?? new List<CyberConstraint>()).Take(MaxConstraints).ToList(); t.FaultSignatures = (t.FaultSignatures ?? new List<CyberFaultSignature>()).Take(MaxFaults).ToList(); t.Assumptions = t.Assumptions ?? new List<string>(); t.EvidenceNodeIds = (t.EvidenceNodeIds ?? new List<string>()).Take(MaxEvidence).ToList(); t.A = t.A ?? new double[0][]; t.B = t.B ?? new double[0][]; t.C = t.C ?? new double[0][]; t.D = t.D ?? new double[0][]; foreach (CyberStateVariable x in t.States) x.EvidenceNodeIds = x.EvidenceNodeIds ?? new List<string>(); foreach (CyberControlInput u in t.Inputs) u.EvidenceNodeIds = u.EvidenceNodeIds ?? new List<string>(); foreach (CyberMeasuredOutput y in t.Outputs) y.EvidenceNodeIds = y.EvidenceNodeIds ?? new List<string>(); foreach (CyberFaultSignature f in t.FaultSignatures) { f.ResidualMeans = f.ResidualMeans ?? new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase); f.ResidualVariances = f.ResidualVariances ?? new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase); f.EvidenceNodeIds = f.EvidenceNodeIds ?? new List<string>(); } } foreach (CyberTwinAnalysisRecord a in Store.Analyses) a.Audit = a.Audit ?? new List<string>(); foreach (CyberTelemetryFrame f in Store.Telemetry) { f.Input = f.Input ?? new double[0]; f.Output = f.Output ?? new double[0]; f.EstimatedState = f.EstimatedState ?? new double[0]; f.Innovation = f.Innovation ?? new double[0]; } foreach (CyberTwinSnapshot s in Store.Snapshots) { s.EstimatedState = s.EstimatedState ?? new double[0]; s.LastInput = s.LastInput ?? new double[0]; s.LastOutput = s.LastOutput ?? new double[0]; s.Assumptions = s.Assumptions ?? new List<string>(); } foreach (CyberControlDossier d in Store.Dossiers) { d.Assumptions = d.Assumptions ?? new List<string>(); d.Risks = d.Risks ?? new List<string>(); d.Dissent = d.Dissent ?? new List<string>(); d.EvidenceNodeIds = d.EvidenceNodeIds ?? new List<string>(); } }
        private static void TrimStore() { NormalizeStore(); Store.Twins = Store.Twins.Take(MaxTwins).ToList(); Store.Analyses = Store.Analyses.Take(MaxAnalyses).ToList(); Store.Telemetry = Store.Telemetry.Take(MaxTelemetry).ToList(); Store.Snapshots = Store.Snapshots.Take(MaxSnapshots).ToList(); Store.Baselines = Store.Baselines.Take(MaxBaselines).ToList(); Store.Dossiers = Store.Dossiers.Take(MaxDossiers).ToList(); Store.RecentQuestions = Store.RecentQuestions.Take(256).ToList(); }
        private static void Save(DeepSystemsContext ctx) { lock (Gate) { TrimStore(); Store.Revision = Math.Max(0, Store.Revision) + 1; Store.UpdatedUtc = Now(); Store.LastCommitId = Id("cyber-commit"); string path = StorePath(ctx); Directory.CreateDirectory(Path.GetDirectoryName(path)); AtomicWrite(path, Json.Serialize(Store)); } }
        private static void AtomicWrite(string path, string text) { string temp = path + ".tmp." + Guid.NewGuid().ToString("N"); File.WriteAllText(temp, text ?? "", new UTF8Encoding(false)); if (File.Exists(path)) { string previous = path + ".previous"; try { File.Replace(temp, path, previous, true); return; } catch { try { File.Copy(path, previous, true); } catch { } } } if (File.Exists(path)) File.Delete(path); File.Move(temp, path); }
        private static void PreserveCorrupt(string path) { try { if (!File.Exists(path)) return; byte[] bytes = File.ReadAllBytes(path); string destination = path + ".corrupt." + HashBytes(bytes).Substring(0, 16) + ".json"; if (!File.Exists(destination)) File.Copy(path, destination); } catch { } }
        private static string StorePath(DeepSystemsContext ctx) { return Path.Combine(ctx.StateRoot, "controller-cybernetic-digital-twins.json"); }
        private static string LedgerPath(DeepSystemsContext ctx) { return Path.Combine(ctx.StateRoot, "controller-cybernetic-digital-twins-ledger.jsonl"); }
        private static void AppendLedger(DeepSystemsContext ctx, string evt, string subject, string detail, string fingerprint, string certificate) { lock (Gate) try { Directory.CreateDirectory(ctx.StateRoot); List<CyberTwinLedgerRecord> prior = ReadLedger(ctx, 16384); CyberTwinLedgerRecord last = prior.OrderByDescending(x => x.Sequence).FirstOrDefault(); CyberTwinLedgerRecord r = new CyberTwinLedgerRecord { Schema = 1, Sequence = last == null ? 1 : last.Sequence + 1, Utc = Now(), Event = Short(evt, 120), Subject = Short(subject, 512), Detail = Short(detail, MaxLongText), CorrelationId = Store == null ? "" : Store.LastCommitId, TwinFingerprint = Short(fingerprint, 128), CertificateHash = Short(certificate, 128), PrevHash = last == null ? new string('0', 64) : last.EntryHash }; r.EntryHash = LedgerHash(r); byte[] bytes = Encoding.UTF8.GetBytes(Json.Serialize(r) + Environment.NewLine); using (FileStream stream = new FileStream(LedgerPath(ctx), FileMode.Append, FileAccess.Write, FileShare.Read, 4096, FileOptions.WriteThrough)) { stream.Write(bytes, 0, bytes.Length); stream.Flush(); } } catch { } }
        private static List<CyberTwinLedgerRecord> ReadLedger(DeepSystemsContext ctx, int cap) { List<CyberTwinLedgerRecord> rows = new List<CyberTwinLedgerRecord>(); if (!File.Exists(LedgerPath(ctx))) return rows; try { foreach (string line in TakeLast(File.ReadLines(LedgerPath(ctx)).Where(x => !String.IsNullOrWhiteSpace(x)), cap)) try { CyberTwinLedgerRecord row = Json.Deserialize<CyberTwinLedgerRecord>(line); if (row != null) rows.Add(row); } catch { } } catch { } return rows; }
        private static string VerifyLedger(List<CyberTwinLedgerRecord> rows) { if (rows == null || rows.Count == 0) return "EMPTY LEDGER"; rows = rows.OrderBy(x => x.Sequence).ToList(); long expected = rows[0].Sequence; string prior = expected == 1 ? new string('0', 64) : rows[0].PrevHash; foreach (CyberTwinLedgerRecord row in rows) { if (row.Sequence != expected) return "CHAIN GAP @ " + expected; if (!Eq(row.PrevHash, prior)) return "PREV HASH MISMATCH @ " + row.Sequence; if (!Eq(row.EntryHash, LedgerHash(row))) return "ENTRY HASH MISMATCH @ " + row.Sequence; expected++; prior = row.EntryHash; } return "CHAIN VERIFIED · " + rows.Count.ToString(CultureInfo.InvariantCulture) + " RECORDS"; }
        private static string LedgerHash(CyberTwinLedgerRecord r) { return HashText(r.Schema + "|" + r.Sequence + "|" + (r.Utc ?? "") + "|" + (r.Event ?? "") + "|" + (r.Subject ?? "") + "|" + (r.Detail ?? "") + "|" + (r.CorrelationId ?? "") + "|" + (r.TwinFingerprint ?? "") + "|" + (r.CertificateHash ?? "") + "|" + (r.PrevHash ?? "")); }

        private static CyberStateVariable X(string id, string name, string unit, double initial, double minimum, double maximum, double processNoise, double weight) { return new CyberStateVariable { Id = id, Name = name, Unit = unit, Status = "ACTIVE", InitialValue = initial, Minimum = minimum, Maximum = maximum, ProcessNoiseVariance = Math.Max(1e-12, processNoise), RegulationWeight = Math.Max(1e-9, weight) }; }
        private static CyberControlInput U(string id, string name, string unit, double minimum, double maximum, double minSlew, double maxSlew, double weight) { return new CyberControlInput { Id = id, Name = name, Unit = unit, Status = "ACTIVE", Minimum = minimum, Maximum = maximum, MinimumSlew = minSlew, MaximumSlew = maxSlew, EffortWeight = Math.Max(1e-9, weight) }; }
        private static CyberMeasuredOutput Y(string id, string name, string unit, double target, double minimum, double maximum, double noise, double weight, double cost) { return new CyberMeasuredOutput { Id = id, Name = name, Unit = unit, Status = "ACTIVE", Target = target, Minimum = minimum, Maximum = maximum, MeasurementNoiseVariance = Math.Max(1e-12, noise), TrackingWeight = Math.Max(1e-9, weight), SensorCost = Math.Max(0, cost) }; }
        private static double[][] M(params double[][] rows) { return rows ?? new double[0][]; }
        private static double[][] Z(int rows, int cols) { double[][] value = new double[Math.Max(0, rows)][]; for (int i = 0; i < value.Length; i++) value[i] = new double[Math.Max(0, cols)]; return value; }
        private static void Touch(CyberTwinModel t) { t.Revision = Math.Max(1, t.Revision) + 1; t.UpdatedUtc = Now(); }
        private static bool Active(string status) { return !Eq(status, "ARCHIVED") && !Eq(status, "DISABLED") && !Eq(status, "RETIRED") && !Eq(status, "REJECTED"); }
        private static bool Eq(string a, string b) { return String.Equals(a ?? "", b ?? "", StringComparison.OrdinalIgnoreCase); }
        private static double Number(string raw, double fallback) { double value; return Double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out value) && !Double.IsNaN(value) && !Double.IsInfinity(value) ? value : fallback; }
        private static double[] Vector(string raw, int count) { string[] parts = (raw ?? "").Split(new[] { ',', ';', ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries); double[] values = new double[Math.Max(0, count)]; for (int i = 0; i < values.Length; i++) values[i] = i < parts.Length ? Number(parts[i], 0) : 0; return values; }
        private static Dictionary<string, double> Pairs(string raw) { Dictionary<string, double> result = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase); foreach (string part in (raw ?? "").Split(new[] { ',', ';', '\n' }, StringSplitOptions.RemoveEmptyEntries)) { int at = part.IndexOf('='); if (at > 0) result[part.Substring(0, at).Trim()] = Number(part.Substring(at + 1).Trim(), 0); } return result; }
        private static string Join(IEnumerable<double> values) { return String.Join(",", (values ?? Enumerable.Empty<double>()).Select(x => x.ToString("R", CultureInfo.InvariantCulture)).ToArray()); }
        private static string Short(string value, int cap) { value = value ?? ""; cap = Math.Max(1, cap); return value.Length <= cap ? value : value.Substring(0, cap - 1) + "…"; }
        private static string HashText(string value) { return HashBytes(Encoding.UTF8.GetBytes(value ?? "")); }
        private static string HashBytes(byte[] value) { using (SHA256 hash = SHA256.Create()) return BitConverter.ToString(hash.ComputeHash(value ?? new byte[0])).Replace("-", "").ToLowerInvariant(); }
        private static string Id(string prefix) { return prefix + "-" + DateTime.UtcNow.ToString("yyyyMMddHHmmssfff", CultureInfo.InvariantCulture) + "-" + Guid.NewGuid().ToString("N").Substring(0, 8); }
        private static string Now() { return DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture); }
        private static IEnumerable<TValue> TakeLast<TValue>(IEnumerable<TValue> source, int count) { Queue<TValue> q = new Queue<TValue>(); foreach (TValue item in source ?? Enumerable.Empty<TValue>()) { q.Enqueue(item); if (q.Count > count) q.Dequeue(); } foreach (TValue item in q) yield return item; }

        private static void AddGrid(Grid grid, UIElement child, int row, int column) { Grid.SetRow(child, row); Grid.SetColumn(child, column); grid.Children.Add(child); }
        private static Window W(Window owner, string title, double width, double height) { return new Window { Title = title, Width = width, Height = height, MinWidth = Math.Min(width, 820), MinHeight = Math.Min(height, 560), Background = Bg, Foreground = Text, WindowStartupLocation = WindowStartupLocation.CenterOwner, Owner = owner, FontFamily = new FontFamily("Segoe UI") }; }
        private static DockPanel Shell(string title, string subtitle) { DockPanel root = new DockPanel { Margin = new Thickness(16) }; StackPanel head = new StackPanel { Margin = new Thickness(0, 0, 0, 10) }; head.Children.Add(T(title, 24, Text, FontWeights.Bold)); head.Children.Add(T(subtitle, 12, Muted, FontWeights.Normal)); DockPanel.SetDock(head, Dock.Top); root.Children.Add(head); return root; }
        private static TextBlock T(string value, double size, Brush foreground, FontWeight weight) { return new TextBlock { Text = value ?? "", FontSize = size, Foreground = foreground, FontWeight = weight, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 2, 0, 2) }; }
        private static Button Btn(string label, RoutedEventHandler click) { Button button = new Button { Content = label, Margin = new Thickness(0, 0, 8, 8), Padding = new Thickness(12, 7, 12, 7), Background = Raised, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), MinWidth = 112 }; if (click != null) button.Click += click; return button; }
        private static ListBox List() { return new ListBox { Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), Margin = new Thickness(0, 6, 6, 0), Padding = new Thickness(5), FontFamily = new FontFamily("Cascadia Mono, Consolas") }; }
        private static void Portal(Panel parent, string badge, string title, string description, Action open) { Button button = new Button { Width = 360, Height = 120, Margin = new Thickness(0, 0, 10, 10), Padding = new Thickness(12), Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), HorizontalContentAlignment = HorizontalAlignment.Stretch }; StackPanel content = new StackPanel(); content.Children.Add(T(badge + "   " + title, 14, Accent, FontWeights.Bold)); content.Children.Add(T(description, 11.5, Muted, FontWeights.Normal)); button.Content = content; button.Click += delegate { if (open != null) open(); }; parent.Children.Add(button); }
        private static Brush B(string hex) { return new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex)); }
        private static string Prompt(Window owner, string title, string label, string initial) { Window w = W(owner, "YOMI · " + title, 680, 290); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); TextBox editor = new TextBox { Text = initial ?? "", MaxLength = MaxShortText, Margin = new Thickness(0, 8, 0, 10), Background = Surface, Foreground = Text, BorderBrush = Border, Padding = new Thickness(8) }; DockPanel.SetDock(editor, Dock.Top); root.Children.Add(editor); WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right }; string result = null; buttons.Children.Add(Btn("OK", delegate { result = editor.Text; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); root.Children.Add(buttons); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static string PromptLarge(Window owner, string title, string label, string initial) { Window w = W(owner, "YOMI · " + title, 800, 560); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); TextBox editor = new TextBox { Text = initial ?? "", MaxLength = MaxLongText, AcceptsReturn = true, AcceptsTab = true, TextWrapping = TextWrapping.Wrap, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, Margin = new Thickness(0, 8, 0, 0), Background = Surface, Foreground = Text, BorderBrush = Border, Padding = new Thickness(10), FontFamily = new FontFamily("Cascadia Mono, Consolas") }; WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) }; string result = null; buttons.Children.Add(Btn("SAVE", delegate { result = editor.Text; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(editor); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static object ChooseObject(Window owner, string title, string label, IList<object> choices) { Window w = W(owner, "YOMI · " + title, 720, 500); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); ListBox list = List(); list.ItemsSource = choices ?? new List<object>(); if (list.Items.Count > 0) list.SelectedIndex = 0; WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) }; object result = null; buttons.Children.Add(Btn("SELECT", delegate { result = list.SelectedItem; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); list.MouseDoubleClick += delegate { result = list.SelectedItem; if (result != null) w.DialogResult = true; }; DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(list); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static void OpenRows(Window owner, string title, object value, string subtitle) { IEnumerable<object> rows = value as IEnumerable<object>; OpenRows(owner, title, rows == null ? new object[] { value } : rows.ToArray(), subtitle); }
        private static void OpenRows(Window owner, string title, IList<object> rows, string subtitle) { Window w = W(owner, "YOMI · " + title, 1220, 820); DockPanel root = Shell(title, subtitle); ListBox list = List(); list.ItemsSource = rows ?? new List<object>(); root.Children.Add(list); w.Content = root; w.Show(); }
    }
}
