using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class VoidNote
    {
        public string Id { get; set; }
        public string SubjectId { get; set; }
        public string Text { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (SubjectId??"VOIDΩ")+"   ·   "+(Text??"");}
    }
    internal sealed class TheoryStressRecord
    {
        public string Id { get; set; }
        public string TheoryStressId { get; set; }
        public string Prediction { get; set; }
        public string Falsifier { get; set; }
        public string CompetingExplanation { get; set; }
        public string BoundaryCondition { get; set; }
        public string Status { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (Status??"PROPOSED")+"   ·   "+(Prediction??Id)+"   ·   falsifier "+(Falsifier??"MISSING");}
    }
    internal sealed class VoidBaseline
    {
        public string Id { get; set; }
        public string SnapshotFingerprint { get; set; }
        public int BlindSpots { get; set; }
        public int Disagreements { get; set; }
        public int TheoryStress { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (CreatedUtc??"")+"   ·   blind spots "+BlindSpots+"   ·   disagreements "+Disagreements+"   ·   theory stress "+TheoryStress+"   ·   "+UnknownUnknownsKernel.Short(SnapshotFingerprint);}
    }
    internal sealed class VoidSeal
    {
        public string Id { get; set; }
        public string SnapshotFingerprint { get; set; }
        public int BlindSpots { get; set; }
        public int Reviewed { get; set; }
        public string CreatedUtc { get; set; }
        public string CertificateHash { get; set; }
        public override string ToString(){return "VOIDΩ SEAL   ·   blind spots "+BlindSpots+"   ·   reviewed "+Reviewed+"   ·   "+UnknownUnknownsKernel.Short(SnapshotFingerprint);}
    }
    internal sealed class VoidStore
    {
        public int Schema { get; set; }
        public List<VoidNote> Notes { get; set; }
        public List<TheoryStressRecord> TheoryRecords { get; set; }
        public List<string> ReviewedBlindSpotIds { get; set; }
        public List<string> DismissedBlindSpotIds { get; set; }
        public List<VoidBaseline> Baselines { get; set; }
        public List<VoidSeal> Seals { get; set; }
        public VoidStore(){Schema=1;Notes=new List<VoidNote>();TheoryRecords=new List<TheoryStressRecord>();ReviewedBlindSpotIds=new List<string>();DismissedBlindSpotIds=new List<string>();Baselines=new List<VoidBaseline>();Seals=new List<VoidSeal>();}
    }

    internal static class UnknownUnknownsObservatory
    {
        private static readonly JavaScriptSerializer Json=new JavaScriptSerializer{MaxJsonLength=Int32.MaxValue,RecursionLimit=256};
        private static readonly Brush Bg=B("#09090D"),Surface=B("#11121A"),Raised=B("#181B26"),Border=B("#303344"),Text=B("#ECECF4"),Muted=B("#9FA3B5"),Accent=B("#D29BFF"),Green=B("#7DE3AE"),Red=B("#FF808E"),Amber=B("#FFD071");
        private static VoidStore Store;private static VoidSnapshot Snapshot;private static ExpeditionCommandStore Expeditions;private static SynthesisStore SynthesisReview;private static SynthesisSnapshot Synthesis;private static string LoadedRoot;

        public static void Open(Window owner,DeepSystemsContext ctx)
        {
            if(ctx==null)return;Load(ctx);Refresh(ctx);Window w=W(owner,"YOMI · VOIDΩ · UNKNOWN UNKNOWNS OBSERVATORY",1560,980);DockPanel root=Shell("VOIDΩ · UNKNOWN UNKNOWNS OBSERVATORY","The final civilization-layer observatory. It searches retained investigations for structural absences, monocultures, unchallenged assumptions, unresolved contradictions, underused lenses and theory-test debt. It can expose blind-spot candidates. It cannot prove that it found the things nobody has imagined.");
            TextBlock status=new TextBlock{Text="DEV13.37.30   ·   FINAL CIVILIZATION-LAYER RELEASE   ·   "+Snapshot.BlindSpots.Count+" blind-spot candidates   ·   "+Snapshot.Disagreements.Count+" disagreements   ·   Ctrl+Alt+V",Foreground=Accent,FontWeight=FontWeights.Bold,Margin=new Thickness(20,0,20,12)};DockPanel.SetDock(status,Dock.Top);root.Children.Add(status);
            ScrollViewer scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};WrapPanel chambers=new WrapPanel{Margin=new Thickness(12)};scroll.Content=chambers;root.Children.Add(scroll);
            Portal(chambers,"VOID","BLIND-SPOT UNIVERSE","All detected absences and asymmetries, with observed structure separated from heuristic suspicion.",delegate{Refresh(ctx);OpenCollection(w,"BLIND-SPOT UNIVERSE",VisibleBlindSpots().Cast<object>().ToList(),"Candidate blind spots are navigation prompts, not omniscience claims.");});
            Portal(chambers,"TOP","HIGHEST-PRESSURE BLIND SPOTS","What most deserves skeptical attention next.",delegate{Refresh(ctx);OpenCollection(w,"HIGHEST-PRESSURE BLIND SPOTS",VisibleBlindSpots().OrderByDescending(x=>x.Priority).Take(128).Cast<object>().ToList(),"Priority is deterministic triage, not truth probability.");});
            Portal(chambers,"ABS","STRUCTURAL ABSENCE FIELD","Missing source lineage, missing civilization coverage, missing decision evidence and other directly observable absences.",delegate{Refresh(ctx);OpenCollection(w,"STRUCTURAL ABSENCE FIELD",VisibleBlindSpots().Where(x=>x.StructuralAbsence).Cast<object>().ToList(),"These are absences in retained structure, not proof that missing information exists outside it.");});
            Portal(chambers,"≈","HEURISTIC SUSPICION FIELD","Candidates inferred from sparse use, text cues or weak coverage. Every row remains visibly heuristic.",delegate{Refresh(ctx);OpenCollection(w,"HEURISTIC SUSPICION FIELD",VisibleBlindSpots().Where(x=>x.Heuristic).Cast<object>().ToList(),"Heuristics suggest where to look; they do not certify a blind spot.");});
            Portal(chambers,"SRC1","SOURCE MONOCULTURES","Missions and synthesis patterns whose apparent breadth rests on too few retained source fingerprints.",delegate{Kinds(w,ctx,"SOURCE MONOCULTURES","SOURCE_MONOCULTURE","SYNTHESIS_SOURCE_MONOCULTURE","CROSS_MISSION_SOURCE_GRAVITY");});
            Portal(chambers,"ORPH","ORPHAN EVIDENCE","Findings with no explicit source-step lineage and decisions with no finding lineage.",delegate{Kinds(w,ctx,"ORPHAN EVIDENCE","ORPHAN_FINDING","DECISION_WITHOUT_FINDING_LINEAGE");});
            Portal(chambers,"ASSUME","UNCHALLENGED ASSUMPTIONS","Active assumptions for which no challenge link can be detected.",delegate{Kinds(w,ctx,"UNCHALLENGED ASSUMPTIONS","UNCHALLENGED_ASSUMPTION");});
            Portal(chambers,"Q?","UNRESOLVED FRONTIERS","Open EXPΩ questions, including debt stranded on inactive branches.",delegate{Kinds(w,ctx,"UNRESOLVED FRONTIERS","OPEN_FRONTIER","ABANDONED_BRANCH_FRONTIER");});
            Portal(chambers,"COV","CIVILIZATION COVERAGE MATRIX","Which specialist lenses actually appear in retained investigations and which are neglected or absent.",delegate{Refresh(ctx);OpenCollection(w,"CIVILIZATION COVERAGE MATRIX",Snapshot.Coverage.Cast<object>().ToList(),"Coverage is descriptive. An unused civilization may be irrelevant rather than missing.");});
            Portal(chambers,"ZERO","NEVER-CONSULTED LENSES","Civilizations with zero retained EXPΩ crossings.",delegate{Kinds(w,ctx,"NEVER-CONSULTED LENSES","CIVILIZATION_COVERAGE_GAP");});
            Portal(chambers,"NEG","NEGLECTED LENSES","Rarely used civilizations surfaced for deliberate relevance review.",delegate{Kinds(w,ctx,"NEGLECTED LENSES","CIVILIZATION_NEGLECT");});
            Portal(chambers,"DIA","CONTRADICTION FURNACE","All unresolved contradictions with bounded heuristic disagreement classification.",delegate{Refresh(ctx);OpenCollection(w,"CONTRADICTION FURNACE",Snapshot.Disagreements.Cast<object>().ToList(),"Classification distinguishes likely scope/assumption/time/model/terminology conflict without pretending text cues settle the dispute.");});
            Portal(chambers,"TERM","TERMINOLOGY MISMATCH","Conflicts that may disappear when definitions are aligned.",delegate{DisagreementKind(w,ctx,"TERMINOLOGY_MISMATCH");});
            Portal(chambers,"SCOPE","SCOPE MISMATCH","Conflicts that may concern different domains, populations or conditions.",delegate{DisagreementKind(w,ctx,"SCOPE_MISMATCH");});
            Portal(chambers,"PREM","ASSUMPTION CONFLICT","Disagreements with premise/assumption cues.",delegate{DisagreementKind(w,ctx,"ASSUMPTION_CONFLICT");});
            Portal(chambers,"TIME","TEMPORAL / VERSION MISMATCH","Potential stale-data or version-context conflicts.",delegate{DisagreementKind(w,ctx,"TEMPORAL_OR_VERSION_MISMATCH");});
            Portal(chambers,"MODEL","MODEL CONFLICT","Disagreements involving estimates, models or simulations.",delegate{DisagreementKind(w,ctx,"MODEL_CONFLICT");});
            Portal(chambers,"THRY","THEORY STRESS DECK","SYNTHΩ theorem candidates converted into explicit test-debt surfaces.",delegate{Refresh(ctx);OpenCollection(w,"THEORY STRESS DECK",Snapshot.TheoryStress.Cast<object>().ToList(),"A theorem candidate stays a candidate. VOIDΩ asks what would have to fail for us to stop believing it.");});
            Portal(chambers,"FALS","FALSIFIER WORKSHOP","Add an explicit prediction, falsifier, competing explanation and boundary condition to a theory-stress candidate.",delegate{AddTheoryStressRecord(w,ctx);});
            Portal(chambers,"TEST","THEORY TEST RECORDS","Human-authored falsification structures retained separately from automatic synthesis.",delegate{OpenCollection(w,"THEORY TEST RECORDS",Store.TheoryRecords.Cast<object>().ToList(),"These are plans/criteria, not experimental results.");});
            Portal(chambers,"XFER","TRANSFER PRECONDITION GAPS","SYNTHΩ transfer suggestions missing important supporting contexts.",delegate{Kinds(w,ctx,"TRANSFER PRECONDITION GAPS","TRANSFER_PRECONDITION_GAP");});
            Portal(chambers,"SEAL?","SEALED WITH OPEN DEBT","Integrity-sealed missions that still contain open questions or contradictions.",delegate{Kinds(w,ctx,"SEALED WITH OPEN DEBT","SEALED_WITH_OPEN_DEBT");});
            Portal(chambers,"PROBE","LAUNCH BLIND-SPOT EXPEDITION","Turn one candidate into a fresh EXPΩ mission explicitly tasked with disproving the suspicion if possible.",delegate{LaunchProbe(w,ctx);});
            Portal(chambers,"REVIEW","MARK REVIEWED","Mark a candidate as examined without deleting it from the snapshot.",delegate{MarkReviewed(w,ctx);});
            Portal(chambers,"DISMISS","DISMISS FROM WORKING VIEW","Locally hide a candidate while retaining its ID and the ability to inspect dismissed rows.",delegate{Dismiss(w,ctx);});
            Portal(chambers,"HIDDEN","DISMISSED CANDIDATES","Inspect locally dismissed candidates.",delegate{Refresh(ctx);OpenCollection(w,"DISMISSED CANDIDATES",Snapshot.BlindSpots.Where(x=>Store.DismissedBlindSpotIds.Contains(x.Id,StringComparer.OrdinalIgnoreCase)).Cast<object>().ToList(),"Dismissal is UI state, not deletion of upstream evidence.");});
            Portal(chambers,"NOTE","VOID NOTEBOOK","Notes attached to blind spots, disagreements and theory-test identities.",delegate{OpenCollection(w,"VOID NOTEBOOK",Store.Notes.Cast<object>().ToList(),"Notes never mutate EXPΩ/METAΩ/SYNTHΩ authority stores.");});
            Portal(chambers,"+NOTE","ADD VOID NOTE","Attach a local review note to an identity.",delegate{AddNote(w,ctx);});
            Portal(chambers,"BASE","VOID BASELINES","Immutable local snapshots of blind-spot/disagreement/theory-stress dimensions.",delegate{OpenCollection(w,"VOID BASELINES",Store.Baselines.Cast<object>().ToList(),"Baseline identity supports drift inspection only.");});
            Portal(chambers,"+BASE","CAPTURE VOID BASELINE","Record current structural dimensions and fingerprint.",delegate{Baseline(ctx);});
            Portal(chambers,"DRIFT","BLIND-SPOT DRIFT","Compare a baseline with the current VOIDΩ snapshot.",delegate{Drift(w,ctx);});
            Portal(chambers,"VALID","STRUCTURAL VALIDATOR","Validate IDs, heuristic-basis visibility, coverage ranges and snapshot collections.",delegate{Refresh(ctx);OpenCollection(w,"VOIDΩ STRUCTURAL VALIDATOR",UnknownUnknownsKernel.Validate(Snapshot).Cast<object>().ToList(),"Validation checks data structure, not epistemic completeness.");});
            Portal(chambers,"SEAL","VOID INTEGRITY SEAL","Bind a structurally valid snapshot and local review count to a local hash record.",delegate{Seal(w,ctx);});
            Portal(chambers,"EXPORT","LOCAL VOID CAPSULE","Export snapshot + review state + Markdown summary under YOMI local data.",delegate{Export(w,ctx);});
            Portal(chambers,"AUTOPSY","VOID AUTOPSY","One dense accounting of what the observatory can and cannot see.",delegate{Autopsy(w,ctx);});
            Portal(chambers,"BOUND","YOMI RELEVANCE FIREWALL","Explicit boundary between core music/OBS product authority and the optional civilization research laboratory.",delegate{TextView(w,"YOMI RELEVANCE FIREWALL",RelevanceFirewall());});
            Portal(chambers,"FREEZE","CIVILIZATION FREEZE CHARTER","Why DEV13.37.30 closes this expansion run and what maintenance is still allowed.",delegate{TextView(w,"CIVILIZATION FREEZE CHARTER",FreezeCharter());});
            Portal(chambers,"COREY","RETURN TO ACTUAL YOMI","Read the post-civilization development priorities: playback, queue, media acquisition, OBS presentation, controller UX, caching, performance, personalization and diagnostics.",delegate{TextView(w,"RETURN TO ACTUAL YOMI",CoreYomiRoadmap());});
            Portal(chambers,"EXPΩ","GRAND UNIFIED EXPEDITION COMMAND","Descend into the mission worldlines that supply VOIDΩ.",delegate{GrandUnifiedExpeditionCommand.Open(w,ctx);});
            Portal(chambers,"METAΩ","KNOWLEDGE CONSTELLATION","Inspect the exact/heuristic cross-mission graph beneath blind-spot analysis.",delegate{KnowledgeConstellationMetastructure.Open(w,ctx);});
            Portal(chambers,"SYNTHΩ","CIVILIZATIONAL SYNTHESIS","Inspect recurring motifs, transfer candidates and theorem candidates beneath theory stress.",delegate{CivilizationalSynthesisReactor.Open(w,ctx);});
            w.Content=root;w.Show();
        }

        private static IEnumerable<BlindSpotCandidate> VisibleBlindSpots(){return Snapshot.BlindSpots.Where(x=>!Store.DismissedBlindSpotIds.Contains(x.Id,StringComparer.OrdinalIgnoreCase));}
        private static string StatePath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-unknown-unknowns.json");}
        private static string ExpeditionPath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-grand-unified-expedition.json");}
        private static string SynthesisPath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-civilizational-synthesis.json");}
        private static void Load(DeepSystemsContext ctx){if(Store!=null&&Eq(LoadedRoot,ctx.StateRoot))return;LoadedRoot=ctx.StateRoot;Store=new VoidStore();string p=StatePath(ctx);if(File.Exists(p))try{VoidStore x=Json.Deserialize<VoidStore>(File.ReadAllText(p,Encoding.UTF8));if(x!=null)Store=x;}catch{PreserveCorrupt(p);}Normalize();}
        private static void Normalize(){if(Store==null)Store=new VoidStore();if(Store.Notes==null)Store.Notes=new List<VoidNote>();if(Store.TheoryRecords==null)Store.TheoryRecords=new List<TheoryStressRecord>();if(Store.ReviewedBlindSpotIds==null)Store.ReviewedBlindSpotIds=new List<string>();if(Store.DismissedBlindSpotIds==null)Store.DismissedBlindSpotIds=new List<string>();if(Store.Baselines==null)Store.Baselines=new List<VoidBaseline>();if(Store.Seals==null)Store.Seals=new List<VoidSeal>();}
        private static void Save(DeepSystemsContext ctx){Normalize();string p=StatePath(ctx),n=p+".next",prev=p+".previous";File.WriteAllText(n,Json.Serialize(Store),new UTF8Encoding(false));if(File.Exists(p))try{File.Copy(p,prev,true);}catch{}if(File.Exists(p))File.Delete(p);File.Move(n,p);}
        private static void PreserveCorrupt(string p){try{File.Copy(p,p+".corrupt-"+DateTime.UtcNow.ToString("yyyyMMddHHmmss",CultureInfo.InvariantCulture),true);}catch{}}
        private static void Refresh(DeepSystemsContext ctx)
        {
            Expeditions=new ExpeditionCommandStore();string ep=ExpeditionPath(ctx);if(File.Exists(ep))try{ExpeditionCommandStore x=Json.Deserialize<ExpeditionCommandStore>(File.ReadAllText(ep,Encoding.UTF8));if(x!=null)Expeditions=x;}catch{}if(Expeditions.Missions==null)Expeditions.Missions=new List<ExpeditionMission>();string expeditionFp=UnknownUnknownsKernel.HashText(Json.Serialize(Expeditions));
            SynthesisReview=new SynthesisStore();string sp=SynthesisPath(ctx);if(File.Exists(sp))try{SynthesisStore x=Json.Deserialize<SynthesisStore>(File.ReadAllText(sp,Encoding.UTF8));if(x!=null)SynthesisReview=x;}catch{}if(SynthesisReview.Theorems==null)SynthesisReview.Theorems=new List<SynthesisTheoremCandidate>();
            ConstellationSnapshot constellation=KnowledgeConstellationKernel.Build(Expeditions.Missions,expeditionFp);Synthesis=CivilizationalSynthesisKernel.Build(constellation,Expeditions.Missions,expeditionFp);string synthFp=Synthesis==null?UnknownUnknownsKernel.HashText(""):Synthesis.Fingerprint;Snapshot=UnknownUnknownsKernel.Build(Expeditions.Missions,Synthesis,SynthesisReview.Theorems,expeditionFp,synthFp);
        }
        private static void Kinds(Window w,DeepSystemsContext ctx,string title,params string[] kinds){Refresh(ctx);OpenCollection(w,title,VisibleBlindSpots().Where(x=>kinds.Any(k=>Eq(k,x.Kind))).Cast<object>().ToList(),"Structural and heuristic candidates remain visibly distinguished.");}
        private static void DisagreementKind(Window w,DeepSystemsContext ctx,string kind){Refresh(ctx);OpenCollection(w,kind.Replace('_',' '),Snapshot.Disagreements.Where(x=>Eq(x.Kind,kind)).Cast<object>().ToList(),"Text-cue classification is heuristic and should be reviewed against the underlying findings.");}
        private static void LaunchProbe(Window w,DeepSystemsContext ctx){Refresh(ctx);BlindSpotCandidate b=Choose(w,"SELECT BLIND-SPOT CANDIDATE",VisibleBlindSpots().OrderByDescending(x=>x.Priority).ToList());if(b==null)return;string q="Blind-spot probe: "+(b.Label??b.Kind)+". Test whether this candidate reflects a real missing consideration or merely an irrelevant absence. "+(b.SuggestedProbe??"");GrandUnifiedExpeditionCommand.OpenFromUnknownUnknown(w,ctx,q,b.Kind,b.Fingerprint);}
        private static void MarkReviewed(Window w,DeepSystemsContext ctx){Refresh(ctx);BlindSpotCandidate b=Choose(w,"MARK REVIEWED",VisibleBlindSpots().ToList());if(b==null)return;if(!Store.ReviewedBlindSpotIds.Contains(b.Id,StringComparer.OrdinalIgnoreCase))Store.ReviewedBlindSpotIds.Insert(0,b.Id);Save(ctx);}
        private static void Dismiss(Window w,DeepSystemsContext ctx){Refresh(ctx);BlindSpotCandidate b=Choose(w,"DISMISS FROM WORKING VIEW",VisibleBlindSpots().ToList());if(b==null)return;if(!Store.DismissedBlindSpotIds.Contains(b.Id,StringComparer.OrdinalIgnoreCase))Store.DismissedBlindSpotIds.Insert(0,b.Id);Save(ctx);}
        private static void AddNote(Window w,DeepSystemsContext ctx){string id=Prompt(w,"VOID NOTE","Subject identity","");if(String.IsNullOrWhiteSpace(id))return;string text=Prompt(w,"VOID NOTE","Note","");if(String.IsNullOrWhiteSpace(text))return;Store.Notes.Insert(0,new VoidNote{Id="NOTE-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),SubjectId=id.Trim(),Text=text.Trim(),CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)});Save(ctx);}
        private static void AddTheoryStressRecord(Window w,DeepSystemsContext ctx){Refresh(ctx);TheoryStressCandidate t=Choose(w,"SELECT THEORY CANDIDATE",Snapshot.TheoryStress);if(t==null)return;string prediction=Prompt(w,"THEORY STRESS","Prediction that should be observed if the candidate is useful",t.Statement??"");if(String.IsNullOrWhiteSpace(prediction))return;string falsifier=Prompt(w,"THEORY STRESS","Observation that would count against the candidate","");string competitor=Prompt(w,"THEORY STRESS","Competing explanation","");string boundary=Prompt(w,"THEORY STRESS","Boundary condition / scope break",t.Scope??"");Store.TheoryRecords.Insert(0,new TheoryStressRecord{Id="TEST-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),TheoryStressId=t.Id,Prediction=prediction.Trim(),Falsifier=(falsifier??"").Trim(),CompetingExplanation=(competitor??"").Trim(),BoundaryCondition=(boundary??"").Trim(),Status="PROPOSED",CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)});Save(ctx);}
        private static void Baseline(DeepSystemsContext ctx){Refresh(ctx);Store.Baselines.Insert(0,new VoidBaseline{Id="BASE-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),SnapshotFingerprint=Snapshot.Fingerprint,BlindSpots=Snapshot.BlindSpots.Count,Disagreements=Snapshot.Disagreements.Count,TheoryStress=Snapshot.TheoryStress.Count,CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)});Save(ctx);}
        private static void Drift(Window w,DeepSystemsContext ctx){Refresh(ctx);VoidBaseline b=Choose(w,"SELECT VOID BASELINE",Store.Baselines);if(b==null)return;StringBuilder s=new StringBuilder();s.AppendLine("VOIDΩ BLIND-SPOT DRIFT");s.AppendLine(new string('=',68));s.AppendLine("baseline fingerprint: "+b.SnapshotFingerprint);s.AppendLine("current fingerprint:  "+Snapshot.Fingerprint);s.AppendLine("blind spots:          "+b.BlindSpots+" → "+Snapshot.BlindSpots.Count+"   Δ "+(Snapshot.BlindSpots.Count-b.BlindSpots));s.AppendLine("disagreements:        "+b.Disagreements+" → "+Snapshot.Disagreements.Count+"   Δ "+(Snapshot.Disagreements.Count-b.Disagreements));s.AppendLine("theory stress:        "+b.TheoryStress+" → "+Snapshot.TheoryStress.Count+"   Δ "+(Snapshot.TheoryStress.Count-b.TheoryStress));s.AppendLine();s.AppendLine("Drift means the retained investigation structure changed. It does not mean the world became more or less knowable.");TextView(w,"BLIND-SPOT DRIFT",s.ToString());}
        private static void Seal(Window w,DeepSystemsContext ctx){Refresh(ctx);List<VoidValidationFinding> v=UnknownUnknownsKernel.Validate(Snapshot);if(v.Any(x=>Eq(x.Severity,"ERROR"))){OpenCollection(w,"SEAL REFUSED",v.Cast<object>().ToList(),"Repair structural errors first.");return;}VoidSeal s=new VoidSeal{Id="SEAL-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),SnapshotFingerprint=Snapshot.Fingerprint,BlindSpots=Snapshot.BlindSpots.Count,Reviewed=Store.ReviewedBlindSpotIds.Count,CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};s.CertificateHash=UnknownUnknownsKernel.HashText(s.Id+"|"+s.SnapshotFingerprint+"|"+s.BlindSpots+"|"+s.Reviewed+"|"+s.CreatedUtc);Store.Seals.Insert(0,s);Save(ctx);}
        private static void Export(Window w,DeepSystemsContext ctx){Refresh(ctx);string dir=Path.Combine(ctx.DataRoot,"exports","unknown-unknowns");Directory.CreateDirectory(dir);string stamp=DateTime.UtcNow.ToString("yyyyMMdd-HHmmss",CultureInfo.InvariantCulture),root=Path.Combine(dir,"void-omega-"+stamp);File.WriteAllText(root+".snapshot.json",Json.Serialize(Snapshot),new UTF8Encoding(false));File.WriteAllText(root+".review.json",Json.Serialize(Store),new UTF8Encoding(false));StringBuilder md=new StringBuilder();md.AppendLine("# VOIDΩ Unknown Unknowns Observatory");md.AppendLine();md.AppendLine("Snapshot fingerprint: `"+Snapshot.Fingerprint+"`");md.AppendLine();md.AppendLine("Blind-spot candidates: "+Snapshot.BlindSpots.Count+"  ");md.AppendLine("Disagreements: "+Snapshot.Disagreements.Count+"  ");md.AppendLine("Theory stress candidates: "+Snapshot.TheoryStress.Count+"  ");md.AppendLine();md.AppendLine("## Highest pressure");foreach(BlindSpotCandidate b in Snapshot.BlindSpots.Take(40))md.AppendLine("- "+b.ToString());md.AppendLine();md.AppendLine("VOIDΩ detects structural absences and heuristic suspicions in retained investigation state. It cannot prove discovery of genuinely unimagined unknowns.");File.WriteAllText(root+".md",md.ToString(),new UTF8Encoding(false));TextView(w,"EXPORT COMPLETE",root+Environment.NewLine+Snapshot.Fingerprint);}
        private static void Autopsy(Window w,DeepSystemsContext ctx){Refresh(ctx);StringBuilder b=new StringBuilder();b.AppendLine("VOIDΩ UNKNOWN-UNKNOWNS AUTOPSY");b.AppendLine(new string('=',74));b.AppendLine("missions:                    "+Snapshot.Missions);b.AppendLine("findings:                    "+Snapshot.Findings);b.AppendLine("questions:                   "+Snapshot.Questions);b.AppendLine("contradictions:              "+Snapshot.Contradictions);b.AppendLine("assumptions:                 "+Snapshot.Assumptions);b.AppendLine("decisions:                   "+Snapshot.Decisions);b.AppendLine("unique retained sources:     "+Snapshot.UniqueSources);b.AppendLine("blind-spot candidates:       "+Snapshot.BlindSpots.Count);b.AppendLine("structural absences:         "+Snapshot.BlindSpots.Count(x=>x.StructuralAbsence));b.AppendLine("heuristic suspicions:        "+Snapshot.BlindSpots.Count(x=>x.Heuristic));b.AppendLine("disagreements:               "+Snapshot.Disagreements.Count);b.AppendLine("theory-stress candidates:    "+Snapshot.TheoryStress.Count);b.AppendLine("reviewed candidates:         "+Store.ReviewedBlindSpotIds.Count);b.AppendLine("dismissed working-view rows: "+Store.DismissedBlindSpotIds.Count);b.AppendLine("snapshot fingerprint:        "+Snapshot.Fingerprint);b.AppendLine();b.AppendLine("Hard limit: a system cannot enumerate what no retained data, model, question, residual or structural absence gives it any handle on. VOIDΩ is a disciplined blind-spot detector, not omniscience.");TextView(w,"VOID AUTOPSY",b.ToString());}
        private static string RelevanceFirewall(){return "YOMI RELEVANCE FIREWALL\r\n"+new string('=',72)+"\r\n\r\nCORE PRODUCT AUTHORITY\r\n  YouTube playlist playback\r\n  media acquisition / quality routing / fallback\r\n  queue and history\r\n  audio continuity and caching\r\n  artwork / tiny-video / visualizer presentation\r\n  OBS Browser Source output\r\n  controller, settings and personalization\r\n  updater / installer / diagnostics / recovery / performance\r\n\r\nOPTIONAL RESEARCH LABORATORY\r\n  DEV13.37 civilization systems, EXPΩ, METAΩ, SYNTHΩ and VOIDΩ\r\n\r\nBOUNDARY LAW\r\n  Research-lab failure must never be required for playback, media preparation, OBS output, controller basics or update safety.\r\n  Civilization data is local auxiliary state. It has no production-control authority.\r\n  Future core-YOMI work does not need to extend the civilization lattice merely because a new feature exists.\r\n\r\nThe weird shit is preserved. It is no longer allowed to pretend it is the music player.";}
        private static string FreezeCharter(){return "CIVILIZATION LAYER FREEZE CHARTER\r\n"+new string('=',72)+"\r\n\r\nDEV13.37.30 closes the open-ended civilization expansion run.\r\n\r\nAllowed after freeze:\r\n  - bug fixes\r\n  - data compatibility repairs\r\n  - navigation cleanup\r\n  - integrity / recovery fixes\r\n  - bounded performance maintenance\r\n  - changes required by a real user workflow\r\n\r\nNot a default reason to reopen expansion:\r\n  - another cool Ω name\r\n  - filling a version number\r\n  - adding a specialist domain unrelated to music/OBS\r\n  - abstract capability claims without a concrete user action/output\r\n\r\nThe subsystem remains explorable and preserved. New civilization development now requires a concrete product case instead of momentum.";}
        private static string CoreYomiRoadmap(){return "POST-CIVILIZATION YOMI ROADMAP\r\n"+new string('=',72)+"\r\n\r\n1. Playback continuity, error recovery and low-overhead media preparation.\r\n2. 240p → 360p → 144p preference/fallback behavior and transparent route diagnostics.\r\n3. Visual queue / upcoming + previous track experience with click-to-jump.\r\n4. OBS overlay composition: separate modules, multi-module sources, alignment and zero-gap media geometry.\r\n5. Visualizer frequency response, resolution modes, colors/gradients and 60 FPS option.\r\n6. Cache strategy: full-track vs split A/V, prefetch depth, worker governance and disk pressure.\r\n7. Controller/settings polish: single-instance windows, spacing, presets, silent save state and restore defaults.\r\n8. Personalization without turning settings into an aircraft cockpit.\r\n9. Updater/installer/Defender/performance maintenance and diagnostic quality.\r\n10. Music/media discovery, history and library exploration that actually belongs in YOMI.\r\n\r\nThat is where primary development returns after this release.";}
        private static T Choose<T>(Window owner,string title,IList<T> items) where T:class{if(items==null||items.Count==0)return null;Window w=W(owner,"YOMI · "+title,1180,780);DockPanel root=Shell(title,"Double-click to select.");ListBox list=List();list.ItemsSource=items;T selected=null;list.MouseDoubleClick+=delegate{selected=list.SelectedItem as T;w.DialogResult=selected!=null;w.Close();};root.Children.Add(list);w.Content=root;bool? r=w.ShowDialog();return r==true?selected:null;}
        private static Window W(Window owner,string title,double width,double height){return new Window{Title=title,Width=width,Height=height,Background=Bg,Foreground=Text,WindowStartupLocation=owner==null?WindowStartupLocation.CenterScreen:WindowStartupLocation.CenterOwner,Owner=owner};}
        private static DockPanel Shell(string title,string subtitle){DockPanel root=new DockPanel{Background=Bg};StackPanel head=new StackPanel{Margin=new Thickness(20,18,20,10)};head.Children.Add(new TextBlock{Text=title,Foreground=Text,FontSize=25,FontWeight=FontWeights.Bold});head.Children.Add(new TextBlock{Text=subtitle??"",Foreground=Muted,FontSize=13,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,5,0,0)});DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);return root;}
        private static void Portal(WrapPanel panel,string badge,string title,string detail,RoutedEventHandler click){Button b=new Button{Width=288,MinHeight=120,Margin=new Thickness(7),Padding=new Thickness(14),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),HorizontalContentAlignment=HorizontalAlignment.Stretch};StackPanel p=new StackPanel();p.Children.Add(new TextBlock{Text=badge+"   "+title,Foreground=Accent,FontWeight=FontWeights.Bold,FontSize=13,TextWrapping=TextWrapping.Wrap});p.Children.Add(new TextBlock{Text=detail,Foreground=Muted,FontSize=12,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,7,0,0)});b.Content=p;b.Click+=click;panel.Children.Add(b);}
        private static ListBox List(){return new ListBox{Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),FontFamily=new FontFamily("Consolas"),FontSize=12};}
        private static void OpenCollection(Window owner,string title,IList<object> items,string note){Window w=W(owner,"YOMI · "+title,1380,850);DockPanel root=Shell(title,note+"   ·   "+(items==null?0:items.Count)+" rows");ListBox list=List();list.ItemsSource=items??new List<object>();root.Children.Add(list);w.Content=root;w.Show();}
        private static void TextView(Window owner,string title,string text){Window w=W(owner,"YOMI · "+title,1380,880);DockPanel root=Shell(title,"Read-only representation.");TextBox box=new TextBox{Text=text??"",Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,FontFamily=new FontFamily("Consolas"),FontSize=13,IsReadOnly=true,AcceptsReturn=true,AcceptsTab=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto};root.Children.Add(box);w.Content=root;w.Show();}
        private static string Prompt(Window owner,string title,string label,string initial){Window w=W(owner,"YOMI · "+title,820,340);DockPanel root=Shell(title,label);TextBox box=new TextBox{Text=initial??"",Margin=new Thickness(20,6,20,10),Padding=new Thickness(8),Background=Surface,Foreground=Text,BorderBrush=Border,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};DockPanel.SetDock(box,Dock.Top);root.Children.Add(box);StackPanel buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(20)};Button ok=new Button{Content="COMMIT",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Green,BorderBrush=Border};Button cancel=new Button{Content="CANCEL",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Muted,BorderBrush=Border};string value=null;ok.Click+=delegate{value=box.Text;w.DialogResult=true;w.Close();};cancel.Click+=delegate{w.DialogResult=false;w.Close();};buttons.Children.Add(cancel);buttons.Children.Add(ok);root.Children.Add(buttons);w.Content=root;bool? r=w.ShowDialog();return r==true?value:null;}
        private static bool Eq(string a,string b){return String.Equals(a,b,StringComparison.OrdinalIgnoreCase);}private static Brush B(string hex){return (Brush)new BrushConverter().ConvertFromString(hex);}
    }
}
