using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class DiscoveryDesignRecord
    {
        public string Id { get; set; }
        public string ProtocolId { get; set; }
        public string CreatedUtc { get; set; }
        public string ProtocolFingerprint { get; set; }
        public string PreregistrationFingerprint { get; set; }
        public string DesignFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public string Method { get; set; }
        public List<DiscoveryRun> Runs { get; set; }
        public DiscoveryDesignDiagnostics Diagnostics { get; set; }
        public DiscoveryDiscrimination Discrimination { get; set; }
        public List<DiscoveryPowerPlan> PowerPlans { get; set; }
        public DiscoveryDesignRecord() { Runs = new List<DiscoveryRun>(); PowerPlans = new List<DiscoveryPowerPlan>(); }
        public override string ToString() { return (CreatedUtc ?? "") + "   ·   " + (Method ?? "DESIGN") + "   ·   " + Runs.Count.ToString(CultureInfo.InvariantCulture) + " runs   ·   " + (Diagnostics == null ? "UNDIAGNOSED" : (Diagnostics.Estimable ? "ESTIMABLE" : "RANK DEFICIENT")) + "   ·   cert " + ShortHash(CertificateHash); }
        private static string ShortHash(string value) { return String.IsNullOrWhiteSpace(value) ? "∅" : value.Substring(0, Math.Min(16, value.Length)); }
    }

    internal sealed class DiscoveryPreregistration
    {
        public string Id { get; set; }
        public string ProtocolId { get; set; }
        public string FrozenUtc { get; set; }
        public string Status { get; set; }
        public string ProtocolFingerprint { get; set; }
        public string PreregistrationFingerprint { get; set; }
        public string ParentPreregistrationId { get; set; }
        public string AmendmentReason { get; set; }
        public string SnapshotJson { get; set; }
        public override string ToString() { return (Status ?? "FROZEN") + "   ·   " + (FrozenUtc ?? "") + "   ·   protocol " + (ProtocolId ?? "∅") + "   ·   prereg " + ShortHash(PreregistrationFingerprint); }
        private static string ShortHash(string value) { return String.IsNullOrWhiteSpace(value) ? "∅" : value.Substring(0, Math.Min(16, value.Length)); }
    }

    internal sealed class DiscoveryDossier
    {
        public string Id { get; set; }
        public string ProtocolId { get; set; }
        public string DesignId { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string CreatedUtc { get; set; }
        public string UpdatedUtc { get; set; }
        public string Question { get; set; }
        public string DesignBoundary { get; set; }
        public string InterpretationBoundary { get; set; }
        public string ProtocolFingerprint { get; set; }
        public string DesignCertificate { get; set; }
        public List<string> Caveats { get; set; }
        public List<string> EvidenceNodeIds { get; set; }
        public DiscoveryDossier() { Status = "DRAFT"; Caveats = new List<string>(); EvidenceNodeIds = new List<string>(); }
        public override string ToString() { return (Status ?? "DRAFT") + "   ·   " + (Title ?? "DISCOVERY DOSSIER") + "   ·   " + (UpdatedUtc ?? CreatedUtc ?? ""); }
    }

    internal sealed class DiscoveryLedgerRecord
    {
        public int Schema { get; set; }
        public long Sequence { get; set; }
        public string Utc { get; set; }
        public string Event { get; set; }
        public string Subject { get; set; }
        public string Detail { get; set; }
        public string CorrelationId { get; set; }
        public string ProtocolFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public string PrevHash { get; set; }
        public string EntryHash { get; set; }
        public override string ToString() { return Sequence.ToString(CultureInfo.InvariantCulture).PadLeft(7) + "   " + (Utc ?? "") + "   " + (Event ?? "") + "   ·   " + (Subject ?? "∅") + "   ·   " + (Detail ?? ""); }
    }

    internal sealed class ScientificDiscoveryStore
    {
        public int Schema { get; set; }
        public long Revision { get; set; }
        public string UpdatedUtc { get; set; }
        public string LastCommitId { get; set; }
        public List<DiscoveryProtocol> Protocols { get; set; }
        public List<DiscoveryDesignRecord> Designs { get; set; }
        public List<DiscoveryObservation> Observations { get; set; }
        public List<DiscoveryPreregistration> Preregistrations { get; set; }
        public List<DiscoveryDossier> Dossiers { get; set; }
        public List<DiscoveryExperimentCandidate> PortfolioCandidates { get; set; }
        public List<string> RecentQuestions { get; set; }
        public ScientificDiscoveryStore() { Schema = 1; Protocols = new List<DiscoveryProtocol>(); Designs = new List<DiscoveryDesignRecord>(); Observations = new List<DiscoveryObservation>(); Preregistrations = new List<DiscoveryPreregistration>(); Dossiers = new List<DiscoveryDossier>(); PortfolioCandidates = new List<DiscoveryExperimentCandidate>(); RecentQuestions = new List<string>(); }
    }

    internal static class ScientificDiscoveryHyperstructure
    {
        private static readonly Brush Bg = B("#05080B");
        private static readonly Brush Surface = B("#0C1419");
        private static readonly Brush Raised = B("#15252D");
        private static readonly Brush Border = B("#315363");
        private static readonly Brush Text = B("#F1FAFC");
        private static readonly Brush Muted = B("#9CB5BE");
        private static readonly Brush Accent = B("#72F2C0");
        private static readonly Brush Blue = B("#71C8FF");
        private static readonly Brush Amber = B("#FFD371");
        private static readonly Brush Violet = B("#C8A9FF");
        private static readonly Brush Danger = B("#FF8192");
        private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = Int32.MaxValue, RecursionLimit = 256 };
        private static readonly object Gate = new object();
        private static ScientificDiscoveryStore Store;
        private static string LoadedRoot;
        private const int MaxProtocols = 192;
        private const int MaxDesigns = 384;
        private const int MaxObservations = 32768;
        private const int MaxPreregistrations = 1024;
        private const int MaxDossiers = 1024;
        private const int MaxFactors = 64;
        private const int MaxOutcomes = 128;
        private const int MaxHypotheses = 128;
        private const int MaxPredictions = 512;
        private const int MaxTerms = 512;
        private const int MaxEvidence = 512;
        private const int MaxShortText = 2048;
        private const int MaxLongText = 65536;

        public static void Open(Window owner, DeepSystemsContext ctx) { if (ctx == null) return; Load(ctx); OpenHub(owner, ctx, WorldKernel.ExternalIndex(ctx, false)); }

        public static void OpenFromWorldNode(Window owner, DeepSystemsContext ctx, WorldIndex index, string nodeId)
        {
            if (ctx == null || index == null || String.IsNullOrWhiteSpace(nodeId)) return; WorldNode node; if (!index.Nodes.TryGetValue(nodeId, out node)) { Open(owner, ctx); return; } Load(ctx); string fingerprint = HashText((node.Id ?? "") + "|" + (node.Kind ?? "") + "|" + (node.Label ?? "") + "|" + (node.Fingerprint ?? "")); OpenProjection(owner, ctx, index, "WORLD", node.Id, fingerprint, delegate { DiscoveryProtocol p = StarterProtocol("Measure · " + (node.Label ?? node.Kind), "A bounded observation protocol projected from a World Kernel passport. Identity and provenance remain evidence; they are not randomized causes."); p.EvidenceNodeIds.Add(node.Id); p.Factors[0].Name = "observable coordinate"; p.Factors[0].Controllable = false; p.Outcomes[0].Name = "measured signal"; p.Hypotheses[0].Statement = "The selected world object remains within its declared baseline envelope."; p.Hypotheses[1].Statement = "The selected world object exhibits a materially discriminable deviation."; return p; });
        }

        public static void OpenFromCivilResolution(Window owner, DeepSystemsContext ctx, WorldIndex index, CivilResolution resolution)
        {
            if (ctx == null || resolution == null) return; Load(ctx); WorldIndex target = index ?? WorldKernel.ExternalIndex(ctx, false); string fingerprint = HashText((resolution.Id ?? "") + "|" + (resolution.Title ?? "") + "|" + (resolution.Proposition ?? "") + "|" + (resolution.Status ?? "") + "|" + String.Join("|", (resolution.EvidenceNodeIds ?? new List<string>()).OrderBy(x => x).ToArray())); OpenProjection(owner, ctx, target, "CIVILIZATION", resolution.Id, fingerprint, delegate { DiscoveryProtocol p = StarterProtocol("Pilot · " + (resolution.Title ?? "Resolution"), "Preregistered policy-pilot scaffold projected from a civilization resolution. Adoption status is not evidence of efficacy."); p.EvidenceNodeIds.AddRange(resolution.EvidenceNodeIds ?? new List<string>()); p.Factors[0].Name = "pilot exposure"; p.Outcomes[0].Name = "preregistered resolution outcome"; p.Hypotheses[0].Statement = "The proposed resolution produces no practically relevant change under the declared pilot."; p.Hypotheses[1].Statement = resolution.Proposition ?? "The proposed resolution produces the declared practically relevant change."; return p; });
        }

        public static void OpenFromLogicTheory(Window owner, DeepSystemsContext ctx, WorldIndex index, LogicTheory theory)
        {
            if (ctx == null || theory == null) return; Load(ctx); WorldIndex target = index ?? WorldKernel.ExternalIndex(ctx, false); Dictionary<string, string> truth = EpistemicLogicFoundry.ExternalTheoryTruth(ctx, theory); string fingerprint = HashText((theory.Id ?? "") + "|" + (theory.Name ?? "") + "|" + (theory.Status ?? "") + "|" + String.Join("|", truth.OrderBy(x => x.Key).Select(x => x.Key + "=" + x.Value).ToArray())); OpenProjection(owner, ctx, target, "LOGIC", theory.Id, fingerprint, delegate { DiscoveryProtocol p = StarterProtocol("Discriminate · " + (theory.Name ?? "Theory"), "Hypothesis-discrimination protocol projected from a frozen paraconsistent theory. Logical support and empirical likelihood remain separate coordinates."); p.Factors[0].Name = "evidence perturbation"; p.Factors[0].Controllable = false; p.Outcomes[0].Name = theory.Questions == null || theory.Questions.Count == 0 ? "theory discriminant" : theory.Questions[0]; p.Hypotheses[0].Statement = "The frozen theory's current proof spectrum remains observationally adequate."; p.Hypotheses[1].Statement = "A rival empirical mechanism explains the discriminant more accurately."; p.Assumptions.Add("Frozen truth spectrum at projection: " + String.Join(", ", truth.Select(x => x.Key + "=" + x.Value).Take(24).ToArray())); return p; });
        }

        public static void OpenFromVerificationModel(Window owner, DeepSystemsContext ctx, WorldIndex index, VerificationModel model)
        {
            if (ctx == null || model == null) return; Load(ctx); WorldIndex target = index ?? WorldKernel.ExternalIndex(ctx, false); string fingerprint = VerificationKernel.Fingerprint(model); OpenProjection(owner, ctx, target, "VERIFICATION", model.Id, fingerprint, delegate { DiscoveryProtocol p = StarterProtocol("Conformance · " + (model.Name ?? "Finite-state model"), "Conformance measurement plan projected from a formal model. Empirical observation cannot replace the model-checking certificate, and the certificate cannot replace observation."); p.EvidenceNodeIds.AddRange(model.EvidenceNodeIds ?? new List<string>()); p.Factors[0].Name = "input / environment perturbation"; p.Outcomes[0].Name = "trace conformance indicator"; p.Outcomes[0].Scale = "BINARY"; p.Hypotheses[0].Statement = "Observed traces conform to the declared finite-state abstraction within the acceptance boundary."; p.Hypotheses[1].Statement = "Observed traces reveal a systematic abstraction or implementation fault."; p.Assumptions.Add(model.States.Count + " modeled states and " + model.Transitions.Count + " modeled transitions at projection."); return p; });
        }

        public static void OpenFromStrategyModel(Window owner, DeepSystemsContext ctx, WorldIndex index, StrategyModel model)
        {
            if (ctx == null || model == null) return; Load(ctx); WorldIndex target = index ?? WorldKernel.ExternalIndex(ctx, false); string fingerprint = CounterfactualStrategyKernel.Fingerprint(model); OpenProjection(owner, ctx, target, "STRATEGY", model.Id, fingerprint, delegate { DiscoveryProtocol p = ProjectStrategy(model); return p; });
        }

        private static void OpenProjection(Window owner, DeepSystemsContext ctx, WorldIndex index, string kind, string sourceId, string fingerprint, Func<DiscoveryProtocol> create)
        {
            DiscoveryProtocol existing = LatestProjection(kind, sourceId); if (existing != null && Eq(existing.SourceFingerprint, fingerprint)) { OpenProtocol(owner, ctx, index, existing); return; } if (existing != null) { string action = Choose(owner, "DISCOVERY PROJECTION DRIFT", "The source changed after an earlier experimental abstraction. Preserve the historical protocol boundary or create a current projection?", new[] { "OPEN HISTORICAL PROTOCOL", "CREATE CURRENT PROJECTION" }, "OPEN HISTORICAL PROTOCOL"); if (action == "OPEN HISTORICAL PROTOCOL") { OpenProtocol(owner, ctx, index, existing); return; } if (action != "CREATE CURRENT PROJECTION") return; }
            DiscoveryProtocol protocol = create(); protocol.SourceKind = kind; protocol.SourceId = sourceId; protocol.SourceFingerprint = fingerprint; Store.Protocols.Insert(0, protocol); TrimStore(); Save(ctx); AppendLedger(ctx, "PROJECTION_CREATED", protocol.Id, kind + " · " + sourceId, ExperimentalDesignKernel.ProtocolFingerprint(protocol), ""); OpenProtocol(owner, ctx, index, protocol);
        }

        private static void OpenHub(Window owner, DeepSystemsContext ctx, WorldIndex index)
        {
            Window w = W(owner, "YOMI · SCIENTIFIC DISCOVERY HYPERSTRUCTURE", 1300, 880); DockPanel root = new DockPanel { Margin = new Thickness(18) }; StackPanel head = new StackPanel(); head.Children.Add(T("SCIENTIFIC DISCOVERY HYPERSTRUCTURE / EXPERIMENTAL REASONING CIVILIZATION", 27, Text, FontWeights.Bold)); head.Children.Add(T("Preregistered protocols, competing hypotheses, deterministic design synthesis, D-optimal exchange, estimability tribunals, expected information gain, sequential inference, power, replication and bounded research portfolios. It designs and records; it never executes experiments.", 13, Muted, FontWeights.Normal)); head.Children.Add(T(CensusLine(), 11.5, Blue, FontWeights.SemiBold)); WrapPanel tools = new WrapPanel { Margin = new Thickness(0, 10, 0, 10) }; tools.Children.Add(Btn("FORGE PROTOCOL", delegate { CreateProtocolPrompt(w, ctx, index); })); tools.Children.Add(Btn("PORTFOLIO OPTIMIZER", delegate { OpenPortfolio(w, ctx); })); tools.Children.Add(Btn("WORLD KERNEL", delegate { WorldKernel.Open(w, ctx); })); head.Children.Add(tools); DockPanel.SetDock(head, Dock.Top); root.Children.Add(head);
            WrapPanel cards = new WrapPanel();
            Portal(cards, "H₁…Hₙ", "HYPOTHESIS CONSTELLATION", "Competing explicit models with normalized priors, outcome distributions, response-surface terms, assumptions and falsifiers.", delegate { OpenProtocols(w, ctx, index); });
            Portal(cards, "X'X", "DESIGN SYNTHESIZER", "Full and fractional factorial, Latin-hypercube, Halton and deterministic Fedorov-exchange D-optimal run matrices.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) GenerateDesign(w, ctx, index, p); });
            Portal(cards, "rank", "ESTIMABILITY TRIBUNAL", "Matrix rank, log determinant, condition bound, D/G efficiency and pairwise alias cartography for declared models.", delegate { OpenDesigns(w, ctx, index); });
            Portal(cards, "I(H;Y)", "INFORMATION GEOMETRY", "Prior entropy, expected posterior entropy, information gain and Gaussian pairwise separation by candidate run.", delegate { OpenDesigns(w, ctx, index); });
            Portal(cards, "PREREG", "FROZEN PROTOCOL VAULT", "SHA-256 protocol boundaries containing hypotheses, outcomes, stopping, analysis, exclusion, blocking and randomization rules.", delegate { OpenPreregistrations(w, ctx, index); });
            Portal(cards, "P(H|D)", "SEQUENTIAL INFERENCE CHAMBER", "Manual observation intake and stable log-likelihood Bayesian updates without claiming calibration the operator did not supply.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) OpenPosterior(w, ctx, index, p); });
            Portal(cards, "1−β", "POWER & SENSITIVITY FORGE", "Normal-approximation sample-size planning with explicit alpha, target power, variance and minimum relevant effect assumptions.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) OpenPower(w, p); });
            Portal(cards, "ICC", "REPLICATION OBSERVATORY", "Cell replication coverage, pooled within-cell variance, intraclass correlation and sign agreement over recorded observations.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) OpenReproducibility(w, ctx, p); });
            Portal(cards, "ΣEIG", "RESEARCH PORTFOLIO ENGINE", "Exact bounded subset selection under budget, risk, mandatory, dependency and exclusion constraints.", delegate { OpenPortfolio(w, ctx); });
            Portal(cards, "DOSSIER", "DISCOVERY DOSSIERS", "Model-bound research briefs that keep design certificates, interpretation boundaries, caveats and source evidence inseparable.", delegate { OpenDossiers(w, ctx, index); });
            Portal(cards, "AUDIT", "SCIENTIFIC METHOD AUDITOR", "Structural audit for missing factors, outcomes, priors, noise, prediction targets and preregistration boundaries.", delegate { OpenAudit(w, ctx); });
            Portal(cards, "LEDGER", "INTEGRITY LEDGER", "Hash-linked protocol, freeze, design, observation and dossier provenance with independent chain verification.", delegate { OpenLedger(w, ctx); });
            Portal(cards, "ΣSYS", "DYSON SYSTEMS ENGINEERING MEGASTRUCTURE", "Translate a selected protocol into assignment boundaries, calibrated measurement requirements, provenance components, inference interfaces, work packages, budgets and configuration obligations.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) DysonSystemsEngineeringMegastructure.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "ΣPOP", "COMPLEX SYSTEMS LABORATORY", "Project a preregistered protocol into a synthetic interacting population to expose interference, heterogeneity, cascades and emergent confounding omitted by independent-unit assumptions.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) ComplexSystemsLaboratory.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "ORΩ", "OPERATIONS RESEARCH EMPIRE", "Project a preregistered protocol into experiment schedules, scarce-capacity assignments, staffing, inventory and research portfolios while retaining every scientific freeze boundary.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) OperationsResearchEmpire.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "ECONΩ", "ECONOMIC CIVILIZATION", "Project a preregistered protocol into a budget, labor, production and institutional economy without changing its frozen scientific commitments.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) EconomicCivilization.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "GEOΩ", "SPATIAL WORLD CARTOGRAPHY", "Project a preregistered protocol into sites, sampling routes, spatial blocks and field infrastructure without changing its frozen scientific commitments.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) SpatialWorldCartography.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "DISTΩ", "DISTRIBUTED SYSTEMS PLANETARIUM", "Project a preregistered protocol into bounded network and chaos experiments while preserving its frozen design, hypotheses and evidence boundary.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) DistributedSystemsPlanetarium.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "SECΩ", "ADVERSARIAL SECURITY FORTRESS", "Project a preregistered protocol into bounded synthetic defensive exercises while preserving hypotheses, metrics and evidence boundaries.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) AdversarialSecurityFortress.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "DATAΩ", "DATA FOUNDRY", "Project protocol structure and evidence commitments into immutable field-addressable data provenance.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) DataFoundry.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "GENOMEΩ", "SOFTWARE GENOME", "Project a discovery protocol into preregistered codebase investigation context.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) SoftwareGenomeObservatory.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "DOCΩ", "LIVING DOCUMENT", "Project protocol, hypotheses and research evidence into a living dossier without flattening provenance.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) LivingDocumentIntelligenceFactory.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "EXPΩ", "EXPEDITION COMMAND", "Capture the active discovery protocol as a fingerprinted mission crossing with hypotheses, protocol and research evidence retained.", delegate { DiscoveryProtocol p = ChooseProtocol(w); if (p != null) GrandUnifiedExpeditionCommand.OpenFromDiscoveryProtocol(w, ctx, index, p); });
            Portal(cards, "HADAL", "HADAL DESCENT", "Descend recursively into protocols, designs, observations, frozen snapshots, dossiers, portfolios, stores and ledger entries.", delegate { AbyssalKnowledgeEngine.DescendFromExternal(w, ctx, "Scientific Discovery Hyperstructure", Store, StorePath(ctx), "$scientific-discovery", "DISCOVERY HYPERSTRUCTURE"); });
            ScrollViewer scroll = new ScrollViewer { Content = cards, VerticalScrollBarVisibility = ScrollBarVisibility.Auto }; root.Children.Add(scroll); w.Content = root; w.Show();
        }

        private static string CensusLine() { return Store.Protocols.Count(x => Active(x.Status)).ToString(CultureInfo.InvariantCulture) + " active protocols · " + Store.Protocols.Sum(x => x.Factors.Count).ToString(CultureInfo.InvariantCulture) + " factors · " + Store.Protocols.Sum(x => x.Outcomes.Count).ToString(CultureInfo.InvariantCulture) + " outcomes · " + Store.Protocols.Sum(x => x.Hypotheses.Count).ToString(CultureInfo.InvariantCulture) + " hypotheses · " + Store.Designs.Count.ToString(CultureInfo.InvariantCulture) + " frozen designs · " + Store.Observations.Count.ToString(CultureInfo.InvariantCulture) + " observations · " + Store.Preregistrations.Count.ToString(CultureInfo.InvariantCulture) + " preregistrations"; }

        private static void OpenProtocols(Window owner, DeepSystemsContext ctx, WorldIndex index) { Window w = W(owner, "YOMI · PROTOCOL CONSTELLATION", 1180, 780); DockPanel root = Shell("EXPERIMENTAL PROTOCOL CONSTELLATION", CensusLine()); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn("FORGE PROTOCOL", delegate { CreateProtocolPrompt(w, ctx, index); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); ListBox list = List(); list.ItemsSource = Store.Protocols.OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).ToList(); list.MouseDoubleClick += delegate { DiscoveryProtocol p = list.SelectedItem as DiscoveryProtocol; if (p != null) OpenProtocol(w, ctx, index, p); }; root.Children.Add(list); w.Content = root; w.Show(); }
        private static void CreateProtocolPrompt(Window owner, DeepSystemsContext ctx, WorldIndex index) { string name = Prompt(owner, "FORGE PROTOCOL", "Protocol name", "Discovery protocol " + DateTime.Now.ToString("yyyy-MM-dd HHmm", CultureInfo.InvariantCulture)); if (String.IsNullOrWhiteSpace(name)) return; string charter = PromptLarge(owner, "PROTOCOL CHARTER", "Question, scope, causal boundary and non-goals", "A bounded protocol for discriminating explicit hypotheses. Design synthesis is advisory and performs no experiment."); if (charter == null) return; DiscoveryProtocol p = StarterProtocol(name, charter); Store.Protocols.Insert(0, p); TrimStore(); Save(ctx); AppendLedger(ctx, "PROTOCOL_FORGED", p.Id, p.Name, ExperimentalDesignKernel.ProtocolFingerprint(p), ""); OpenProtocol(owner, ctx, index, p); }

        private static DiscoveryProtocol StarterProtocol(string name, string charter)
        {
            string now = Now(), factorId = Id("factor"), outcomeId = Id("outcome"); DiscoveryProtocol p = new DiscoveryProtocol { Id = Id("protocol"), Name = Short(name, 240), Charter = Short(charter, MaxLongText), Status = "DRAFT", CreatedUtc = now, UpdatedUtc = now, DesignMethod = "D_OPTIMAL", RequestedRuns = 16, CandidatePool = 256, Replicates = 1, Seed = 1337, Budget = 1000000, RiskCeiling = 1000000 };
            p.Factors.Add(new DiscoveryFactor { Id = factorId, Name = "experimental factor", Kind = "CONTINUOUS", Status = "ACTIVE", Minimum = -1, Maximum = 1, Levels = 2, Controllable = true, Unit = "coded" }); p.Outcomes.Add(new DiscoveryOutcome { Id = outcomeId, Name = "primary outcome", Scale = "CONTINUOUS", Direction = "TWO_SIDED", Status = "ACTIVE", Unit = "index", NoiseSigma = 1, RelevantEffect = 0.5, Alpha = 0.05, TargetPower = 0.8 });
            DiscoveryHypothesis nullH = new DiscoveryHypothesis { Id = Id("hypothesis"), Name = "H0 · baseline mechanism", Family = "NULL", Status = "ACTIVE", Statement = "The factor has no practically relevant effect on the primary outcome.", PriorWeight = 1, CreatedUtc = now, UpdatedUtc = now }; DiscoveryPrediction nullP = new DiscoveryPrediction { Id = Id("prediction"), OutcomeId = outcomeId, Intercept = 0, Sigma = 1, Distribution = "GAUSSIAN", Rationale = "Baseline response surface." }; nullP.Terms[factorId] = 0; nullH.Predictions.Add(nullP);
            DiscoveryHypothesis altH = new DiscoveryHypothesis { Id = Id("hypothesis"), Name = "H1 · alternative mechanism", Family = "ALTERNATIVE", Status = "ACTIVE", Statement = "The factor changes the primary outcome by the declared minimum relevant effect.", PriorWeight = 1, CreatedUtc = now, UpdatedUtc = now }; DiscoveryPrediction altP = new DiscoveryPrediction { Id = Id("prediction"), OutcomeId = outcomeId, Intercept = 0, Sigma = 1, Distribution = "GAUSSIAN", Rationale = "Minimum-relevant-effect response surface." }; altP.Terms[factorId] = 0.5; altH.Predictions.Add(altP); p.Hypotheses.Add(nullH); p.Hypotheses.Add(altH); p.Assumptions.Add("Prediction distributions and priors are operator-declared modeling inputs, not automatically calibrated probabilities."); return p;
        }

        private static DiscoveryProtocol ProjectStrategy(StrategyModel model)
        {
            DiscoveryProtocol p = new DiscoveryProtocol { Id = Id("protocol"), Name = "Discriminate SCM · " + (model.Name ?? "Strategy model"), Charter = "Experimental projection of a structural causal strategy model. Interventions become controllable factors; objectives become measured outcomes; equations remain hypotheses until empirically supported.", Status = "DRAFT", CreatedUtc = Now(), UpdatedUtc = Now(), DesignMethod = "D_OPTIMAL", RequestedRuns = 24, CandidatePool = 512, Replicates = 2, Seed = 1337, Budget = 1000000, RiskCeiling = 1000000 };
            foreach (StrategyVariable v in (model.Variables ?? new List<StrategyVariable>()).Where(v => Active(v.Status) && (Eq(v.Kind, "EXOGENOUS") || Eq(v.Kind, "DECISION"))).Take(MaxFactors)) p.Factors.Add(new DiscoveryFactor { Id = "strategy-" + v.Id, Name = v.Name, Kind = "CONTINUOUS", Unit = v.Unit, Status = "ACTIVE", Minimum = v.Minimum, Maximum = v.Maximum, Levels = 3, Controllable = Eq(v.Kind, "DECISION"), EvidenceNodeIds = new List<string>(v.EvidenceNodeIds ?? new List<string>()) });
            foreach (StrategyObjective o in (model.Objectives ?? new List<StrategyObjective>()).Where(o => Active(o.Status)).Take(MaxOutcomes)) { StrategyVariable v = model.Variables.FirstOrDefault(x => Eq(x.Id, o.VariableId)); p.Outcomes.Add(new DiscoveryOutcome { Id = "strategy-outcome-" + o.Id, Name = o.Name, Unit = v == null ? "index" : v.Unit, Scale = "CONTINUOUS", Direction = "TWO_SIDED", Status = "ACTIVE", NoiseSigma = 1, RelevantEffect = Math.Max(0.01, Math.Abs(o.Aspiration - (v == null ? 0 : v.Baseline)) * 0.25), Alpha = 0.05, TargetPower = 0.8, EvidenceNodeIds = v == null ? new List<string>() : new List<string>(v.EvidenceNodeIds ?? new List<string>()) }); }
            if (p.Factors.Count == 0) p.Factors.Add(new DiscoveryFactor { Id = Id("factor"), Name = "declared intervention intensity", Kind = "CONTINUOUS", Unit = "coded", Status = "ACTIVE", Minimum = -1, Maximum = 1, Levels = 3, Controllable = true }); if (p.Outcomes.Count == 0) p.Outcomes.Add(new DiscoveryOutcome { Id = Id("outcome"), Name = "declared strategic outcome", Unit = "index", Scale = "CONTINUOUS", Direction = "TWO_SIDED", Status = "ACTIVE", NoiseSigma = 1, RelevantEffect = 0.5, Alpha = 0.05, TargetPower = 0.8 });
            DiscoveryHypothesis h0 = new DiscoveryHypothesis { Id = Id("hypothesis"), Name = "H0 · baseline structural response", Family = "NULL", Status = "ACTIVE", Statement = "Observed response is not practically distinguishable from the declared baseline.", PriorWeight = 1, CreatedUtc = Now(), UpdatedUtc = Now() }; DiscoveryHypothesis h1 = new DiscoveryHypothesis { Id = Id("hypothesis"), Name = "H1 · projected SCM response", Family = "SCM_PROJECTION", Status = "ACTIVE", Statement = "Observed response follows the projected structural mechanism within declared noise.", PriorWeight = 1, CreatedUtc = Now(), UpdatedUtc = Now() };
            foreach (DiscoveryOutcome o in p.Outcomes) { DiscoveryPrediction n = new DiscoveryPrediction { Id = Id("prediction"), OutcomeId = o.Id, Intercept = 0, Sigma = Math.Max(0.0001, o.NoiseSigma), Distribution = "GAUSSIAN", Rationale = "No practically relevant response." }; DiscoveryPrediction a = new DiscoveryPrediction { Id = Id("prediction"), OutcomeId = o.Id, Intercept = 0, Sigma = Math.Max(0.0001, o.NoiseSigma), Distribution = "GAUSSIAN", Rationale = "Projected directional response requiring empirical calibration." }; foreach (DiscoveryFactor f in p.Factors) { n.Terms[f.Id] = 0; a.Terms[f.Id] = o.RelevantEffect / Math.Max(1, p.Factors.Count); } h0.Predictions.Add(n); h1.Predictions.Add(a); } p.Hypotheses.Add(h0); p.Hypotheses.Add(h1); p.Assumptions.Add("Projected from strategy model fingerprint " + Short(CounterfactualStrategyKernel.Fingerprint(model), 32) + "; structural coefficients are not automatically treated as empirical effect estimates."); p.EvidenceNodeIds.AddRange(model.EvidenceNodeIds ?? new List<string>()); return p;
        }

        private static void OpenProtocol(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol p)
        {
            Window w = W(owner, "YOMI · DISCOVERY PROTOCOL · " + p.Name, 1300, 860); DockPanel root = Shell((p.Status ?? "DRAFT") + " · " + p.Name, (p.DesignMethod ?? "D_OPTIMAL") + " · " + p.RequestedRuns + " requested runs / " + p.Replicates + " replicates · r" + p.Revision + " · fingerprint " + Short(ExperimentalDesignKernel.ProtocolFingerprint(p), 20)); WrapPanel tools = new WrapPanel { Margin = new Thickness(0, 6, 0, 8) }; tools.Children.Add(Btn("ADD FACTOR", delegate { AddFactor(w, ctx, p); })); tools.Children.Add(Btn("ADD OUTCOME", delegate { AddOutcome(w, ctx, p); })); tools.Children.Add(Btn("ADD HYPOTHESIS", delegate { AddHypothesis(w, ctx, p); })); tools.Children.Add(Btn("ADD PREDICTION", delegate { AddPrediction(w, ctx, p); })); tools.Children.Add(Btn("DESIGN SETTINGS", delegate { EditDesign(w, ctx, p); })); tools.Children.Add(Btn("PREREG FIELDS", delegate { EditPreregistrationFields(w, ctx, p); })); tools.Children.Add(Btn("FREEZE PREREG", delegate { FreezePreregistration(w, ctx, p); })); tools.Children.Add(Btn("SYNTHESIZE DESIGN", delegate { GenerateDesign(w, ctx, index, p); })); tools.Children.Add(Btn("POWER", delegate { OpenPower(w, p); })); tools.Children.Add(Btn("CYBERNETIC TWIN", delegate { CyberneticDigitalTwinMetastructure.OpenFromDiscoveryProtocol(w, ctx, index, p); })); tools.Children.Add(Btn("COMPLEX POPULATION", delegate { ComplexSystemsLaboratory.OpenFromDiscoveryProtocol(w, ctx, index, p); })); tools.Children.Add(Btn("OPTIMIZE EXPERIMENTS", delegate { OperationsResearchEmpire.OpenFromDiscoveryProtocol(w, ctx, index, p); })); tools.Children.Add(Btn("AUDIT", delegate { OpenProtocolAudit(w, p); })); tools.Children.Add(Btn(Active(p.Status) ? "ARCHIVE" : "RESTORE", delegate { p.Status = Active(p.Status) ? "ARCHIVED" : "ACTIVE"; Touch(p); Save(ctx); AppendLedger(ctx, "PROTOCOL_" + p.Status, p.Id, p.Name, ExperimentalDesignKernel.ProtocolFingerprint(p), ""); w.Close(); })); tools.Children.Add(Btn("HADAL DESCENT", delegate { AbyssalKnowledgeEngine.DescendFromExternal(w, ctx, p.Name, p, StorePath(ctx), "$protocols:" + p.Id, "DISCOVERY › PROTOCOL"); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools);
            Grid body = new Grid(); body.ColumnDefinitions.Add(new ColumnDefinition()); body.ColumnDefinitions.Add(new ColumnDefinition()); body.ColumnDefinitions.Add(new ColumnDefinition()); ListBox factors = List(); factors.ItemsSource = p.Factors; factors.MouseDoubleClick += delegate { DiscoveryFactor f = factors.SelectedItem as DiscoveryFactor; if (f != null) OpenFactor(w, ctx, index, p, f); }; ListBox outcomes = List(); outcomes.ItemsSource = p.Outcomes; outcomes.MouseDoubleClick += delegate { DiscoveryOutcome o = outcomes.SelectedItem as DiscoveryOutcome; if (o != null) OpenOutcome(w, ctx, index, p, o); }; ListBox hypotheses = List(); hypotheses.ItemsSource = p.Hypotheses; hypotheses.MouseDoubleClick += delegate { DiscoveryHypothesis h = hypotheses.SelectedItem as DiscoveryHypothesis; if (h != null) OpenHypothesis(w, ctx, index, p, h); }; Grid.SetColumn(factors, 0); Grid.SetColumn(outcomes, 1); Grid.SetColumn(hypotheses, 2); body.Children.Add(factors); body.Children.Add(outcomes); body.Children.Add(hypotheses); root.Children.Add(body); w.Content = root; w.Show();
        }

        private static void AddFactor(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { if (p.Factors.Count >= MaxFactors) return; string name = Prompt(owner, "ADD FACTOR", "Factor name", "experimental factor"); if (String.IsNullOrWhiteSpace(name)) return; string kind = Choose(owner, "FACTOR KIND", "Measurement scale", new[] { "CONTINUOUS", "ORDINAL", "CATEGORICAL", "BINARY" }, "CONTINUOUS"); if (kind == null) return; double min = Number(Prompt(owner, "LOW LEVEL", "Minimum coded or physical level", "-1"), -1), max = Number(Prompt(owner, "HIGH LEVEL", "Maximum coded or physical level", "1"), 1); if (max < min) { double t = min; min = max; max = t; } int levels = (int)Math.Max(2, Math.Min(32, Number(Prompt(owner, "LEVELS", "Discrete levels for factorial designs", "2"), 2))); string control = Choose(owner, "ASSIGNMENT", "Can the operator randomize this factor?", new[] { "CONTROLLABLE", "OBSERVATIONAL" }, "CONTROLLABLE"); if (control == null) return; double cost = Math.Max(0, Number(Prompt(owner, "PER-RUN COST", "Nonnegative cost burden", "0"), 0)), risk = Math.Max(0, Number(Prompt(owner, "PER-RUN RISK", "Nonnegative risk burden", "0"), 0)); p.Factors.Add(new DiscoveryFactor { Id = Id("factor"), Name = Short(name, 240), Kind = kind, Unit = Short(Prompt(owner, "UNIT", "Physical or coded unit", "coded"), 80), Status = "ACTIVE", Minimum = min, Maximum = max, Levels = levels, Controllable = control == "CONTROLLABLE", PerRunCost = cost, PerRunRisk = risk }); Touch(p); Save(ctx); AppendLedger(ctx, "FACTOR_ADDED", p.Id, name, ExperimentalDesignKernel.ProtocolFingerprint(p), ""); }
        private static void AddOutcome(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { if (p.Outcomes.Count >= MaxOutcomes) return; string name = Prompt(owner, "ADD OUTCOME", "Measured outcome", "primary outcome"); if (String.IsNullOrWhiteSpace(name)) return; string scale = Choose(owner, "OUTCOME SCALE", "Declared measurement family", new[] { "CONTINUOUS", "BINARY", "COUNT", "ORDINAL" }, "CONTINUOUS"); if (scale == null) return; double sigma = Math.Max(0.0000001, Number(Prompt(owner, "NOISE SIGMA", "Declared measurement / outcome standard deviation", "1"), 1)), effect = Math.Max(0.0000001, Math.Abs(Number(Prompt(owner, "MINIMUM RELEVANT EFFECT", "Smallest effect worth detecting", "0.5"), 0.5))), alpha = Math.Max(0.0000001, Math.Min(0.5, Number(Prompt(owner, "ALPHA", "Type-I error boundary", "0.05"), 0.05))), power = Math.Max(0.500001, Math.Min(0.999999, Number(Prompt(owner, "TARGET POWER", "1−β", "0.8"), 0.8))); p.Outcomes.Add(new DiscoveryOutcome { Id = Id("outcome"), Name = Short(name, 240), Unit = Short(Prompt(owner, "UNIT", "Measurement unit", "index"), 80), Scale = scale, Direction = "TWO_SIDED", Status = "ACTIVE", NoiseSigma = sigma, RelevantEffect = effect, Alpha = alpha, TargetPower = power }); Touch(p); Save(ctx); AppendLedger(ctx, "OUTCOME_ADDED", p.Id, name, ExperimentalDesignKernel.ProtocolFingerprint(p), ""); }
        private static void AddHypothesis(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { if (p.Hypotheses.Count >= MaxHypotheses) return; string name = Prompt(owner, "ADD HYPOTHESIS", "Hypothesis name", "Competing mechanism"); if (String.IsNullOrWhiteSpace(name)) return; string statement = PromptLarge(owner, "HYPOTHESIS STATEMENT", "Falsifiable empirical statement and boundary", "The declared response surface differs from every retained competitor."); if (statement == null) return; double prior = Math.Max(0, Number(Prompt(owner, "PRIOR WEIGHT", "Relative plausibility weight; need not sum to one", "1"), 1)); p.Hypotheses.Add(new DiscoveryHypothesis { Id = Id("hypothesis"), Name = Short(name, 240), Family = "COMPETING_MODEL", Status = "ACTIVE", Statement = Short(statement, MaxLongText), PriorWeight = prior, CreatedUtc = Now(), UpdatedUtc = Now() }); Touch(p); Save(ctx); AppendLedger(ctx, "HYPOTHESIS_ADDED", p.Id, name, ExperimentalDesignKernel.ProtocolFingerprint(p), ""); }
        private static void AddPrediction(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { DiscoveryHypothesis h = ChooseObject(owner, "SELECT HYPOTHESIS", "Prediction owner", p.Hypotheses.Cast<object>().ToList()) as DiscoveryHypothesis; if (h == null || h.Predictions.Count >= MaxPredictions) return; DiscoveryOutcome o = ChooseObject(owner, "SELECT OUTCOME", "Predicted response", p.Outcomes.Cast<object>().ToList()) as DiscoveryOutcome; if (o == null) return; double intercept = Number(Prompt(owner, "PREDICTED INTERCEPT", "Mean at zero-coded factor levels", "0"), 0), sigma = Math.Max(0.0000001, Number(Prompt(owner, "PREDICTIVE SIGMA", "Declared Gaussian predictive standard deviation", o.NoiseSigma.ToString("R", CultureInfo.InvariantCulture)), o.NoiseSigma)); DiscoveryPrediction q = new DiscoveryPrediction { Id = Id("prediction"), OutcomeId = o.Id, Intercept = intercept, Sigma = sigma, Distribution = "GAUSSIAN", Rationale = Short(PromptLarge(owner, "PREDICTION RATIONALE", "Mechanistic rationale and caveats", "Operator-declared response surface."), MaxLongText) }; foreach (DiscoveryFactor f in p.Factors.Where(x => Active(x.Status)).Take(MaxTerms)) q.Terms[f.Id] = Number(Prompt(owner, "TERM · " + f.Name, "Coefficient for raw factor value; zero retains no main effect", "0"), 0); h.Predictions.Add(q); h.UpdatedUtc = Now(); Touch(p); Save(ctx); AppendLedger(ctx, "PREDICTION_ADDED", h.Id, o.Name, ExperimentalDesignKernel.ProtocolFingerprint(p), ""); }

        private static void EditDesign(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { string method = Choose(owner, "DESIGN METHOD", "Candidate synthesis strategy", new[] { "D_OPTIMAL", "LATIN_HYPERCUBE", "HALTON", "FULL_FACTORIAL", "FRACTIONAL_FACTORIAL" }, p.DesignMethod); if (method == null) return; p.DesignMethod = method; p.RequestedRuns = (int)Math.Max(1, Math.Min(4096, Number(Prompt(owner, "RUNS", "Requested base design runs", p.RequestedRuns.ToString(CultureInfo.InvariantCulture)), p.RequestedRuns))); p.Replicates = (int)Math.Max(1, Math.Min(64, Number(Prompt(owner, "REPLICATES", "Planned complete replicates", p.Replicates.ToString(CultureInfo.InvariantCulture)), p.Replicates))); p.CandidatePool = (int)Math.Max(p.RequestedRuns, Math.Min(8192, Number(Prompt(owner, "CANDIDATE POOL", "Candidate points considered by D-optimal exchange", p.CandidatePool.ToString(CultureInfo.InvariantCulture)), p.CandidatePool))); p.Seed = (int)Number(Prompt(owner, "DESIGN SEED", "Deterministic sequence seed", p.Seed.ToString(CultureInfo.InvariantCulture)), p.Seed); p.Budget = Math.Max(0, Number(Prompt(owner, "BUDGET", "Maximum aggregate design cost", p.Budget.ToString("R", CultureInfo.InvariantCulture)), p.Budget)); p.RiskCeiling = Math.Max(0, Number(Prompt(owner, "RISK CEILING", "Maximum aggregate risk", p.RiskCeiling.ToString("R", CultureInfo.InvariantCulture)), p.RiskCeiling)); Touch(p); Save(ctx); AppendLedger(ctx, "DESIGN_SETTINGS_REVISED", p.Id, method, ExperimentalDesignKernel.ProtocolFingerprint(p), ""); }
        private static void EditPreregistrationFields(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { string stopping = PromptLarge(owner, "STOPPING RULE", "Fixed or sequential stopping rule; specify decision boundary", p.StoppingRule); if (stopping == null) return; string analysis = PromptLarge(owner, "ANALYSIS PLAN", "Primary model, contrasts, multiplicity and reporting", p.AnalysisPlan); if (analysis == null) return; string exclusions = PromptLarge(owner, "EXCLUSION RULE", "Pre-outcome exclusion and missingness rules", p.ExclusionRule); if (exclusions == null) return; string randomization = PromptLarge(owner, "RANDOMIZATION RULE", "Assignment and sequence-generation rule", p.RandomizationRule); if (randomization == null) return; string blocking = PromptLarge(owner, "BLOCKING RULE", "Blocks, strata and batch boundaries", p.BlockingRule); if (blocking == null) return; p.StoppingRule = Short(stopping, MaxLongText); p.AnalysisPlan = Short(analysis, MaxLongText); p.ExclusionRule = Short(exclusions, MaxLongText); p.RandomizationRule = Short(randomization, MaxLongText); p.BlockingRule = Short(blocking, MaxLongText); Touch(p); Save(ctx); AppendLedger(ctx, "PREREG_FIELDS_REVISED", p.Id, "stopping · analysis · exclusion · randomization · blocking", ExperimentalDesignKernel.ProtocolFingerprint(p), ""); }
        private static void FreezePreregistration(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { List<string> audit = ExperimentalDesignKernel.Audit(p); if (audit.Any(x => x.StartsWith("BLOCKER", StringComparison.OrdinalIgnoreCase))) { MessageBox.Show(owner, String.Join("\r\n", audit.ToArray()), "YOMI · Preregistration Blocked"); return; } string protocolHash = ExperimentalDesignKernel.ProtocolFingerprint(p), preregHash = ExperimentalDesignKernel.PreregistrationFingerprint(p); DiscoveryPreregistration latest = Store.Preregistrations.Where(x => Eq(x.ProtocolId, p.Id)).OrderByDescending(x => x.FrozenUtc).FirstOrDefault(); if (latest != null && Eq(latest.PreregistrationFingerprint, preregHash)) { MessageBox.Show(owner, "An identical frozen preregistration already exists.\r\n\r\n" + preregHash, "YOMI · Preregistration Vault"); return; } string reason = latest == null ? "INITIAL FREEZE" : PromptLarge(owner, "PREREGISTRATION AMENDMENT", "Explain why the frozen boundary changed; prior freeze remains immutable", "Protocol amendment before additional observation intake."); if (reason == null) return; DiscoveryPreregistration frozen = new DiscoveryPreregistration { Id = Id("preregistration"), ProtocolId = p.Id, FrozenUtc = Now(), Status = latest == null ? "FROZEN" : "AMENDED", ParentPreregistrationId = latest == null ? "" : latest.Id, AmendmentReason = Short(reason, MaxLongText), ProtocolFingerprint = protocolHash, PreregistrationFingerprint = preregHash, SnapshotJson = Json.Serialize(p) }; Store.Preregistrations.Insert(0, frozen); Save(ctx); AppendLedger(ctx, latest == null ? "PREREGISTRATION_FROZEN" : "PREREGISTRATION_AMENDED", p.Id, reason, protocolHash, preregHash); MessageBox.Show(owner, "Frozen boundary created.\r\n\r\n" + preregHash, "YOMI · Preregistration Vault"); }

        private static void GenerateDesign(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol p) { List<string> audit = ExperimentalDesignKernel.Audit(p); if (audit.Any(x => x.StartsWith("BLOCKER", StringComparison.OrdinalIgnoreCase))) { MessageBox.Show(owner, String.Join("\r\n", audit.ToArray()), "YOMI · Design Blocked"); return; } List<DiscoveryRun> runs = ExperimentalDesignKernel.Generate(p); DiscoveryDesignDiagnostics diagnostics = ExperimentalDesignKernel.Diagnose(p, runs); DiscoveryDiscrimination discrimination = ExperimentalDesignKernel.Discriminate(p, runs); string protocolHash = ExperimentalDesignKernel.ProtocolFingerprint(p), prereg = ExperimentalDesignKernel.PreregistrationFingerprint(p), designHash = HashText(protocolHash + "|" + String.Join("|", runs.Select(RunFingerprint).ToArray())); DiscoveryDesignRecord record = new DiscoveryDesignRecord { Id = Id("design"), ProtocolId = p.Id, CreatedUtc = Now(), ProtocolFingerprint = protocolHash, PreregistrationFingerprint = prereg, DesignFingerprint = designHash, Method = p.DesignMethod, Runs = runs, Diagnostics = diagnostics, Discrimination = discrimination, PowerPlans = ExperimentalDesignKernel.PowerPlans(p) }; record.CertificateHash = HashText("DISCOVERY_DESIGN_CERTIFICATE_V1|" + record.Id + "|" + protocolHash + "|" + prereg + "|" + designHash + "|" + diagnostics.Rank + "|" + diagnostics.LogDeterminant.ToString("R", CultureInfo.InvariantCulture) + "|" + discrimination.ExpectedInformationGainBits.ToString("R", CultureInfo.InvariantCulture)); Store.Designs.Insert(0, record); TrimStore(); Save(ctx); AppendLedger(ctx, "DESIGN_SYNTHESIZED", record.Id, runs.Count + " runs · " + diagnostics.Rank + "/" + diagnostics.Parameters + " rank", protocolHash, record.CertificateHash); OpenDesign(owner, ctx, index, record); }
        private static void OpenDesigns(Window owner, DeepSystemsContext ctx, WorldIndex index) { Window w = W(owner, "YOMI · FROZEN DESIGN VAULT", 1180, 760); DockPanel root = Shell("FROZEN DESIGN VAULT", Store.Designs.Count + " immutable design records; each retains source protocol and preregistration fingerprints."); ListBox list = List(); list.ItemsSource = Store.Designs.OrderByDescending(x => x.CreatedUtc).ToList(); list.MouseDoubleClick += delegate { DiscoveryDesignRecord d = list.SelectedItem as DiscoveryDesignRecord; if (d != null) OpenDesign(w, ctx, index, d); }; root.Children.Add(list); w.Content = root; w.Show(); }
        private static void OpenDesign(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryDesignRecord d) { DiscoveryProtocol p = Protocol(d.ProtocolId); bool drift = p == null || !Eq(ExperimentalDesignKernel.ProtocolFingerprint(p), d.ProtocolFingerprint); Window w = W(owner, "YOMI · EXPERIMENT DESIGN · " + d.Method, 1320, 860); DockPanel root = Shell((drift ? "PROTOCOL DRIFT · HISTORICAL DESIGN" : "PROTOCOL CURRENT") + " · " + d.Method, (d.Diagnostics == null ? "UNDIAGNOSED" : d.Diagnostics.ToString()) + "\r\n" + (d.Discrimination == null ? "" : d.Discrimination.ToString()) + "\r\ncertificate " + d.CertificateHash); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn("OBSERVATION INTAKE", delegate { if (p != null) RecordObservation(w, ctx, p, d); })); tools.Children.Add(Btn("POSTERIOR", delegate { if (p != null) OpenPosteriorForDesign(w, ctx, p, d); })); tools.Children.Add(Btn("REPRODUCIBILITY", delegate { if (p != null) OpenReproducibilityForDesign(w, ctx, p, d); })); tools.Children.Add(Btn("CREATE DOSSIER", delegate { if (p != null) CreateDossier(w, ctx, index, p, d); })); tools.Children.Add(Btn("ALIASES", delegate { if (d.Diagnostics != null) OpenRows(w, "DESIGN ALIAS CARTOGRAPHY", d.Diagnostics.Aliases.Cast<object>().ToList(), "Pairwise centered term correlations; exact aliases imply non-identifiability."); })); tools.Children.Add(Btn("HADAL DESCENT", delegate { AbyssalKnowledgeEngine.DescendFromExternal(w, ctx, "Design " + d.Id, d, StorePath(ctx), "$designs:" + d.Id, "DISCOVERY › DESIGN"); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); ListBox runs = List(); runs.ItemsSource = d.Runs; DockPanel.SetDock(runs, Dock.Top); runs.MaxHeight = 430; root.Children.Add(runs); string audit = "WARNINGS\r\n" + String.Join("\r\n", (d.Diagnostics == null ? new List<string>() : d.Diagnostics.Warnings).Select(x => "  ! " + x).ToArray()) + "\r\n\r\nDISCRIMINATION AUDIT\r\n" + String.Join("\r\n", (d.Discrimination == null ? new List<string>() : d.Discrimination.Audit).Select(x => "  • " + x).ToArray()); root.Children.Add(ReadOnly(audit)); w.Content = root; w.Show(); }

        private static void RecordObservation(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p, DiscoveryDesignRecord d) { DiscoveryRun run = ChooseObject(owner, "SELECT RUN", "Manual observation provenance anchor", d.Runs.Cast<object>().ToList()) as DiscoveryRun; if (run == null) return; DiscoveryOutcome outcome = ChooseObject(owner, "SELECT OUTCOME", "Measured response", p.Outcomes.Cast<object>().ToList()) as DiscoveryOutcome; if (outcome == null) return; string raw = Prompt(owner, "OBSERVED VALUE", "Manually recorded value; this surface does not execute or acquire measurements", "0"); if (raw == null) return; double value = Number(raw, Double.NaN); if (Double.IsNaN(value)) return; double se = Math.Max(0, Number(Prompt(owner, "STANDARD ERROR", "Declared standard error; zero means unreported", "0"), 0)); string provenance = PromptLarge(owner, "OBSERVATION PROVENANCE", "Source, instrument, operator, timestamp and integrity notes", "Manual intake. No experiment was executed by YOMI."); if (provenance == null) return; DiscoveryObservation o = new DiscoveryObservation { Id = Id("observation"), RunId = run.Id, OutcomeId = outcome.Id, Value = value, StandardError = se, Status = "OBSERVED", RecordedUtc = Now(), Provenance = Short(provenance, MaxLongText) }; Store.Observations.Insert(0, o); TrimStore(); Save(ctx); AppendLedger(ctx, "OBSERVATION_RECORDED", o.Id, run.Id + " · " + outcome.Id + " · " + value.ToString("R", CultureInfo.InvariantCulture), d.ProtocolFingerprint, d.CertificateHash); }
        private static void OpenPosterior(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol p) { DiscoveryDesignRecord d = Store.Designs.Where(x => Eq(x.ProtocolId, p.Id)).OrderByDescending(x => x.CreatedUtc).FirstOrDefault(); if (d == null) { MessageBox.Show(owner, "Synthesize a design before updating hypotheses.", "YOMI · Sequential Inference"); return; } OpenPosteriorForDesign(owner, ctx, p, d); }
        private static void OpenPosteriorForDesign(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p, DiscoveryDesignRecord d) { List<DiscoveryObservation> observations = Store.Observations.Where(o => d.Runs.Any(r => Eq(r.Id, o.RunId)) && p.Outcomes.Any(x => Eq(x.Id, o.OutcomeId))).ToList(); List<DiscoveryHypothesisPosterior> rows = ExperimentalDesignKernel.Update(p, d.Runs, observations); OpenRows(owner, "SEQUENTIAL HYPOTHESIS POSTERIOR", rows.Cast<object>().ToList(), observations.Count + " recorded observations · priors are normalized weights · likelihoods use declared Gaussian response surfaces and standard errors."); }
        private static void OpenPower(Window owner, DiscoveryProtocol p) { OpenRows(owner, "POWER & SAMPLE-SIZE PLANS", ExperimentalDesignKernel.PowerPlans(p).Cast<object>().ToList(), "Explicit z-approximation assumptions are retained on every row; these are planning numbers, not guarantees."); }
        private static void OpenReproducibility(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p) { DiscoveryDesignRecord d = Store.Designs.Where(x => Eq(x.ProtocolId, p.Id)).OrderByDescending(x => x.CreatedUtc).FirstOrDefault(); if (d == null) return; OpenReproducibilityForDesign(owner, ctx, p, d); }
        private static void OpenReproducibilityForDesign(Window owner, DeepSystemsContext ctx, DiscoveryProtocol p, DiscoveryDesignRecord d) { List<DiscoveryObservation> observations = Store.Observations.Where(o => d.Runs.Any(r => Eq(r.Id, o.RunId))).ToList(); DiscoveryReproducibilityProfile profile = ExperimentalDesignKernel.Reproducibility(p, d.Runs, observations); OpenRows(owner, "REPLICATION OBSERVATORY", new List<object> { profile }.Concat(profile.Warnings.Cast<object>()).ToList(), observations.Count + " observations in the selected immutable design boundary."); }

        private static void OpenPreregistrations(Window owner, DeepSystemsContext ctx, WorldIndex index) { Window w = W(owner, "YOMI · FROZEN PREREGISTRATION VAULT", 1200, 780); DockPanel root = Shell("FROZEN PREREGISTRATION VAULT", Store.Preregistrations.Count + " immutable snapshots; amendments link to their frozen parent instead of mutating history."); ListBox list = List(); list.ItemsSource = Store.Preregistrations.OrderByDescending(x => x.FrozenUtc).ToList(); list.MouseDoubleClick += delegate { DiscoveryPreregistration p = list.SelectedItem as DiscoveryPreregistration; if (p != null) OpenPreregistration(w, ctx, p); }; root.Children.Add(list); w.Content = root; w.Show(); }
        private static void OpenPreregistration(Window owner, DeepSystemsContext ctx, DiscoveryPreregistration p) { Window w = W(owner, "YOMI · PREREGISTRATION · " + p.Id, 1120, 780); DockPanel root = Shell((p.Status ?? "FROZEN") + " · " + p.FrozenUtc, "protocol " + p.ProtocolFingerprint + "\r\npreregistration " + p.PreregistrationFingerprint + (String.IsNullOrWhiteSpace(p.ParentPreregistrationId) ? "" : "\r\nparent " + p.ParentPreregistrationId)); root.Children.Add(ReadOnly("AMENDMENT REASON\r\n" + p.AmendmentReason + "\r\n\r\nFROZEN JSON SNAPSHOT\r\n" + p.SnapshotJson)); w.Content = root; w.Show(); }
        private static void CreateDossier(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol p, DiscoveryDesignRecord d) { string title = Prompt(owner, "DISCOVERY DOSSIER", "Dossier title", p.Name + " · experimental design"); if (String.IsNullOrWhiteSpace(title)) return; string boundary = PromptLarge(owner, "INTERPRETATION BOUNDARY", "State what this design could and could not establish", "This design can discriminate the declared models only under the frozen assumptions, ranges, noise model and measurement plan. A synthesized design is not experimental evidence."); if (boundary == null) return; DiscoveryDossier dossier = new DiscoveryDossier { Id = Id("dossier"), ProtocolId = p.Id, DesignId = d.Id, Title = Short(title, 240), Status = "DRAFT", CreatedUtc = Now(), UpdatedUtc = Now(), Question = p.Charter, DesignBoundary = d.Diagnostics == null ? "" : d.Diagnostics.ToString(), InterpretationBoundary = Short(boundary, MaxLongText), ProtocolFingerprint = d.ProtocolFingerprint, DesignCertificate = d.CertificateHash, Caveats = new List<string>(p.Assumptions ?? new List<string>()), EvidenceNodeIds = new List<string>(p.EvidenceNodeIds ?? new List<string>()) }; Store.Dossiers.Insert(0, dossier); Save(ctx); AppendLedger(ctx, "DOSSIER_CREATED", dossier.Id, dossier.Title, d.ProtocolFingerprint, d.CertificateHash); OpenDossier(owner, ctx, index, dossier); }
        private static void OpenDossiers(Window owner, DeepSystemsContext ctx, WorldIndex index) { Window w = W(owner, "YOMI · DISCOVERY DOSSIERS", 1180, 760); DockPanel root = Shell("DISCOVERY DOSSIERS", Store.Dossiers.Count + " model-bound scientific briefs."); ListBox list = List(); list.ItemsSource = Store.Dossiers.OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).ToList(); list.MouseDoubleClick += delegate { DiscoveryDossier d = list.SelectedItem as DiscoveryDossier; if (d != null) OpenDossier(w, ctx, index, d); }; root.Children.Add(list); w.Content = root; w.Show(); }
        private static void OpenDossier(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryDossier d) { DiscoveryProtocol p = Protocol(d.ProtocolId); bool drift = p == null || !Eq(ExperimentalDesignKernel.ProtocolFingerprint(p), d.ProtocolFingerprint); Window w = W(owner, "YOMI · DISCOVERY DOSSIER · " + d.Title, 1220, 820); DockPanel root = Shell((d.Status ?? "DRAFT") + " · " + d.Title, (drift ? "PROTOCOL DRIFT · HISTORICAL BOUNDARY RETAINED" : "PROTOCOL FINGERPRINT CURRENT") + "\r\ncertificate " + d.DesignCertificate); WrapPanel tools = new WrapPanel(); foreach (string status in new[] { "DRAFT", "REVIEWING", "REGISTERED", "RETIRED" }) { string captured = status; tools.Children.Add(Btn(captured, delegate { d.Status = captured; d.UpdatedUtc = Now(); Save(ctx); AppendLedger(ctx, "DOSSIER_" + captured, d.Id, d.Title, d.ProtocolFingerprint, d.DesignCertificate); })); } tools.Children.Add(Btn("ADD CAVEAT", delegate { string text = PromptLarge(w, "DOSSIER CAVEAT", "Threat to validity, alternative explanation or boundary", ""); if (!String.IsNullOrWhiteSpace(text)) { d.Caveats.Insert(0, Short(text, MaxLongText)); d.Caveats = d.Caveats.Take(512).ToList(); d.UpdatedUtc = Now(); Save(ctx); } })); tools.Children.Add(Btn("HADAL DESCENT", delegate { AbyssalKnowledgeEngine.DescendFromExternal(w, ctx, d.Title, d, StorePath(ctx), "$dossiers:" + d.Id, "DISCOVERY › DOSSIER"); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); root.Children.Add(ReadOnly("QUESTION\r\n" + d.Question + "\r\n\r\nDESIGN BOUNDARY\r\n" + d.DesignBoundary + "\r\n\r\nINTERPRETATION BOUNDARY\r\n" + d.InterpretationBoundary + "\r\n\r\nCAVEATS\r\n" + String.Join("\r\n", d.Caveats.Select(x => "  ! " + x).ToArray()))); root.Children.Add(EvidenceList(w, ctx, index, d.EvidenceNodeIds)); w.Content = root; w.Show(); }

        private static void OpenPortfolio(Window owner, DeepSystemsContext ctx) { Window w = W(owner, "YOMI · RESEARCH PORTFOLIO ENGINE", 1220, 820); DockPanel root = Shell("BOUNDED RESEARCH PORTFOLIO", "Experiment candidates are selected under explicit aggregate cost, risk, dependency, exclusion and mandatory constraints."); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn("ADD CANDIDATE", delegate { AddPortfolioCandidate(w, ctx); })); tools.Children.Add(Btn("OPTIMIZE", delegate { double budget = Math.Max(0, Number(Prompt(w, "PORTFOLIO BUDGET", "Maximum total cost", "100"), 100)), risk = Math.Max(0, Number(Prompt(w, "PORTFOLIO RISK", "Maximum total risk", "10"), 10)); DiscoveryPortfolio p = ExperimentalDesignKernel.OptimizePortfolio(Store.PortfolioCandidates, budget, risk); AppendLedger(ctx, "PORTFOLIO_OPTIMIZED", p.Fingerprint, p.ToString(), "", p.Fingerprint); OpenRows(w, "OPTIMIZED RESEARCH PORTFOLIO", new List<object> { p }.Concat(p.SelectedIds.Select(id => (object)(Store.PortfolioCandidates.FirstOrDefault(x => Eq(x.Id, id)) ?? new DiscoveryExperimentCandidate { Id = id })).ToList()).Concat(p.Audit.Cast<object>()).ToList(), "Objective: maximize declared information value under hard burden constraints."); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); ListBox list = List(); list.ItemsSource = Store.PortfolioCandidates; root.Children.Add(list); w.Content = root; w.Show(); }
        private static void AddPortfolioCandidate(Window owner, DeepSystemsContext ctx) { string name = Prompt(owner, "EXPERIMENT CANDIDATE", "Candidate name", "Candidate experiment"); if (String.IsNullOrWhiteSpace(name)) return; double value = Math.Max(0, Number(Prompt(owner, "INFORMATION VALUE", "Declared expected information gain or comparable score", "1"), 1)), cost = Math.Max(0, Number(Prompt(owner, "COST", "Aggregate monetary/time burden", "1"), 1)), risk = Math.Max(0, Number(Prompt(owner, "RISK", "Aggregate ethical/operational risk", "0"), 0)); string mandatory = Choose(owner, "MANDATORY", "Must this candidate be included?", new[] { "NO", "YES" }, "NO"); DiscoveryExperimentCandidate c = new DiscoveryExperimentCandidate { Id = Id("experiment"), Name = Short(name, 240), InformationValue = value, Cost = cost, Risk = risk, Mandatory = mandatory == "YES" }; c.RequiresIds = Lines(PromptLarge(owner, "DEPENDENCIES", "Required candidate IDs, one per line", "")).Take(64).ToList(); c.ExcludesIds = Lines(PromptLarge(owner, "EXCLUSIONS", "Mutually exclusive candidate IDs, one per line", "")).Take(64).ToList(); Store.PortfolioCandidates.Insert(0, c); Save(ctx); AppendLedger(ctx, "PORTFOLIO_CANDIDATE_ADDED", c.Id, c.Name, "", ""); }
        private static void OpenAudit(Window owner, DeepSystemsContext ctx) { List<object> rows = new List<object>(); foreach (DiscoveryProtocol p in Store.Protocols) foreach (string finding in ExperimentalDesignKernel.Audit(p)) rows.Add((p.Name ?? p.Id) + "   ·   " + finding); OpenRows(owner, "SCIENTIFIC METHOD AUDITOR", rows, Store.Protocols.Count + " protocols inspected structurally; this is not empirical validation."); }
        private static void OpenProtocolAudit(Window owner, DiscoveryProtocol p) { OpenRows(owner, "PROTOCOL STRUCTURAL AUDIT", ExperimentalDesignKernel.Audit(p).Cast<object>().ToList(), "Protocol fingerprint " + ExperimentalDesignKernel.ProtocolFingerprint(p)); }
        private static void OpenLedger(Window owner, DeepSystemsContext ctx) { List<DiscoveryLedgerRecord> rows = ReadLedger(ctx, 8192); OpenRows(owner, "DISCOVERY INTEGRITY LEDGER", rows.OrderByDescending(x => x.Sequence).Cast<object>().ToList(), VerifyLedger(rows)); }

        private static void OpenFactor(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol p, DiscoveryFactor f) { Window w = W(owner, "YOMI · FACTOR · " + f.Name, 1060, 720); DockPanel root = Shell((f.Controllable ? "CONTROLLABLE" : "OBSERVATIONAL") + " · " + f.Name, "Domain [" + f.Minimum.ToString("0.######", CultureInfo.InvariantCulture) + ", " + f.Maximum.ToString("0.######", CultureInfo.InvariantCulture) + "] · " + f.Levels + " levels · cost " + f.PerRunCost + " · risk " + f.PerRunRisk); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn(f.Controllable ? "MARK OBSERVATIONAL" : "MARK CONTROLLABLE", delegate { f.Controllable = !f.Controllable; Touch(p); Save(ctx); w.Close(); })); tools.Children.Add(Btn(Active(f.Status) ? "DISABLE" : "ENABLE", delegate { f.Status = Active(f.Status) ? "DISABLED" : "ACTIVE"; Touch(p); Save(ctx); w.Close(); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); root.Children.Add(EvidenceList(w, ctx, index, f.EvidenceNodeIds)); w.Content = root; w.Show(); }
        private static void OpenOutcome(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol p, DiscoveryOutcome o) { Window w = W(owner, "YOMI · OUTCOME · " + o.Name, 1060, 720); DockPanel root = Shell((o.Scale ?? "CONTINUOUS") + " · " + o.Name, "σ " + o.NoiseSigma + " · MDE " + o.RelevantEffect + " · α " + o.Alpha + " · target power " + o.TargetPower); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn(Active(o.Status) ? "DISABLE" : "ENABLE", delegate { o.Status = Active(o.Status) ? "DISABLED" : "ACTIVE"; Touch(p); Save(ctx); w.Close(); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); root.Children.Add(EvidenceList(w, ctx, index, o.EvidenceNodeIds)); w.Content = root; w.Show(); }
        private static void OpenHypothesis(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol p, DiscoveryHypothesis h) { Window w = W(owner, "YOMI · HYPOTHESIS · " + h.Name, 1180, 800); DockPanel root = Shell((h.Status ?? "ACTIVE") + " · " + h.Name, "Prior weight " + h.PriorWeight.ToString("0.######", CultureInfo.InvariantCulture) + " · " + (h.Family ?? "COMPETING_MODEL") + "\r\n" + h.Statement); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn("ASSUMPTIONS", delegate { string raw = PromptLarge(w, "HYPOTHESIS ASSUMPTIONS", "One per line", String.Join("\r\n", h.Assumptions.ToArray())); if (raw != null) { h.Assumptions = Lines(raw).Take(512).ToList(); h.UpdatedUtc = Now(); Touch(p); Save(ctx); } })); tools.Children.Add(Btn("FALSIFIERS", delegate { string raw = PromptLarge(w, "HYPOTHESIS FALSIFIERS", "One empirical disconfirming condition per line", String.Join("\r\n", h.Falsifiers.ToArray())); if (raw != null) { h.Falsifiers = Lines(raw).Take(512).ToList(); h.UpdatedUtc = Now(); Touch(p); Save(ctx); } })); tools.Children.Add(Btn(Active(h.Status) ? "RETRACT" : "RESTORE", delegate { h.Status = Active(h.Status) ? "RETRACTED" : "ACTIVE"; h.UpdatedUtc = Now(); Touch(p); Save(ctx); w.Close(); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); ListBox list = List(); list.ItemsSource = h.Predictions; root.Children.Add(list); root.Children.Add(EvidenceList(w, ctx, index, h.EvidenceNodeIds)); w.Content = root; w.Show(); }

        private static DiscoveryProtocol LatestProjection(string kind, string id) { return Store.Protocols.Where(x => Eq(x.SourceKind, kind) && Eq(x.SourceId, id)).OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).FirstOrDefault(); }
        private static DiscoveryProtocol Protocol(string id) { return Store.Protocols.FirstOrDefault(x => Eq(x.Id, id)); }
        private static DiscoveryProtocol ChooseProtocol(Window owner) { return ChooseObject(owner, "SELECT DISCOVERY PROTOCOL", "Choose an active protocol", Store.Protocols.Where(x => Active(x.Status)).OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).Cast<object>().ToList()) as DiscoveryProtocol; }
        private static void Touch(DiscoveryProtocol p) { p.Revision = Math.Max(1, p.Revision) + 1; p.UpdatedUtc = Now(); }

        private static void Load(DeepSystemsContext ctx) { lock (Gate) { if (Store != null && Eq(LoadedRoot, ctx.StateRoot)) return; LoadedRoot = ctx.StateRoot; Store = null; string path = StorePath(ctx); if (File.Exists(path)) try { Store = Json.Deserialize<ScientificDiscoveryStore>(File.ReadAllText(path, Encoding.UTF8)); } catch { PreserveCorrupt(path); } if (Store == null && File.Exists(path + ".previous")) try { Store = Json.Deserialize<ScientificDiscoveryStore>(File.ReadAllText(path + ".previous", Encoding.UTF8)); } catch { } if (Store == null) Store = new ScientificDiscoveryStore(); NormalizeStore(); } }
        private static void NormalizeStore() { if (Store == null) Store = new ScientificDiscoveryStore(); Store.Schema = 1; Store.Protocols = Store.Protocols ?? new List<DiscoveryProtocol>(); Store.Designs = Store.Designs ?? new List<DiscoveryDesignRecord>(); Store.Observations = Store.Observations ?? new List<DiscoveryObservation>(); Store.Preregistrations = Store.Preregistrations ?? new List<DiscoveryPreregistration>(); Store.Dossiers = Store.Dossiers ?? new List<DiscoveryDossier>(); Store.PortfolioCandidates = Store.PortfolioCandidates ?? new List<DiscoveryExperimentCandidate>(); Store.RecentQuestions = Store.RecentQuestions ?? new List<string>(); foreach (DiscoveryProtocol p in Store.Protocols) { p.Factors = (p.Factors ?? new List<DiscoveryFactor>()).Take(MaxFactors).ToList(); p.Outcomes = (p.Outcomes ?? new List<DiscoveryOutcome>()).Take(MaxOutcomes).ToList(); p.Hypotheses = (p.Hypotheses ?? new List<DiscoveryHypothesis>()).Take(MaxHypotheses).ToList(); p.Assumptions = p.Assumptions ?? new List<string>(); p.EvidenceNodeIds = (p.EvidenceNodeIds ?? new List<string>()).Distinct(StringComparer.OrdinalIgnoreCase).Take(MaxEvidence).ToList(); foreach (DiscoveryFactor f in p.Factors) f.EvidenceNodeIds = (f.EvidenceNodeIds ?? new List<string>()).Take(MaxEvidence).ToList(); foreach (DiscoveryOutcome o in p.Outcomes) o.EvidenceNodeIds = (o.EvidenceNodeIds ?? new List<string>()).Take(MaxEvidence).ToList(); foreach (DiscoveryHypothesis h in p.Hypotheses) { h.Predictions = (h.Predictions ?? new List<DiscoveryPrediction>()).Take(MaxPredictions).ToList(); h.Assumptions = h.Assumptions ?? new List<string>(); h.Falsifiers = h.Falsifiers ?? new List<string>(); h.EvidenceNodeIds = (h.EvidenceNodeIds ?? new List<string>()).Take(MaxEvidence).ToList(); foreach (DiscoveryPrediction q in h.Predictions) { q.Terms = q.Terms ?? new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase); q.EvidenceNodeIds = q.EvidenceNodeIds ?? new List<string>(); } } } foreach (DiscoveryDesignRecord d in Store.Designs) { d.Runs = d.Runs ?? new List<DiscoveryRun>(); d.PowerPlans = d.PowerPlans ?? new List<DiscoveryPowerPlan>(); } foreach (DiscoveryObservation o in Store.Observations) o.EvidenceNodeIds = o.EvidenceNodeIds ?? new List<string>(); foreach (DiscoveryDossier d in Store.Dossiers) { d.Caveats = d.Caveats ?? new List<string>(); d.EvidenceNodeIds = d.EvidenceNodeIds ?? new List<string>(); } foreach (DiscoveryExperimentCandidate c in Store.PortfolioCandidates) { c.RequiresIds = c.RequiresIds ?? new List<string>(); c.ExcludesIds = c.ExcludesIds ?? new List<string>(); } }
        private static void TrimStore() { NormalizeStore(); Store.Protocols = Store.Protocols.Take(MaxProtocols).ToList(); Store.Designs = Store.Designs.Take(MaxDesigns).ToList(); Store.Observations = Store.Observations.Take(MaxObservations).ToList(); Store.Preregistrations = Store.Preregistrations.Take(MaxPreregistrations).ToList(); Store.Dossiers = Store.Dossiers.Take(MaxDossiers).ToList(); Store.PortfolioCandidates = Store.PortfolioCandidates.Take(256).ToList(); Store.RecentQuestions = Store.RecentQuestions.Take(192).ToList(); }
        private static void Save(DeepSystemsContext ctx) { lock (Gate) { TrimStore(); Store.Revision = Math.Max(0, Store.Revision) + 1; Store.UpdatedUtc = Now(); Store.LastCommitId = Id("discovery-commit"); string path = StorePath(ctx); Directory.CreateDirectory(Path.GetDirectoryName(path)); AtomicWrite(path, Json.Serialize(Store)); } }
        private static void AtomicWrite(string path, string text) { string temp = path + ".tmp." + Guid.NewGuid().ToString("N"); File.WriteAllText(temp, text ?? "", new UTF8Encoding(false)); if (File.Exists(path)) { string previous = path + ".previous"; try { File.Replace(temp, path, previous, true); return; } catch { try { File.Copy(path, previous, true); } catch { } } } if (File.Exists(path)) File.Delete(path); File.Move(temp, path); }
        private static void PreserveCorrupt(string path) { try { if (!File.Exists(path)) return; byte[] bytes = File.ReadAllBytes(path); string destination = path + ".corrupt." + HashBytes(bytes).Substring(0, 16) + ".json"; if (!File.Exists(destination)) File.Copy(path, destination); } catch { } }
        private static string StorePath(DeepSystemsContext ctx) { return Path.Combine(ctx.StateRoot, "controller-scientific-discovery.json"); }
        private static string LedgerPath(DeepSystemsContext ctx) { return Path.Combine(ctx.StateRoot, "controller-scientific-discovery-ledger.jsonl"); }
        private static void AppendLedger(DeepSystemsContext ctx, string evt, string subject, string detail, string fingerprint, string certificate) { lock (Gate) try { Directory.CreateDirectory(ctx.StateRoot); List<DiscoveryLedgerRecord> prior = ReadLedger(ctx, 8192); DiscoveryLedgerRecord last = prior.OrderByDescending(x => x.Sequence).FirstOrDefault(); DiscoveryLedgerRecord r = new DiscoveryLedgerRecord { Schema = 1, Sequence = last == null ? 1 : last.Sequence + 1, Utc = Now(), Event = Short(evt, 120), Subject = Short(subject, 512), Detail = Short(detail, MaxLongText), CorrelationId = Store == null ? "" : Store.LastCommitId, ProtocolFingerprint = Short(fingerprint, 128), CertificateHash = Short(certificate, 128), PrevHash = last == null ? new string('0', 64) : last.EntryHash }; r.EntryHash = LedgerHash(r); byte[] bytes = Encoding.UTF8.GetBytes(Json.Serialize(r) + Environment.NewLine); using (FileStream stream = new FileStream(LedgerPath(ctx), FileMode.Append, FileAccess.Write, FileShare.Read, 4096, FileOptions.WriteThrough)) { stream.Write(bytes, 0, bytes.Length); stream.Flush(); } } catch { } }
        private static List<DiscoveryLedgerRecord> ReadLedger(DeepSystemsContext ctx, int cap) { List<DiscoveryLedgerRecord> rows = new List<DiscoveryLedgerRecord>(); if (!File.Exists(LedgerPath(ctx))) return rows; try { foreach (string line in TakeLast(File.ReadLines(LedgerPath(ctx)).Where(x => !String.IsNullOrWhiteSpace(x)), cap)) try { DiscoveryLedgerRecord row = Json.Deserialize<DiscoveryLedgerRecord>(line); if (row != null) rows.Add(row); } catch { } } catch { } return rows; }
        private static string VerifyLedger(List<DiscoveryLedgerRecord> rows) { if (rows == null || rows.Count == 0) return "EMPTY LEDGER"; rows = rows.OrderBy(x => x.Sequence).ToList(); long expected = rows[0].Sequence; string prior = rows[0].PrevHash; foreach (DiscoveryLedgerRecord row in rows) { if (row.Sequence != expected) return "CHAIN GAP @ " + expected; if (!Eq(row.PrevHash, prior)) return "PREV HASH MISMATCH @ " + row.Sequence; if (!Eq(row.EntryHash, LedgerHash(row))) return "ENTRY HASH MISMATCH @ " + row.Sequence; expected++; prior = row.EntryHash; } return "CHAIN VERIFIED · " + rows.Count.ToString(CultureInfo.InvariantCulture) + " RECORDS"; }
        private static string LedgerHash(DiscoveryLedgerRecord r) { return HashText(r.Schema + "|" + r.Sequence + "|" + (r.Utc ?? "") + "|" + (r.Event ?? "") + "|" + (r.Subject ?? "") + "|" + (r.Detail ?? "") + "|" + (r.CorrelationId ?? "") + "|" + (r.ProtocolFingerprint ?? "") + "|" + (r.CertificateHash ?? "") + "|" + (r.PrevHash ?? "")); }

        private static void OpenRows(Window owner, string title, IList<object> rows, string subtitle) { Window w = W(owner, "YOMI · " + title, 1180, 780); DockPanel root = Shell(title, subtitle); ListBox list = List(); list.ItemsSource = rows ?? new List<object>(); root.Children.Add(list); w.Content = root; w.Show(); }
        private static string RunFingerprint(DiscoveryRun r) { return r.Id + "|" + r.Sequence + "|" + r.Block + "|" + r.Replicate + "|" + r.Cost.ToString("R", CultureInfo.InvariantCulture) + "|" + r.Risk.ToString("R", CultureInfo.InvariantCulture) + "|" + String.Join("|", r.Levels.OrderBy(x => x.Key).Select(x => x.Key + "=" + x.Value.ToString("R", CultureInfo.InvariantCulture)).ToArray()); }
        private static bool Active(string status) { return !Eq(status, "ARCHIVED") && !Eq(status, "DISABLED") && !Eq(status, "RETRACTED") && !Eq(status, "REJECTED"); }
        private static bool Eq(string a, string b) { return String.Equals(a ?? "", b ?? "", StringComparison.OrdinalIgnoreCase); }
        private static double Number(string raw, double fallback) { double value; return Double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out value) && !Double.IsNaN(value) && !Double.IsInfinity(value) ? value : fallback; }
        private static List<string> Lines(string raw) { return (raw ?? "").Replace("\r", "").Split(new[] { '\n', ';' }, StringSplitOptions.RemoveEmptyEntries).Select(x => x.Trim()).Where(x => x.Length > 0).Distinct(StringComparer.OrdinalIgnoreCase).ToList(); }
        private static string Short(string value, int cap) { value = value ?? ""; cap = Math.Max(1, cap); return value.Length <= cap ? value : value.Substring(0, cap - 1) + "…"; }
        private static string HashText(string value) { return HashBytes(Encoding.UTF8.GetBytes(value ?? "")); }
        private static string HashBytes(byte[] value) { using (SHA256 hash = SHA256.Create()) return BitConverter.ToString(hash.ComputeHash(value ?? new byte[0])).Replace("-", "").ToLowerInvariant(); }
        private static string Id(string prefix) { return prefix + "-" + DateTime.UtcNow.ToString("yyyyMMddHHmmssfff", CultureInfo.InvariantCulture) + "-" + Guid.NewGuid().ToString("N").Substring(0, 8); }
        private static string Now() { return DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture); }
        private static IEnumerable<TValue> TakeLast<TValue>(IEnumerable<TValue> source, int count) { Queue<TValue> q = new Queue<TValue>(); foreach (TValue item in source ?? Enumerable.Empty<TValue>()) { q.Enqueue(item); if (q.Count > count) q.Dequeue(); } foreach (TValue item in q) yield return item; }

        private static ListBox EvidenceList(Window owner, DeepSystemsContext ctx, WorldIndex index, IEnumerable<string> ids) { ListBox list = List(); list.MaxHeight = 180; if (index != null) list.ItemsSource = (ids ?? Enumerable.Empty<string>()).Where(index.Nodes.ContainsKey).Select(x => index.Nodes[x]).ToList(); list.MouseDoubleClick += delegate { WorldNode n = list.SelectedItem as WorldNode; if (n != null) WorldKernel.ExternalOpenDossier(owner, ctx, index, n.Id); }; return list; }
        private static Window W(Window owner, string title, double width, double height) { return new Window { Title = title, Width = width, Height = height, MinWidth = Math.Min(width, 820), MinHeight = Math.Min(height, 560), Background = Bg, Foreground = Text, WindowStartupLocation = WindowStartupLocation.CenterOwner, Owner = owner, FontFamily = new FontFamily("Segoe UI") }; }
        private static DockPanel Shell(string title, string subtitle) { DockPanel root = new DockPanel { Margin = new Thickness(16) }; StackPanel head = new StackPanel { Margin = new Thickness(0, 0, 0, 10) }; head.Children.Add(T(title, 24, Text, FontWeights.Bold)); head.Children.Add(T(subtitle, 12, Muted, FontWeights.Normal)); DockPanel.SetDock(head, Dock.Top); root.Children.Add(head); return root; }
        private static TextBlock T(string value, double size, Brush foreground, FontWeight weight) { return new TextBlock { Text = value ?? "", FontSize = size, Foreground = foreground, FontWeight = weight, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 2, 0, 2) }; }
        private static Button Btn(string label, RoutedEventHandler click) { Button button = new Button { Content = label, Margin = new Thickness(0, 0, 8, 8), Padding = new Thickness(12, 7, 12, 7), Background = Raised, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), MinWidth = 112 }; if (click != null) button.Click += click; return button; }
        private static ListBox List() { return new ListBox { Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), Margin = new Thickness(0, 6, 6, 0), Padding = new Thickness(5), FontFamily = new FontFamily("Cascadia Mono, Consolas") }; }
        private static TextBox ReadOnly(string value) { return new TextBox { Text = value ?? "", IsReadOnly = true, AcceptsReturn = true, TextWrapping = TextWrapping.Wrap, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollBarVisibility = ScrollBarVisibility.Auto, Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), Padding = new Thickness(10), Margin = new Thickness(0, 6, 6, 0), FontFamily = new FontFamily("Cascadia Mono, Consolas") }; }
        private static void Portal(Panel parent, string badge, string title, string description, Action open) { Button button = new Button { Width = 360, Height = 120, Margin = new Thickness(0, 0, 10, 10), Padding = new Thickness(12), Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), HorizontalContentAlignment = HorizontalAlignment.Stretch }; StackPanel content = new StackPanel(); content.Children.Add(T(badge + "   " + title, 14, Accent, FontWeights.Bold)); content.Children.Add(T(description, 11.5, Muted, FontWeights.Normal)); button.Content = content; button.Click += delegate { if (open != null) open(); }; parent.Children.Add(button); }
        private static Brush B(string hex) { return new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex)); }
        private static string Prompt(Window owner, string title, string label, string initial) { Window w = W(owner, "YOMI · " + title, 660, 280); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); TextBox editor = new TextBox { Text = initial ?? "", MaxLength = MaxShortText, Margin = new Thickness(0, 8, 0, 10), Background = Surface, Foreground = Text, BorderBrush = Border, Padding = new Thickness(8) }; DockPanel.SetDock(editor, Dock.Top); root.Children.Add(editor); WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right }; string result = null; buttons.Children.Add(Btn("OK", delegate { result = editor.Text; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); root.Children.Add(buttons); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static string PromptLarge(Window owner, string title, string label, string initial) { Window w = W(owner, "YOMI · " + title, 780, 540); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); TextBox editor = new TextBox { Text = initial ?? "", MaxLength = MaxLongText, AcceptsReturn = true, AcceptsTab = true, TextWrapping = TextWrapping.NoWrap, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollBarVisibility = ScrollBarVisibility.Auto, Margin = new Thickness(0, 8, 0, 0), Background = Surface, Foreground = Text, BorderBrush = Border, Padding = new Thickness(10), FontFamily = new FontFamily("Cascadia Mono, Consolas") }; WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) }; string result = null; buttons.Children.Add(Btn("SAVE", delegate { result = editor.Text; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(editor); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static string Choose(Window owner, string title, string label, IEnumerable<string> choices, string preferred) { object selected = ChooseObject(owner, title, label, (choices ?? Enumerable.Empty<string>()).Cast<object>().ToList(), preferred); return selected == null ? null : Convert.ToString(selected, CultureInfo.InvariantCulture); }
        private static object ChooseObject(Window owner, string title, string label, IList<object> choices) { return ChooseObject(owner, title, label, choices, null); }
        private static object ChooseObject(Window owner, string title, string label, IList<object> choices, string preferred) { Window w = W(owner, "YOMI · " + title, 700, 470); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); ListBox list = List(); list.ItemsSource = choices ?? new List<object>(); if (!String.IsNullOrWhiteSpace(preferred)) list.SelectedItem = list.Items.Cast<object>().FirstOrDefault(x => Eq(Convert.ToString(x, CultureInfo.InvariantCulture), preferred)); if (list.SelectedIndex < 0 && list.Items.Count > 0) list.SelectedIndex = 0; WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) }; object result = null; buttons.Children.Add(Btn("SELECT", delegate { result = list.SelectedItem; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); list.MouseDoubleClick += delegate { result = list.SelectedItem; if (result != null) w.DialogResult = true; }; DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(list); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
    }
}
