using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class SynthesisTheoremCandidate
    {
        public string Id { get; set; }
        public string PatternId { get; set; }
        public string Statement { get; set; }
        public string Scope { get; set; }
        public string Status { get; set; }
        public string CreatedUtc { get; set; }
        public string Fingerprint { get; set; }
        public override string ToString(){return (Status??"CANDIDATE")+"   ·   "+(Statement??Id)+"   ·   scope "+(Scope??"UNSPECIFIED")+"   ·   pattern "+CivilizationalSynthesisKernel.Short(PatternId);}
    }
    internal sealed class SynthesisNote
    {
        public string Id { get; set; }
        public string SubjectId { get; set; }
        public string Text { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (SubjectId??"SYNTHΩ")+"   ·   "+(Text??"");}
    }
    internal sealed class SynthesisTransferTrial
    {
        public string Id { get; set; }
        public string PatternId { get; set; }
        public string TargetMissionId { get; set; }
        public string Question { get; set; }
        public string Status { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (Status??"PROPOSED")+"   ·   "+(Question??Id)+"   ·   target "+(TargetMissionId??"NEW")+"   ·   pattern "+CivilizationalSynthesisKernel.Short(PatternId);}
    }
    internal sealed class SynthesisBaseline
    {
        public string Id { get; set; }
        public string SnapshotFingerprint { get; set; }
        public int Patterns { get; set; }
        public int Transfers { get; set; }
        public int Missions { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (CreatedUtc??"")+"   ·   patterns "+Patterns+"   ·   transfers "+Transfers+"   ·   missions "+Missions+"   ·   "+CivilizationalSynthesisKernel.Short(SnapshotFingerprint);}
    }
    internal sealed class SynthesisSeal
    {
        public string Id { get; set; }
        public string SnapshotFingerprint { get; set; }
        public int Patterns { get; set; }
        public int TheoremCandidates { get; set; }
        public string CreatedUtc { get; set; }
        public string CertificateHash { get; set; }
        public override string ToString(){return "SYNTHESIS SEAL   ·   patterns "+Patterns+"   ·   theorem candidates "+TheoremCandidates+"   ·   "+CivilizationalSynthesisKernel.Short(SnapshotFingerprint);}
    }
    internal sealed class SynthesisStore
    {
        public int Schema { get; set; }
        public List<SynthesisTheoremCandidate> Theorems { get; set; }
        public List<SynthesisNote> Notes { get; set; }
        public List<SynthesisTransferTrial> Trials { get; set; }
        public List<SynthesisBaseline> Baselines { get; set; }
        public List<SynthesisSeal> Seals { get; set; }
        public SynthesisStore(){Schema=1;Theorems=new List<SynthesisTheoremCandidate>();Notes=new List<SynthesisNote>();Trials=new List<SynthesisTransferTrial>();Baselines=new List<SynthesisBaseline>();Seals=new List<SynthesisSeal>();}
    }

    internal static class CivilizationalSynthesisReactor
    {
        private static readonly Brush Bg=B("#080A0E"),Surface=B("#10141B"),Raised=B("#171D27"),Border=B("#2B3443"),Text=B("#E8EDF4"),Muted=B("#97A2B2"),Accent=B("#F3B44C"),Green=B("#70D6A4"),Red=B("#FF7B7B");
        private static SynthesisStore Store;
        private static SynthesisSnapshot Snapshot;
        private static string LoadedExpeditionFingerprint;

        public static void Open(Window owner,DeepSystemsContext ctx)
        {
            if(ctx==null)return;Load(ctx);RefreshSnapshot(ctx);
            Window w=W(owner,"YOMI · SYNTHΩ · CIVILIZATIONAL SYNTHESIS REACTOR",1540,980);DockPanel root=Shell("SYNTHΩ · CIVILIZATIONAL SYNTHESIS REACTOR","Mine recurring structures across the investigation universe, preserve counterexamples, test transferability, and promote only explicitly reviewed theorem candidates. Recurrence is never silently promoted to truth.");
            ScrollViewer scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};WrapPanel chambers=new WrapPanel{Margin=new Thickness(12)};scroll.Content=chambers;root.Children.Add(scroll);
            Portal(chambers,"VOIDΩ","UNKNOWN UNKNOWNS OBSERVATORY","Rise from recurring patterns into source monocultures, theory-test debt, unresolved disagreements and blind-spot candidates.",delegate{UnknownUnknownsObservatory.Open(w,ctx);});
            Portal(chambers,"CORE","SYNTHESIS SNAPSHOT","Current pattern universe derived from METAΩ + retained EXPΩ missions.",delegate{RefreshSnapshot(ctx);TextView(w,"SYNTHESIS SNAPSHOT",ctx.Json.Serialize(Snapshot));});
            Portal(chambers,"PAT","PATTERN UNIVERSE","All automatically mined cross-mission structures, visibly marked heuristic.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"PATTERN UNIVERSE",Snapshot.Patterns.Cast<object>().ToList(),"Every automatic pattern remains a candidate navigation structure, not a theorem.");});
            Portal(chambers,"INV?","INVARIANT CANDIDATES","Broad low-conflict recurrences with multi-mission and multi-source support.",delegate{Kinds(w,ctx,"INVARIANT CANDIDATE","INVARIANT_CANDIDATE");});
            Portal(chambers,"MOTIF","RECURRING MOTIFS","Cross-mission co-occurrence structures retained with support breadth.",delegate{Kinds(w,ctx,"RECURRING MOTIFS","MOTIF");});
            Portal(chambers,"REC","RECURRENCE FIELD","Single-concept recurrences across independent mission worldlines.",delegate{Kinds(w,ctx,"RECURRENCE FIELD","RECURRENCE");});
            Portal(chambers,"FAIL","FAILURE SIGNATURES","Structures repeatedly appearing inside explicit unresolved contradiction contexts.",delegate{Kinds(w,ctx,"FAILURE SIGNATURES","FAILURE_SIGNATURE");});
            Portal(chambers,"ANTI","ANTI-PATTERN CANDIDATES","Recurring motifs with elevated explicit contradiction load.",delegate{Kinds(w,ctx,"ANTI-PATTERN CANDIDATES","ANTI_PATTERN_CANDIDATE");});
            Portal(chambers,"STAB","STABILITY SPECTRUM","Rank patterns by bounded support/independence/contradiction synthesis score.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"STABILITY SPECTRUM",Snapshot.Patterns.OrderByDescending(x=>x.Stability).Cast<object>().ToList(),"Stability is a deterministic prioritization score, not empirical truth probability.");});
            Portal(chambers,"INDEP","INDEPENDENCE SPECTRUM","Patterns ranked by source diversity relative to mission support.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"INDEPENDENCE SPECTRUM",Snapshot.Patterns.OrderByDescending(x=>x.Independence).Cast<object>().ToList(),"Repeated use of the same source is not independent replication.");});
            Portal(chambers,"BREADTH","SUPPORT BREADTH","Patterns ordered by number of distinct supporting missions.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"SUPPORT BREADTH",Snapshot.Patterns.OrderByDescending(x=>x.SupportMissions).ThenByDescending(x=>x.SupportFindings).Cast<object>().ToList(),"Breadth describes recurrence coverage only.");});
            Portal(chambers,"SRC","SOURCE MULTIPLICITY","Patterns ordered by distinct retained source fingerprints.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"SOURCE MULTIPLICITY",Snapshot.Patterns.OrderByDescending(x=>x.UniqueSources).Cast<object>().ToList(),"Fingerprint diversity is structural diversity, not source quality certification.");});
            Portal(chambers,"CONTRA","COUNTEREXAMPLE VAULT","Patterns carrying mission-level contradiction counterexamples.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"COUNTEREXAMPLE VAULT",Snapshot.Patterns.Where(x=>x.CounterexampleMissionIds.Count>0).OrderByDescending(x=>x.CounterexampleMissionIds.Count).Cast<object>().ToList(),"Counterexamples remain attached; promotion never erases them.");});
            Portal(chambers,"LOAD","CONTRADICTION LOAD","Patterns ranked by explicit unresolved contradiction participation.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CONTRADICTION LOAD",Snapshot.Patterns.OrderByDescending(x=>x.ContradictionLoad).Cast<object>().ToList(),"Conflict load is recorded contradiction participation, not falsity probability.");});
            Portal(chambers,"PRE","PRECONDITION MATRIX","Inspect supporting civilization contexts attached as transfer prerequisites.",delegate{ShowPreconditions(w,ctx);});
            Portal(chambers,"FAM","PATTERN FAMILIES","Group the mined universe by pattern kind.",delegate{ShowFamilies(w,ctx);});
            Portal(chambers,"TOK","CONCEPT MOTIF INDEX","Index recurring concept tokens and paired motifs.",delegate{ShowTokens(w,ctx);});
            Portal(chambers,"XFER","TRANSFER LAB","All candidate pattern-to-mission transfer probes.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"TRANSFER LAB",Snapshot.TransferProbes.Cast<object>().ToList(),"Transfer probes are untested suggestions with explicit risk and missing preconditions.");});
            Portal(chambers,"LOW","LOW-RISK TRANSFER QUEUE","Transfer candidates with bounded risk below 0.34.",delegate{TransferBand(w,ctx,"LOW-RISK TRANSFER QUEUE",0,0.34);});
            Portal(chambers,"MID","MEDIUM-RISK TRANSFER QUEUE","Transfer candidates between 0.34 and 0.67 risk.",delegate{TransferBand(w,ctx,"MEDIUM-RISK TRANSFER QUEUE",0.34,0.67);});
            Portal(chambers,"HIGH","HIGH-RISK TRANSFER QUEUE","Transfers requiring aggressive skepticism before use.",delegate{TransferBand(w,ctx,"HIGH-RISK TRANSFER QUEUE",0.67,1.01);});
            Portal(chambers,"MISS","MISSING PRECONDITIONS","Transfers sorted by absent supporting civilization contexts.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"MISSING PRECONDITIONS",Snapshot.TransferProbes.OrderByDescending(x=>x.MissingPreconditions.Count).Cast<object>().ToList(),"Missing context raises transfer risk; it does not prove transfer failure.");});
            Portal(chambers,"CTX","CONTEXT OVERLAP","Transfers ranked by lexical overlap with target mission context.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CONTEXT OVERLAP",Snapshot.TransferProbes.OrderByDescending(x=>x.ContextOverlap).Cast<object>().ToList(),"Lexical overlap is heuristic context similarity only.");});
            Portal(chambers,"TRY","LAUNCH TRANSFER EXPEDITION","Choose a pattern and create a new EXPΩ mission whose job is to test transfer, not assume it.",delegate{LaunchTransfer(w,ctx);});
            Portal(chambers,"TRIAL","TRANSFER TRIAL LEDGER","Persistent proposed/started transfer tests.",delegate{OpenCollection(w,"TRANSFER TRIAL LEDGER",Store.Trials.Cast<object>().ToList(),"Trials are local synthesis planning records; EXPΩ owns mission evidence.");});
            Portal(chambers,"THM?","THEOREM-CANDIDATE VAULT","Human-promoted scoped statements. Candidate status is mandatory.",delegate{OpenCollection(w,"THEOREM-CANDIDATE VAULT",Store.Theorems.Cast<object>().ToList(),"Promotion means worthy of explicit testing and review, not proven.");});
            Portal(chambers,"PROM","PROMOTE PATTERN TO THEOREM CANDIDATE","Select a mined pattern, write a scoped statement, preserve its provenance.",delegate{Promote(w,ctx);});
            Portal(chambers,"SCOPE","SCOPE AUDITOR","Inspect promoted statements for explicit scope text.",delegate{OpenCollection(w,"SCOPE AUDITOR",Store.Theorems.OrderBy(x=>String.IsNullOrWhiteSpace(x.Scope)?0:1).Cast<object>().ToList(),"An empty scope is visibly weaker and should be repaired before use.");});
            Portal(chambers,"PROV","THEOREM PROVENANCE","Resolve promoted candidates back to mined pattern identities.",delegate{ShowTheoremProvenance(w,ctx);});
            Portal(chambers,"NOTE","SYNTHESIS NOTEBOOK","Local interpretation notes attached to pattern/theorem/transfer identities.",delegate{OpenCollection(w,"SYNTHESIS NOTEBOOK",Store.Notes.Cast<object>().ToList(),"Notes never rewrite EXPΩ or METAΩ evidence.");});
            Portal(chambers,"+NOTE","ADD SYNTHESIS NOTE","Attach a local note to any synthesis subject id.",delegate{AddNote(w,ctx);});
            Portal(chambers,"QUERY","PATTERN QUERY","Search labels, descriptions, basis, tokens and pattern kind.",delegate{Query(w,ctx);});
            Portal(chambers,"RISK","TRANSFER-RISK SURFACE","Patterns themselves ranked by generic transfer risk.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"TRANSFER-RISK SURFACE",Snapshot.Patterns.OrderByDescending(x=>x.TransferRisk).Cast<object>().ToList(),"Generic risk is pattern-level and must be combined with target-specific probes.");});
            Portal(chambers,"ROBUST","ROBUSTNESS CANDIDATES","High-stability patterns that still retain explicit heuristic status.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"ROBUSTNESS CANDIDATES",Snapshot.Patterns.Where(x=>x.Stability>=0.70&&x.CounterexampleMissionIds.Count==0).Cast<object>().ToList(),"High stability is not proof; use transfer experiments and counterexample search.");});
            Portal(chambers,"FRAG","FRAGILE PATTERNS","Low-stability structures useful mainly as research leads.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"FRAGILE PATTERNS",Snapshot.Patterns.Where(x=>x.Stability<0.35).Cast<object>().ToList(),"Fragile patterns remain visible instead of being silently discarded.");});
            Portal(chambers,"ORPH","TRANSFER ORPHANS","Patterns with no current target mission probe.",delegate{RefreshSnapshot(ctx);HashSet<string> ids=new HashSet<string>(Snapshot.TransferProbes.Select(x=>x.PatternId),StringComparer.OrdinalIgnoreCase);OpenCollection(w,"TRANSFER ORPHANS",Snapshot.Patterns.Where(x=>!ids.Contains(x.Id)).Cast<object>().ToList(),"No probe can mean saturation, no lexical target overlap, or insufficient target missions.");});
            Portal(chambers,"SRC=1","SINGLE-SOURCE RECURRENCE","Patterns spanning missions but resting on only one retained source fingerprint.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"SINGLE-SOURCE RECURRENCE",Snapshot.Patterns.Where(x=>x.SupportMissions>1&&x.UniqueSources<=1).Cast<object>().ToList(),"Cross-mission repetition over one source is not independent confirmation.");});
            Portal(chambers,"REPL","INDEPENDENT-REPLICATION CANDIDATES","Broad structures with multiple missions and multiple retained sources.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"INDEPENDENT-REPLICATION CANDIDATES",Snapshot.Patterns.Where(x=>x.SupportMissions>=3&&x.UniqueSources>=3&&x.CounterexampleMissionIds.Count==0).Cast<object>().ToList(),"Still candidates: source fingerprint diversity does not establish methodological independence.");});
            Portal(chambers,"NEG","NEGATIVE EVIDENCE SURFACE","Counterexamples and contradiction-heavy patterns brought forward instead of optimized away.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"NEGATIVE EVIDENCE SURFACE",Snapshot.Patterns.Where(x=>x.ContradictionLoad>0||x.CounterexampleMissionIds.Count>0).OrderByDescending(x=>x.ContradictionLoad).Cast<object>().ToList(),"SYNTHΩ is designed to retain disconfirming structure.");});
            Portal(chambers,"CIV","CIVILIZATION PRECONDITION INDEX","Aggregate which specialist civilizations recur as supporting contexts.",delegate{ShowCivilizationIndex(w,ctx);});
            Portal(chambers,"MAP","PATTERN→MISSION MATRIX","Flatten support relations for direct inspection.",delegate{ShowPatternMission(w,ctx);});
            Portal(chambers,"MAP","PATTERN→SOURCE MATRIX","Flatten exact retained source-fingerprint support relations.",delegate{ShowPatternSource(w,ctx);});
            Portal(chambers,"MAP","PATTERN→COUNTEREXAMPLE MATRIX","Flatten disconfirming mission associations.",delegate{ShowPatternCounterexamples(w,ctx);});
            Portal(chambers,"BASE","SYNTHESIS BASELINES","Immutable local records of synthesis-universe identity and dimensions.",delegate{OpenCollection(w,"SYNTHESIS BASELINES",Store.Baselines.Cast<object>().ToList(),"Baselines record a moment; they do not freeze upstream missions.");});
            Portal(chambers,"+BASE","CREATE SYNTHESIS BASELINE","Capture current snapshot fingerprint and dimensions.",delegate{CreateBaseline(w,ctx);});
            Portal(chambers,"DRIFT","PATTERN DRIFT RADAR","Compare the current synthesis universe with a retained baseline.",delegate{Drift(w,ctx);});
            Portal(chambers,"VAL","STRUCTURAL VALIDATOR","Check identifiers, ranges, transfer references and heuristic-authority invariants.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"SYNTHΩ STRUCTURAL VALIDATION",CivilizationalSynthesisKernel.Validate(Snapshot).Cast<object>().ToList(),"Structural validation cannot certify external truth.");});
            Portal(chambers,"SEAL","SYNTHESIS SEAL","Bind the current structurally validated synthesis identity to a local integrity record.",delegate{Seal(w,ctx);});
            Portal(chambers,"SEALS","SEAL VAULT","Inspect retained SYNTHΩ integrity records.",delegate{OpenCollection(w,"SYNTHESIS SEALS",Store.Seals.Cast<object>().ToList(),"A seal is not a theorem certificate or external signature.");});
            Portal(chambers,"LEDGER","SYNTHΩ LEDGER","Inspect the local previous-hash mutation chain.",delegate{ShowLedger(w,ctx);});
            Portal(chambers,"EXPORT","SYNTHESIS CAPSULE EXPORT","Write snapshot, local review state and a Markdown summary to YOMI-owned storage.",delegate{Export(w,ctx);});
            Portal(chambers,"AUTO","SYNTHESIS AUTOPSY","One read-only scale/integrity/fragility/transfer summary.",delegate{Autopsy(w,ctx);});
            Portal(chambers,"METAΩ","KNOWLEDGE CONSTELLATION","Drop one level down into the cross-mission graph this reactor synthesizes.",delegate{KnowledgeConstellationMetastructure.Open(w,ctx);});
            Portal(chambers,"EXPΩ","EXPEDITION COMMAND","Return to individual mission worldlines and run explicit pattern tests.",delegate{GrandUnifiedExpeditionCommand.Open(w,ctx);});
            Portal(chambers,"DOCΩ","LIVING DOCUMENT FACTORY","Publish scoped synthesis dossiers with evidence lineage.",delegate{LivingDocumentIntelligenceFactory.Open(w,ctx);});
            Portal(chambers,"DATAΩ","DATA FOUNDRY","Materialize structured pattern/support/counterexample tables.",delegate{DataFoundry.Open(w,ctx);});
            Portal(chambers,"GENOMEΩ","SOFTWARE GENOME","Test whether recurrent structures map onto codebase-organism evidence.",delegate{SoftwareGenomeObservatory.Open(w,ctx);});
            Portal(chambers,"WORLD","UNIVERSAL WORLD KERNEL","Cross into stable object passports and identity.",delegate{WorldKernel.Open(w,ctx);});
            Portal(chambers,"CIVIL","CIVILIZATION LAYER","Cross into institutions, commons and civil memory.",delegate{CivilizationLayer.Open(w,ctx);});
            Portal(chambers,"LOGIC","EPISTEMIC LOGIC","Formalize promoted candidates as explicit propositions and assumptions.",delegate{EpistemicLogicFoundry.Open(w,ctx);});
            Portal(chambers,"VERIFY","AXIOMATIC VERIFICATION","Test finite formal structures where a candidate can actually be proven or refuted.",delegate{AxiomaticVerificationReactor.Open(w,ctx);});
            Portal(chambers,"STRAT","COUNTERFACTUAL STRATEGY","Stress reusable decision patterns across counterfactual worlds.",delegate{CounterfactualStrategySuperstructure.Open(w,ctx);});
            Portal(chambers,"SCI","SCIENTIFIC DISCOVERY","Turn synthesis candidates into experiments and falsification plans.",delegate{ScientificDiscoveryHyperstructure.Open(w,ctx);});
            Portal(chambers,"SYS","SYSTEMS ENGINEERING","Translate reusable structures into requirements/architecture patterns.",delegate{DysonSystemsEngineeringMegastructure.Open(w,ctx);});
            Portal(chambers,"TWIN","CYBERNETIC TWINS","Test transfer against dynamic estimation/control models.",delegate{CyberneticDigitalTwinMetastructure.Open(w,ctx);});
            Portal(chambers,"COMPLEX","COMPLEX SYSTEMS","Test motifs against emergence and ensemble behavior.",delegate{ComplexSystemsLaboratory.Open(w,ctx);});
            Portal(chambers,"ORΩ","OPERATIONS RESEARCH","Turn candidate patterns into bounded optimization hypotheses.",delegate{OperationsResearchEmpire.Open(w,ctx);});
            Portal(chambers,"ECONΩ","ECONOMIC CIVILIZATION","Test pattern scope inside stock-flow and market worlds.",delegate{EconomicCivilization.Open(w,ctx);});
            Portal(chambers,"GEOΩ","SPATIAL CARTOGRAPHY","Test whether candidate structure survives geography and topology.",delegate{SpatialWorldCartography.Open(w,ctx);});
            Portal(chambers,"DISTΩ","DISTRIBUTED SYSTEMS","Stress recurring coordination patterns under partitions and faults.",delegate{DistributedSystemsPlanetarium.Open(w,ctx);});
            Portal(chambers,"SECΩ","ADVERSARIAL SECURITY","Stress pattern transfer against defensive-assurance counterexamples.",delegate{AdversarialSecurityFortress.Open(w,ctx);});
            Portal(chambers,"ΔT","TEMPORAL OBSERVATORY","Inspect whether patterns survive epoch and drift.",delegate{TemporalObservatory.Open(w,ctx);});
            Portal(chambers,"GRAPH","CAUSAL GRAPH LAB","Separate recurrent association from causal structure.",delegate{CausalGraphLab.Open(w,ctx);});
            Portal(chambers,"R&D","RESEARCH WORKBENCH","Turn weak or fragile patterns into explicit research leads.",delegate{ResearchWorkbench.Open(w,ctx);});
            Portal(chambers,"WORK","PRODUCTIVITY FABRIC","Convert synthesis debt and transfer tests into resumable work.",delegate{ProductivityFabric.Open(w,ctx);});
            Portal(chambers,"HADAL","HADAL SYSTEMS","Descend through pattern ancestry, counterexamples and null space.",delegate{AbyssalKnowledgeEngine.Open(w,ctx);});
            Portal(chambers,"ATLAS","DEEP SYSTEMS ATLAS","Return to the entire civilization map.",delegate{DeepSystems.OpenAtlasFromContext(w);});
            w.Content=root;w.Show();
        }

        private static string StatePath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-civilizational-synthesis.json");}
        private static string LedgerPath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-civilizational-synthesis-ledger.jsonl");}
        private static string ExpeditionPath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-grand-unified-expedition.json");}
        private static void Load(DeepSystemsContext ctx){Store=new SynthesisStore();string p=StatePath(ctx);if(File.Exists(p))try{SynthesisStore x=ctx.Json.Deserialize<SynthesisStore>(File.ReadAllText(p,Encoding.UTF8));if(x!=null)Store=x;}catch{try{File.Copy(p,p+".corrupt-"+DateTime.UtcNow.ToString("yyyyMMddHHmmss",CultureInfo.InvariantCulture),true);}catch{}}if(Store.Theorems==null)Store.Theorems=new List<SynthesisTheoremCandidate>();if(Store.Notes==null)Store.Notes=new List<SynthesisNote>();if(Store.Trials==null)Store.Trials=new List<SynthesisTransferTrial>();if(Store.Baselines==null)Store.Baselines=new List<SynthesisBaseline>();if(Store.Seals==null)Store.Seals=new List<SynthesisSeal>();}
        private static void Save(DeepSystemsContext ctx){string p=StatePath(ctx),next=p+".next",prev=p+".previous";File.WriteAllText(next,ctx.Json.Serialize(Store),new UTF8Encoding(false));if(File.Exists(p))File.Copy(p,prev,true);if(File.Exists(p))File.Delete(p);File.Move(next,p);}
        private static void RefreshSnapshot(DeepSystemsContext ctx){string p=ExpeditionPath(ctx);ExpeditionCommandStore ex=new ExpeditionCommandStore();string raw="";if(File.Exists(p)){try{raw=File.ReadAllText(p,Encoding.UTF8);ExpeditionCommandStore z=ctx.Json.Deserialize<ExpeditionCommandStore>(raw);if(z!=null)ex=z;}catch{raw="CORRUPT";}}string fp=CivilizationalSynthesisKernel.HashText(raw);if(Snapshot==null||!Eq(fp,LoadedExpeditionFingerprint)){ConstellationSnapshot meta=KnowledgeConstellationKernel.Build(ex.Missions,fp);Snapshot=CivilizationalSynthesisKernel.Build(meta,ex.Missions,fp);LoadedExpeditionFingerprint=fp;}}
        private static void AppendLedger(DeepSystemsContext ctx,string kind,string subject){string p=LedgerPath(ctx);string prev="GENESIS";if(File.Exists(p)){string[] lines=File.ReadAllLines(p,Encoding.UTF8);if(lines.Length>0){string last=lines[lines.Length-1];int i=last.IndexOf("\"hash\":\"");if(i>=0){int a=i+8,b=last.IndexOf('"',a);if(b>a)prev=last.Substring(a,b-a);}}}string ts=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture);string hash=CivilizationalSynthesisKernel.HashText(prev+"|"+ts+"|"+kind+"|"+(subject??""));string json="{\"utc\":\""+ts+"\",\"kind\":\""+Esc(kind)+"\",\"subject\":\""+Esc(subject)+"\",\"previous\":\""+prev+"\",\"hash\":\""+hash+"\"}";File.AppendAllText(p,json+Environment.NewLine,new UTF8Encoding(false));}
        private static string Esc(string s){return (s??"").Replace("\\","\\\\").Replace("\"","\\\"").Replace("\r"," ").Replace("\n"," ");}
        private static void Kinds(Window w,DeepSystemsContext ctx,string title,string kind){RefreshSnapshot(ctx);OpenCollection(w,title,Snapshot.Patterns.Where(x=>Eq(x.Kind,kind)).Cast<object>().ToList(),"Automatically mined; heuristic status retained.");}
        private static void TransferBand(Window w,DeepSystemsContext ctx,string title,double lo,double hi){RefreshSnapshot(ctx);OpenCollection(w,title,Snapshot.TransferProbes.Where(x=>x.Risk>=lo&&x.Risk<hi).Cast<object>().ToList(),"Target-specific risk combines pattern fragility, missing preconditions and context overlap.");}
        private static void ShowFamilies(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);OpenCollection(w,"PATTERN FAMILIES",Snapshot.Patterns.GroupBy(x=>x.Kind??"UNKNOWN",StringComparer.OrdinalIgnoreCase).OrderByDescending(g=>g.Count()).Select(g=>(object)(g.Count().ToString("0000",CultureInfo.InvariantCulture)+"   ·   "+g.Key+"   ·   mean stability "+g.Average(x=>x.Stability).ToString("0.000",CultureInfo.InvariantCulture))).ToList(),"Family counts are descriptive.");}
        private static void ShowTokens(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);OpenCollection(w,"CONCEPT MOTIF INDEX",Snapshot.Patterns.SelectMany(p=>p.Tokens.Select(t=>new{T=t,P=p.Id})).GroupBy(x=>x.T,StringComparer.OrdinalIgnoreCase).OrderByDescending(g=>g.Count()).Select(g=>(object)(g.Count().ToString("0000",CultureInfo.InvariantCulture)+" patterns   ·   "+g.Key)).ToList(),"Token index is lexical structure only.");}
        private static void ShowPreconditions(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);OpenCollection(w,"PRECONDITION MATRIX",Snapshot.Patterns.SelectMany(p=>p.Preconditions.Select(c=>(object)(c+"   ·   "+p.Kind+"   ·   "+p.Label+"   ·   "+p.Id))).ToList(),"Preconditions are supporting civilization contexts, not proven necessary conditions.");}
        private static void ShowCivilizationIndex(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);OpenCollection(w,"CIVILIZATION PRECONDITION INDEX",Snapshot.Patterns.SelectMany(p=>p.Preconditions).GroupBy(x=>x,StringComparer.OrdinalIgnoreCase).OrderByDescending(g=>g.Count()).Select(g=>(object)(g.Count().ToString("0000",CultureInfo.InvariantCulture)+" patterns   ·   "+g.Key)).ToList(),"Frequency says where support was observed, not where the pattern must hold.");}
        private static void ShowPatternMission(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);OpenCollection(w,"PATTERN→MISSION MATRIX",Snapshot.Patterns.SelectMany(p=>p.MissionIds.Select(m=>(object)(p.Id+"   →   "+m+"   ·   "+p.Kind+"   ·   "+p.Label))).ToList(),"Recorded support relation from mined findings.");}
        private static void ShowPatternSource(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);OpenCollection(w,"PATTERN→SOURCE MATRIX",Snapshot.Patterns.SelectMany(p=>p.SourceFingerprints.Select(s=>(object)(p.Id+"   →   "+s+"   ·   "+p.Label))).ToList(),"Exact retained source fingerprints only.");}
        private static void ShowPatternCounterexamples(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);OpenCollection(w,"PATTERN→COUNTEREXAMPLE MATRIX",Snapshot.Patterns.SelectMany(p=>p.CounterexampleMissionIds.Select(m=>(object)(p.Id+"   ×   "+m+"   ·   "+p.Label))).ToList(),"Counterexample association comes from explicit unresolved contradiction participation.");}
        private static void Promote(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);SynthesisPattern p=Choose(w,"SELECT PATTERN",Snapshot.Patterns);if(p==null)return;string statement=Prompt(w,"THEOREM CANDIDATE","Write the candidate statement. It remains explicitly unproven.",p.Description);if(String.IsNullOrWhiteSpace(statement))return;string scope=Prompt(w,"SCOPE","State where this candidate is intended to apply and where it is not.",String.Join(", ",p.Preconditions));SynthesisTheoremCandidate t=new SynthesisTheoremCandidate{Id="THM-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),PatternId=p.Id,Statement=statement.Trim(),Scope=(scope??"").Trim(),Status="CANDIDATE",CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};t.Fingerprint=CivilizationalSynthesisKernel.HashText(t.Id+"|"+t.PatternId+"|"+t.Statement+"|"+t.Scope+"|"+p.Fingerprint);Store.Theorems.Insert(0,t);Save(ctx);AppendLedger(ctx,"THEOREM_CANDIDATE",t.Id);}
        private static void ShowTheoremProvenance(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);Dictionary<string,SynthesisPattern> p=Snapshot.Patterns.ToDictionary(x=>x.Id,StringComparer.OrdinalIgnoreCase);List<object> rows=new List<object>();foreach(SynthesisTheoremCandidate t in Store.Theorems){SynthesisPattern x;rows.Add((object)(t.Id+"   →   "+t.PatternId+"   ·   "+(p.TryGetValue(t.PatternId,out x)?("missions "+x.SupportMissions+" sources "+x.UniqueSources+" counterexamples "+x.CounterexampleMissionIds.Count):"PATTERN NO LONGER IN CURRENT SNAPSHOT")));}OpenCollection(w,"THEOREM PROVENANCE",rows,"A promoted candidate never sheds its originating pattern identity.");}
        private static void AddNote(Window w,DeepSystemsContext ctx){string subject=Prompt(w,"NOTE SUBJECT","Pattern/theorem/transfer id, or SYNTHΩ for a global note.","SYNTHΩ");if(String.IsNullOrWhiteSpace(subject))return;string text=Prompt(w,"NOTE","Interpretation, caveat, objection, transfer idea or follow-up.","");if(String.IsNullOrWhiteSpace(text))return;SynthesisNote n=new SynthesisNote{Id="NOTE-"+Guid.NewGuid().ToString("N").Substring(0,12).ToUpperInvariant(),SubjectId=subject.Trim(),Text=text.Trim(),CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};Store.Notes.Insert(0,n);Save(ctx);AppendLedger(ctx,"NOTE",n.Id);}
        private static void LaunchTransfer(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);SynthesisPattern p=Choose(w,"SELECT PATTERN TO TEST",Snapshot.Patterns);if(p==null)return;string q="Under what explicit conditions does the candidate pattern '"+p.Label+"' transfer, fail, or require revision in a new context?";SynthesisTransferTrial t=new SynthesisTransferTrial{Id="TRIAL-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),PatternId=p.Id,Question=q,Status="STARTED",CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};Store.Trials.Insert(0,t);Save(ctx);AppendLedger(ctx,"TRANSFER_TRIAL",t.Id);GrandUnifiedExpeditionCommand.OpenFromSynthesisPattern(w,ctx,q,"SYNTHΩ:"+p.Id,p.Fingerprint);}
        private static void Query(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);string q=Prompt(w,"PATTERN QUERY","Search kind, label, description, basis or tokens.","");if(String.IsNullOrWhiteSpace(q))return;OpenCollection(w,"QUERY · "+q,Snapshot.Patterns.Where(p=>Contains(p.Kind,q)||Contains(p.Label,q)||Contains(p.Description,q)||Contains(p.Basis,q)||p.Tokens.Any(t=>Contains(t,q))).Cast<object>().ToList(),"Lexical local query over the current synthesis snapshot.");}
        private static void CreateBaseline(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);SynthesisBaseline b=new SynthesisBaseline{Id="BASE-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),SnapshotFingerprint=Snapshot.Fingerprint,Patterns=Snapshot.Patterns.Count,Transfers=Snapshot.TransferProbes.Count,Missions=Snapshot.Missions,CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};Store.Baselines.Insert(0,b);Save(ctx);AppendLedger(ctx,"BASELINE",b.Id);}
        private static void Drift(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);SynthesisBaseline b=Choose(w,"SELECT BASELINE",Store.Baselines);if(b==null)return;StringBuilder s=new StringBuilder();s.AppendLine("SYNTHΩ PATTERN DRIFT");s.AppendLine(new string('=',70));s.AppendLine("baseline fingerprint: "+b.SnapshotFingerprint);s.AppendLine("current fingerprint:  "+Snapshot.Fingerprint);s.AppendLine("identity changed:     "+(!Eq(b.SnapshotFingerprint,Snapshot.Fingerprint)));s.AppendLine("patterns:             "+b.Patterns+" → "+Snapshot.Patterns.Count+"   Δ "+(Snapshot.Patterns.Count-b.Patterns));s.AppendLine("transfers:            "+b.Transfers+" → "+Snapshot.TransferProbes.Count+"   Δ "+(Snapshot.TransferProbes.Count-b.Transfers));s.AppendLine("missions:             "+b.Missions+" → "+Snapshot.Missions+"   Δ "+(Snapshot.Missions-b.Missions));s.AppendLine();s.AppendLine("Drift records structural change. It does not infer why meaning changed.");TextView(w,"PATTERN DRIFT RADAR",s.ToString());}
        private static void Seal(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);List<SynthesisValidationFinding> v=CivilizationalSynthesisKernel.Validate(Snapshot);if(v.Any(x=>Eq(x.Severity,"ERROR"))){OpenCollection(w,"SEAL REFUSED",v.Cast<object>().ToList(),"Structural errors must be repaired before sealing.");return;}SynthesisSeal s=new SynthesisSeal{Id="SEAL-"+Guid.NewGuid().ToString("N").Substring(0,16).ToUpperInvariant(),SnapshotFingerprint=Snapshot.Fingerprint,Patterns=Snapshot.Patterns.Count,TheoremCandidates=Store.Theorems.Count,CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};s.CertificateHash=CivilizationalSynthesisKernel.HashText(s.Id+"|"+s.SnapshotFingerprint+"|"+s.Patterns+"|"+s.TheoremCandidates+"|"+s.CreatedUtc);Store.Seals.Insert(0,s);Save(ctx);AppendLedger(ctx,"SEAL",s.Id);}
        private static void ShowLedger(Window w,DeepSystemsContext ctx){string p=LedgerPath(ctx);List<object> rows=File.Exists(p)?File.ReadAllLines(p,Encoding.UTF8).Reverse().Cast<object>().ToList():new List<object>();OpenCollection(w,"SYNTHΩ LEDGER",rows,"Local activity chain. EXPΩ and METAΩ retain their own authority ledgers.");}
        private static void Export(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);string dir=Path.Combine(ctx.DataRoot,"exports","civilizational-synthesis");Directory.CreateDirectory(dir);string stamp=DateTime.UtcNow.ToString("yyyyMMdd-HHmmss",CultureInfo.InvariantCulture);string root=Path.Combine(dir,"synth-omega-"+stamp);File.WriteAllText(root+".snapshot.json",ctx.Json.Serialize(Snapshot),new UTF8Encoding(false));File.WriteAllText(root+".review.json",ctx.Json.Serialize(Store),new UTF8Encoding(false));StringBuilder md=new StringBuilder();md.AppendLine("# SYNTHΩ Civilizational Synthesis");md.AppendLine();md.AppendLine("Snapshot fingerprint: `"+Snapshot.Fingerprint+"`");md.AppendLine();md.AppendLine("Patterns: "+Snapshot.Patterns.Count+"  ");md.AppendLine("Transfer probes: "+Snapshot.TransferProbes.Count+"  ");md.AppendLine("Theorem candidates: "+Store.Theorems.Count+"  ");md.AppendLine();md.AppendLine("## Highest-stability candidates");foreach(SynthesisPattern p in Snapshot.Patterns.Take(30))md.AppendLine("- "+p.ToString());File.WriteAllText(root+".md",md.ToString(),new UTF8Encoding(false));AppendLedger(ctx,"EXPORT",root);TextView(w,"EXPORT COMPLETE",root+Environment.NewLine+Snapshot.Fingerprint);}
        private static void Autopsy(Window w,DeepSystemsContext ctx){RefreshSnapshot(ctx);StringBuilder b=new StringBuilder();b.AppendLine("SYNTHΩ CIVILIZATIONAL SYNTHESIS AUTOPSY");b.AppendLine(new string('=',76));b.AppendLine("missions:                 "+Snapshot.Missions);b.AppendLine("findings:                 "+Snapshot.Findings);b.AppendLine("unique sources:           "+Snapshot.UniqueSources);b.AppendLine("open contradictions:      "+Snapshot.OpenContradictions);b.AppendLine("patterns:                 "+Snapshot.Patterns.Count);b.AppendLine("invariant candidates:     "+Snapshot.Patterns.Count(x=>Eq(x.Kind,"INVARIANT_CANDIDATE")));b.AppendLine("failure signatures:       "+Snapshot.Patterns.Count(x=>Eq(x.Kind,"FAILURE_SIGNATURE")));b.AppendLine("anti-pattern candidates:  "+Snapshot.Patterns.Count(x=>Eq(x.Kind,"ANTI_PATTERN_CANDIDATE")));b.AppendLine("patterns w/counterexample:"+Snapshot.Patterns.Count(x=>x.CounterexampleMissionIds.Count>0));b.AppendLine("transfer probes:          "+Snapshot.TransferProbes.Count);b.AppendLine("theorem candidates:       "+Store.Theorems.Count);b.AppendLine("transfer trials:          "+Store.Trials.Count);b.AppendLine("validation errors:        "+CivilizationalSynthesisKernel.Validate(Snapshot).Count(x=>Eq(x.Severity,"ERROR")));b.AppendLine("snapshot fp:              "+Snapshot.Fingerprint);b.AppendLine();b.AppendLine("Authority boundary: automatic recurrence is heuristic; theorem candidates are human-promoted hypotheses; transfer remains untested until an expedition gathers evidence.");TextView(w,"SYNTHESIS AUTOPSY",b.ToString());}
        private static T Choose<T>(Window owner,string title,IList<T> items) where T:class{if(items==null||items.Count==0)return null;Window w=W(owner,"YOMI · "+title,1120,760);DockPanel root=Shell(title,"Double-click to select.");ListBox list=List();list.ItemsSource=items;T selected=null;list.MouseDoubleClick+=delegate{selected=list.SelectedItem as T;w.DialogResult=selected!=null;w.Close();};root.Children.Add(list);w.Content=root;bool? r=w.ShowDialog();return r==true?selected:null;}
        private static Window W(Window owner,string title,double width,double height){return new Window{Title=title,Width=width,Height=height,Background=Bg,Foreground=Text,WindowStartupLocation=owner==null?WindowStartupLocation.CenterScreen:WindowStartupLocation.CenterOwner,Owner=owner};}
        private static DockPanel Shell(string title,string subtitle){DockPanel root=new DockPanel{Background=Bg};StackPanel head=new StackPanel{Margin=new Thickness(20,18,20,10)};head.Children.Add(new TextBlock{Text=title,Foreground=Text,FontSize=25,FontWeight=FontWeights.Bold});head.Children.Add(new TextBlock{Text=subtitle??"",Foreground=Muted,FontSize=13,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,5,0,0)});DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);return root;}
        private static void Portal(WrapPanel panel,string badge,string title,string detail,RoutedEventHandler click){Button b=new Button{Width=285,MinHeight=118,Margin=new Thickness(7),Padding=new Thickness(14),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),HorizontalContentAlignment=HorizontalAlignment.Stretch};StackPanel p=new StackPanel();p.Children.Add(new TextBlock{Text=badge+"   "+title,Foreground=Accent,FontWeight=FontWeights.Bold,FontSize=13,TextWrapping=TextWrapping.Wrap});p.Children.Add(new TextBlock{Text=detail,Foreground=Muted,FontSize=12,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,7,0,0)});b.Content=p;b.Click+=click;panel.Children.Add(b);}
        private static ListBox List(){return new ListBox{Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),FontFamily=new FontFamily("Consolas"),FontSize=12};}
        private static void OpenCollection(Window owner,string title,IList<object> items,string note){Window w=W(owner,"YOMI · "+title,1380,850);DockPanel root=Shell(title,note+"   ·   "+(items==null?0:items.Count)+" rows");ListBox list=List();list.ItemsSource=items??new List<object>();root.Children.Add(list);w.Content=root;w.Show();}
        private static void TextView(Window owner,string title,string text){Window w=W(owner,"YOMI · "+title,1380,880);DockPanel root=Shell(title,"Read-only representation.");TextBox box=new TextBox{Text=text??"",Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,FontFamily=new FontFamily("Consolas"),FontSize=13,IsReadOnly=true,AcceptsReturn=true,AcceptsTab=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto};root.Children.Add(box);w.Content=root;w.Show();}
        private static string Prompt(Window owner,string title,string label,string initial){Window w=W(owner,"YOMI · "+title,820,340);DockPanel root=Shell(title,label);TextBox box=new TextBox{Text=initial??"",Margin=new Thickness(20,6,20,10),Padding=new Thickness(8),Background=Surface,Foreground=Text,BorderBrush=Border,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};DockPanel.SetDock(box,Dock.Top);root.Children.Add(box);StackPanel buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(20)};Button ok=new Button{Content="COMMIT",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Green,BorderBrush=Border};Button cancel=new Button{Content="CANCEL",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Muted,BorderBrush=Border};string value=null;ok.Click+=delegate{value=box.Text;w.DialogResult=true;w.Close();};cancel.Click+=delegate{w.DialogResult=false;w.Close();};buttons.Children.Add(cancel);buttons.Children.Add(ok);root.Children.Add(buttons);w.Content=root;bool? r=w.ShowDialog();return r==true?value:null;}
        private static bool Eq(string a,string b){return String.Equals(a,b,StringComparison.OrdinalIgnoreCase);}private static bool Contains(string a,string b){return !String.IsNullOrWhiteSpace(a)&&!String.IsNullOrWhiteSpace(b)&&a.IndexOf(b,StringComparison.OrdinalIgnoreCase)>=0;}private static Brush B(string hex){return (Brush)new BrushConverter().ConvertFromString(hex);}
    }
}
