using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class ConstellationSavedLens
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Query { get; set; }
        public string KindFilter { get; set; }
        public string MissionFilter { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (Name??Id)+"   ·   query "+(Query??"∅")+"   ·   kind "+(KindFilter??"ANY")+"   ·   mission "+(MissionFilter??"ANY");}
    }
    internal sealed class ConstellationBaseline
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string SnapshotFingerprint { get; set; }
        public string ExpeditionStoreFingerprint { get; set; }
        public int Missions { get; set; }
        public int Nodes { get; set; }
        public int Edges { get; set; }
        public int Frontiers { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (Name??Id)+"   ·   missions "+Missions+"   ·   nodes "+Nodes+"   ·   edges "+Edges+"   ·   frontiers "+Frontiers+"   ·   "+KnowledgeConstellationKernel.Short(SnapshotFingerprint);}
    }
    internal sealed class ConstellationNote
    {
        public string Id { get; set; }
        public string SubjectId { get; set; }
        public string Text { get; set; }
        public string CreatedUtc { get; set; }
        public override string ToString(){return (SubjectId??"CONSTELLATION")+"   ·   "+(Text??"");}
    }
    internal sealed class ConstellationSeal
    {
        public string Id { get; set; }
        public string SnapshotFingerprint { get; set; }
        public string StoreFingerprint { get; set; }
        public int Missions { get; set; }
        public int Nodes { get; set; }
        public int Edges { get; set; }
        public string CreatedUtc { get; set; }
        public string CertificateHash { get; set; }
        public override string ToString(){return "METAΩ SEAL   ·   missions "+Missions+"   ·   nodes "+Nodes+"   ·   edges "+Edges+"   ·   fp "+KnowledgeConstellationKernel.Short(SnapshotFingerprint);}
    }
    internal sealed class ConstellationStore
    {
        public int Schema { get; set; }
        public long Revision { get; set; }
        public string UpdatedUtc { get; set; }
        public List<ConstellationSavedLens> Lenses { get; set; }
        public List<ConstellationBaseline> Baselines { get; set; }
        public List<ConstellationNote> Notes { get; set; }
        public List<ConstellationSeal> Seals { get; set; }
        public ConstellationStore(){Schema=1;Lenses=new List<ConstellationSavedLens>();Baselines=new List<ConstellationBaseline>();Notes=new List<ConstellationNote>();Seals=new List<ConstellationSeal>();}
    }
    internal sealed class ConstellationLedgerRecord
    {
        public int Schema { get; set; }
        public long Sequence { get; set; }
        public string Utc { get; set; }
        public string Event { get; set; }
        public string Detail { get; set; }
        public string SnapshotFingerprint { get; set; }
        public string PrevHash { get; set; }
        public string EntryHash { get; set; }
        public override string ToString(){return Sequence.ToString("000000",CultureInfo.InvariantCulture)+"   ·   "+(Utc??"")+"   ·   "+(Event??"EVENT")+"   ·   "+KnowledgeConstellationKernel.Short(EntryHash);}
    }

    internal static class KnowledgeConstellationMetastructure
    {
        private static readonly object Gate=new object();
        private static readonly JavaScriptSerializer Json=new JavaScriptSerializer{MaxJsonLength=Int32.MaxValue,RecursionLimit=256};
        private static readonly Brush Bg=B("#0B0F13"),Surface=B("#141A20"),Raised=B("#1D2630"),Border=B("#33404C"),Text=B("#F2F5F7"),Muted=B("#9DAAB5"),Accent=B("#8AF0FF"),Green=B("#8CE89A"),Amber=B("#FFD06A"),Danger=B("#FF8585");
        private static ConstellationStore Store;private static string LoadedRoot;private static ConstellationSnapshot Snapshot;private static string LoadedExpeditionFingerprint;
        private const int MaxLedgerRead=32768;

        public static void Open(Window owner,DeepSystemsContext ctx)
        {
            if(ctx==null)return;LoadStore(ctx);RefreshSnapshot(ctx);Window w=W(owner,"YOMI · KNOWLEDGE CONSTELLATION METASTRUCTURE",1560,950);DockPanel root=Shell("KNOWLEDGE CONSTELLATION METASTRUCTURE","METAΩ treats the entire retained expedition universe as one provenance graph. Exact recorded relationships remain exact. Similarity, convergence and frontier heat remain explicitly heuristic until a human investigation records stronger evidence.");
            TextBlock status=new TextBlock{Text="METAΩ   ·   DEV13.37.28   ·   "+Snapshot.Missions.Count+" missions   ·   "+Snapshot.Nodes.Count+" nodes   ·   "+Snapshot.Edges.Count+" edges   ·   "+Snapshot.Frontiers.Count+" open frontiers   ·   Ctrl+Alt+C",Foreground=Accent,FontWeight=FontWeights.Bold,Margin=new Thickness(20,0,20,14)};DockPanel.SetDock(status,Dock.Top);root.Children.Add(status);
            ScrollViewer scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};WrapPanel chambers=new WrapPanel{Margin=new Thickness(12)};
            Portal(chambers,"SYNTHΩ","CIVILIZATIONAL SYNTHESIS REACTOR","Rise above graph connectivity into recurring motifs, counterexamples, transfer probes and scoped theorem candidates.",delegate{CivilizationalSynthesisReactor.Open(w,ctx);});
            Portal(chambers,"VOIDΩ","UNKNOWN UNKNOWNS OBSERVATORY","Inspect where the retained mission universe is structurally sparse, monocultural, unresolved or under-challenged.",delegate{UnknownUnknownsObservatory.Open(w,ctx);});
            Portal(chambers,"UNIV","MISSION UNIVERSE","Every retained EXPΩ mission summarized as a graph-bearing object rather than an isolated file.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"MISSION UNIVERSE",Snapshot.Missions.Cast<object>().ToList(),"Mission digests retain exact EXPΩ identities and fingerprints.");});
            Portal(chambers,"GRAPH","CONSTELLATION HYPERGRAPH","All mission, branch, step, finding, question, contradiction, decision, checkpoint and source nodes.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CONSTELLATION NODES",Snapshot.Nodes.Cast<object>().ToList(),"Addressable node species in the current cross-mission graph.");});
            Portal(chambers,"EDGE","EDGE SEMANTICS","Recorded and heuristic edges shown together but never conflated.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CONSTELLATION EDGES",Snapshot.Edges.Cast<object>().ToList(),"Arrow = recorded structure; approximation = heuristic affinity.");});
            Portal(chambers,"OBS","OBSERVED RELATIONSHIPS","Only exact branch ancestry, step lineage, evidence references, contradictions, checkpoints and shared source fingerprints.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"OBSERVED EDGES",Snapshot.Edges.Where(x=>!x.Heuristic).Cast<object>().ToList(),"These edges arise from retained explicit structure or exact fingerprint equality.");});
            Portal(chambers,"≈","HEURISTIC RELATIONSHIPS","Similarity and affinity candidates kept visibly weaker than observed links.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"HEURISTIC EDGES",Snapshot.Edges.Where(x=>x.Heuristic).Cast<object>().ToList(),"Candidate bridges are navigation hints, not facts.");});
            Portal(chambers,"FRONT","KNOWLEDGE FRONTIER ATLAS","Open questions ranked by contradiction pressure, cross-mission relevance and sparse local support.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"FRONTIER ATLAS",Snapshot.Frontiers.Cast<object>().ToList(),"Frontier pressure is a deterministic prioritization heuristic.");});
            Portal(chambers,"LAUNCH","LAUNCH EXPEDITION FROM FRONTIER","Select an unresolved frontier and turn it into a new EXPΩ mission without losing its origin.",delegate{LaunchFrontier(w,ctx);});
            Portal(chambers,"CONV","CONVERGENCE TELESCOPE","Candidate themes appearing in findings from multiple independent missions.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CONVERGENCE TELESCOPE",Snapshot.Convergences.Cast<object>().ToList(),"Token convergence is heuristic; inspect sources before treating it as substantive agreement.");});
            Portal(chambers,"SRC","SOURCE REUSE CONSTELLATIONS","Exact source fingerprints reused across multiple missions and crossings.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"SOURCE REUSE",Snapshot.SourceReuse.Cast<object>().ToList(),"These clusters use exact retained fingerprint equality.");});
            Portal(chambers,"AFF","MISSION AFFINITY MATRIX","Cross-mission affinity from exact source overlap plus bounded lexical overlap.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"MISSION AFFINITY",Snapshot.Affinities.Cast<object>().ToList(),"Rows state whether the basis contains exact source overlap or heuristic lexical overlap only.");});
            Portal(chambers,"DEBT","GLOBAL RESEARCH DEBT","All unresolved questions across all missions, ranked as a civilization-wide debt inventory.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"GLOBAL RESEARCH DEBT",Snapshot.Frontiers.Cast<object>().ToList(),"Open questions remain owned by their originating missions.");});
            Portal(chambers,"CONTRA","CONTRADICTION SKY","All explicit contradiction objects projected into one cross-mission field.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CONTRADICTION SKY",Snapshot.Nodes.Where(x=>Eq(x.Kind,"CONTRADICTION")).Cast<object>().ToList(),"Only recorded contradiction objects appear here; similarity is not silently promoted to contradiction.");});
            Portal(chambers,"FIND","FINDING NEBULA","Every retained finding across the expedition universe.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"FINDING NEBULA",Snapshot.Nodes.Where(x=>Eq(x.Kind,"FINDING")).Cast<object>().ToList(),"Findings retain mission/branch/step identity.");});
            Portal(chambers,"Q","QUESTION NEBULA","Every retained question, open or resolved, across all mission branches.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"QUESTION NEBULA",Snapshot.Nodes.Where(x=>Eq(x.Kind,"QUESTION")).Cast<object>().ToList(),"Question ancestry remains explicit.");});
            Portal(chambers,"STEP","CROSSING STARFIELD","Every civilization crossing from every retained mission.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CROSSING STARFIELD",Snapshot.Nodes.Where(x=>Eq(x.Kind,"STEP")).Cast<object>().ToList(),"Each star is a concrete EXPΩ crossing step.");});
            Portal(chambers,"BR","BRANCH FOREST","Mission forks and branch lineages projected across the whole universe.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"BRANCH FOREST",Snapshot.Nodes.Where(x=>Eq(x.Kind,"BRANCH")).Cast<object>().ToList(),"Branch ancestry is recorded structure.");});
            Portal(chambers,"DEC","DECISION CONSTELLATION","Decisions from all missions with their explicit finding references.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"DECISION CONSTELLATION",Snapshot.Nodes.Where(x=>Eq(x.Kind,"DECISION")).Cast<object>().ToList(),"Decision edges preserve recorded support references only.");});
            Portal(chambers,"CP","CHECKPOINT GALAXY","Exact resume points across every retained mission.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"CHECKPOINT GALAXY",Snapshot.Nodes.Where(x=>Eq(x.Kind,"CHECKPOINT")).Cast<object>().ToList(),"Checkpoints remain mission-local durable resume anchors.");});
            Portal(chambers,"SRCN","SOURCE STARFIELD","Every unique captured source fingerprint represented as a graph node.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"SOURCE STARFIELD",Snapshot.Nodes.Where(x=>Eq(x.Kind,"SOURCE")).Cast<object>().ToList(),"Fingerprint equality is structural identity of retained bytes, not truth certification.");});
            Portal(chambers,"HOT","FRONTIER HEATMAP","Rank unresolved regions by deterministic pressure rather than by recency alone.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"FRONTIER HEATMAP",Snapshot.Frontiers.OrderByDescending(x=>x.Pressure).Cast<object>().ToList(),"Pressure combines contradiction load, related missions and sparse local support.");});
            Portal(chambers,"ORPH","ORPHAN NODE RADAR","Nodes with no graph edge reveal retained material that may be structurally isolated.",delegate{RefreshSnapshot(ctx);HashSet<string> eids=new HashSet<string>(Snapshot.Edges.SelectMany(x=>new[]{x.FromId,x.ToId}),StringComparer.OrdinalIgnoreCase);OpenCollection(w,"ORPHAN NODE RADAR",Snapshot.Nodes.Where(x=>!eids.Contains(x.Id)).Cast<object>().ToList(),"Isolation is graph structure, not evidence of irrelevance.");});
            Portal(chambers,"HUB","HUB CENTRALITY","Simple degree ranking reveals objects sitting at dense investigation junctions.",delegate{ShowDegree(w);});
            Portal(chambers,"BRIDGE","BRIDGE OBJECTS","Find nodes whose edges connect multiple mission identities.",delegate{ShowBridges(w);});
            Portal(chambers,"CIV","CIVILIZATION COVERAGE UNIVERSE","Aggregate where the expedition civilization lattice has actually been crossed.",delegate{ShowCivilizations(w,ctx);});
            Portal(chambers,"MISS","MISSION COVERAGE GAPS","Missions with the most unvisited concrete civilizations.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"MISSION COVERAGE GAPS",Snapshot.Missions.OrderBy(x=>x.Civilizations).Cast<object>().ToList(),"Coverage is breadth, not quality.");});
            Portal(chambers,"DENSE","EVIDENCE DENSITY","Compare findings and source diversity against crossing count.",delegate{ShowDensity(w);});
            Portal(chambers,"PRESS","PRESSURE INDEX","Compare open questions, contradictions and frontier pressure across missions.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"MISSION PRESSURE INDEX",Snapshot.Missions.OrderByDescending(x=>x.FrontierPressure).Cast<object>().ToList(),"Pressure is a triage heuristic, not importance truth.");});
            Portal(chambers,"QUERY","CONSTELLATION QUERY","Search node labels/details/identities across the live snapshot.",delegate{Query(w,ctx);});
            Portal(chambers,"LENS","SAVED LENS VAULT","Persist named local graph queries without freezing the underlying expedition universe.",delegate{OpenCollection(w,"SAVED LENSES",Store.Lenses.Cast<object>().ToList(),"Lenses are local query definitions, not snapshots.");});
            Portal(chambers,"NEWL","SAVE NEW LENS","Capture a named text/kind/mission filter for repeated exploration.",delegate{SaveLens(w,ctx);});
            Portal(chambers,"NOTE","CONSTELLATION NOTEBOOK","Local notes attached to graph object identities or the constellation as a whole.",delegate{OpenCollection(w,"CONSTELLATION NOTES",Store.Notes.Cast<object>().ToList(),"Notes never mutate EXPΩ evidence.");});
            Portal(chambers,"+NOTE","ADD CONSTELLATION NOTE","Record interpretation or follow-up without rewriting mission history.",delegate{AddNote(w,ctx);});
            Portal(chambers,"BASE","CONSTELLATION BASELINES","Immutable local records of graph dimensions and fingerprints at a chosen moment.",delegate{OpenCollection(w,"CONSTELLATION BASELINES",Store.Baselines.Cast<object>().ToList(),"A baseline records identity; it does not freeze upstream EXPΩ missions.");});
            Portal(chambers,"+BASE","CREATE BASELINE","Fingerprint the current universe for later structural drift comparison.",delegate{CreateBaseline(w,ctx);});
            Portal(chambers,"DRIFT","UNIVERSE DRIFT RADAR","Compare the current snapshot fingerprint and dimensions with a retained baseline.",delegate{Drift(w,ctx);});
            Portal(chambers,"VAL","STRUCTURAL VALIDATOR","Check node identities, edge endpoints and authority-boundary invariants.",delegate{RefreshSnapshot(ctx);OpenCollection(w,"METAΩ STRUCTURAL VALIDATION",KnowledgeConstellationKernel.Validate(Snapshot).Cast<object>().ToList(),"Structural validation cannot certify external facts.");});
            Portal(chambers,"SEAL","CONSTELLATION SEAL","Bind the current cross-mission graph identity to a local seal record.",delegate{Seal(w,ctx);});
            Portal(chambers,"SEALS","SEAL VAULT","Inspect retained METAΩ structural seals.",delegate{OpenCollection(w,"CONSTELLATION SEALS",Store.Seals.Cast<object>().ToList(),"Seals are local integrity records, not signatures from an external authority.");});
            Portal(chambers,"LEDGER","METAΩ LEDGER","Verify and inspect the local previous-hash activity chain.",delegate{ShowLedger(w,ctx);});
            Portal(chambers,"EXPORT","CONSTELLATION CAPSULE EXPORT","Write the current snapshot plus persistent METAΩ annotations to local YOMI-owned storage.",delegate{Export(w,ctx);});
            Portal(chambers,"AUTO","CONSTELLATION AUTOPSY","One read-only summary of graph scale, unresolved frontier, overlap and integrity.",delegate{Autopsy(w,ctx);});
            Portal(chambers,"EXPΩ","GRAND UNIFIED EXPEDITION COMMAND","Dive from the universe back into individual mission worldlines.",delegate{GrandUnifiedExpeditionCommand.Open(w,ctx);});
            Portal(chambers,"DOCΩ","LIVING DOCUMENT FACTORY","Turn selected mission evidence into provenance-native documentary synthesis.",delegate{LivingDocumentIntelligenceFactory.Open(w,ctx);});
            Portal(chambers,"DATAΩ","DATA FOUNDRY","Inspect structured evidence and lineage at dataset scale.",delegate{DataFoundry.Open(w,ctx);});
            Portal(chambers,"GENOMEΩ","SOFTWARE GENOME OBSERVATORY","Cross from the mission universe into codebase organism evidence.",delegate{SoftwareGenomeObservatory.Open(w,ctx);});
            Portal(chambers,"WORLD","UNIVERSAL WORLD KERNEL","Return to stable object passports and cross-system identity.",delegate{WorldKernel.Open(w,ctx);});
            Portal(chambers,"CIVIL","CIVILIZATION LAYER","Return to institutions, commons, councils, resolutions and civil memory.",delegate{CivilizationLayer.Open(w,ctx);});
            Portal(chambers,"LOGIC","EPISTEMIC LOGIC FOUNDRY","Inspect formal proposition and contradiction structures.",delegate{EpistemicLogicFoundry.Open(w,ctx);});
            Portal(chambers,"VERIFY","AXIOMATIC VERIFICATION REACTOR","Inspect formal finite-state verification evidence.",delegate{AxiomaticVerificationReactor.Open(w,ctx);});
            Portal(chambers,"STRAT","COUNTERFACTUAL STRATEGY","Inspect decision and counterfactual evidence.",delegate{CounterfactualStrategySuperstructure.Open(w,ctx);});
            Portal(chambers,"SCI","SCIENTIFIC DISCOVERY","Inspect experimental reasoning and hypothesis evidence.",delegate{ScientificDiscoveryHyperstructure.Open(w,ctx);});
            Portal(chambers,"SYS","SYSTEMS ENGINEERING","Inspect requirements, architecture and assurance evidence.",delegate{DysonSystemsEngineeringMegastructure.Open(w,ctx);});
            Portal(chambers,"TWIN","CYBERNETIC TWINS","Inspect state, estimation and control evidence.",delegate{CyberneticDigitalTwinMetastructure.Open(w,ctx);});
            Portal(chambers,"COMPLEX","COMPLEX SYSTEMS","Inspect emergence and ensemble evidence.",delegate{ComplexSystemsLaboratory.Open(w,ctx);});
            Portal(chambers,"ORΩ","OPERATIONS RESEARCH","Inspect optimization and logistics evidence.",delegate{OperationsResearchEmpire.Open(w,ctx);});
            Portal(chambers,"ECONΩ","ECONOMIC CIVILIZATION","Inspect stock-flow economic evidence.",delegate{EconomicCivilization.Open(w,ctx);});
            Portal(chambers,"GEOΩ","SPATIAL CARTOGRAPHY","Inspect geographic/topological evidence.",delegate{SpatialWorldCartography.Open(w,ctx);});
            Portal(chambers,"DISTΩ","DISTRIBUTED SYSTEMS","Inspect networked computation evidence.",delegate{DistributedSystemsPlanetarium.Open(w,ctx);});
            Portal(chambers,"SECΩ","ADVERSARIAL SECURITY","Inspect defensive-assurance evidence.",delegate{AdversarialSecurityFortress.Open(w,ctx);});
            Portal(chambers,"ΔT","TEMPORAL OBSERVATORY","Cross into history, epochs and drift.",delegate{TemporalObservatory.Open(w,ctx);});
            Portal(chambers,"GRAPH","CAUSAL GRAPH LAB","Cross into evidence-chain and causal exploration.",delegate{CausalGraphLab.Open(w,ctx);});
            Portal(chambers,"R&D","RESEARCH WORKBENCH","Cross into anomaly and hypothesis exploration.",delegate{ResearchWorkbench.Open(w,ctx);});
            Portal(chambers,"WORK","PRODUCTIVITY FABRIC","Cross into resumable deep-work and research debt execution.",delegate{ProductivityFabric.Open(w,ctx);});
            Portal(chambers,"HADAL","HADAL SYSTEMS","Descend recursively through ancestry, consequence and unanswered null-space.",delegate{AbyssalKnowledgeEngine.Open(w,ctx);});
            Portal(chambers,"ATLAS","DEEP SYSTEMS ATLAS","Return to the whole system map.",delegate{DeepSystems.OpenAtlasFromContext(w);});
            scroll.Content=chambers;root.Children.Add(scroll);w.Content=root;w.Show();
        }

        private static void RefreshSnapshot(DeepSystemsContext ctx){string p=ExpeditionPath(ctx);ExpeditionCommandStore ex=new ExpeditionCommandStore();string raw="";if(File.Exists(p)){try{raw=File.ReadAllText(p,Encoding.UTF8);ExpeditionCommandStore read=Json.Deserialize<ExpeditionCommandStore>(raw);if(read!=null)ex=read;}catch{raw="CORRUPT";}}string fp=KnowledgeConstellationKernel.HashText(raw);if(Snapshot==null||!Eq(fp,LoadedExpeditionFingerprint)){Snapshot=KnowledgeConstellationKernel.Build(ex.Missions,fp);LoadedExpeditionFingerprint=fp;}}
        private static string ExpeditionPath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-grand-unified-expedition.json");}
        private static string StorePath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-knowledge-constellation.json");}
        private static string LedgerPath(DeepSystemsContext ctx){Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-knowledge-constellation-ledger.jsonl");}
        private static void LoadStore(DeepSystemsContext ctx){lock(Gate){if(Store!=null&&Eq(LoadedRoot,ctx.StateRoot))return;LoadedRoot=ctx.StateRoot;Store=null;string p=StorePath(ctx);if(File.Exists(p))try{Store=Json.Deserialize<ConstellationStore>(File.ReadAllText(p,Encoding.UTF8));}catch{PreserveCorrupt(p);}if(Store==null&&File.Exists(p+".previous"))try{Store=Json.Deserialize<ConstellationStore>(File.ReadAllText(p+".previous",Encoding.UTF8));}catch{}if(Store==null)Store=new ConstellationStore();Normalize();}}
        private static void Normalize(){if(Store==null)Store=new ConstellationStore();if(Store.Lenses==null)Store.Lenses=new List<ConstellationSavedLens>();if(Store.Baselines==null)Store.Baselines=new List<ConstellationBaseline>();if(Store.Notes==null)Store.Notes=new List<ConstellationNote>();if(Store.Seals==null)Store.Seals=new List<ConstellationSeal>();Store.Lenses=Store.Lenses.Take(256).ToList();Store.Baselines=Store.Baselines.Take(256).ToList();Store.Notes=Store.Notes.Take(2048).ToList();Store.Seals=Store.Seals.Take(256).ToList();}
        private static void Save(DeepSystemsContext ctx){lock(Gate){Normalize();Store.Revision++;Store.UpdatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture);string p=StorePath(ctx),n=p+".next",prev=p+".previous";File.WriteAllText(n,Json.Serialize(Store),new UTF8Encoding(false));if(File.Exists(p))try{File.Copy(p,prev,true);}catch{}if(File.Exists(p))File.Delete(p);File.Move(n,p);}}
        private static void PreserveCorrupt(string p){try{File.Copy(p,p+".corrupt-"+DateTime.UtcNow.ToString("yyyyMMddHHmmss",CultureInfo.InvariantCulture),true);}catch{}}
        private static void AppendLedger(DeepSystemsContext ctx,string ev,string detail){List<ConstellationLedgerRecord> old=ReadLedger(ctx);long seq=old.Count==0?1:old[old.Count-1].Sequence+1;string prev=old.Count==0?new string('0',64):old[old.Count-1].EntryHash;ConstellationLedgerRecord r=new ConstellationLedgerRecord{Schema=1,Sequence=seq,Utc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture),Event=ev,Detail=detail,SnapshotFingerprint=Snapshot==null?null:Snapshot.Fingerprint,PrevHash=prev};r.EntryHash=KnowledgeConstellationKernel.HashText(r.Schema+"|"+r.Sequence+"|"+r.Utc+"|"+r.Event+"|"+r.Detail+"|"+r.SnapshotFingerprint+"|"+r.PrevHash);File.AppendAllText(LedgerPath(ctx),Json.Serialize(r)+Environment.NewLine,new UTF8Encoding(false));}
        private static List<ConstellationLedgerRecord> ReadLedger(DeepSystemsContext ctx){List<ConstellationLedgerRecord> r=new List<ConstellationLedgerRecord>();string p=LedgerPath(ctx);if(!File.Exists(p))return r;Queue<string> q=new Queue<string>();foreach(string line in File.ReadLines(p)){q.Enqueue(line);if(q.Count>MaxLedgerRead)q.Dequeue();}foreach(string line in q){if(String.IsNullOrWhiteSpace(line))continue;try{ConstellationLedgerRecord x=Json.Deserialize<ConstellationLedgerRecord>(line);if(x!=null)r.Add(x);}catch{}}return r;}
        private static bool VerifyLedger(List<ConstellationLedgerRecord> xs){for(int i=0;i<xs.Count;i++){ConstellationLedgerRecord r=xs[i];if(i>0&&!Eq(r.PrevHash,xs[i-1].EntryHash))return false;string h=KnowledgeConstellationKernel.HashText(r.Schema+"|"+r.Sequence+"|"+r.Utc+"|"+r.Event+"|"+r.Detail+"|"+r.SnapshotFingerprint+"|"+r.PrevHash);if(!Eq(h,r.EntryHash))return false;}return true;}
        private static void LaunchFrontier(Window owner,DeepSystemsContext ctx){RefreshSnapshot(ctx);KnowledgeFrontier f=Choose(owner,"SELECT KNOWLEDGE FRONTIER",Snapshot.Frontiers);if(f==null)return;AppendLedger(ctx,"FRONTIER_LAUNCH",f.Id+" "+f.Question);GrandUnifiedExpeditionCommand.OpenFromKnowledgeFrontier(owner,ctx,f.Question,"METAΩ frontier "+f.Id+" from mission "+f.MissionId);}
        private static void Query(Window owner,DeepSystemsContext ctx){RefreshSnapshot(ctx);string q=Prompt(owner,"CONSTELLATION QUERY","Text contained in node id, label or detail","");if(String.IsNullOrWhiteSpace(q))return;List<object> rows=Snapshot.Nodes.Where(x=>Contains(x.Id,q)||Contains(x.Label,q)||Contains(x.Detail,q)||Contains(x.MissionId,q)||Contains(x.Kind,q)).Cast<object>().ToList();OpenCollection(owner,"QUERY · "+q,rows,"Live snapshot search; no index is persisted by the query.");}
        private static void SaveLens(Window owner,DeepSystemsContext ctx){string name=Prompt(owner,"SAVE LENS","Lens name","");if(String.IsNullOrWhiteSpace(name))return;string q=Prompt(owner,"SAVE LENS","Query text (optional)","");string kind=Prompt(owner,"SAVE LENS","Kind filter, e.g. FINDING / QUESTION / SOURCE / ANY","ANY");ConstellationSavedLens l=new ConstellationSavedLens{Id="LENS-"+Guid.NewGuid().ToString("N").Substring(0,12).ToUpperInvariant(),Name=name.Trim(),Query=q,KindFilter=kind,CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};Store.Lenses.Insert(0,l);Save(ctx);AppendLedger(ctx,"LENS_SAVED",l.Id+" "+l.Name);}
        private static void AddNote(Window owner,DeepSystemsContext ctx){string subject=Prompt(owner,"ADD NOTE","Graph subject identity, or CONSTELLATION","CONSTELLATION");if(subject==null)return;string text=Prompt(owner,"ADD NOTE","Note","");if(String.IsNullOrWhiteSpace(text))return;ConstellationNote n=new ConstellationNote{Id="NOTE-"+Guid.NewGuid().ToString("N").Substring(0,12).ToUpperInvariant(),SubjectId=String.IsNullOrWhiteSpace(subject)?"CONSTELLATION":subject.Trim(),Text=text.Trim(),CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};Store.Notes.Insert(0,n);Save(ctx);AppendLedger(ctx,"NOTE_ADDED",n.SubjectId);}
        private static void CreateBaseline(Window owner,DeepSystemsContext ctx){RefreshSnapshot(ctx);string name=Prompt(owner,"CREATE BASELINE","Baseline name","Constellation "+DateTime.Now.ToString("yyyy-MM-dd HH:mm",CultureInfo.CurrentCulture));if(String.IsNullOrWhiteSpace(name))return;ConstellationBaseline b=new ConstellationBaseline{Id="BASE-"+Guid.NewGuid().ToString("N").Substring(0,12).ToUpperInvariant(),Name=name.Trim(),SnapshotFingerprint=Snapshot.Fingerprint,ExpeditionStoreFingerprint=Snapshot.ExpeditionStoreFingerprint,Missions=Snapshot.Missions.Count,Nodes=Snapshot.Nodes.Count,Edges=Snapshot.Edges.Count,Frontiers=Snapshot.Frontiers.Count,CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};Store.Baselines.Insert(0,b);Save(ctx);AppendLedger(ctx,"BASELINE",b.Id+" "+b.SnapshotFingerprint);}
        private static void Drift(Window owner,DeepSystemsContext ctx){RefreshSnapshot(ctx);ConstellationBaseline b=Choose(owner,"SELECT BASELINE",Store.Baselines);if(b==null)return;List<object> rows=new List<object>{"baseline fp   "+b.SnapshotFingerprint,"current fp    "+Snapshot.Fingerprint,"changed       "+(!Eq(b.SnapshotFingerprint,Snapshot.Fingerprint)),"missions      "+b.Missions+" → "+Snapshot.Missions.Count,"nodes         "+b.Nodes+" → "+Snapshot.Nodes.Count,"edges         "+b.Edges+" → "+Snapshot.Edges.Count,"frontiers     "+b.Frontiers+" → "+Snapshot.Frontiers.Count};OpenCollection(owner,"UNIVERSE DRIFT · "+b.Name,rows,"Dimension/fingerprint drift does not explain semantic meaning by itself.");}
        private static void Seal(Window owner,DeepSystemsContext ctx){RefreshSnapshot(ctx);List<ConstellationValidationFinding> v=KnowledgeConstellationKernel.Validate(Snapshot);if(v.Any(x=>Eq(x.Severity,"ERROR"))){OpenCollection(owner,"CONSTELLATION SEAL REFUSED",v.Cast<object>().ToList(),"Structural errors must be repaired before sealing.");return;}ConstellationSeal s=new ConstellationSeal{Id="SEAL-"+Guid.NewGuid().ToString("N").Substring(0,12).ToUpperInvariant(),SnapshotFingerprint=Snapshot.Fingerprint,StoreFingerprint=Snapshot.ExpeditionStoreFingerprint,Missions=Snapshot.Missions.Count,Nodes=Snapshot.Nodes.Count,Edges=Snapshot.Edges.Count,CreatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)};s.CertificateHash=KnowledgeConstellationKernel.HashText(s.Id+"|"+s.SnapshotFingerprint+"|"+s.StoreFingerprint+"|"+s.Missions+"|"+s.Nodes+"|"+s.Edges+"|"+s.CreatedUtc);Store.Seals.Insert(0,s);Save(ctx);AppendLedger(ctx,"SEAL",s.CertificateHash);OpenCollection(owner,"CONSTELLATION SEALED",new List<object>{s},"Seal binds local graph identity only.");}
        private static void ShowLedger(Window owner,DeepSystemsContext ctx){List<ConstellationLedgerRecord> xs=ReadLedger(ctx);List<object> rows=new List<object>{"previous-hash chain: "+(VerifyLedger(xs)?"PASS":"FAIL"),"records: "+xs.Count};rows.AddRange(xs.Cast<object>());OpenCollection(owner,"METAΩ LEDGER",rows,"Ledger covers METAΩ local mutations; EXPΩ has its own mission ledger.");}
        private static void Export(Window owner,DeepSystemsContext ctx){RefreshSnapshot(ctx);string dir=Path.Combine(ctx.DataRoot,"exports","knowledge-constellation");Directory.CreateDirectory(dir);string stamp=DateTime.UtcNow.ToString("yyyyMMdd-HHmmss",CultureInfo.InvariantCulture);string root=Path.Combine(dir,"meta-omega-"+stamp);File.WriteAllText(root+".snapshot.json",Json.Serialize(Snapshot),new UTF8Encoding(false));File.WriteAllText(root+".annotations.json",Json.Serialize(Store),new UTF8Encoding(false));StringBuilder md=new StringBuilder();md.AppendLine("# METAΩ Knowledge Constellation");md.AppendLine();md.AppendLine("Snapshot fingerprint: `"+Snapshot.Fingerprint+"`");md.AppendLine();md.AppendLine("Missions: "+Snapshot.Missions.Count+"  ");md.AppendLine("Nodes: "+Snapshot.Nodes.Count+"  ");md.AppendLine("Edges: "+Snapshot.Edges.Count+"  ");md.AppendLine("Open frontiers: "+Snapshot.Frontiers.Count+"  ");md.AppendLine();md.AppendLine("## Highest-pressure frontiers");foreach(KnowledgeFrontier f in Snapshot.Frontiers.Take(30))md.AppendLine("- "+f.ToString());File.WriteAllText(root+".md",md.ToString(),new UTF8Encoding(false));AppendLedger(ctx,"EXPORT",root);TextView(owner,"EXPORT COMPLETE",root+Environment.NewLine+"\n"+Snapshot.Fingerprint);}
        private static void Autopsy(Window owner,DeepSystemsContext ctx){RefreshSnapshot(ctx);List<ConstellationValidationFinding> val=KnowledgeConstellationKernel.Validate(Snapshot);StringBuilder b=new StringBuilder();b.AppendLine("METAΩ CONSTELLATION AUTOPSY");b.AppendLine(new string('=',72));b.AppendLine("missions:            "+Snapshot.Missions.Count);b.AppendLine("nodes:               "+Snapshot.Nodes.Count);b.AppendLine("edges:               "+Snapshot.Edges.Count);b.AppendLine("observed edges:      "+Snapshot.Edges.Count(x=>!x.Heuristic));b.AppendLine("heuristic edges:     "+Snapshot.Edges.Count(x=>x.Heuristic));b.AppendLine("open frontiers:      "+Snapshot.Frontiers.Count);b.AppendLine("convergences:        "+Snapshot.Convergences.Count);b.AppendLine("shared-source sets:  "+Snapshot.SourceReuse.Count);b.AppendLine("mission affinities:  "+Snapshot.Affinities.Count);b.AppendLine("validation errors:   "+val.Count(x=>Eq(x.Severity,"ERROR")));b.AppendLine("snapshot fp:         "+Snapshot.Fingerprint);b.AppendLine();b.AppendLine("Highest pressure frontiers:");foreach(KnowledgeFrontier f in Snapshot.Frontiers.Take(12))b.AppendLine("  "+f);TextView(owner,"CONSTELLATION AUTOPSY",b.ToString());}
        private static void ShowDegree(Window owner){Dictionary<string,int> d=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);foreach(ConstellationEdge e in Snapshot.Edges){if(!d.ContainsKey(e.FromId))d[e.FromId]=0;if(!d.ContainsKey(e.ToId))d[e.ToId]=0;d[e.FromId]++;d[e.ToId]++;}List<object> rows=d.OrderByDescending(x=>x.Value).Take(512).Select(x=>(object)(x.Value.ToString("0000",CultureInfo.InvariantCulture)+"   ·   "+x.Key)).ToList();OpenCollection(owner,"HUB CENTRALITY",rows,"Undirected degree over the retained graph; descriptive only.");}
        private static void ShowBridges(Window owner){Dictionary<string,HashSet<string>> n2m=new Dictionary<string,HashSet<string>>(StringComparer.OrdinalIgnoreCase);Dictionary<string,string> nodeMission=Snapshot.Nodes.ToDictionary(x=>x.Id,x=>x.MissionId??"",StringComparer.OrdinalIgnoreCase);foreach(ConstellationEdge e in Snapshot.Edges){string a,b;nodeMission.TryGetValue(e.FromId,out a);nodeMission.TryGetValue(e.ToId,out b);if(String.IsNullOrWhiteSpace(a)||String.IsNullOrWhiteSpace(b)||Eq(a,b))continue;if(!n2m.ContainsKey(e.FromId))n2m[e.FromId]=new HashSet<string>(StringComparer.OrdinalIgnoreCase);if(!n2m.ContainsKey(e.ToId))n2m[e.ToId]=new HashSet<string>(StringComparer.OrdinalIgnoreCase);n2m[e.FromId].Add(b);n2m[e.ToId].Add(a);}OpenCollection(owner,"BRIDGE OBJECTS",n2m.OrderByDescending(x=>x.Value.Count).Select(x=>(object)(x.Value.Count.ToString("000",CultureInfo.InvariantCulture)+" mission bridges   ·   "+x.Key)).ToList(),"Bridge count describes cross-mission connectivity in this projection.");}
        private static void ShowCivilizations(Window owner,DeepSystemsContext ctx){string p=ExpeditionPath(ctx);ExpeditionCommandStore ex=new ExpeditionCommandStore();if(File.Exists(p))try{ex=Json.Deserialize<ExpeditionCommandStore>(File.ReadAllText(p,Encoding.UTF8))??ex;}catch{}var rows=ex.Missions.SelectMany(m=>m.Steps.Select(s=>new{Civ=s.Civilization??"UNKNOWN",Mission=m.Id})).GroupBy(x=>x.Civ,StringComparer.OrdinalIgnoreCase).Select(g=>(object)(g.Key+"   ·   crossings "+g.Count()+"   ·   missions "+g.Select(x=>x.Mission).Distinct(StringComparer.OrdinalIgnoreCase).Count())).ToList();OpenCollection(owner,"CIVILIZATION COVERAGE UNIVERSE",rows,"Counts are retained crossing events, not claims of evidentiary sufficiency.");}
        private static void ShowDensity(Window owner){var rows=Snapshot.Missions.Select(m=>(object)((m.Steps==0?0:(double)m.Findings/m.Steps).ToString("0.00",CultureInfo.InvariantCulture)+" findings/step   ·   "+m.UniqueSources+" sources   ·   "+(m.Title??m.MissionId))).ToList();OpenCollection(owner,"EVIDENCE DENSITY",rows,"Density is descriptive and not a quality score.");}
        private static T Choose<T>(Window owner,string title,IList<T> items) where T:class{if(items==null||items.Count==0)return null;Window w=W(owner,"YOMI · "+title,1080,740);DockPanel root=Shell(title,"Double-click to select.");ListBox list=List();list.ItemsSource=items;T selected=null;list.MouseDoubleClick+=delegate{selected=list.SelectedItem as T;w.DialogResult=selected!=null;w.Close();};root.Children.Add(list);w.Content=root;bool? r=w.ShowDialog();return r==true?selected:null;}
        private static Window W(Window owner,string title,double width,double height){return new Window{Title=title,Width=width,Height=height,Background=Bg,Foreground=Text,WindowStartupLocation=owner==null?WindowStartupLocation.CenterScreen:WindowStartupLocation.CenterOwner,Owner=owner};}
        private static DockPanel Shell(string title,string subtitle){DockPanel root=new DockPanel{Background=Bg};StackPanel head=new StackPanel{Margin=new Thickness(20,18,20,10)};head.Children.Add(new TextBlock{Text=title,Foreground=Text,FontSize=25,FontWeight=FontWeights.Bold});head.Children.Add(new TextBlock{Text=subtitle??"",Foreground=Muted,FontSize=13,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,5,0,0)});DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);return root;}
        private static void Portal(WrapPanel panel,string badge,string title,string detail,RoutedEventHandler click){Button b=new Button{Width=285,MinHeight=118,Margin=new Thickness(7),Padding=new Thickness(14),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),HorizontalContentAlignment=HorizontalAlignment.Stretch};StackPanel p=new StackPanel();p.Children.Add(new TextBlock{Text=badge+"   "+title,Foreground=Accent,FontWeight=FontWeights.Bold,FontSize=13,TextWrapping=TextWrapping.Wrap});p.Children.Add(new TextBlock{Text=detail,Foreground=Muted,FontSize=12,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,7,0,0)});b.Content=p;b.Click+=click;panel.Children.Add(b);}
        private static ListBox List(){return new ListBox{Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),FontFamily=new FontFamily("Consolas"),FontSize=12};}
        private static void OpenCollection(Window owner,string title,IList<object> items,string note){Window w=W(owner,"YOMI · "+title,1380,850);DockPanel root=Shell(title,note+"   ·   "+(items==null?0:items.Count)+" rows");ListBox list=List();list.ItemsSource=items??new List<object>();root.Children.Add(list);w.Content=root;w.Show();}
        private static void TextView(Window owner,string title,string text){Window w=W(owner,"YOMI · "+title,1380,880);DockPanel root=Shell(title,"Read-only representation.");TextBox box=new TextBox{Text=text??"",Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,FontFamily=new FontFamily("Consolas"),FontSize=13,IsReadOnly=true,AcceptsReturn=true,AcceptsTab=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto};root.Children.Add(box);w.Content=root;w.Show();}
        private static string Prompt(Window owner,string title,string label,string initial){Window w=W(owner,"YOMI · "+title,800,320);DockPanel root=Shell(title,label);TextBox box=new TextBox{Text=initial??"",Margin=new Thickness(20,6,20,10),Padding=new Thickness(8),Background=Surface,Foreground=Text,BorderBrush=Border,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=90,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};DockPanel.SetDock(box,Dock.Top);root.Children.Add(box);StackPanel buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(20)};Button ok=new Button{Content="COMMIT",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Green,BorderBrush=Border};Button cancel=new Button{Content="CANCEL",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Muted,BorderBrush=Border};string value=null;ok.Click+=delegate{value=box.Text;w.DialogResult=true;w.Close();};cancel.Click+=delegate{w.DialogResult=false;w.Close();};buttons.Children.Add(cancel);buttons.Children.Add(ok);root.Children.Add(buttons);w.Content=root;bool? r=w.ShowDialog();return r==true?value:null;}
        private static bool Eq(string a,string b){return String.Equals(a,b,StringComparison.OrdinalIgnoreCase);}private static bool Contains(string a,string b){return !String.IsNullOrWhiteSpace(a)&&!String.IsNullOrWhiteSpace(b)&&a.IndexOf(b,StringComparison.OrdinalIgnoreCase)>=0;}private static Brush B(string hex){return (Brush)new BrushConverter().ConvertFromString(hex);}
    }
}
