using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class ComplexRunRecord
    {
        public string Id { get; set; }
        public string ModelId { get; set; }
        public string CreatedUtc { get; set; }
        public string ModelFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public string Label { get; set; }
        public ComplexSimulationResult Result { get; set; }
        public List<string> Notes { get; set; }
        public ComplexRunRecord() { Notes = new List<string>(); }
        public override string ToString() { return (CreatedUtc ?? "") + "   ·   " + (Label ?? "SIMULATION") + "   ·   " + (Result == null ? "NO RESULT" : Result.ToString()) + "   ·   cert " + Short(CertificateHash); }
        private static string Short(string x) { return String.IsNullOrWhiteSpace(x) ? "∅" : x.Substring(0, Math.Min(16, x.Length)); }
    }

    internal sealed class ComplexEnsembleRecord
    {
        public string Id { get; set; }
        public string ModelId { get; set; }
        public string CreatedUtc { get; set; }
        public string ModelFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public ComplexEnsembleResult Result { get; set; }
        public override string ToString() { return (CreatedUtc ?? "") + "   ·   " + (Result == null ? "EMPTY ENSEMBLE" : Result.ToString()) + "   ·   cert " + Short(CertificateHash); }
        private static string Short(string x) { return String.IsNullOrWhiteSpace(x) ? "∅" : x.Substring(0, Math.Min(16, x.Length)); }
    }

    internal sealed class ComplexSweepRecord
    {
        public string Id { get; set; }
        public string ModelId { get; set; }
        public string CreatedUtc { get; set; }
        public string ModelFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public ComplexPhaseSweepResult Result { get; set; }
        public override string ToString() { return (CreatedUtc ?? "") + "   ·   " + (Result == null ? "EMPTY SWEEP" : Result.ToString()) + "   ·   cert " + Short(CertificateHash); }
        private static string Short(string x) { return String.IsNullOrWhiteSpace(x) ? "∅" : x.Substring(0, Math.Min(16, x.Length)); }
    }

    internal sealed class ComplexExperimentCapsule
    {
        public string Id { get; set; }
        public string ModelId { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public string Status { get; set; }
        public string FrozenUtc { get; set; }
        public string ModelFingerprint { get; set; }
        public string PrimaryMetric { get; set; }
        public int PlannedReplicates { get; set; }
        public int SeedOffset { get; set; }
        public string StoppingRule { get; set; }
        public string AnalysisPlan { get; set; }
        public string NullExpectation { get; set; }
        public string AuthorityBoundary { get; set; }
        public string CertificateHash { get; set; }
        public Dictionary<string, double> FrozenParameters { get; set; }
        public List<string> Assumptions { get; set; }
        public List<string> Falsifiers { get; set; }
        public List<string> EvidenceNodeIds { get; set; }
        public ComplexExperimentCapsule() { Status = "PREREGISTERED"; PlannedReplicates = 64; PrimaryMetric = "terminal_order_parameter"; StoppingRule = "FIXED_REPLICATE_COUNT"; AnalysisPlan = "Report the complete declared ensemble, uncertainty quantiles, basin multiplicity and all audit boundaries."; AuthorityBoundary = "SIMULATION-ONLY · no observation, prediction, experiment execution, deployment or autonomous authority."; FrozenParameters = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase); Assumptions = new List<string>(); Falsifiers = new List<string>(); EvidenceNodeIds = new List<string>(); }
        public override string ToString() { return (Status ?? "PREREGISTERED") + "   ·   " + (Title ?? Id ?? "EXPERIMENT CAPSULE") + "   ·   " + PlannedReplicates.ToString(CultureInfo.InvariantCulture) + " replicates   ·   " + (PrimaryMetric ?? "metric") + "   ·   cert " + Short(CertificateHash); }
        private static string Short(string x) { return String.IsNullOrWhiteSpace(x) ? "∅" : x.Substring(0, Math.Min(16, x.Length)); }
    }

    internal sealed class ComplexModelBaseline
    {
        public string Id { get; set; }
        public string ModelId { get; set; }
        public string ParentBaselineId { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string FrozenUtc { get; set; }
        public string Reason { get; set; }
        public string ModelFingerprint { get; set; }
        public string SnapshotJson { get; set; }
        public string BaselineFingerprint { get; set; }
        public override string ToString() { return (Status ?? "FROZEN") + "   ·   " + (Name ?? Id ?? "BASELINE") + "   ·   " + (FrozenUtc ?? "") + "   ·   " + Short(BaselineFingerprint); }
        private static string Short(string x) { return String.IsNullOrWhiteSpace(x) ? "∅" : x.Substring(0, Math.Min(16, x.Length)); }
    }

    internal sealed class ComplexScenarioDossier
    {
        public string Id { get; set; }
        public string ModelId { get; set; }
        public string RunId { get; set; }
        public string EnsembleId { get; set; }
        public string SweepId { get; set; }
        public string BaselineId { get; set; }
        public string CapsuleId { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string CreatedUtc { get; set; }
        public string UpdatedUtc { get; set; }
        public string ModelFingerprint { get; set; }
        public string BoundedClaim { get; set; }
        public string AuthorityBoundary { get; set; }
        public List<string> Mechanisms { get; set; }
        public List<string> Alternatives { get; set; }
        public List<string> Unknowns { get; set; }
        public List<string> Dissent { get; set; }
        public List<string> EvidenceNodeIds { get; set; }
        public ComplexScenarioDossier() { Status = "DRAFT"; AuthorityBoundary = "MODEL-BOUND · no empirical truth, forecast, policy, command, deployment or autonomous execution authority."; Mechanisms = new List<string>(); Alternatives = new List<string>(); Unknowns = new List<string>(); Dissent = new List<string>(); EvidenceNodeIds = new List<string>(); }
        public override string ToString() { return (Status ?? "DRAFT") + "   ·   " + (Title ?? Id ?? "SCENARIO DOSSIER") + "   ·   " + (UpdatedUtc ?? CreatedUtc ?? "") + "   ·   " + Short(ModelFingerprint); }
        private static string Short(string x) { return String.IsNullOrWhiteSpace(x) ? "∅" : x.Substring(0, Math.Min(16, x.Length)); }
    }

    internal sealed class ComplexLabLedgerRecord
    {
        public int Schema { get; set; }
        public long Sequence { get; set; }
        public string Utc { get; set; }
        public string Event { get; set; }
        public string Subject { get; set; }
        public string Detail { get; set; }
        public string CorrelationId { get; set; }
        public string ModelFingerprint { get; set; }
        public string CertificateHash { get; set; }
        public string PrevHash { get; set; }
        public string EntryHash { get; set; }
        public override string ToString() { return Sequence.ToString(CultureInfo.InvariantCulture).PadLeft(7) + "   " + (Utc ?? "") + "   " + (Event ?? "") + "   ·   " + (Subject ?? "∅") + "   ·   " + (Detail ?? ""); }
    }

    internal sealed class ComplexSystemsStore
    {
        public int Schema { get; set; }
        public long Revision { get; set; }
        public string UpdatedUtc { get; set; }
        public string LastCommitId { get; set; }
        public List<ComplexSystemModel> Models { get; set; }
        public List<ComplexRunRecord> Runs { get; set; }
        public List<ComplexEnsembleRecord> Ensembles { get; set; }
        public List<ComplexSweepRecord> Sweeps { get; set; }
        public List<ComplexExperimentCapsule> Capsules { get; set; }
        public List<ComplexModelBaseline> Baselines { get; set; }
        public List<ComplexScenarioDossier> Dossiers { get; set; }
        public List<string> RecentQuestions { get; set; }
        public ComplexSystemsStore() { Schema = 1; Models = new List<ComplexSystemModel>(); Runs = new List<ComplexRunRecord>(); Ensembles = new List<ComplexEnsembleRecord>(); Sweeps = new List<ComplexSweepRecord>(); Capsules = new List<ComplexExperimentCapsule>(); Baselines = new List<ComplexModelBaseline>(); Dossiers = new List<ComplexScenarioDossier>(); RecentQuestions = new List<string>(); }
    }

    internal static class ComplexSystemsLaboratory
    {
        private static readonly Brush Bg = B("#05040A");
        private static readonly Brush Surface = B("#100D19");
        private static readonly Brush Raised = B("#1A1530");
        private static readonly Brush Border = B("#594D87");
        private static readonly Brush Text = B("#FBF8FF");
        private static readonly Brush Muted = B("#B8AFCA");
        private static readonly Brush Accent = B("#B9FF6A");
        private static readonly Brush Blue = B("#75CFFF");
        private static readonly Brush Amber = B("#FFD875");
        private static readonly Brush Violet = B("#D8A8FF");
        private static readonly Brush Danger = B("#FF829D");
        private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = Int32.MaxValue, RecursionLimit = 256 };
        private static readonly object Gate = new object();
        private static ComplexSystemsStore Store;
        private static string LoadedRoot;
        private const int MaxModels = 512;
        private const int MaxRuns = 2048;
        private const int MaxEnsembles = 1024;
        private const int MaxSweeps = 512;
        private const int MaxCapsules = 1024;
        private const int MaxBaselines = 1024;
        private const int MaxDossiers = 1024;
        private const int MaxAgents = 4096;
        private const int MaxEdges = 262144;
        private const int MaxRules = 4096;
        private const int MaxInterventions = 4096;
        private const int MaxEvidence = 2048;
        private const int MaxShortText = 2048;
        private const int MaxLongText = 65536;

        public static void Open(Window owner, DeepSystemsContext ctx) { if (ctx == null) return; Load(ctx); OpenHub(owner, ctx, WorldKernel.ExternalIndex(ctx, false)); }

        public static void OpenFromWorldNode(Window owner, DeepSystemsContext ctx, WorldIndex index, string nodeId)
        {
            if (ctx == null || index == null || String.IsNullOrWhiteSpace(nodeId)) return; WorldNode node; if (!index.Nodes.TryGetValue(nodeId, out node)) { Open(owner, ctx); return; } string fingerprint = HashText((node.Id ?? "") + "|" + (node.Kind ?? "") + "|" + (node.Label ?? "") + "|" + (node.Fingerprint ?? ""));
            OpenProjection(owner, ctx, index, "WORLD", node.Id, fingerprint, delegate { ComplexSystemModel m = StarterModel("Emergent world population · " + (node.Label ?? node.Kind ?? "World object"), "Synthetic population projected from a World Passport identity. Passport provenance remains evidence; agent rules are new declarations."); m.PopulationKind = node.Kind ?? "ACTORS"; m.EvidenceNodeIds.Add(node.Id); return m; });
        }

        public static void OpenFromCivilResolution(Window owner, DeepSystemsContext ctx, WorldIndex index, CivilResolution resolution)
        {
            if (ctx == null || resolution == null) return; string fingerprint = HashText((resolution.Id ?? "") + "|" + (resolution.Title ?? "") + "|" + (resolution.Proposition ?? "") + "|" + (resolution.Status ?? "") + "|" + String.Join("|", (resolution.EvidenceNodeIds ?? new List<string>()).OrderBy(x => x).ToArray()));
            OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "CIVILIZATION", resolution.Id, fingerprint, delegate { ComplexSystemModel m = StarterModel("Institutional emergence · " + (resolution.Title ?? "Resolution"), "Population model of heterogeneous institutional adoption, resistance, diffusion and unintended collective consequences."); m.Assumptions.Add("Civil proposition: " + (resolution.Proposition ?? "")); m.EvidenceNodeIds.AddRange(resolution.EvidenceNodeIds ?? new List<string>()); return m; });
        }

        public static void OpenFromLogicTheory(Window owner, DeepSystemsContext ctx, WorldIndex index, LogicTheory theory)
        {
            if (ctx == null || theory == null) return; Dictionary<string, string> truth = EpistemicLogicFoundry.ExternalTheoryTruth(ctx, theory); string fingerprint = HashText((theory.Id ?? "") + "|" + (theory.Name ?? "") + "|" + String.Join("|", truth.OrderBy(x => x.Key).Select(x => x.Key + "=" + x.Value).ToArray()));
            OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "LOGIC", theory.Id, fingerprint, delegate { ComplexSystemModel m = StarterModel("Epistemic ecology · " + (theory.Name ?? "Theory"), "Agent ecology for belief propagation under contradiction, confidence, bounded neighborhoods and competing attractors."); m.DynamicsKind = "BOUNDED_CONFIDENCE"; m.Parameters["confidence_bound"] = 0.3; m.Parameters["adaptation_rate"] = 0.2; m.Assumptions.Add("Frozen paraconsistent spectrum: " + String.Join(", ", truth.Take(32).Select(x => x.Key + "=" + x.Value).ToArray())); return m; });
        }

        public static void OpenFromVerificationModel(Window owner, DeepSystemsContext ctx, WorldIndex index, VerificationModel source)
        {
            if (ctx == null || source == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "VERIFICATION", source.Id, VerificationKernel.Fingerprint(source), delegate { ComplexSystemModel m = StarterModel("Protocol population · " + (source.Name ?? "Verification model"), "Population-level interaction projection of a finite-state protocol. It does not replace exact temporal verification."); m.TopologyKind = "EXPLICIT"; m.DynamicsKind = "VOTER"; m.PopulationSize = Math.Max(2, Math.Min(4096, (source.States ?? new List<VerificationState>()).Count)); foreach (VerificationState s in (source.States ?? new List<VerificationState>()).Take(4096)) m.Agents.Add(new ComplexAgentSpec { Id = s.Id, Label = s.Name, Kind = "PROTOCOL_STATE", Archetype = "STATE", InitialMode = (source.InitialStateIds ?? new List<string>()).Contains(s.Id, StringComparer.OrdinalIgnoreCase) ? "1" : "0", InitialValue = 0, Capacity = 1, EvidenceNodeIds = new List<string>(s.EvidenceNodeIds ?? new List<string>()) }); foreach (VerificationTransition t in (source.Transitions ?? new List<VerificationTransition>()).Take(MaxEdges)) m.Edges.Add(new ComplexInteractionEdge { Id = t.Id, SourceId = t.FromStateId, TargetId = t.ToStateId, Kind = t.Kind ?? "TRANSITION", Weight = 1, Bidirectional = false, Status = t.Status, EvidenceNodeIds = new List<string>(t.EvidenceNodeIds ?? new List<string>()) }); m.EvidenceNodeIds.AddRange(source.EvidenceNodeIds ?? new List<string>()); return m; });
        }

        public static void OpenFromStrategyModel(Window owner, DeepSystemsContext ctx, WorldIndex index, StrategyModel source)
        {
            if (ctx == null || source == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "STRATEGY", source.Id, CounterfactualStrategyKernel.Fingerprint(source), delegate { ComplexSystemModel m = StarterModel("Strategic interaction ecology · " + (source.Name ?? "Strategy"), "Agent interaction lens over declared causal variables and mechanisms. Structural hypotheses are not upgraded into validated social laws."); m.TopologyKind = "EXPLICIT"; m.DynamicsKind = "COUPLED_MAP"; m.PopulationSize = Math.Max(2, Math.Min(4096, (source.Variables ?? new List<StrategyVariable>()).Count)); foreach (StrategyVariable v in (source.Variables ?? new List<StrategyVariable>()).Take(4096)) m.Agents.Add(new ComplexAgentSpec { Id = v.Id, Label = v.Name, Kind = v.Kind, Archetype = v.Kind, InitialMode = v.Baseline >= 0 ? "1" : "0", InitialValue = Normalize(v.Baseline, v.Minimum, v.Maximum), Capacity = 1, EvidenceNodeIds = new List<string>(v.EvidenceNodeIds ?? new List<string>()) }); foreach (StrategyEdge e in (source.Edges ?? new List<StrategyEdge>()).Take(MaxEdges)) m.Edges.Add(new ComplexInteractionEdge { Id = e.Id, SourceId = e.FromVariableId, TargetId = e.ToVariableId, Kind = e.Kind, Weight = e.Coefficient, Bidirectional = false, Status = e.Status, EvidenceNodeIds = new List<string>(e.EvidenceNodeIds ?? new List<string>()) }); m.Assumptions.AddRange(source.Assumptions ?? new List<string>()); m.EvidenceNodeIds.AddRange(source.EvidenceNodeIds ?? new List<string>()); return m; });
        }

        public static void OpenFromDiscoveryProtocol(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol source)
        {
            if (ctx == null || source == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "DISCOVERY", source.Id, ExperimentalDesignKernel.ProtocolFingerprint(source), delegate { ComplexSystemModel m = StarterModel("Experimental population · " + (source.Name ?? "Discovery protocol"), "Synthetic-population extension of a preregistered protocol for examining interference, heterogeneity and emergence that the original independent-unit design may omit."); m.Seed = source.Seed; m.PopulationSize = Math.Max(16, Math.Min(4096, source.RequestedRuns * Math.Max(1, source.Replicates))); foreach (DiscoveryFactor f in (source.Factors ?? new List<DiscoveryFactor>()).Where(x => x != null).Take(64)) m.Parameters["factor_" + SafeKey(f.Id ?? f.Name)] = (f.Minimum + f.Maximum) * 0.5; m.Assumptions.AddRange(source.Assumptions ?? new List<string>()); m.EvidenceNodeIds.AddRange(source.EvidenceNodeIds ?? new List<string>()); return m; });
        }

        public static void OpenFromEngineeringArchitecture(Window owner, DeepSystemsContext ctx, WorldIndex index, EngineeringArchitecture source)
        {
            if (ctx == null || source == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "ENGINEERING", source.Id, SystemsEngineeringKernel.Fingerprint(source), delegate { ComplexSystemModel m = StarterModel("Architecture cascade ecology · " + (source.Name ?? "Engineering architecture"), "Failure propagation and collective capacity projection of an engineering architecture. Declared interface structure is retained without asserting calibrated field behavior."); m.TopologyKind = "EXPLICIT"; m.DynamicsKind = "CASCADE_FAILURE"; m.PopulationKind = "MACHINES"; m.PopulationSize = Math.Max(2, Math.Min(4096, (source.Components ?? new List<EngineeringComponent>()).Count)); foreach (EngineeringComponent c in (source.Components ?? new List<EngineeringComponent>()).Take(4096)) m.Agents.Add(new ComplexAgentSpec { Id = c.Id, Label = c.Name, Kind = c.Kind, Archetype = c.Kind, InitialMode = "1", InitialValue = 1, Capacity = Math.Max(0.001, c.Capacity == 0 ? 1 : c.Capacity), InitialLoad = Math.Max(0, c.Capacity == 0 ? 0.4 : 0.4 * c.Capacity), EvidenceNodeIds = new List<string>(c.EvidenceNodeIds ?? new List<string>()) }); foreach (EngineeringInterface e in (source.Interfaces ?? new List<EngineeringInterface>()).Take(MaxEdges)) m.Edges.Add(new ComplexInteractionEdge { Id = e.Id, SourceId = e.FromComponentId, TargetId = e.ToComponentId, Kind = e.Kind, Weight = e.Capacity == 0 ? 1 : e.Capacity, Bidirectional = false, Status = e.Status, EvidenceNodeIds = new List<string>(e.EvidenceNodeIds ?? new List<string>()) }); m.Assumptions.AddRange(source.Assumptions ?? new List<string>()); m.EvidenceNodeIds.AddRange(source.EvidenceNodeIds ?? new List<string>()); return m; });
        }

        public static void OpenFromCyberneticTwin(Window owner, DeepSystemsContext ctx, WorldIndex index, CyberTwinModel source)
        {
            if (ctx == null || source == null) return; OpenProjection(owner, ctx, index ?? WorldKernel.ExternalIndex(ctx, false), "CYBERNETIC", source.Id, CyberneticsKernel.Fingerprint(source), delegate { ComplexSystemModel m = StarterModel("Coupled twin population · " + (source.Name ?? "Digital twin"), "Nonlinear population and interaction-network projection of a linear cybernetic twin. It supplements rather than replaces the state-space analysis."); m.TopologyKind = "EXPLICIT"; m.DynamicsKind = "COUPLED_MAP"; m.PopulationKind = "STATE_COORDINATES"; m.PopulationSize = Math.Max(2, Math.Min(4096, (source.States ?? new List<CyberStateVariable>()).Count)); for (int i = 0; i < (source.States ?? new List<CyberStateVariable>()).Count && i < 4096; i++) { CyberStateVariable s = source.States[i]; m.Agents.Add(new ComplexAgentSpec { Id = s.Id, Label = s.Name, Kind = "STATE", Archetype = "STATE", InitialMode = s.InitialValue >= 0 ? "1" : "0", InitialValue = Normalize(s.InitialValue, s.Minimum, s.Maximum), Capacity = 1, EvidenceNodeIds = new List<string>(s.EvidenceNodeIds ?? new List<string>()) }); } for (int row = 0; row < (source.A ?? new double[0][]).Length && row < m.Agents.Count; row++) for (int col = 0; source.A[row] != null && col < source.A[row].Length && col < m.Agents.Count; col++) if (Math.Abs(source.A[row][col]) > 1e-12) m.Edges.Add(new ComplexInteractionEdge { Id = "A-" + row + "-" + col, SourceId = m.Agents[col].Id, TargetId = m.Agents[row].Id, Kind = "STATE_COUPLING", Weight = source.A[row][col], Bidirectional = false }); m.Assumptions.AddRange(source.Assumptions ?? new List<string>()); m.EvidenceNodeIds.AddRange(source.EvidenceNodeIds ?? new List<string>()); return m; });
        }

        private static void OpenProjection(Window owner, DeepSystemsContext ctx, WorldIndex index, string sourceKind, string sourceId, string fingerprint, Func<ComplexSystemModel> factory)
        {
            Load(ctx); List<ComplexSystemModel> existing = Store.Models.Where(x => Eq(x.SourceKind, sourceKind) && Eq(x.SourceId, sourceId)).OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).ToList(); ComplexSystemModel exact = existing.FirstOrDefault(x => Eq(x.SourceFingerprint, fingerprint)); if (exact != null) { OpenModel(owner, ctx, index, exact); return; }
            if (existing.Count > 0) { MessageBoxResult drift = MessageBox.Show(owner, "The source fingerprint has changed since the latest complexity projection.\n\nYES · create a traceable child revision\nNO · open the historical projection\nCANCEL · leave unchanged", "YOMI · SOURCE DRIFT BOUNDARY", MessageBoxButton.YesNoCancel, MessageBoxImage.Warning); if (drift == MessageBoxResult.No) { OpenModel(owner, ctx, index, existing[0]); return; } if (drift != MessageBoxResult.Yes) return; }
            ComplexSystemModel model = factory == null ? StarterModel("Untitled complex system", "Declared complex-system abstraction.") : factory(); if (model == null) return; model.Id = Id("complex-model"); model.ParentModelId = existing.Count == 0 ? null : existing[0].Id; model.SourceKind = sourceKind; model.SourceId = sourceId; model.SourceFingerprint = fingerprint; model.CreatedUtc = Now(); model.UpdatedUtc = model.CreatedUtc; model.Revision = existing.Count == 0 ? 1 : Math.Max(1, existing[0].Revision) + 1; Store.Models.Insert(0, model); Save(ctx); AppendLedger(ctx, "MODEL_PROJECTED", model.Id, sourceKind + ":" + sourceId + (existing.Count == 0 ? "" : " · source drift child of " + existing[0].Id), ComplexSystemsKernel.Fingerprint(model), ""); OpenModel(owner, ctx, index, model);
        }

        private static void OpenHub(Window owner, DeepSystemsContext ctx, WorldIndex index)
        {
            Load(ctx); Window w = W(owner, "YOMI · COMPLEX SYSTEMS LABORATORY", 1360, 920); DockPanel root = Shell("COMPLEX SYSTEMS LABORATORY", "DEV13.37.18 · emergence, nonlinear populations, interaction networks, phase transitions, cascades, resilience and criticality · simulation authority only"); root.Children.Add(T(CensusLine(), 12, Blue, FontWeights.SemiBold)); ScrollViewer scroll = new ScrollViewer { VerticalScrollBarVisibility = ScrollBarVisibility.Auto }; WrapPanel cards = new WrapPanel { Margin = new Thickness(0, 12, 0, 0) };
            Portal(cards, "ΣPOP", "MODEL REGISTRY", "Inspect versioned populations, source projections and lineage branches.", delegate { OpenRegistry(w, ctx, index); });
            Portal(cards, "N↔N", "POPULATION FORGE", "Create people, machines, firms, animals, protocols or abstract actors with heterogeneous traits.", delegate { CreateModel(w, ctx, index); });
            Portal(cards, "G(V,E)", "INTERACTION TOPOLOGY", "Measure components, clustering, path length, assortativity, modularity and spectral radius.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenRows(w, "INTERACTION TOPOLOGY", ComplexSystemsKernel.AnalyzeNetwork(m), "Declared interaction network diagnostics"); }); });
            Portal(cards, "f(x,N)", "RULE ECOLOGY", "Inspect and edit generic state transitions, value dynamics, failure and recovery rules.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenRules(w, ctx, index, m); }); });
            Portal(cards, "t→∞", "SIMULATION CHAMBER", "Run deterministic seeded micro-to-macro evolution with bounded attractor detection.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { RunSimulation(w, ctx, m); }); });
            Portal(cards, "Ω", "ENSEMBLE OBSERVATORY", "Compare many deterministic seed worlds, quantiles, collapse frequency and terminal basins.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { RunEnsemble(w, ctx, m); }); });
            Portal(cards, "λc", "PHASE TRANSITION ATLAS", "Sweep a declared parameter for finite-size susceptibility, Binder and derivative peaks.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { RunPhaseSweep(w, ctx, m); }); });
            Portal(cards, "𝒜", "ATTRACTOR BASIN VAULT", "Explore recurrent microstate hashes, transients, periods and basin multiplicity.", delegate { OpenRunVault(w, ctx, "ATTRACTOR BASIN VAULT", true); });
            Portal(cards, "⚡", "CASCADE & CONTAGION LAB", "Investigate threshold diffusion, SIR waves, overload failure and intervention shocks.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenDynamicsLens(w, ctx, index, m); }); });
            Portal(cards, "R(t)", "RESILIENCE TRIBUNAL", "Compare same-seed baseline and shocked worlds for disruption, loss and recovery.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { RunResilience(w, m); }); });
            Portal(cards, "ESS", "EVOLUTIONARY ECOLOGY", "Study cooperation, defection, mutation, selection pressure and strategy fixation.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenEvolutionaryLens(w, m); }); });
            Portal(cards, "σ≈1", "CRITICALITY CHAMBER", "Measure avalanche families, branching ratio, tail slope and critical slowing proxies.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenRows(w, "CRITICALITY CHAMBER", ComplexSystemsKernel.AnalyzeCriticality(m, 32), "Finite bounded proxies; not a thermodynamic-limit proof"); }); });
            Portal(cards, "∂m/∂θ", "SENSITIVITY MANIFOLD", "Rank local parameter effects and expose brittle emergence claims.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { ComplexSensitivityResult r = ComplexSystemsKernel.AnalyzeSensitivity(m, m.Parameters.Keys, 0.05); OpenRows(w, "SENSITIVITY MANIFOLD", new object[] { r }.Concat(r.Effects.Cast<object>()).Concat(r.Audit.Cast<object>()).ToArray(), "One-at-a-time local effects over the current model fingerprint"); }); });
            Portal(cards, "PERC", "PERCOLATION CRUCIBLE", "Compare random failure against degree-targeted attack and map giant-component collapse.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenPercolation(w, m); }); });
            Portal(cards, "Iμ", "INFORMATION DYNAMICS", "Measure entropy rate, mutual information, predictive structure, complexity and change points.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenInformationDynamics(w, m); }); });
            Portal(cards, "SYNC", "UPDATE-SEMANTICS BIFURCATION", "Expose macroscopic divergence caused solely by synchronous versus asynchronous updating.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { OpenUpdateSemantics(w, m); }); });
            Portal(cards, "PREREG", "EXPERIMENT CAPSULES", "Freeze questions, seed families, metrics, stopping rules, falsifiers and model fingerprints.", delegate { OpenCapsules(w, ctx); });
            Portal(cards, "BASE", "IMMUTABLE BASELINES", "Freeze full population models with lineage and independently recomputable fingerprints.", delegate { OpenBaselines(w, ctx); });
            Portal(cards, "DOSSIER", "EMERGENCE DOSSIERS", "Bind bounded claims to runs, ensembles, sweeps, alternatives, unknowns and dissent.", delegate { OpenDossiers(w, ctx); });
            Portal(cards, "AUDIT", "LABORATORY AUDITOR", "Audit dimensions, references, probabilities, parameter ranges and epistemic boundaries.", delegate { OpenAudit(w, ctx); });
            Portal(cards, "CHAIN", "INTEGRITY LEDGER", "Verify append-only mutation and certificate ancestry.", delegate { OpenLedger(w, ctx); });
            Portal(cards, "x̂|u", "CYBERNETIC METASTRUCTURE", "Return to estimation, control synthesis and bounded digital twins.", delegate { CyberneticDigitalTwinMetastructure.Open(w, ctx); });
            Portal(cards, "ΣSYS", "DYSON ENGINEERING", "Return to architectures, interfaces, hazards, resources and baselines.", delegate { DysonSystemsEngineeringMegastructure.Open(w, ctx); });
            Portal(cards, "WORLD", "UNIVERSAL WORLD KERNEL", "Return to stable object passports, identity graphs, source coordinates and World evidence.", delegate { WorldKernel.Open(w, ctx); });
            Portal(cards, "CIV", "CIVILIZATION LAYER", "Return to institutions, resolutions, knowledge territories, plurality and civil chronology.", delegate { CivilizationLayer.Open(w, ctx); });
            Portal(cards, "⊢4V", "EPISTEMIC LOGIC FOUNDRY", "Return to contradiction-tolerant theories, proof DAGs, abduction and falsification.", delegate { EpistemicLogicFoundry.Open(w, ctx); });
            Portal(cards, "⊨CTL", "AXIOMATIC VERIFICATION", "Return to exact finite-state obligations, invariants, counterexamples and proof certificates.", delegate { AxiomaticVerificationReactor.Open(w, ctx); });
            Portal(cards, "do(X)", "COUNTERFACTUAL STRATEGY", "Return to causal hypotheses, interventions, twin worlds, regret and decision dossiers.", delegate { CounterfactualStrategySuperstructure.Open(w, ctx); });
            Portal(cards, "I(H;Y)", "SCIENTIFIC DISCOVERY", "Return to preregistered measurement designs and empirical calibration boundaries.", delegate { ScientificDiscoveryHyperstructure.Open(w, ctx); });
            Portal(cards, "ORΩ", "OPERATIONS RESEARCH EMPIRE", "Translate an interacting population and its network into explicit service, capacity, placement, staffing and robust-allocation decisions while preserving simulation-only authority.", delegate { OperationsResearchEmpire.Open(w, ctx); });
            Portal(cards, "ECONΩ", "ECONOMIC CIVILIZATION", "Translate an interacting synthetic population into household, firm, production, market, credit, fiscal and distributional sectors while preserving simulation-only authority.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { EconomicCivilization.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "GEOΩ", "SPATIAL WORLD CARTOGRAPHY", "Translate an interacting synthetic population into habitats, territories, proximity networks and movement corridors while preserving simulation-only authority.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { SpatialWorldCartography.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "DISTΩ", "DISTRIBUTED SYSTEMS PLANETARIUM", "Translate an interacting population into message-passing actors, membership diffusion and cascade failures while preserving simulation-only authority.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { DistributedSystemsPlanetarium.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "SECΩ", "ADVERSARIAL SECURITY FORTRESS", "Translate emergent populations and cascades into identities, dependencies, propagation and containment worlds with simulation-only authority.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { AdversarialSecurityFortress.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "DATAΩ", "DATA FOUNDRY", "Project complex-system populations, parameters and retained outcomes into lineage-aware bounded data evidence.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { DataFoundry.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "GENOMEΩ", "SOFTWARE GENOME", "Project emergence-model structure into codebase dependency and change context.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { SoftwareGenomeObservatory.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "DOCΩ", "LIVING DOCUMENT", "Project simulation assumptions, ensemble outcomes and uncertainties into a living research dossier.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { LivingDocumentIntelligenceFactory.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "EXPΩ", "EXPEDITION COMMAND", "Capture the active emergence model as a fingerprinted mission crossing with assumptions, ensembles and uncertainty retained.", delegate { WithModel(w, ctx, delegate(ComplexSystemModel m) { GrandUnifiedExpeditionCommand.OpenFromComplexSystem(w, ctx, index, m); }); });
            Portal(cards, "HADAL", "HADAL DESCENT", "Descend recursively through agents, edges, rules, traces, basins, certificates and ledgers.", delegate { AbyssalKnowledgeEngine.DescendFromExternal(w, ctx, "Complex Systems Laboratory", Store, StorePath(ctx), "$complex-systems", "COMPLEX SYSTEMS LABORATORY"); });
            scroll.Content = cards; root.Children.Add(scroll); w.Content = root; w.Show();
        }

        private static void OpenRegistry(Window owner, DeepSystemsContext ctx, WorldIndex index) { Load(ctx); Window w = W(owner, "YOMI · COMPLEX SYSTEM MODEL REGISTRY", 1240, 820); DockPanel root = Shell("COMPLEX SYSTEM MODEL REGISTRY", CensusLine()); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn("CREATE MODEL", delegate { CreateModel(w, ctx, index); })); tools.Children.Add(Btn("RUN VAULT", delegate { OpenRunVault(w, ctx, "SIMULATION VAULT", false); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); ListBox list = List(); list.ItemsSource = Store.Models.OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).ToList(); list.MouseDoubleClick += delegate { ComplexSystemModel m = list.SelectedItem as ComplexSystemModel; if (m != null) OpenModel(w, ctx, index, m); }; root.Children.Add(list); w.Content = root; w.Show(); }

        private static void OpenModel(Window owner, DeepSystemsContext ctx, WorldIndex index, ComplexSystemModel model)
        {
            Load(ctx); ComplexNetworkMetrics network = ComplexSystemsKernel.AnalyzeNetwork(model); Window w = W(owner, "YOMI · COMPLEX SYSTEM · " + (model.Name ?? model.Id), 1320, 880); DockPanel root = Shell((model.Status ?? "ACTIVE") + " · " + (model.Name ?? "COMPLEX SYSTEM"), (model.Description ?? "") + "\r\nFingerprint " + Short(ComplexSystemsKernel.Fingerprint(model), 24) + " · source " + (model.SourceKind ?? "MANUAL") + ":" + (model.SourceId ?? "∅") + " · " + network.ToString());
            WrapPanel tools = new WrapPanel { Margin = new Thickness(0, 6, 0, 8) }; tools.Children.Add(Btn("RUN", delegate { RunSimulation(w, ctx, model); })); tools.Children.Add(Btn("ENSEMBLE", delegate { RunEnsemble(w, ctx, model); })); tools.Children.Add(Btn("PHASE SWEEP", delegate { RunPhaseSweep(w, ctx, model); })); tools.Children.Add(Btn("RESILIENCE", delegate { RunResilience(w, model); })); tools.Children.Add(Btn("PERCOLATION", delegate { OpenPercolation(w, model); })); tools.Children.Add(Btn("INFORMATION", delegate { OpenInformationDynamics(w, model); })); tools.Children.Add(Btn("UPDATE MODES", delegate { OpenUpdateSemantics(w, model); })); tools.Children.Add(Btn("CONFIGURE", delegate { ConfigureModel(w, ctx, model); })); tools.Children.Add(Btn("ADD AGENT", delegate { AddAgent(w, ctx, model); })); tools.Children.Add(Btn("ADD EDGE", delegate { AddEdge(w, ctx, model); })); tools.Children.Add(Btn("RULES", delegate { OpenRules(w, ctx, index, model); })); tools.Children.Add(Btn("INTERVENTIONS", delegate { OpenInterventions(w, ctx, model); })); tools.Children.Add(Btn("PARAMETERS", delegate { EditParameters(w, ctx, model); })); tools.Children.Add(Btn("PREREGISTER", delegate { CreateCapsule(w, ctx, model); })); tools.Children.Add(Btn("FREEZE BASELINE", delegate { FreezeBaseline(w, ctx, model); })); tools.Children.Add(Btn("CREATE DOSSIER", delegate { CreateDossier(w, ctx, model); })); tools.Children.Add(Btn("OPTIMIZE ECOLOGY", delegate { OperationsResearchEmpire.OpenFromComplexSystem(w, ctx, index, model); })); tools.Children.Add(Btn("FORK", delegate { ForkModel(w, ctx, index, model); })); tools.Children.Add(Btn(Active(model.Status) ? "ARCHIVE" : "RESTORE", delegate { model.Status = Active(model.Status) ? "ARCHIVED" : "ACTIVE"; Touch(model); Save(ctx); AppendLedger(ctx, "MODEL_" + model.Status, model.Id, model.Name, ComplexSystemsKernel.Fingerprint(model), ""); w.Close(); })); tools.Children.Add(Btn("HADAL DESCENT", delegate { AbyssalKnowledgeEngine.DescendFromExternal(w, ctx, model.Name, model, StorePath(ctx), "$models:" + model.Id, "COMPLEX SYSTEMS › MODEL"); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools);
            Grid body = new Grid(); body.ColumnDefinitions.Add(new ColumnDefinition()); body.ColumnDefinitions.Add(new ColumnDefinition()); body.ColumnDefinitions.Add(new ColumnDefinition()); ListBox agents = List(), edges = List(), artifacts = List(); agents.ItemsSource = (model.Agents ?? new List<ComplexAgentSpec>()).Cast<object>().Concat(new object[] { "Generated population remainder: " + Math.Max(0, model.PopulationSize - (model.Agents ?? new List<ComplexAgentSpec>()).Count).ToString(CultureInfo.InvariantCulture) }).ToList(); edges.ItemsSource = (model.Edges ?? new List<ComplexInteractionEdge>()).Count == 0 ? new List<object> { "Procedural topology · " + model.TopologyKind + " · mean degree " + model.MeanDegree } : model.Edges.Cast<object>().ToList(); artifacts.ItemsSource = Store.Runs.Where(x => Eq(x.ModelId, model.Id)).Cast<object>().Concat(Store.Ensembles.Where(x => Eq(x.ModelId, model.Id)).Cast<object>()).Concat(Store.Sweeps.Where(x => Eq(x.ModelId, model.Id)).Cast<object>()).Concat(Store.Baselines.Where(x => Eq(x.ModelId, model.Id)).Cast<object>()).Concat(Store.Capsules.Where(x => Eq(x.ModelId, model.Id)).Cast<object>()).ToList(); Grid.SetColumn(agents, 0); Grid.SetColumn(edges, 1); Grid.SetColumn(artifacts, 2); body.Children.Add(agents); body.Children.Add(edges); body.Children.Add(artifacts); root.Children.Add(body); w.Content = root; w.Show();
        }

        private static void CreateModel(Window owner, DeepSystemsContext ctx, WorldIndex index)
        {
            string name = Prompt(owner, "POPULATION FORGE", "Model name", "Emergent interaction world"); if (String.IsNullOrWhiteSpace(name)) return; string kind = Prompt(owner, "POPULATION KIND", "PEOPLE, MACHINES, COMPANIES, ANIMALS, PROTOCOLS, ACTORS…", "ACTORS"); if (kind == null) return; int population = Integer(Prompt(owner, "POPULATION SIZE", "2..4096", "256"), 256, 2, 4096); string topology = Prompt(owner, "TOPOLOGY", "RING, SMALL_WORLD, ERDOS_RENYI, SCALE_FREE, COMMUNITY, COMPLETE or EXPLICIT", "SMALL_WORLD"); if (topology == null) return; string dynamics = Prompt(owner, "DYNAMICS", "THRESHOLD_CONTAGION, SIR, BOUNDED_CONFIDENCE, VOTER, ISING, EVOLUTIONARY_GAME, CASCADE_FAILURE, COUPLED_MAP, CELLULAR_AUTOMATON or GENERIC_RULES", "THRESHOLD_CONTAGION"); if (dynamics == null) return; ComplexSystemModel m = StarterModel(name.Trim(), "Operator-authored heterogeneous population and interaction world."); m.Id = Id("complex-model"); m.PopulationKind = Short(kind.Trim().ToUpperInvariant(), 80); m.PopulationSize = population; m.TopologyKind = Short(topology.Trim().ToUpperInvariant(), 80); m.DynamicsKind = Short(dynamics.Trim().ToUpperInvariant(), 80); m.Seed = Integer(Prompt(owner, "DETERMINISTIC SEED", "Signed integer seed", "1337"), 1337, Int32.MinValue, Int32.MaxValue); m.Steps = Integer(Prompt(owner, "HORIZON", "1..8192 update steps", "256"), 256, 1, 8192); m.CreatedUtc = Now(); m.UpdatedUtc = m.CreatedUtc; Store.Models.Insert(0, m); Save(ctx); AppendLedger(ctx, "MODEL_CREATED", m.Id, m.Name, ComplexSystemsKernel.Fingerprint(m), ""); OpenModel(owner, ctx, index, m);
        }

        private static ComplexSystemModel StarterModel(string name, string description)
        {
            ComplexSystemModel m = new ComplexSystemModel { Name = name, Description = description, Status = "ACTIVE", PopulationSize = 256, TopologyKind = "SMALL_WORLD", DynamicsKind = "THRESHOLD_CONTAGION", UpdateMode = "SYNCHRONOUS", Seed = 1337, Steps = 256, MeanDegree = 8, LinkProbability = 0.04, RewireProbability = 0.08, CommunityCount = 4 }; m.Parameters["initial_active_fraction"] = 0.03; m.Parameters["threshold"] = 0.35; m.Parameters["susceptibility"] = 1; m.Parameters["transmission"] = 0.18; m.Parameters["recovery"] = 0.02; m.Parameters["noise"] = 0.001; m.Parameters["coupling"] = 0.1; m.Parameters["temperature"] = 1; m.Parameters["map_rate"] = 3.7; m.Parameters["capacity"] = 1; m.Parameters["initial_load"] = 0.4; m.Parameters["redistribution"] = 1; m.Parameters["performance_target_activity"] = 0; m.Parameters["payoff_reward"] = 1; m.Parameters["payoff_sucker"] = 0; m.Parameters["payoff_temptation"] = 1.5; m.Parameters["payoff_punishment"] = 0.1; m.Assumptions.Add("Agents, topology, parameters and update rules are declarations for synthetic reasoning, not measurements of a real population."); m.Assumptions.Add("Deterministic seed families support reproducibility but do not become probability distributions without calibration."); return m;
        }

        private static void RunSimulation(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { ComplexSimulationResult result = ComplexSystemsKernel.Simulate(model, model.Seed); string created = Now(), certificate = HashText(ComplexSystemsKernel.Fingerprint(model) + "|" + created + "|" + Json.Serialize(result)); ComplexRunRecord record = new ComplexRunRecord { Id = Id("complex-run"), ModelId = model.Id, CreatedUtc = created, ModelFingerprint = ComplexSystemsKernel.Fingerprint(model), CertificateHash = certificate, Label = "SEEDED EVOLUTION", Result = result }; Store.Runs.Insert(0, record); Save(ctx); AppendLedger(ctx, "SIMULATION_CERTIFIED", record.Id, model.Name, record.ModelFingerprint, certificate); OpenRows(owner, "SEEDED EVOLUTION", new object[] { record, result.Network }.Concat(result.Trace.Cast<object>()).Concat(result.TerminalSample.Cast<object>()).Concat(result.Audit.Cast<object>()).ToArray(), "Certificate " + certificate + " · conditional simulation, not observation or forecast"); }
        private static void RunEnsemble(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { int n = Integer(Prompt(owner, "ENSEMBLE SIZE", "1..512 deterministic seed worlds", "64"), 64, 1, 512); int offset = Integer(Prompt(owner, "SEED OFFSET", "Offset added to the model seed family", "0"), 0, Int32.MinValue, Int32.MaxValue); ComplexEnsembleResult result = ComplexSystemsKernel.RunEnsemble(model, n, offset); string created = Now(), certificate = HashText(ComplexSystemsKernel.Fingerprint(model) + "|" + created + "|" + Json.Serialize(result)); ComplexEnsembleRecord record = new ComplexEnsembleRecord { Id = Id("complex-ensemble"), ModelId = model.Id, CreatedUtc = created, ModelFingerprint = ComplexSystemsKernel.Fingerprint(model), CertificateHash = certificate, Result = result }; Store.Ensembles.Insert(0, record); Save(ctx); AppendLedger(ctx, "ENSEMBLE_CERTIFIED", record.Id, model.Name + " · n=" + n, record.ModelFingerprint, certificate); OpenRows(owner, "ENSEMBLE OBSERVATORY", new object[] { record, result }.Concat(result.TerminalBasins.OrderByDescending(x => x.Value).Select(x => (object)(x.Key + "   ·   " + x.Value + " worlds"))).Concat(result.Audit.Cast<object>()).ToArray(), "Certificate " + certificate + " · declared seed family only"); }
        private static void RunPhaseSweep(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { string key = Prompt(owner, "PHASE PARAMETER", "Parameter key to sweep", model.Parameters.Keys.FirstOrDefault() ?? "coupling"); if (String.IsNullOrWhiteSpace(key)) return; double current = Number(model.Parameters.ContainsKey(key) ? model.Parameters[key].ToString("R", CultureInfo.InvariantCulture) : "0.5", 0.5); double minimum = Number(Prompt(owner, "SWEEP MINIMUM", "Inclusive parameter minimum", (current * 0.25).ToString("R", CultureInfo.InvariantCulture)), current * 0.25), maximum = Number(Prompt(owner, "SWEEP MAXIMUM", "Inclusive parameter maximum", (Math.Abs(current) < 1e-12 ? 1 : current * 2).ToString("R", CultureInfo.InvariantCulture)), Math.Abs(current) < 1e-12 ? 1 : current * 2); int points = Integer(Prompt(owner, "SWEEP RESOLUTION", "3..129 parameter points", "17"), 17, 3, 129), replicates = Integer(Prompt(owner, "REPLICATES PER POINT", "2..128 seed worlds", "16"), 16, 2, 128); ComplexPhaseSweepResult result = ComplexSystemsKernel.SweepParameter(model, key.Trim(), minimum, maximum, points, replicates); string created = Now(), certificate = HashText(ComplexSystemsKernel.Fingerprint(model) + "|" + created + "|" + Json.Serialize(result)); ComplexSweepRecord record = new ComplexSweepRecord { Id = Id("complex-sweep"), ModelId = model.Id, CreatedUtc = created, ModelFingerprint = ComplexSystemsKernel.Fingerprint(model), CertificateHash = certificate, Result = result }; Store.Sweeps.Insert(0, record); Save(ctx); AppendLedger(ctx, "PHASE_SWEEP_CERTIFIED", record.Id, key + " · " + points + "x" + replicates, record.ModelFingerprint, certificate); OpenRows(owner, "PHASE TRANSITION ATLAS", new object[] { record, result }.Concat(result.Points.Cast<object>()).Concat(result.Audit.Cast<object>()).ToArray(), "Finite-size critical candidate · certificate " + certificate); }
        private static void RunResilience(Window owner, ComplexSystemModel model) { int step = Integer(Prompt(owner, "SHOCK STEP", "Update step for the synthetic perturbation", Math.Max(1, model.Steps / 3).ToString(CultureInfo.InvariantCulture)), Math.Max(1, model.Steps / 3), 1, model.Steps); double fraction = Number(Prompt(owner, "SHOCK FRACTION", "Fraction of eligible agents, 0..1", "0.10"), 0.1), magnitude = Number(Prompt(owner, "SHOCK MAGNITUDE", "Signed value shock", "-0.75"), -0.75); ComplexResilienceResult result = ComplexSystemsKernel.AnalyzeResilience(model, step, fraction, magnitude); OpenRows(owner, "RESILIENCE TRIBUNAL", new object[] { result }.Concat(result.Divergence.Select((x, i) => (object)("t=" + i.ToString(CultureInfo.InvariantCulture).PadLeft(6) + "   ·   divergence " + x.ToString("0.000000", CultureInfo.InvariantCulture)))).Concat(result.Audit.Cast<object>()).ToArray(), "Same-seed counterfactual baseline versus one explicit synthetic shock"); }
        private static void OpenPercolation(Window owner, ComplexSystemModel model) { ComplexPercolationResult result = ComplexSystemsKernel.AnalyzePercolation(model, 21, 16); OpenRows(owner, "PERCOLATION CRUCIBLE", new object[] { result }.Concat(result.Points.Cast<object>()).Concat(result.Audit.Cast<object>()).ToArray(), "Random removal ensemble versus static initial-degree attack · synthetic topology only"); }
        private static void OpenInformationDynamics(Window owner, ComplexSystemModel model) { ComplexInformationDynamicsResult result = ComplexSystemsKernel.AnalyzeInformationDynamics(model, model.Seed); OpenRows(owner, "INFORMATION DYNAMICS", new object[] { result, "early/late variance   ·   " + result.EarlyVariance.ToString("0.######", CultureInfo.InvariantCulture) + " / " + result.LateVariance.ToString("0.######", CultureInfo.InvariantCulture), "early/late AC₁   ·   " + result.EarlyAutocorrelation.ToString("0.######", CultureInfo.InvariantCulture) + " / " + result.LateAutocorrelation.ToString("0.######", CultureInfo.InvariantCulture), "change strength   ·   " + result.ChangePointStrength.ToString("0.######", CultureInfo.InvariantCulture), "predictive efficiency   ·   " + result.PredictiveEfficiency.ToString("0.######", CultureInfo.InvariantCulture) }.Concat(result.Audit.Cast<object>()).ToArray(), "Information-theoretic observables over the declared aggregate activity trace"); }
        private static void OpenUpdateSemantics(Window owner, ComplexSystemModel model) { ComplexUpdateSemanticsResult result = ComplexSystemsKernel.CompareUpdateSemantics(model, model.Seed); List<object> rows = new List<object> { result, result.Synchronous, result.Asynchronous, "certificate   ·   " + (result.CertificateHash ?? "∅") }; rows.AddRange(result.Audit.Cast<object>()); OpenRows(owner, "UPDATE-SEMANTICS BIFURCATION", rows, "Same model and seed; only event ordering changes"); }

        private static void ConfigureModel(Window owner, DeepSystemsContext ctx, ComplexSystemModel model)
        {
            string name = Prompt(owner, "MODEL CONFIGURATION", "Model name", model.Name); if (String.IsNullOrWhiteSpace(name)) return;
            string description = PromptLarge(owner, "MODEL DESCRIPTION", "Declared scope, mechanism and intended use", model.Description); if (description == null) return;
            string populationKind = Prompt(owner, "POPULATION KIND", "PEOPLE, MACHINES, COMPANIES, ANIMALS, PROTOCOLS, ACTORS…", model.PopulationKind ?? "ACTORS"); if (populationKind == null) return;
            object topologyChoice = ChooseObject(owner, "TOPOLOGY", "Select the procedural or explicit interaction topology", CurrentFirst(model.TopologyKind, new[] { "RING", "LATTICE", "SMALL_WORLD", "ERDOS_RENYI", "SCALE_FREE", "COMMUNITY", "COMPLETE", "EXPLICIT" })); if (topologyChoice == null) return;
            object dynamicsChoice = ChooseObject(owner, "DYNAMICS", "Select the native evolution law", CurrentFirst(model.DynamicsKind, new[] { "THRESHOLD_CONTAGION", "SIR", "BOUNDED_CONFIDENCE", "VOTER", "ISING", "EVOLUTIONARY_GAME", "CASCADE_FAILURE", "COUPLED_MAP", "CELLULAR_AUTOMATON", "GENERIC_RULES" })); if (dynamicsChoice == null) return;
            object updateChoice = ChooseObject(owner, "UPDATE SEMANTICS", "Select how agent transitions are ordered", CurrentFirst(model.UpdateMode, new[] { "SYNCHRONOUS", "ASYNCHRONOUS" })); if (updateChoice == null) return;
            string populationRaw = Prompt(owner, "POPULATION SIZE", "2..4096 agents", model.PopulationSize.ToString(CultureInfo.InvariantCulture)); if (populationRaw == null) return; int population = Integer(populationRaw, model.PopulationSize, 2, 4096);
            string stepsRaw = Prompt(owner, "HORIZON", "1..8192 update steps", model.Steps.ToString(CultureInfo.InvariantCulture)); if (stepsRaw == null) return; int steps = Integer(stepsRaw, model.Steps, 1, 8192);
            string degreeRaw = Prompt(owner, "MEAN DEGREE", "0..population-1 procedural neighbor target", model.MeanDegree.ToString(CultureInfo.InvariantCulture)); if (degreeRaw == null) return; int degree = Integer(degreeRaw, model.MeanDegree, 0, population - 1);
            string linkRaw = Prompt(owner, "LINK PROBABILITY", "0..1 random-link probability", model.LinkProbability.ToString("R", CultureInfo.InvariantCulture)); if (linkRaw == null) return; double linkProbability = Math.Max(0, Math.Min(1, Number(linkRaw, model.LinkProbability)));
            string rewireRaw = Prompt(owner, "REWIRE PROBABILITY", "0..1 small-world rewiring probability", model.RewireProbability.ToString("R", CultureInfo.InvariantCulture)); if (rewireRaw == null) return; double rewireProbability = Math.Max(0, Math.Min(1, Number(rewireRaw, model.RewireProbability)));
            string communityRaw = Prompt(owner, "COMMUNITIES", "1..population community count", model.CommunityCount.ToString(CultureInfo.InvariantCulture)); if (communityRaw == null) return; int communities = Integer(communityRaw, model.CommunityCount, 1, population);
            string seedRaw = Prompt(owner, "DETERMINISTIC SEED", "Signed 32-bit integer seed", model.Seed.ToString(CultureInfo.InvariantCulture)); if (seedRaw == null) return; int seed = Integer(seedRaw, model.Seed, Int32.MinValue, Int32.MaxValue);
            model.Name = Short(name.Trim(), 512); model.Description = Short(description.Trim(), MaxLongText); model.PopulationKind = Short(populationKind.Trim().ToUpperInvariant(), 80); model.TopologyKind = topologyChoice.ToString(); model.DynamicsKind = dynamicsChoice.ToString(); model.UpdateMode = updateChoice.ToString(); model.PopulationSize = population; model.Steps = steps; model.MeanDegree = degree; model.LinkProbability = linkProbability; model.RewireProbability = rewireProbability; model.CommunityCount = communities; model.Seed = seed; Touch(model); Save(ctx); string fingerprint = ComplexSystemsKernel.Fingerprint(model); AppendLedger(ctx, "MODEL_RECONFIGURED", model.Id, model.TopologyKind + " · " + model.DynamicsKind + " · " + model.UpdateMode, fingerprint, ""); MessageBox.Show(owner, "Configuration committed.\n\nFingerprint " + fingerprint, "YOMI · MODEL CONFIGURATION", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        private static void OpenDynamicsLens(Window owner, DeepSystemsContext ctx, WorldIndex index, ComplexSystemModel model) { Window w = W(owner, "YOMI · CASCADE & CONTAGION LAB", 1120, 760); DockPanel root = Shell("CASCADE & CONTAGION LAB", model.Name + " · current dynamics " + model.DynamicsKind); WrapPanel tools = new WrapPanel(); foreach (string dynamics in new[] { "THRESHOLD_CONTAGION", "SIR", "CASCADE_FAILURE", "VOTER", "ISING", "CELLULAR_AUTOMATON" }) { string chosen = dynamics; tools.Children.Add(Btn(chosen, delegate { model.DynamicsKind = chosen; Touch(model); Save(ctx); AppendLedger(ctx, "DYNAMICS_SELECTED", model.Id, chosen, ComplexSystemsKernel.Fingerprint(model), ""); RunSimulation(w, ctx, model); })); } root.Children.Add(tools); w.Content = root; w.Show(); }
        private static void OpenEvolutionaryLens(Window owner, ComplexSystemModel model) { string original = model.DynamicsKind; model.DynamicsKind = "EVOLUTIONARY_GAME"; try { ComplexEnsembleResult result = ComplexSystemsKernel.RunEnsemble(model, 64, 0); OpenRows(owner, "EVOLUTIONARY ECOLOGY", new object[] { result }.Concat(result.TerminalBasins.Select(x => (object)(x.Key + "   ·   " + x.Value + " seed worlds"))).Concat(result.Audit.Cast<object>()).ToArray(), "Temporary evolutionary-game lens; model dynamics remain " + original); } finally { model.DynamicsKind = original; } }
        private static void OpenRunVault(Window owner, DeepSystemsContext ctx, string title, bool attractorsOnly) { Load(ctx); IEnumerable<object> rows = Store.Runs.Cast<object>().Concat(Store.Ensembles.Cast<object>()).Concat(Store.Sweeps.Cast<object>()); if (attractorsOnly) rows = Store.Runs.Where(x => x.Result != null && x.Result.AttractorDetected).Cast<object>().Concat(Store.Ensembles.Where(x => x.Result != null && x.Result.TerminalBasins.Count > 0).Cast<object>()); OpenRows(owner, title, rows.ToArray(), attractorsOnly ? "Repeated aggregate microstate hashes and ensemble terminal-basin families" : "Fingerprint-bound certified laboratory artifacts"); }

        private static void AddAgent(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { string name = Prompt(owner, "ADD EXPLICIT AGENT", "Agent label", "Actor " + (model.Agents.Count + 1)); if (String.IsNullOrWhiteSpace(name)) return; string archetype = Prompt(owner, "ARCHETYPE", "Archetype / population role", "DEFAULT"); if (archetype == null) return; ComplexAgentSpec a = new ComplexAgentSpec { Id = Id("agent"), Label = name.Trim(), Kind = model.PopulationKind, Archetype = Short(archetype.Trim(), 256), InitialMode = Prompt(owner, "INITIAL MODE", "0, 1, 2 or a named state", "0") ?? "0", InitialValue = Number(Prompt(owner, "INITIAL VALUE", "Finite scalar", "0"), 0), Threshold = Number(Prompt(owner, "THRESHOLD", "0..1", "0.35"), 0.35), Susceptibility = Number(Prompt(owner, "SUSCEPTIBILITY", "Nonnegative multiplier", "1"), 1), Capacity = Math.Max(0.001, Number(Prompt(owner, "CAPACITY", "Positive capacity", "1"), 1)) }; model.Agents.Add(a); model.PopulationSize = Math.Max(model.PopulationSize, model.Agents.Count); Touch(model); Save(ctx); AppendLedger(ctx, "AGENT_ADDED", a.Id, model.Id + " · " + a.Label, ComplexSystemsKernel.Fingerprint(model), ""); }
        private static void AddEdge(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { if (model.Agents.Count < 2) { MessageBox.Show(owner, "Create at least two explicit agents before adding an explicit edge.", "YOMI · EDGE FORGE", MessageBoxButton.OK, MessageBoxImage.Information); return; } ComplexAgentSpec from = ChooseObject(owner, "EDGE SOURCE", "Select source agent", model.Agents.Cast<object>().ToList()) as ComplexAgentSpec; if (from == null) return; ComplexAgentSpec to = ChooseObject(owner, "EDGE TARGET", "Select target agent", model.Agents.Where(x => !Eq(x.Id, from.Id)).Cast<object>().ToList()) as ComplexAgentSpec; if (to == null) return; ComplexInteractionEdge e = new ComplexInteractionEdge { Id = Id("edge"), SourceId = from.Id, TargetId = to.Id, Kind = Prompt(owner, "EDGE KIND", "Interaction type", "INTERACTION") ?? "INTERACTION", Weight = Number(Prompt(owner, "EDGE WEIGHT", "Signed finite weight", "1"), 1), Bidirectional = MessageBox.Show(owner, "Make this interaction bidirectional?", "YOMI · EDGE FORGE", MessageBoxButton.YesNo, MessageBoxImage.Question) == MessageBoxResult.Yes }; model.TopologyKind = "EXPLICIT"; model.Edges.Add(e); Touch(model); Save(ctx); AppendLedger(ctx, "EDGE_ADDED", e.Id, e.SourceId + " → " + e.TargetId, ComplexSystemsKernel.Fingerprint(model), ""); }
        private static void OpenRules(Window owner, DeepSystemsContext ctx, WorldIndex index, ComplexSystemModel model) { Window w = W(owner, "YOMI · RULE ECOLOGY · " + model.Name, 1100, 760); DockPanel root = Shell("RULE ECOLOGY", model.DynamicsKind + " · generic rules execute after the native dynamics step"); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn("ADD TRANSITION RULE", delegate { string name = Prompt(w, "RULE NAME", "Rule label", "Neighbor threshold transition"); if (String.IsNullOrWhiteSpace(name)) return; ComplexRuleSpec rule = new ComplexRuleSpec { Id = Id("rule"), Name = name, Kind = "STATE_TRANSITION", StateFrom = Prompt(w, "FROM STATE", "State or *", "0") ?? "0", StateTo = Prompt(w, "TO STATE", "Target state", "1") ?? "1", NeighborState = "1", MinimumNeighborFraction = Number(Prompt(w, "NEIGHBOR THRESHOLD", "0..1", "0.5"), 0.5), Probability = Number(Prompt(w, "PROBABILITY", "0..1", "1"), 1), Enabled = true }; model.Rules.Add(rule); Touch(model); Save(ctx); AppendLedger(ctx, "RULE_ADDED", rule.Id, model.Id + " · " + rule.Name, ComplexSystemsKernel.Fingerprint(model), ""); w.Close(); OpenRules(owner, ctx, index, model); })); tools.Children.Add(Btn("ADD VALUE RULE", delegate { string name = Prompt(w, "RULE NAME", "Rule label", "Local adaptation"); if (String.IsNullOrWhiteSpace(name)) return; ComplexRuleSpec rule = new ComplexRuleSpec { Id = Id("rule"), Name = name, Kind = "VALUE_DELTA", StateFrom = "*", ScalarDelta = Number(Prompt(w, "SCALAR DELTA", "Per-step value delta", "0.01"), 0.01), Coupling = Number(Prompt(w, "NEIGHBOR COUPLING", "Active-neighbor coupling", "0.10"), 0.1), Probability = 1, Enabled = true }; model.Rules.Add(rule); Touch(model); Save(ctx); AppendLedger(ctx, "RULE_ADDED", rule.Id, model.Id + " · " + rule.Name, ComplexSystemsKernel.Fingerprint(model), ""); w.Close(); OpenRules(owner, ctx, index, model); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); ListBox list = List(); list.ItemsSource = model.Rules.ToList(); root.Children.Add(list); w.Content = root; w.Show(); }
        private static void OpenInterventions(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { Window w = W(owner, "YOMI · INTERVENTION CHRONICLE · " + model.Name, 1100, 760); DockPanel root = Shell("INTERVENTION CHRONICLE", "Explicit synthetic shocks only; no scheduler or real-world action authority"); WrapPanel tools = new WrapPanel(); tools.Children.Add(Btn("ADD INTERVENTION", delegate { string name = Prompt(w, "INTERVENTION NAME", "Label", "Bounded perturbation"); if (String.IsNullOrWhiteSpace(name)) return; ComplexInterventionSpec x = new ComplexInterventionSpec { Id = Id("intervention"), Name = name, Step = Integer(Prompt(w, "STEP", "0.." + model.Steps, Math.Max(1, model.Steps / 3).ToString(CultureInfo.InvariantCulture)), Math.Max(1, model.Steps / 3), 0, model.Steps), Kind = (Prompt(w, "KIND", "SEED_STATE, SHOCK_VALUE, ADD_LOAD, REMOVE_NODE, CAPACITY_MULTIPLIER", "SHOCK_VALUE") ?? "SHOCK_VALUE").ToUpperInvariant(), TargetKind = (Prompt(w, "TARGET", "ALL or archetype", "ALL") ?? "ALL").ToUpperInvariant(), TargetValue = Prompt(w, "TARGET VALUE", "State value or archetype", "1") ?? "1", Magnitude = Number(Prompt(w, "MAGNITUDE", "Signed finite magnitude", "-0.5"), -0.5), Fraction = Number(Prompt(w, "FRACTION", "0..1", "0.10"), 0.1), Duration = 1, Enabled = true }; model.Interventions.Add(x); Touch(model); Save(ctx); AppendLedger(ctx, "INTERVENTION_ADDED", x.Id, model.Id + " · " + x.Name, ComplexSystemsKernel.Fingerprint(model), ""); w.Close(); OpenInterventions(owner, ctx, model); })); DockPanel.SetDock(tools, Dock.Top); root.Children.Add(tools); ListBox list = List(); list.ItemsSource = model.Interventions.ToList(); root.Children.Add(list); w.Content = root; w.Show(); }
        private static void EditParameters(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { string initial = String.Join(Environment.NewLine, model.Parameters.OrderBy(x => x.Key).Select(x => x.Key + "=" + x.Value.ToString("R", CultureInfo.InvariantCulture)).ToArray()); string raw = PromptLarge(owner, "PARAMETER MANIFOLD", "One key=value declaration per line", initial); if (raw == null) return; Dictionary<string, double> parsed = Pairs(raw); if (parsed.Count == 0) return; model.Parameters = parsed; Touch(model); Save(ctx); AppendLedger(ctx, "PARAMETERS_REPLACED", model.Id, parsed.Count + " declared parameters", ComplexSystemsKernel.Fingerprint(model), ""); }

        private static void CreateCapsule(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { string title = Prompt(owner, "PREREGISTER EXPERIMENT CAPSULE", "Capsule title", "Emergence test · " + model.Name); if (String.IsNullOrWhiteSpace(title)) return; string question = PromptLarge(owner, "RESEARCH QUESTION", "Question to freeze before running the declared ensemble", "Under this exact model fingerprint, does macroscopic order emerge robustly across the declared deterministic seed family?"); if (question == null) return; ComplexExperimentCapsule c = new ComplexExperimentCapsule { Id = Id("complex-capsule"), ModelId = model.Id, Title = title.Trim(), Question = question.Trim(), FrozenUtc = Now(), ModelFingerprint = ComplexSystemsKernel.Fingerprint(model), PlannedReplicates = Integer(Prompt(owner, "PLANNED REPLICATES", "Fixed deterministic seed count", "64"), 64, 1, 512), SeedOffset = Integer(Prompt(owner, "SEED OFFSET", "Predeclared offset", "0"), 0, Int32.MinValue, Int32.MaxValue), PrimaryMetric = Prompt(owner, "PRIMARY METRIC", "Exact declared metric", "terminal_order_parameter") ?? "terminal_order_parameter", NullExpectation = PromptLarge(owner, "NULL EXPECTATION", "What result would count against the proposed emergence claim?", "Order remains near the finite-size baseline and no stable basin dominates the seed family."), FrozenParameters = new Dictionary<string, double>(model.Parameters, StringComparer.OrdinalIgnoreCase), Assumptions = new List<string>(model.Assumptions ?? new List<string>()), EvidenceNodeIds = new List<string>(model.EvidenceNodeIds ?? new List<string>()) }; c.CertificateHash = HashText(Json.Serialize(c) + "|" + c.ModelFingerprint); Store.Capsules.Insert(0, c); Save(ctx); AppendLedger(ctx, "CAPSULE_PREREGISTERED", c.Id, c.Title, c.ModelFingerprint, c.CertificateHash); OpenRows(owner, "EXPERIMENT CAPSULE", c, c.AuthorityBoundary); }
        private static void OpenCapsules(Window owner, DeepSystemsContext ctx) { Load(ctx); Window w = W(owner, "YOMI · EXPERIMENT CAPSULE VAULT", 1200, 800); DockPanel root = Shell("EXPERIMENT CAPSULE VAULT", "Immutable question, seed-family, metric and stopping declarations bound to exact model fingerprints"); ListBox list = List(); list.ItemsSource = Store.Capsules.OrderByDescending(x => x.FrozenUtc).ToList(); root.Children.Add(list); w.Content = root; w.Show(); }
        private static void FreezeBaseline(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { string name = Prompt(owner, "FREEZE COMPLEX-SYSTEM BASELINE", "Immutable baseline name", model.Name + " · baseline " + Now()); if (String.IsNullOrWhiteSpace(name)) return; string reason = PromptLarge(owner, "BASELINE RATIONALE", "Why this exact population model must remain recoverable", "Preserve a reproducible reference before further topology, rule or parameter evolution."); if (reason == null) return; string snapshot = Json.Serialize(model), modelFingerprint = ComplexSystemsKernel.Fingerprint(model); ComplexModelBaseline parent = Store.Baselines.FirstOrDefault(x => Eq(x.ModelId, model.Id)); ComplexModelBaseline b = new ComplexModelBaseline { Id = Id("complex-baseline"), ModelId = model.Id, ParentBaselineId = parent == null ? null : parent.Id, Name = name.Trim(), Status = "FROZEN", FrozenUtc = Now(), Reason = reason.Trim(), ModelFingerprint = modelFingerprint, SnapshotJson = snapshot }; b.BaselineFingerprint = BaselineFingerprint(b); Store.Baselines.Insert(0, b); Save(ctx); AppendLedger(ctx, "BASELINE_FROZEN", b.Id, b.Name, modelFingerprint, b.BaselineFingerprint); OpenRows(owner, "IMMUTABLE BASELINE", b, "Recomputed " + BaselineFingerprint(b)); }
        private static string BaselineFingerprint(ComplexModelBaseline b) { return HashText((b.Id ?? "") + "|" + (b.ModelId ?? "") + "|" + (b.ParentBaselineId ?? "") + "|" + (b.Name ?? "") + "|" + (b.FrozenUtc ?? "") + "|" + (b.Reason ?? "") + "|" + (b.ModelFingerprint ?? "") + "|" + (b.SnapshotJson ?? "")); }
        private static void OpenBaselines(Window owner, DeepSystemsContext ctx) { Load(ctx); OpenRows(owner, "IMMUTABLE BASELINE VAULT", Store.Baselines.Cast<object>().Concat(Store.Baselines.Select(x => (object)(x.Id + "   ·   " + (Eq(x.BaselineFingerprint, BaselineFingerprint(x)) ? "VERIFIED" : "FINGERPRINT MISMATCH"))).ToArray()).ToArray(), "Full model snapshots with lineage and recomputable SHA-256 identities"); }
        private static void CreateDossier(Window owner, DeepSystemsContext ctx, ComplexSystemModel model) { string title = Prompt(owner, "CREATE EMERGENCE DOSSIER", "Dossier title", "Bounded emergence claim · " + model.Name); if (String.IsNullOrWhiteSpace(title)) return; string claim = PromptLarge(owner, "BOUNDED CLAIM", "State only what the current declared model artifacts support", "Under the declared topology, rules, parameters and seed family, the simulated population exhibits a reproducible macroscopic pattern."); if (claim == null) return; ComplexRunRecord run = Store.Runs.FirstOrDefault(x => Eq(x.ModelId, model.Id) && Eq(x.ModelFingerprint, ComplexSystemsKernel.Fingerprint(model))); ComplexEnsembleRecord ensemble = Store.Ensembles.FirstOrDefault(x => Eq(x.ModelId, model.Id) && Eq(x.ModelFingerprint, ComplexSystemsKernel.Fingerprint(model))); ComplexSweepRecord sweep = Store.Sweeps.FirstOrDefault(x => Eq(x.ModelId, model.Id) && Eq(x.ModelFingerprint, ComplexSystemsKernel.Fingerprint(model))); ComplexModelBaseline baseline = Store.Baselines.FirstOrDefault(x => Eq(x.ModelId, model.Id) && Eq(x.ModelFingerprint, ComplexSystemsKernel.Fingerprint(model))); ComplexExperimentCapsule capsule = Store.Capsules.FirstOrDefault(x => Eq(x.ModelId, model.Id) && Eq(x.ModelFingerprint, ComplexSystemsKernel.Fingerprint(model))); ComplexScenarioDossier d = new ComplexScenarioDossier { Id = Id("complex-dossier"), ModelId = model.Id, RunId = run == null ? null : run.Id, EnsembleId = ensemble == null ? null : ensemble.Id, SweepId = sweep == null ? null : sweep.Id, BaselineId = baseline == null ? null : baseline.Id, CapsuleId = capsule == null ? null : capsule.Id, Title = title.Trim(), CreatedUtc = Now(), UpdatedUtc = Now(), ModelFingerprint = ComplexSystemsKernel.Fingerprint(model), BoundedClaim = claim.Trim(), EvidenceNodeIds = new List<string>(model.EvidenceNodeIds ?? new List<string>()) }; d.Unknowns.Add("External validity and calibration remain unresolved unless independently evidenced."); if (ensemble == null) d.Unknowns.Add("No matching ensemble is attached."); if (sweep == null) d.Unknowns.Add("No matching phase sweep is attached."); if (baseline == null) d.Unknowns.Add("No immutable matching baseline is attached."); if (capsule == null) d.Unknowns.Add("No preregistered experiment capsule is attached."); d.Dissent.Add("Absence of recorded dissent is not consensus and must not strengthen the bounded claim."); Store.Dossiers.Insert(0, d); Save(ctx); AppendLedger(ctx, "DOSSIER_CREATED", d.Id, d.Title, d.ModelFingerprint, ""); OpenRows(owner, "EMERGENCE DOSSIER", d, d.AuthorityBoundary); }
        private static void OpenDossiers(Window owner, DeepSystemsContext ctx) { Load(ctx); OpenRows(owner, "EMERGENCE DOSSIER VAULT", Store.Dossiers.ToArray(), "Claims remain attached to exact model fingerprints, alternatives, unknowns and dissent"); }

        private static void ForkModel(Window owner, DeepSystemsContext ctx, WorldIndex index, ComplexSystemModel source) { string name = Prompt(owner, "FORK COMPLEX SYSTEM", "Child model name", source.Name + " · branch"); if (String.IsNullOrWhiteSpace(name)) return; ComplexSystemModel child = Json.Deserialize<ComplexSystemModel>(Json.Serialize(source)); child.Id = Id("complex-model"); child.ParentModelId = source.Id; child.Name = name.Trim(); child.SourceKind = "MODEL_FORK"; child.SourceId = source.Id; child.SourceFingerprint = ComplexSystemsKernel.Fingerprint(source); child.Status = "ACTIVE"; child.Revision = Math.Max(1, source.Revision) + 1; child.CreatedUtc = Now(); child.UpdatedUtc = child.CreatedUtc; Store.Models.Insert(0, child); Save(ctx); AppendLedger(ctx, "MODEL_FORKED", child.Id, "parent " + source.Id, ComplexSystemsKernel.Fingerprint(child), ""); OpenModel(owner, ctx, index, child); }
        private static void OpenAudit(Window owner, DeepSystemsContext ctx) { Load(ctx); List<object> rows = new List<object>(); foreach (ComplexSystemModel model in Store.Models) { string fp = ComplexSystemsKernel.Fingerprint(model); rows.Add((model.Name ?? model.Id) + "   ·   " + fp); rows.AddRange(ComplexSystemsKernel.Audit(model).Cast<object>()); foreach (ComplexRunRecord run in Store.Runs.Where(x => Eq(x.ModelId, model.Id))) if (!Eq(run.ModelFingerprint, fp)) rows.Add("HISTORY · run " + run.Id + " correctly remains bound to historical fingerprint " + Short(run.ModelFingerprint, 20)); } foreach (ComplexModelBaseline b in Store.Baselines) if (!Eq(b.BaselineFingerprint, BaselineFingerprint(b))) rows.Add("BLOCKER · BASELINE_FINGERPRINT_MISMATCH · " + b.Id); rows.Add("LEDGER · " + VerifyLedger(ReadLedger(ctx, 32768))); OpenRows(owner, "LABORATORY AUDITOR", rows, "Structural, provenance, history and epistemic-boundary audit"); }
        private static void OpenLedger(Window owner, DeepSystemsContext ctx) { List<ComplexLabLedgerRecord> rows = ReadLedger(ctx, 32768); OpenRows(owner, "COMPLEX SYSTEMS INTEGRITY LEDGER", new object[] { VerifyLedger(rows) }.Concat(rows.OrderByDescending(x => x.Sequence).Cast<object>()).ToArray(), "Append-only SHA-256 chain · " + LedgerPath(ctx)); }

        private static void WithModel(Window owner, DeepSystemsContext ctx, Action<ComplexSystemModel> action) { ComplexSystemModel model = ChooseObject(owner, "SELECT COMPLEX SYSTEM", "Choose an active population model", Store.Models.Where(x => Active(x.Status)).OrderByDescending(x => x.UpdatedUtc ?? x.CreatedUtc).Cast<object>().ToList()) as ComplexSystemModel; if (model != null && action != null) action(model); }
        private static string CensusLine() { return Store.Models.Count + " models   ·   " + Store.Runs.Count + " runs   ·   " + Store.Ensembles.Count + " ensembles   ·   " + Store.Sweeps.Count + " phase sweeps   ·   " + Store.Capsules.Count + " preregistrations   ·   " + Store.Baselines.Count + " baselines   ·   " + Store.Dossiers.Count + " dossiers"; }

        private static void Load(DeepSystemsContext ctx) { lock (Gate) { if (Store != null && Eq(LoadedRoot, ctx.StateRoot)) return; LoadedRoot = ctx.StateRoot; Store = null; string path = StorePath(ctx); if (File.Exists(path)) try { Store = Json.Deserialize<ComplexSystemsStore>(File.ReadAllText(path, Encoding.UTF8)); } catch { PreserveCorrupt(path); } if (Store == null && File.Exists(path + ".previous")) try { Store = Json.Deserialize<ComplexSystemsStore>(File.ReadAllText(path + ".previous", Encoding.UTF8)); } catch { } if (Store == null) Store = new ComplexSystemsStore(); NormalizeStore(); } }
        private static void NormalizeStore() { if (Store == null) Store = new ComplexSystemsStore(); Store.Schema = 1; Store.Models = Store.Models ?? new List<ComplexSystemModel>(); Store.Runs = Store.Runs ?? new List<ComplexRunRecord>(); Store.Ensembles = Store.Ensembles ?? new List<ComplexEnsembleRecord>(); Store.Sweeps = Store.Sweeps ?? new List<ComplexSweepRecord>(); Store.Capsules = Store.Capsules ?? new List<ComplexExperimentCapsule>(); Store.Baselines = Store.Baselines ?? new List<ComplexModelBaseline>(); Store.Dossiers = Store.Dossiers ?? new List<ComplexScenarioDossier>(); Store.RecentQuestions = Store.RecentQuestions ?? new List<string>(); foreach (ComplexSystemModel m in Store.Models) { m.Parameters = new Dictionary<string, double>(m.Parameters ?? new Dictionary<string, double>(), StringComparer.OrdinalIgnoreCase); m.Agents = (m.Agents ?? new List<ComplexAgentSpec>()).Take(MaxAgents).ToList(); m.Edges = (m.Edges ?? new List<ComplexInteractionEdge>()).Take(MaxEdges).ToList(); m.Rules = (m.Rules ?? new List<ComplexRuleSpec>()).Take(MaxRules).ToList(); m.Interventions = (m.Interventions ?? new List<ComplexInterventionSpec>()).Take(MaxInterventions).ToList(); m.Assumptions = m.Assumptions ?? new List<string>(); m.EvidenceNodeIds = (m.EvidenceNodeIds ?? new List<string>()).Take(MaxEvidence).ToList(); foreach (ComplexAgentSpec a in m.Agents) { a.Traits = new Dictionary<string, double>(a.Traits ?? new Dictionary<string, double>(), StringComparer.OrdinalIgnoreCase); a.EvidenceNodeIds = a.EvidenceNodeIds ?? new List<string>(); } foreach (ComplexInteractionEdge e in m.Edges) e.EvidenceNodeIds = e.EvidenceNodeIds ?? new List<string>(); foreach (ComplexRuleSpec r in m.Rules) r.EvidenceNodeIds = r.EvidenceNodeIds ?? new List<string>(); foreach (ComplexInterventionSpec x in m.Interventions) x.EvidenceNodeIds = x.EvidenceNodeIds ?? new List<string>(); } foreach (ComplexRunRecord r in Store.Runs) r.Notes = r.Notes ?? new List<string>(); foreach (ComplexExperimentCapsule c in Store.Capsules) { c.FrozenParameters = new Dictionary<string, double>(c.FrozenParameters ?? new Dictionary<string, double>(), StringComparer.OrdinalIgnoreCase); c.Assumptions = c.Assumptions ?? new List<string>(); c.Falsifiers = c.Falsifiers ?? new List<string>(); c.EvidenceNodeIds = c.EvidenceNodeIds ?? new List<string>(); } foreach (ComplexScenarioDossier d in Store.Dossiers) { d.Mechanisms = d.Mechanisms ?? new List<string>(); d.Alternatives = d.Alternatives ?? new List<string>(); d.Unknowns = d.Unknowns ?? new List<string>(); d.Dissent = d.Dissent ?? new List<string>(); d.EvidenceNodeIds = d.EvidenceNodeIds ?? new List<string>(); } }
        private static void TrimStore() { NormalizeStore(); Store.Models = Store.Models.Take(MaxModels).ToList(); Store.Runs = Store.Runs.Take(MaxRuns).ToList(); Store.Ensembles = Store.Ensembles.Take(MaxEnsembles).ToList(); Store.Sweeps = Store.Sweeps.Take(MaxSweeps).ToList(); Store.Capsules = Store.Capsules.Take(MaxCapsules).ToList(); Store.Baselines = Store.Baselines.Take(MaxBaselines).ToList(); Store.Dossiers = Store.Dossiers.Take(MaxDossiers).ToList(); Store.RecentQuestions = Store.RecentQuestions.Take(256).ToList(); }
        private static void Save(DeepSystemsContext ctx) { lock (Gate) { TrimStore(); Store.Revision = Math.Max(0, Store.Revision) + 1; Store.UpdatedUtc = Now(); Store.LastCommitId = Id("complex-commit"); string path = StorePath(ctx); Directory.CreateDirectory(Path.GetDirectoryName(path)); AtomicWrite(path, Json.Serialize(Store)); } }
        private static void AtomicWrite(string path, string text) { string temp = path + ".tmp." + Guid.NewGuid().ToString("N"); File.WriteAllText(temp, text ?? "", new UTF8Encoding(false)); if (File.Exists(path)) { string previous = path + ".previous"; try { File.Replace(temp, path, previous, true); return; } catch { try { File.Copy(path, previous, true); } catch { } } } if (File.Exists(path)) File.Delete(path); File.Move(temp, path); }
        private static void PreserveCorrupt(string path) { try { if (!File.Exists(path)) return; byte[] bytes = File.ReadAllBytes(path); string destination = path + ".corrupt." + HashBytes(bytes).Substring(0, 16) + ".json"; if (!File.Exists(destination)) File.Copy(path, destination); } catch { } }
        private static string StorePath(DeepSystemsContext ctx) { return Path.Combine(ctx.StateRoot, "controller-complex-systems-laboratory.json"); }
        private static string LedgerPath(DeepSystemsContext ctx) { return Path.Combine(ctx.StateRoot, "controller-complex-systems-laboratory-ledger.jsonl"); }
        private static void AppendLedger(DeepSystemsContext ctx, string evt, string subject, string detail, string fingerprint, string certificate) { lock (Gate) try { Directory.CreateDirectory(ctx.StateRoot); List<ComplexLabLedgerRecord> prior = ReadLedger(ctx, 32768); ComplexLabLedgerRecord last = prior.OrderByDescending(x => x.Sequence).FirstOrDefault(); ComplexLabLedgerRecord r = new ComplexLabLedgerRecord { Schema = 1, Sequence = last == null ? 1 : last.Sequence + 1, Utc = Now(), Event = Short(evt, 120), Subject = Short(subject, 512), Detail = Short(detail, MaxLongText), CorrelationId = Store == null ? "" : Store.LastCommitId, ModelFingerprint = Short(fingerprint, 128), CertificateHash = Short(certificate, 128), PrevHash = last == null ? new string('0', 64) : last.EntryHash }; r.EntryHash = LedgerHash(r); byte[] bytes = Encoding.UTF8.GetBytes(Json.Serialize(r) + Environment.NewLine); using (FileStream stream = new FileStream(LedgerPath(ctx), FileMode.Append, FileAccess.Write, FileShare.Read, 4096, FileOptions.WriteThrough)) { stream.Write(bytes, 0, bytes.Length); stream.Flush(); } } catch { } }
        private static List<ComplexLabLedgerRecord> ReadLedger(DeepSystemsContext ctx, int cap) { List<ComplexLabLedgerRecord> rows = new List<ComplexLabLedgerRecord>(); if (!File.Exists(LedgerPath(ctx))) return rows; try { foreach (string line in TakeLast(File.ReadLines(LedgerPath(ctx)).Where(x => !String.IsNullOrWhiteSpace(x)), cap)) try { ComplexLabLedgerRecord row = Json.Deserialize<ComplexLabLedgerRecord>(line); if (row != null) rows.Add(row); } catch { } } catch { } return rows; }
        private static string VerifyLedger(List<ComplexLabLedgerRecord> rows) { if (rows == null || rows.Count == 0) return "EMPTY LEDGER"; rows = rows.OrderBy(x => x.Sequence).ToList(); long expected = rows[0].Sequence; string prior = expected == 1 ? new string('0', 64) : rows[0].PrevHash; foreach (ComplexLabLedgerRecord row in rows) { if (row.Sequence != expected) return "CHAIN GAP @ " + expected; if (!Eq(row.PrevHash, prior)) return "PREV HASH MISMATCH @ " + row.Sequence; if (!Eq(row.EntryHash, LedgerHash(row))) return "ENTRY HASH MISMATCH @ " + row.Sequence; expected++; prior = row.EntryHash; } return "CHAIN VERIFIED · " + rows.Count.ToString(CultureInfo.InvariantCulture) + " RECORDS"; }
        private static string LedgerHash(ComplexLabLedgerRecord r) { return HashText(r.Schema + "|" + r.Sequence + "|" + (r.Utc ?? "") + "|" + (r.Event ?? "") + "|" + (r.Subject ?? "") + "|" + (r.Detail ?? "") + "|" + (r.CorrelationId ?? "") + "|" + (r.ModelFingerprint ?? "") + "|" + (r.CertificateHash ?? "") + "|" + (r.PrevHash ?? "")); }

        private static void Touch(ComplexSystemModel m) { m.Revision = Math.Max(1, m.Revision) + 1; m.UpdatedUtc = Now(); }
        private static bool Active(string status) { return !Eq(status, "ARCHIVED") && !Eq(status, "DISABLED") && !Eq(status, "RETIRED") && !Eq(status, "REJECTED"); }
        private static bool Eq(string a, string b) { return String.Equals(a ?? "", b ?? "", StringComparison.OrdinalIgnoreCase); }
        private static IList<object> CurrentFirst(string current, IEnumerable<string> values) { return (values ?? Enumerable.Empty<string>()).OrderBy(x => Eq(x, current) ? 0 : 1).ThenBy(x => x).Cast<object>().ToList(); }
        private static double Normalize(double value, double minimum, double maximum) { if (Double.IsNaN(value) || Double.IsInfinity(value)) return 0; if (maximum <= minimum) return value >= 0 ? 1 : 0; return Math.Max(0, Math.Min(1, (value - minimum) / (maximum - minimum))); }
        private static double Number(string raw, double fallback) { double value; return Double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out value) && !Double.IsNaN(value) && !Double.IsInfinity(value) ? value : fallback; }
        private static int Integer(string raw, int fallback, int minimum, int maximum) { int value; if (!Int32.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out value)) value = fallback; return Math.Max(minimum, Math.Min(maximum, value)); }
        private static Dictionary<string, double> Pairs(string raw) { Dictionary<string, double> result = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase); foreach (string line in (raw ?? "").Split(new[] { '\r', '\n', ';' }, StringSplitOptions.RemoveEmptyEntries)) { int at = line.IndexOf('='); if (at > 0) { string key = SafeKey(line.Substring(0, at).Trim()); if (!String.IsNullOrWhiteSpace(key)) result[key] = Number(line.Substring(at + 1).Trim(), 0); } } return result; }
        private static string SafeKey(string value) { StringBuilder s = new StringBuilder(); foreach (char c in (value ?? "").ToLowerInvariant()) if (Char.IsLetterOrDigit(c) || c == '_') s.Append(c); else if (s.Length > 0 && s[s.Length - 1] != '_') s.Append('_'); return s.ToString().Trim('_'); }
        private static string Short(string value, int cap) { value = value ?? ""; cap = Math.Max(1, cap); return value.Length <= cap ? value : value.Substring(0, cap - 1) + "…"; }
        private static string HashText(string value) { return HashBytes(Encoding.UTF8.GetBytes(value ?? "")); }
        private static string HashBytes(byte[] value) { using (SHA256 hash = SHA256.Create()) return BitConverter.ToString(hash.ComputeHash(value ?? new byte[0])).Replace("-", "").ToLowerInvariant(); }
        private static string Id(string prefix) { return prefix + "-" + DateTime.UtcNow.ToString("yyyyMMddHHmmssfff", CultureInfo.InvariantCulture) + "-" + Guid.NewGuid().ToString("N").Substring(0, 8); }
        private static string Now() { return DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture); }
        private static IEnumerable<TValue> TakeLast<TValue>(IEnumerable<TValue> source, int count) { Queue<TValue> q = new Queue<TValue>(); foreach (TValue item in source ?? Enumerable.Empty<TValue>()) { q.Enqueue(item); if (q.Count > count) q.Dequeue(); } foreach (TValue item in q) yield return item; }

        private static Window W(Window owner, string title, double width, double height) { return new Window { Title = title, Width = width, Height = height, MinWidth = Math.Min(width, 820), MinHeight = Math.Min(height, 560), Background = Bg, Foreground = Text, WindowStartupLocation = WindowStartupLocation.CenterOwner, Owner = owner, FontFamily = new FontFamily("Segoe UI") }; }
        private static DockPanel Shell(string title, string subtitle) { DockPanel root = new DockPanel { Margin = new Thickness(16) }; StackPanel head = new StackPanel { Margin = new Thickness(0, 0, 0, 10) }; head.Children.Add(T(title, 24, Text, FontWeights.Bold)); head.Children.Add(T(subtitle, 12, Muted, FontWeights.Normal)); DockPanel.SetDock(head, Dock.Top); root.Children.Add(head); return root; }
        private static TextBlock T(string value, double size, Brush foreground, FontWeight weight) { return new TextBlock { Text = value ?? "", FontSize = size, Foreground = foreground, FontWeight = weight, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 2, 0, 2) }; }
        private static Button Btn(string label, RoutedEventHandler click) { Button button = new Button { Content = label, Margin = new Thickness(0, 0, 8, 8), Padding = new Thickness(12, 7, 12, 7), Background = Raised, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), MinWidth = 112 }; if (click != null) button.Click += click; return button; }
        private static ListBox List() { return new ListBox { Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), Margin = new Thickness(0, 6, 6, 0), Padding = new Thickness(5), FontFamily = new FontFamily("Cascadia Mono, Consolas") }; }
        private static void Portal(Panel parent, string badge, string title, string description, Action open) { Button button = new Button { Width = 360, Height = 120, Margin = new Thickness(0, 0, 10, 10), Padding = new Thickness(12), Background = Surface, Foreground = Text, BorderBrush = Border, BorderThickness = new Thickness(1), HorizontalContentAlignment = HorizontalAlignment.Stretch }; StackPanel content = new StackPanel(); content.Children.Add(T(badge + "   " + title, 14, Accent, FontWeights.Bold)); content.Children.Add(T(description, 11.5, Muted, FontWeights.Normal)); button.Content = content; button.Click += delegate { if (open != null) open(); }; parent.Children.Add(button); }
        private static Brush B(string hex) { return new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex)); }
        private static string Prompt(Window owner, string title, string label, string initial) { Window w = W(owner, "YOMI · " + title, 680, 290); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); TextBox editor = new TextBox { Text = initial ?? "", MaxLength = MaxShortText, Margin = new Thickness(0, 8, 0, 10), Background = Surface, Foreground = Text, BorderBrush = Border, Padding = new Thickness(8) }; DockPanel.SetDock(editor, Dock.Top); root.Children.Add(editor); WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right }; string result = null; buttons.Children.Add(Btn("OK", delegate { result = editor.Text; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); root.Children.Add(buttons); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static string PromptLarge(Window owner, string title, string label, string initial) { Window w = W(owner, "YOMI · " + title, 800, 560); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); TextBox editor = new TextBox { Text = initial ?? "", MaxLength = MaxLongText, AcceptsReturn = true, AcceptsTab = true, TextWrapping = TextWrapping.Wrap, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, Margin = new Thickness(0, 8, 0, 0), Background = Surface, Foreground = Text, BorderBrush = Border, Padding = new Thickness(10), FontFamily = new FontFamily("Cascadia Mono, Consolas") }; WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) }; string result = null; buttons.Children.Add(Btn("SAVE", delegate { result = editor.Text; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(editor); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static object ChooseObject(Window owner, string title, string label, IList<object> choices) { Window w = W(owner, "YOMI · " + title, 720, 500); DockPanel root = new DockPanel { Margin = new Thickness(16) }; TextBlock caption = T(label, 12, Muted, FontWeights.Normal); DockPanel.SetDock(caption, Dock.Top); root.Children.Add(caption); ListBox list = List(); list.ItemsSource = choices ?? new List<object>(); if (list.Items.Count > 0) list.SelectedIndex = 0; WrapPanel buttons = new WrapPanel { HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) }; object result = null; buttons.Children.Add(Btn("SELECT", delegate { result = list.SelectedItem; w.DialogResult = true; })); buttons.Children.Add(Btn("CANCEL", delegate { w.DialogResult = false; })); list.MouseDoubleClick += delegate { result = list.SelectedItem; if (result != null) w.DialogResult = true; }; DockPanel.SetDock(buttons, Dock.Bottom); root.Children.Add(buttons); root.Children.Add(list); w.Content = root; bool? accepted = w.ShowDialog(); return accepted == true ? result : null; }
        private static void OpenRows(Window owner, string title, object value, string subtitle) { IEnumerable<object> rows = value as IEnumerable<object>; OpenRows(owner, title, rows == null ? new object[] { value } : rows.ToArray(), subtitle); }
        private static void OpenRows(Window owner, string title, IList<object> rows, string subtitle) { Window w = W(owner, "YOMI · " + title, 1240, 830); DockPanel root = Shell(title, subtitle); ListBox list = List(); list.ItemsSource = rows ?? new List<object>(); root.Children.Add(list); w.Content = root; w.Show(); }
    }
}
