using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

namespace Yomi.ProductShell
{
    internal sealed class ExpeditionLedgerRecord
    {
        public int Schema { get; set; }
        public long Sequence { get; set; }
        public string Utc { get; set; }
        public string Event { get; set; }
        public string MissionId { get; set; }
        public string BranchId { get; set; }
        public string StepId { get; set; }
        public string Detail { get; set; }
        public string MissionFingerprint { get; set; }
        public string PrevHash { get; set; }
        public string EntryHash { get; set; }
        public override string ToString() { return Sequence.ToString("000000", CultureInfo.InvariantCulture) + "   ·   " + (Utc ?? "") + "   ·   " + (Event ?? "EVENT") + "   ·   " + (MissionId ?? "") + "   ·   " + ExpeditionKernel.Short(EntryHash); }
    }

    internal sealed class ExpeditionCommandStore
    {
        public int Schema { get; set; }
        public long Revision { get; set; }
        public string UpdatedUtc { get; set; }
        public string ActiveMissionId { get; set; }
        public List<ExpeditionMission> Missions { get; set; }
        public ExpeditionCommandStore() { Schema = 1; Missions = new List<ExpeditionMission>(); }
    }

    internal static class GrandUnifiedExpeditionCommand
    {
        private static readonly object Gate = new object();
        private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = Int32.MaxValue, RecursionLimit = 256 };
        private static ExpeditionCommandStore Store;
        private static string LoadedRoot;
        private const int MaxMissions = 64;
        private const int MaxSteps = 4096;
        private const int MaxFindings = 4096;
        private const int MaxQuestions = 2048;
        private const int MaxArtifacts = 8192;
        private const int MaxCheckpoints = 512;
        private const int MaxLedgerRead = 32768;
        private const int MaxSourceChars = 2000000;
        private static readonly Brush Bg = B("#0E1114"), Surface = B("#161B20"), Raised = B("#20272E"), Border = B("#35404A"), Text = B("#F0F4F6"), Muted = B("#9FAAB4"), Accent = B("#77F1C3"), Blue = B("#78BBFF"), Amber = B("#FFD16E"), Green = B("#87E38C"), Danger = B("#FF8585");

        public static void Open(Window owner, DeepSystemsContext ctx)
        {
            if (ctx == null) return; Load(ctx); Window w = W(owner, "YOMI · GRAND UNIFIED EXPEDITION COMMAND", 1540, 940); DockPanel root = Shell("GRAND UNIFIED EXPEDITION COMMAND", "Start with a question. Travel through every civilization. Preserve the entire evidence worldline. Fork when the investigation forks. Resume from an exact fingerprinted checkpoint instead of trying to remember what the hell you were doing.");
            ExpeditionMission active = ActiveMission(); int steps = active == null ? 0 : active.Steps.Count; int openQ = active == null ? 0 : active.Questions.Count(x => Eq(x.Status,"OPEN")); TextBlock status = new TextBlock { Text = "EXPΩ   ·   DEV13.37.27   ·   " + Store.Missions.Count + " missions   ·   " + steps + " active-mission steps   ·   " + openQ + " open questions   ·   Ctrl+Alt+X", Foreground = Accent, FontWeight = FontWeights.Bold, Margin = new Thickness(20,0,20,14) }; DockPanel.SetDock(status,Dock.Top); root.Children.Add(status);
            ScrollViewer scroll = new ScrollViewer { VerticalScrollBarVisibility = ScrollBarVisibility.Auto }; WrapPanel chambers = new WrapPanel { Margin = new Thickness(12) };

            Portal(chambers,"REG","MISSION REGISTRY","Open every retained expedition and its branch/step/finding/checkpoint worldline.",delegate { OpenMissions(w,ctx); });
            Portal(chambers,"NEW","NEW EXPEDITION","Begin with a question instead of choosing a subsystem first.",delegate { NewMission(w,ctx); });
            Portal(chambers,"Q","QUESTION FORGE","Add a child question to the active investigation frontier without losing the parent question.",delegate { AddQuestion(w,ctx); });
            Portal(chambers,"CHARTER","MISSION CHARTER","Inspect question, objective, status, active branch and root fingerprint.",delegate { ShowMissionCharter(w); });
            Portal(chambers,"COCKPIT","ACTIVE MISSION COCKPIT","One surface for the current branch, current step, current question, evidence load and open debt.",delegate { MissionCockpit(w,ctx); });
            Portal(chambers,"METAΩ","KNOWLEDGE CONSTELLATION METASTRUCTURE","Rise above the active worldline into the cross-mission universe: shared source fingerprints, convergence candidates, contradiction sky and global research frontiers.",delegate { KnowledgeConstellationMetastructure.Open(w,ctx); });
            Portal(chambers,"SYNTHΩ","CIVILIZATIONAL SYNTHESIS REACTOR","Rise from one mission into reusable cross-mission motifs, counterexamples, transfer tests and explicitly scoped theorem candidates.",delegate { CivilizationalSynthesisReactor.Open(w,ctx); });
            Portal(chambers,"VOIDΩ","UNKNOWN UNKNOWNS OBSERVATORY","Inspect structural absences, source monocultures, unresolved debt and underused civilization lenses across retained investigations.",delegate { UnknownUnknownsObservatory.Open(w,ctx); });
            Portal(chambers,"COVER","CIVILIZATION COVERAGE MATRIX","Which of the seventeen concrete civilizations have been visited on this mission, on which branches, and with what source fingerprints?",delegate { CoverageMatrix(w); });
            Portal(chambers,"ROUTE","ROUTE PLANNER","Deterministically rank the next civilizations from question keywords plus unvisited frontiers.",delegate { RoutePlanner(w,ctx,false); });
            Portal(chambers,"FRONTIER","FRONTIER RECOMMENDATIONS","Show the highest-ranked unvisited systems rather than bouncing randomly through the lattice.",delegate { RoutePlanner(w,ctx,true); });
            Portal(chambers,"TRAIL","TRAIL TIMELINE","Every civilization crossing in sequence with branch, source identity and retained fingerprint.",delegate { WithMission(w,delegate(ExpeditionMission m){ OpenCollection(w,"EXPEDITION TRAIL · " + m.Title,m.Steps.OrderBy(x=>x.Sequence).Cast<object>().ToList(),"The trail is append-only history; branch identity is retained on each step."); }); });
            Portal(chambers,"STEP","CURRENT STEP MICROSCOPE","Open the active crossing, its captured source snapshot, findings, artifacts and live-window route constellation.",delegate { CurrentStep(w,ctx); });
            Portal(chambers,"SOURCE","CAPTURED SOURCE VAULT","Open the immutable serialized source snapshot retained at each crossing.",delegate { SourceVault(w,ctx); });
            Portal(chambers,"PIN","EVIDENCE PINBOARD","Mission artifacts bound to exact civilization/source fingerprints rather than loose notes.",delegate { WithMission(w,delegate(ExpeditionMission m){ OpenCollection(w,"EVIDENCE PINBOARD · " + m.Title,m.Artifacts.Cast<object>().ToList(),"Artifacts remain bound to the crossing that produced them."); }); });
            Portal(chambers,"FIND","FINDING FORGE","Record a finding against the active step with confidence and source-step lineage.",delegate { AddFinding(w,ctx); });
            Portal(chambers,"QSTACK","QUESTION STACK","All open, answered and superseded questions across mission branches.",delegate { WithMission(w,delegate(ExpeditionMission m){ OpenCollection(w,"QUESTION STACK · " + m.Title,m.Questions.Cast<object>().ToList(),"Questions are durable investigation objects, not disposable search-box text."); }); });
            Portal(chambers,"DEBT","RESEARCH DEBT / UNKNOWNS","Open questions, unresolved contradictions and active assumptions in one debt surface.",delegate { ResearchDebt(w); });
            Portal(chambers,"CONTRA","CONTRADICTION REGISTER","Bind two findings into an explicit contradiction instead of mentally papering over disagreement.",delegate { AddContradiction(w,ctx); });
            Portal(chambers,"HYP","HYPOTHESIS BOARD","Inspect and revise branch hypotheses without rewriting prior branch history.",delegate { HypothesisBoard(w,ctx); });
            Portal(chambers,"ASM","ASSUMPTION BOARD","Make mission assumptions explicit and bind them to source steps when possible.",delegate { AddAssumption(w,ctx); });
            Portal(chambers,"DEC","DECISION LOG","Record investigation decisions, rationale and alternatives against the current branch/step.",delegate { AddDecision(w,ctx); });
            Portal(chambers,"ART","ARTIFACT VAULT","All fingerprint-bound source captures and operator evidence artifacts.",delegate { WithMission(w,delegate(ExpeditionMission m){ OpenCollection(w,"ARTIFACT VAULT · " + m.Title,m.Artifacts.Cast<object>().ToList(),"Source captures and evidence pins survive branch changes."); }); });
            Portal(chambers,"CP","CHECKPOINT VAULT","Durable mission/branch/step checkpoints carrying root fingerprint plus live Deep Systems window routes.",delegate { CheckpointVault(w,ctx); });
            Portal(chambers,"RESUME","ONE-CLICK RESUME","Choose a checkpoint and restore the mission's active branch and step exactly to that retained worldline point.",delegate { ResumeCheckpoint(w,ctx); });
            Portal(chambers,"CAPSULE","EXACT RESUME CAPSULE","Reopen the current step's captured evidence snapshot and owning civilization beside the retained route constellation.",delegate { ResumeCurrent(w,ctx); });
            Portal(chambers,"BRANCH","BRANCH LAB","Every mission branch with parent, fork step, question, hypothesis and current head.",delegate { WithMission(w,delegate(ExpeditionMission m){ OpenCollection(w,"BRANCH LAB · " + m.Title,m.Branches.Cast<object>().ToList(),"Branches preserve incompatible lines of inquiry instead of flattening them."); }); });
            Portal(chambers,"FORK","FORK MISSION BRANCH","Create a new investigation branch from the exact active step and give it its own question/hypothesis.",delegate { ForkBranch(w,ctx); });
            Portal(chambers,"BDIFF","BRANCH DIFF","Compare civilizations visited and findings retained by any two mission branches.",delegate { BranchDiff(w); });
            Portal(chambers,"MERGE","MERGE MEMO","Create a synthesis finding that cites findings from multiple branches without deleting either branch.",delegate { MergeMemo(w,ctx); });
            Portal(chambers,"DEAD","DEAD-END LEDGER","Mark or inspect branches/questions explicitly retired so failed paths remain useful evidence.",delegate { DeadEndLedger(w,ctx); });
            Portal(chambers,"BACK","BACKTRACK NAVIGATOR","Walk parent-step ancestry from the active head to the branch fork and mission origin.",delegate { Backtrack(w); });
            Portal(chambers,"FP","SOURCE FINGERPRINT RADAR","Group every crossing by civilization/source identity and inspect exact captured fingerprints.",delegate { FingerprintRadar(w); });
            Portal(chambers,"DRIFT","UPSTREAM DRIFT RADAR","Find source identities observed with multiple fingerprints across the mission worldline.",delegate { DriftRadar(w); });
            Portal(chambers,"IMPACT","MISSION IMPACT TELESCOPE","Choose a crossing and expose findings, questions, artifacts and checkpoints that depend on it.",delegate { MissionImpact(w); });
            Portal(chambers,"GRAPH","MISSION WORLDLINE GRAPH","Branch → step → source → finding → checkpoint topology rendered as an explicit route map.",delegate { MissionGraph(w); });
            Portal(chambers,"TRACE","CROSS-SYSTEM TRACE","Search source IDs, fingerprints, findings, questions and routes across the whole mission.",delegate { CrossTrace(w); });
            Portal(chambers,"HANDOFF","CIVILIZATION HAND-OFF MATRIX","Count directed civilization-to-civilization transitions along each branch.",delegate { HandoffMatrix(w); });
            Portal(chambers,"WINDOW","WINDOW CONSTELLATION SNAPSHOT","Capture and inspect live Deep Systems window routes as part of checkpoint context.",delegate { WindowConstellation(w,ctx); });
            Portal(chambers,"CONT","SESSION CONTINUITY","Inspect active heads, latest checkpoints and abandoned branches to answer exactly where work stopped.",delegate { SessionContinuity(w); });
            Portal(chambers,"BASE","MISSION BASELINE","Create a named checkpoint bound to the mission root before a major investigative turn.",delegate { CreateCheckpoint(w,ctx,"BASELINE"); });
            Portal(chambers,"SEAL","MISSION SEAL","Bind current mission root fingerprint to branch/step/finding/open-debt counts.",delegate { SealMission(w,ctx); });
            Portal(chambers,"EXPORT","EXPEDITION CAPSULE EXPORT","Write a local JSON + Markdown mission capsule under YOMI data; no upload or external transmission.",delegate { ExportMission(w,ctx); });
            Portal(chambers,"DOCΩ","COMPILE DOSSIER IN DOCΩ","Project the entire mission into the Living Document Factory as provenance-bound documentary source material.",delegate { WithMission(w,delegate(ExpeditionMission m){ LivingDocumentIntelligenceFactory.OpenFromExpeditionMission(w,ctx,m); }); });
            Portal(chambers,"DATAΩ","PROJECT TRAIL TO DATAΩ","Project mission branches, steps and findings as structured provenance evidence for analysis.",delegate { WithMission(w,delegate(ExpeditionMission m){ DataFoundry.OpenFromExpeditionMission(w,ctx,m); }); });
            Portal(chambers,"GENOMEΩ","SOFTWARE GENOME OBSERVATORY","Cross into code anatomy while keeping the active mission worldline alive.",delegate { SoftwareGenomeObservatory.Open(w,ctx); });
            Portal(chambers,"WORLD","UNIVERSAL WORLD KERNEL","Cross into stable object identity and world passports.",delegate { WorldKernel.Open(w,ctx); });
            Portal(chambers,"CIV","CIVILIZATION LAYER","Cross into institutions, groups, resolutions and chronicles.",delegate { CivilizationLayer.Open(w,ctx); });
            Portal(chambers,"LOGIC","EPISTEMIC LOGIC FOUNDRY","Cross into propositions, assumptions, contradictions and epistemic status.",delegate { EpistemicLogicFoundry.Open(w,ctx); });
            Portal(chambers,"VERIFY","AXIOMATIC VERIFICATION REACTOR","Cross into finite-state proof, invariants and counterexamples.",delegate { AxiomaticVerificationReactor.Open(w,ctx); });
            Portal(chambers,"STRAT","COUNTERFACTUAL STRATEGY","Cross into alternatives, adversaries and consequence worlds.",delegate { CounterfactualStrategySuperstructure.Open(w,ctx); });
            Portal(chambers,"SCI","SCIENTIFIC DISCOVERY","Cross into hypotheses, protocols, experiments and evidence design.",delegate { ScientificDiscoveryHyperstructure.Open(w,ctx); });
            Portal(chambers,"ENG","SYSTEMS ENGINEERING","Cross into requirements, architectures, schedules, reliability and safety cases.",delegate { DysonSystemsEngineeringMegastructure.Open(w,ctx); });
            Portal(chambers,"TWIN","CYBERNETIC DIGITAL TWIN","Cross into dynamic state, feedback, estimation and control evidence.",delegate { CyberneticDigitalTwinMetastructure.Open(w,ctx); });
            Portal(chambers,"COMPLEX","COMPLEX SYSTEMS","Cross into populations, networks, emergence, phase transitions and resilience.",delegate { ComplexSystemsLaboratory.Open(w,ctx); });
            Portal(chambers,"ORΩ","OPERATIONS RESEARCH","Cross into routing, scheduling, allocation, flow and robust optimization.",delegate { OperationsResearchEmpire.Open(w,ctx); });
            Portal(chambers,"ECONΩ","ECONOMIC CIVILIZATION","Cross into stock-flow economies, firms, labor, trade, credit and policy worlds.",delegate { EconomicCivilization.Open(w,ctx); });
            Portal(chambers,"GEOΩ","SPATIAL WORLD CARTOGRAPHY","Cross into places, topology, routes, regions, hazards and accessibility.",delegate { SpatialWorldCartography.Open(w,ctx); });
            Portal(chambers,"DISTΩ","DISTRIBUTED SYSTEMS","Cross into replicas, consensus, clocks, partitions and recovery.",delegate { DistributedSystemsPlanetarium.Open(w,ctx); });
            Portal(chambers,"SECΩ","ADVERSARIAL SECURITY","Cross into assets, trust, privilege paths, controls and defensive assurance.",delegate { AdversarialSecurityFortress.Open(w,ctx); });
            Portal(chambers,"DATA","DATA FOUNDRY","Cross into fields, schemas, lineage, transformations, drift and data evidence.",delegate { DataFoundry.Open(w,ctx); });
            Portal(chambers,"GENOME","SOFTWARE GENOME","Cross into files, symbols, dependencies, history, blast radius and architecture drift.",delegate { SoftwareGenomeObservatory.Open(w,ctx); });
            Portal(chambers,"DOC","LIVING DOCUMENT FACTORY","Cross into paragraphs, claims, source fingerprints, staleness and publication lineage.",delegate { LivingDocumentIntelligenceFactory.Open(w,ctx); });
            Portal(chambers,"TIME","TEMPORAL OBSERVATORY","Open time-oriented history and drift beside the expedition worldline.",delegate { TemporalObservatory.Open(w,ctx); });
            Portal(chambers,"CAUSE","CAUSAL GRAPH LAB","Open evidence-chain and counterfactual genealogy tools beside the expedition.",delegate { CausalGraphLab.Open(w,ctx); });
            Portal(chambers,"R&D","RESEARCH WORKBENCH","Open anomaly, hypothesis and case-file tools without discarding the mission.",delegate { ResearchWorkbench.Open(w,ctx); });
            Portal(chambers,"WORK","COGNITIVE PRODUCTIVITY FABRIC","Turn the expedition frontier into resumable next actions and research debt.",delegate { ProductivityFabric.Open(w,ctx); });
            Portal(chambers,"HADAL","HADAL SYSTEMS","Descend below the mission into provenance gaps, fossils, null space and unanswered consequence horizons.",delegate { AbyssalKnowledgeEngine.Open(w,ctx); });
            Portal(chambers,"ATLAS","DEEP SYSTEMS ATLAS","Open the full recursive system map while the mission stays retained.",delegate { DeepSystems.OpenAtlasFromContext(w); });
            Portal(chambers,"AUTO","MISSION AUTOPSY / VALIDATOR","Audit identities, branch/step references, captured-source fingerprints, open debt and expedition ledger continuity.",delegate { MissionAutopsy(w,ctx); });

            scroll.Content = chambers; root.Children.Add(scroll); w.Content = root; w.Show();
        }

        public static void OpenFromWorldNode(Window owner, DeepSystemsContext ctx, WorldIndex index, string nodeId) { if (index == null || String.IsNullOrWhiteSpace(nodeId)) { Open(owner,ctx); return; } WorldNode source; if (!index.Nodes.TryGetValue(nodeId,out source)) { Open(owner,ctx); return; } Project(owner,ctx,"WORLD",source,nodeId,"World object captured as an expedition source snapshot."); }
        public static void OpenFromCivilResolution(Window owner, DeepSystemsContext ctx, WorldIndex index, CivilResolution source) { Project(owner,ctx,"CIVILIZATION",source,ReadId(source),"Civil resolution captured as institutional evidence."); }
        public static void OpenFromLogicTheory(Window owner, DeepSystemsContext ctx, WorldIndex index, LogicTheory source) { Project(owner,ctx,"EPISTEMIC_LOGIC",source,ReadId(source),"Logic theory captured as proposition/assumption evidence."); }
        public static void OpenFromVerificationModel(Window owner, DeepSystemsContext ctx, WorldIndex index, VerificationModel source) { Project(owner,ctx,"VERIFICATION",source,ReadId(source),"Verification model captured as formal-method evidence."); }
        public static void OpenFromStrategyModel(Window owner, DeepSystemsContext ctx, WorldIndex index, StrategyModel source) { Project(owner,ctx,"STRATEGY",source,ReadId(source),"Strategy model captured as counterfactual decision evidence."); }
        public static void OpenFromDiscoveryProtocol(Window owner, DeepSystemsContext ctx, WorldIndex index, DiscoveryProtocol source) { Project(owner,ctx,"SCIENTIFIC_DISCOVERY",source,ReadId(source),"Discovery protocol captured as scientific-method evidence."); }
        public static void OpenFromEngineeringArchitecture(Window owner, DeepSystemsContext ctx, WorldIndex index, EngineeringArchitecture source) { Project(owner,ctx,"SYSTEMS_ENGINEERING",source,ReadId(source),"Engineering architecture captured as requirements/design evidence."); }
        public static void OpenFromCyberneticTwin(Window owner, DeepSystemsContext ctx, WorldIndex index, CyberTwinModel source) { Project(owner,ctx,"CYBERNETIC_TWIN",source,ReadId(source),"Digital twin captured as dynamic/control evidence."); }
        public static void OpenFromComplexSystem(Window owner, DeepSystemsContext ctx, WorldIndex index, ComplexSystemModel source) { Project(owner,ctx,"COMPLEX_SYSTEMS",source,ReadId(source),"Complex-system model captured as emergence evidence."); }
        public static void OpenFromOperationsResearchModel(Window owner, DeepSystemsContext ctx, WorldIndex index, OperationsResearchModel source) { Project(owner,ctx,"OPERATIONS_RESEARCH",source,ReadId(source),"Optimization model captured as decision-analysis evidence."); }
        public static void OpenFromEconomicModel(Window owner, DeepSystemsContext ctx, WorldIndex index, EconomicModel source) { Project(owner,ctx,"ECONOMIC_CIVILIZATION",source,ReadId(source),"Economic model captured as stock-flow/domain evidence."); }
        public static void OpenFromSpatialWorld(Window owner, DeepSystemsContext ctx, WorldIndex index, SpatialWorldModel source) { Project(owner,ctx,"SPATIAL_CARTOGRAPHY",source,ReadId(source),"Spatial world captured as geographic/topological evidence."); }
        public static void OpenFromDistributedSystem(Window owner, DeepSystemsContext ctx, WorldIndex index, DistributedSystemModel source) { Project(owner,ctx,"DISTRIBUTED_SYSTEMS",source,ReadId(source),"Distributed-system model captured as networked-computation evidence."); }
        public static void OpenFromSecurityModel(Window owner, DeepSystemsContext ctx, WorldIndex index, SecurityModel source) { Project(owner,ctx,"ADVERSARIAL_SECURITY",source,ReadId(source),"Security model captured as defensive assurance evidence."); }
        public static void OpenFromDataDataset(Window owner, DeepSystemsContext ctx, DataDataset source) { Project(owner,ctx,"DATA_FOUNDRY",source,ReadId(source),"Dataset captured as structured provenance evidence."); }
        public static void OpenFromSoftwareGenomeSnapshot(Window owner, DeepSystemsContext ctx, GenomeSnapshot source) { Project(owner,ctx,"SOFTWARE_GENOME",source,source==null?"UNKNOWN":source.Id,"Genome snapshot captured as code-architecture evidence."); }
        public static void OpenFromLivingDocumentVersion(Window owner, DeepSystemsContext ctx, LivingDocument document, LivingVersion source) { Project(owner,ctx,"LIVING_DOCUMENT",source,source==null?"UNKNOWN":source.Id,"Living document version captured as documentary evidence and synthesis state."); }
        public static void OpenFromKnowledgeFrontier(Window owner, DeepSystemsContext ctx, string question, string origin) { if(ctx==null)return; ExpeditionWorkspace.Visit(ctx,"expedition","METAΩ frontier",origin); Load(ctx); ExpeditionMission m=ExpeditionKernel.Starter(question); if(!String.IsNullOrWhiteSpace(origin))m.Objective += " Origin: " + origin; Store.Missions.Insert(0,m); Store.ActiveMissionId=m.Id; Touch(m); Save(ctx); AppendLedger(ctx,"MISSION_FROM_META_FRONTIER",m,ActiveBranch(m),null,origin??"METAΩ"); Open(owner,ctx); }
        public static void OpenFromSynthesisPattern(Window owner, DeepSystemsContext ctx, string question, string origin, string patternFingerprint) { if(ctx==null)return; ExpeditionWorkspace.Visit(ctx,"expedition","SYNTHΩ transfer",origin); Load(ctx); ExpeditionMission m=ExpeditionKernel.Starter(question); m.Objective += " Origin: " + (origin??"SYNTHΩ") + ". Test transfer explicitly; search for counterexamples; do not assume recurrence implies universality."; Store.Missions.Insert(0,m); Store.ActiveMissionId=m.Id; Touch(m); AppendLedger(ctx,"MISSION_FROM_SYNTHESIS_PATTERN",m,ActiveBranch(m),null,(origin??"SYNTHΩ")+"|"+(patternFingerprint??"∅")); Save(ctx); Open(owner,ctx); }
        public static void OpenFromUnknownUnknown(Window owner, DeepSystemsContext ctx, string question, string kind, string blindSpotFingerprint) { if(ctx==null)return; ExpeditionWorkspace.Visit(ctx,"expedition","VOIDΩ blind-spot probe",kind); Load(ctx); ExpeditionMission m=ExpeditionKernel.Starter(question); m.Objective += " Origin: VOIDΩ / " + (kind??"BLIND_SPOT") + ". Treat the blind spot as a candidate. Try to falsify its relevance, identify ordinary explanations for the absence, and only escalate if new evidence survives that challenge."; m.Tags.Add("VOIDΩ"); m.Tags.Add(kind??"BLIND_SPOT"); Store.Missions.Insert(0,m); Store.ActiveMissionId=m.Id; Touch(m); AppendLedger(ctx,"MISSION_FROM_VOID_BLIND_SPOT",m,ActiveBranch(m),null,(kind??"BLIND_SPOT")+"|"+(blindSpotFingerprint??"∅")); Save(ctx); Open(owner,ctx); }

        private static void Project(Window owner, DeepSystemsContext ctx, string civilization, object source, string sourceId, string rule)
        {
            if (ctx == null || source == null) { Open(owner,ctx); return; } ExpeditionWorkspace.Visit(ctx, "expedition", civilization + " source ingress", rule); Load(ctx); ExpeditionMission m = ActiveMission(); if (m == null) { string q = Prompt(owner,"BEGIN EXPEDITION","Question driving this expedition", "What can " + civilization + " evidence tell us about this source?"); if (q == null) return; m = ExpeditionKernel.Starter(q); Store.Missions.Insert(0,m); Store.ActiveMissionId=m.Id; }
            ExpeditionBranch branch = ActiveBranch(m); if (branch == null) return; string json = SerializeBounded(source); string fp = ExpeditionKernel.HashText(json); string label = ReadLabel(source); ExpeditionSourceSnapshot snap = new ExpeditionSourceSnapshot { Civilization=civilization, SourceType=source.GetType().FullName, SourceId=sourceId, SourceFingerprint=fp, SourceJson=json, Label=label }; snap.CertificateHash=ExpeditionKernel.HashText(snap.Civilization+"|"+snap.SourceType+"|"+snap.SourceId+"|"+snap.SourceFingerprint);
            ExpeditionStep prior = ActiveStep(m); if (prior != null && Eq(prior.Status,"ACTIVE")) { prior.Status="COMPLETE"; prior.LeftUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture); prior.CertificateHash=ExpeditionKernel.FingerprintStep(prior); }
            ExpeditionStep step = new ExpeditionStep { Id=ExpeditionKernel.NewId("STEP"), Sequence=m.Steps.Count==0?1:m.Steps.Max(x=>x.Sequence)+1, BranchId=branch.Id, ParentStepId=branch.ActiveStepId, Civilization=civilization, Chamber="SOURCE_INGRESS", QuestionAtEntry=CurrentQuestion(m,branch), Intent=rule, Route="EXPΩ › "+civilization+" › "+sourceId, Source=snap, WindowRoutes=DeepSystems.ExpeditionWindowRoutes() }; step.CertificateHash=ExpeditionKernel.FingerprintStep(step); m.Steps.Add(step); m.ActiveStepId=step.Id; branch.ActiveStepId=step.Id; branch.CertificateHash=ExpeditionKernel.HashText(branch.Id+"|"+branch.Name+"|"+branch.Question+"|"+branch.Hypothesis+"|"+branch.ActiveStepId);
            ExpeditionArtifact a = new ExpeditionArtifact { Id=ExpeditionKernel.NewId("ART"), BranchId=branch.Id, StepId=step.Id, Kind="SOURCE_SNAPSHOT", Label=label, Civilization=civilization, SourceId=sourceId, SourceFingerprint=fp, Note=rule }; a.CertificateHash=ExpeditionKernel.HashText(a.Id+"|"+a.StepId+"|"+a.SourceFingerprint); m.Artifacts.Add(a); step.ArtifactIds.Add(a.Id); Touch(m); Save(ctx); AppendLedger(ctx,"CROSSING",m,branch,step,civilization+" source "+sourceId+" fp "+ExpeditionKernel.Short(fp)); Open(owner,ctx);
        }

        private static void NewMission(Window owner, DeepSystemsContext ctx) { string q=Prompt(owner,"NEW EXPEDITION","Question",""); if(String.IsNullOrWhiteSpace(q))return; ExpeditionMission m=ExpeditionKernel.Starter(q); Store.Missions.Insert(0,m); Store.ActiveMissionId=m.Id; Save(ctx); AppendLedger(ctx,"MISSION_CREATED",m,ActiveBranch(m),null,q); Open(owner,ctx); }
        private static void OpenMissions(Window owner, DeepSystemsContext ctx) { ExpeditionMission m=Choose<ExpeditionMission>(owner,"MISSION REGISTRY",Store.Missions); if(m==null)return; Store.ActiveMissionId=m.Id; Save(ctx); Open(owner,ctx); }
        private static void ShowMissionCharter(Window owner) { WithMission(owner,delegate(ExpeditionMission m){ List<object> rows=new List<object>{m,"ROOT FINGERPRINT   ·   "+ExpeditionKernel.Fingerprint(m),"ACTIVE BRANCH   ·   "+m.ActiveBranchId,"ACTIVE STEP   ·   "+(m.ActiveStepId??"∅"),"OBJECTIVE   ·   "+m.Objective}; OpenCollection(owner,"MISSION CHARTER · "+m.Title,rows,"Mission identity and authority boundary."); }); }
        private static void MissionCockpit(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch b=ActiveBranch(m); ExpeditionStep s=ActiveStep(m); List<object> rows=new List<object>{m,b??(object)"NO ACTIVE BRANCH",s??(object)"NO ACTIVE STEP","OPEN QUESTIONS   ·   "+m.Questions.Count(x=>Eq(x.Status,"OPEN")),"OPEN CONTRADICTIONS   ·   "+m.Contradictions.Count(x=>Eq(x.Status,"OPEN")),"ASSUMPTIONS   ·   "+m.Assumptions.Count,"FINDINGS   ·   "+m.Findings.Count,"CHECKPOINTS   ·   "+m.Checkpoints.Count,"ROOT   ·   "+ExpeditionKernel.Fingerprint(m)}; OpenCollection(owner,"ACTIVE MISSION COCKPIT · "+m.Title,rows,"This is the mission head, not a flattened summary of its history."); }); }
        private static void CoverageMatrix(Window owner) { WithMission(owner,delegate(ExpeditionMission m){ List<object> rows=new List<object>(); foreach(string civ in ExpeditionKernel.Civilizations){ List<ExpeditionStep> xs=m.Steps.Where(x=>Eq(x.Civilization,civ)).ToList(); rows.Add(civ+"   ·   visits "+xs.Count+"   ·   branches "+xs.Select(x=>x.BranchId).Distinct().Count()+"   ·   fingerprints "+xs.Where(x=>x.Source!=null).Select(x=>x.Source.SourceFingerprint).Distinct().Count()+"   ·   "+(xs.Count==0?"FRONTIER":"VISITED")); } OpenCollection(owner,"CIVILIZATION COVERAGE MATRIX · "+m.Title,rows,"Seventeen concrete civilization frontiers."); }); }
        private static void RoutePlanner(Window owner, DeepSystemsContext ctx, bool frontierOnly) { WithMission(owner,delegate(ExpeditionMission m){ List<ExpeditionRouteSuggestion> rows=ExpeditionKernel.SuggestRoutes(m); if(frontierOnly) rows=rows.Where(x=>!x.Visited).ToList(); Window w=W(owner,"YOMI · "+(frontierOnly?"FRONTIER RECOMMENDATIONS":"ROUTE PLANNER"),1180,760); DockPanel root=Shell(frontierOnly?"FRONTIER RECOMMENDATIONS":"ROUTE PLANNER","Double-click a civilization to open it. Route ranking is a transparent keyword/frontier heuristic, not autonomous research authority."); ListBox list=List(); list.ItemsSource=rows; list.MouseDoubleClick+=delegate { ExpeditionRouteSuggestion r=list.SelectedItem as ExpeditionRouteSuggestion; if(r!=null) OpenCivilization(r.Civilization,w,ctx); }; root.Children.Add(list); w.Content=root; w.Show(); }); }
        private static void CurrentStep(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionStep s=ActiveStep(m); if(s==null)return; List<object> rows=new List<object>{s,s.Source??(object)"NO SOURCE","STEP FINGERPRINT   ·   "+ExpeditionKernel.FingerprintStep(s),"WINDOW ROUTES"}; rows.AddRange(s.WindowRoutes.Cast<object>()); rows.AddRange(m.Findings.Where(x=>x.StepId==s.Id).Cast<object>()); rows.AddRange(m.Artifacts.Where(x=>x.StepId==s.Id).Cast<object>()); OpenCollection(owner,"CURRENT STEP MICROSCOPE · "+s.Id,rows,"Everything bound to the active crossing."); }); }
        private static void SourceVault(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionStep s=Choose<ExpeditionStep>(owner,"CAPTURED SOURCE VAULT",m.Steps.Where(x=>x.Source!=null).OrderByDescending(x=>x.Sequence).ToList()); if(s!=null) OpenSourceSnapshot(owner,ctx,s); }); }
        private static void AddFinding(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch b=ActiveBranch(m); ExpeditionStep s=ActiveStep(m); if(b==null)return; string text=Prompt(owner,"FINDING FORGE","Finding",""); if(String.IsNullOrWhiteSpace(text))return; string confText=Prompt(owner,"FINDING CONFIDENCE","0.0 to 1.0","0.7"); double conf=.7; Double.TryParse(confText,NumberStyles.Float,CultureInfo.InvariantCulture,out conf); conf=Math.Max(0,Math.Min(1,conf)); ExpeditionFinding f=new ExpeditionFinding{Id=ExpeditionKernel.NewId("FIND"),BranchId=b.Id,StepId=s==null?null:s.Id,Text=text,Confidence=conf}; if(s!=null){f.SourceStepIds.Add(s.Id);s.FindingIds.Add(f.Id);} f.CertificateHash=ExpeditionKernel.HashText(f.Id+"|"+f.BranchId+"|"+f.StepId+"|"+f.Text+"|"+conf.ToString("R",CultureInfo.InvariantCulture)); m.Findings.Add(f); if(s!=null){s.FindingSummary=text;s.CertificateHash=ExpeditionKernel.FingerprintStep(s);} Touch(m); Save(ctx); AppendLedger(ctx,"FINDING",m,b,s,text); }); }
        private static void AddQuestion(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch b=ActiveBranch(m); if(b==null)return; string text=Prompt(owner,"QUESTION FORGE","Next question",""); if(String.IsNullOrWhiteSpace(text))return; ExpeditionQuestion parent=m.Questions.Where(x=>x.BranchId==b.Id&&Eq(x.Status,"OPEN")).LastOrDefault(); ExpeditionQuestion q=new ExpeditionQuestion{Id=ExpeditionKernel.NewId("Q"),BranchId=b.Id,ParentQuestionId=parent==null?null:parent.Id,Text=text}; q.CertificateHash=ExpeditionKernel.HashText(q.Id+"|"+q.BranchId+"|"+q.ParentQuestionId+"|"+q.Text); m.Questions.Add(q); ExpeditionStep s=ActiveStep(m); if(s!=null){s.NextQuestion=text;s.CertificateHash=ExpeditionKernel.FingerprintStep(s);} Touch(m); Save(ctx); AppendLedger(ctx,"QUESTION",m,b,s,text); }); }
        private static void ResearchDebt(Window owner) { WithMission(owner,delegate(ExpeditionMission m){ List<object> rows=new List<object>(); rows.AddRange(m.Questions.Where(x=>Eq(x.Status,"OPEN")).Cast<object>()); rows.AddRange(m.Contradictions.Where(x=>Eq(x.Status,"OPEN")).Cast<object>()); rows.AddRange(m.Assumptions.Where(x=>Eq(x.Status,"ACTIVE")).Cast<object>()); OpenCollection(owner,"RESEARCH DEBT · "+m.Title,rows,"Open questions + contradictions + assumptions are retained work, not clutter."); }); }
        private static void AddContradiction(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ if(m.Findings.Count<2)return; ExpeditionFinding a=Choose<ExpeditionFinding>(owner,"CONTRADICTION · LEFT FINDING",m.Findings); if(a==null)return; ExpeditionFinding b=Choose<ExpeditionFinding>(owner,"CONTRADICTION · RIGHT FINDING",m.Findings.Where(x=>x.Id!=a.Id).ToList()); if(b==null)return; string d=Prompt(owner,"CONTRADICTION REGISTER","Describe the conflict",a.Text+"  VS  "+b.Text); if(String.IsNullOrWhiteSpace(d))return; ExpeditionContradiction c=new ExpeditionContradiction{Id=ExpeditionKernel.NewId("CONTRA"),BranchId=ActiveBranch(m)==null?m.ActiveBranchId:ActiveBranch(m).Id,LeftFindingId=a.Id,RightFindingId=b.Id,Description=d}; c.CertificateHash=ExpeditionKernel.HashText(c.Id+"|"+c.LeftFindingId+"|"+c.RightFindingId+"|"+c.Description); m.Contradictions.Add(c); Touch(m); Save(ctx); AppendLedger(ctx,"CONTRADICTION",m,ActiveBranch(m),ActiveStep(m),d); }); }
        private static void HypothesisBoard(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch b=Choose<ExpeditionBranch>(owner,"HYPOTHESIS BOARD",m.Branches); if(b==null)return; string h=Prompt(owner,"BRANCH HYPOTHESIS",b.Name,b.Hypothesis); if(h==null)return; b.Hypothesis=h;b.CertificateHash=ExpeditionKernel.HashText(b.Id+"|"+b.Name+"|"+b.Question+"|"+b.Hypothesis+"|"+b.ActiveStepId); Touch(m);Save(ctx);AppendLedger(ctx,"HYPOTHESIS",m,b,ActiveStep(m),h); }); }
        private static void AddAssumption(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch b=ActiveBranch(m); if(b==null)return; string t=Prompt(owner,"ASSUMPTION BOARD","Assumption",""); if(String.IsNullOrWhiteSpace(t))return; ExpeditionAssumption a=new ExpeditionAssumption{Id=ExpeditionKernel.NewId("ASM"),BranchId=b.Id,Text=t}; ExpeditionStep s=ActiveStep(m); if(s!=null)a.SourceStepIds.Add(s.Id);a.CertificateHash=ExpeditionKernel.HashText(a.Id+"|"+a.BranchId+"|"+a.Text+"|"+String.Join(",",a.SourceStepIds.ToArray()));m.Assumptions.Add(a);Touch(m);Save(ctx);AppendLedger(ctx,"ASSUMPTION",m,b,s,t); }); }
        private static void AddDecision(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch b=ActiveBranch(m); if(b==null)return; string d=Prompt(owner,"DECISION LOG","Decision",""); if(String.IsNullOrWhiteSpace(d))return; string r=Prompt(owner,"DECISION RATIONALE","Rationale",""); ExpeditionDecision x=new ExpeditionDecision{Id=ExpeditionKernel.NewId("DEC"),BranchId=b.Id,StepId=m.ActiveStepId,Decision=d,Rationale=r}; x.FindingIds.AddRange(m.Findings.Where(f=>f.BranchId==b.Id).OrderByDescending(f=>f.CreatedUtc).Take(4).Select(f=>f.Id));x.CertificateHash=ExpeditionKernel.HashText(x.Id+"|"+x.BranchId+"|"+x.StepId+"|"+x.Decision+"|"+x.Rationale+"|"+String.Join(",",x.FindingIds.ToArray()));m.Decisions.Add(x);Touch(m);Save(ctx);AppendLedger(ctx,"DECISION",m,b,ActiveStep(m),d); }); }
        private static void CheckpointVault(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ Window w=W(owner,"YOMI · CHECKPOINT VAULT",1180,760);DockPanel root=Shell("CHECKPOINT VAULT","Double-click to resume. Checkpoints restore mission/branch/step worldline state and retain the live window-route constellation captured at that moment.");ListBox list=List();list.ItemsSource=m.Checkpoints.OrderByDescending(x=>x.CreatedUtc).ToList();list.MouseDoubleClick+=delegate{ExpeditionCheckpoint c=list.SelectedItem as ExpeditionCheckpoint;if(c!=null)Resume(m,c,w,ctx);};root.Children.Add(list);w.Content=root;w.Show(); }); }
        private static void ResumeCheckpoint(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionCheckpoint c=Choose<ExpeditionCheckpoint>(owner,"RESUME CHECKPOINT",m.Checkpoints.OrderByDescending(x=>x.CreatedUtc).ToList());if(c!=null)Resume(m,c,owner,ctx); }); }
        private static void ResumeCurrent(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionStep s=ActiveStep(m);if(s!=null)OpenResumeCapsule(owner,ctx,m,s,null); }); }
        private static void ForkBranch(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch parent=ActiveBranch(m);if(parent==null)return;string name=Prompt(owner,"FORK BRANCH","Branch name","branch-"+(m.Branches.Count+1));if(String.IsNullOrWhiteSpace(name))return;string q=Prompt(owner,"FORK QUESTION","Question for this branch",CurrentQuestion(m,parent));if(String.IsNullOrWhiteSpace(q))return;string h=Prompt(owner,"FORK HYPOTHESIS","Hypothesis","Alternative explanation to test.");ExpeditionBranch b=new ExpeditionBranch{Id=ExpeditionKernel.NewId("BRANCH"),Name=name.Trim(),ParentBranchId=parent.Id,ForkStepId=m.ActiveStepId,Question=q,Hypothesis=h,ActiveStepId=m.ActiveStepId};b.CertificateHash=ExpeditionKernel.HashText(b.Id+"|"+b.Name+"|"+b.ParentBranchId+"|"+b.ForkStepId+"|"+b.Question+"|"+b.Hypothesis);m.Branches.Add(b);ExpeditionQuestion eq=new ExpeditionQuestion{Id=ExpeditionKernel.NewId("Q"),BranchId=b.Id,Text=q};eq.CertificateHash=ExpeditionKernel.HashText(eq.Id+"|"+eq.BranchId+"|"+eq.Text);m.Questions.Add(eq);m.ActiveBranchId=b.Id;Touch(m);Save(ctx);AppendLedger(ctx,"BRANCH_FORK",m,b,ActiveStep(m),"fork from "+parent.Id+" at "+(m.ActiveStepId??"∅")); }); }
        private static void BranchDiff(Window owner) { WithMission(owner,delegate(ExpeditionMission m){ if(m.Branches.Count<2)return;ExpeditionBranch a=Choose<ExpeditionBranch>(owner,"BRANCH DIFF · LEFT",m.Branches);if(a==null)return;ExpeditionBranch b=Choose<ExpeditionBranch>(owner,"BRANCH DIFF · RIGHT",m.Branches.Where(x=>x.Id!=a.Id).ToList());if(b==null)return;ExpeditionBranchDiff d=ExpeditionKernel.DiffBranches(m,a.Id,b.Id);List<object> rows=new List<object>{d,"LEFT ONLY CIVILIZATIONS"};rows.AddRange(d.OnlyLeftCivilizations.Cast<object>());rows.Add("RIGHT ONLY CIVILIZATIONS");rows.AddRange(d.OnlyRightCivilizations.Cast<object>());rows.Add("LEFT ONLY FINDINGS");rows.AddRange(d.OnlyLeftFindings.Cast<object>());rows.Add("RIGHT ONLY FINDINGS");rows.AddRange(d.OnlyRightFindings.Cast<object>());OpenCollection(owner,"BRANCH DIFF · "+a.Name+" ↔ "+b.Name,rows,"Comparison preserves both branches."); }); }
        private static void MergeMemo(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ if(m.Branches.Count<2||m.Findings.Count<1)return;string text=Prompt(owner,"MERGE MEMO","Synthesis across branches","");if(String.IsNullOrWhiteSpace(text))return;ExpeditionBranch b=ActiveBranch(m);ExpeditionFinding f=new ExpeditionFinding{Id=ExpeditionKernel.NewId("MERGE"),BranchId=b.Id,StepId=m.ActiveStepId,Text=text,Kind="BRANCH_SYNTHESIS",Confidence=.5};f.SourceStepIds.AddRange(m.Findings.SelectMany(x=>x.SourceStepIds).Distinct().Take(64));f.Challenges.Add("Synthesis preserves source branches; it does not erase disagreement.");f.CertificateHash=ExpeditionKernel.HashText(f.Id+"|"+f.Text+"|"+String.Join(",",f.SourceStepIds.ToArray()));m.Findings.Add(f);Touch(m);Save(ctx);AppendLedger(ctx,"MERGE_MEMO",m,b,ActiveStep(m),text); }); }
        private static void DeadEndLedger(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionBranch b=Choose<ExpeditionBranch>(owner,"DEAD-END LEDGER",m.Branches);if(b==null)return;MessageBoxResult r=MessageBox.Show("Mark branch '"+b.Name+"' as RETIRED? Its history will remain intact.","YOMI · DEAD-END LEDGER",MessageBoxButton.YesNo,MessageBoxImage.Question);if(r==MessageBoxResult.Yes){b.Status="RETIRED";Touch(m);Save(ctx);AppendLedger(ctx,"BRANCH_RETIRED",m,b,ActiveStep(m),b.Name);} }); }
        private static void Backtrack(Window owner) { WithMission(owner,delegate(ExpeditionMission m){ ExpeditionStep s=ActiveStep(m);List<object> rows=new List<object>();HashSet<string> seen=new HashSet<string>(StringComparer.Ordinal);while(s!=null&&seen.Add(s.Id)){rows.Add(s);s=m.Steps.FirstOrDefault(x=>x.Id==s.ParentStepId);}OpenCollection(owner,"BACKTRACK NAVIGATOR · "+m.Title,rows,"Active head back through parent-step ancestry."); }); }
        private static void FingerprintRadar(Window owner) { WithMission(owner,delegate(ExpeditionMission m){List<object> rows=m.Steps.Where(x=>x.Source!=null).GroupBy(x=>(x.Civilization??"")+"|"+(x.Source.SourceId??""),StringComparer.OrdinalIgnoreCase).OrderBy(g=>g.Key).Select(g=>(object)(g.Key+"   ·   observations "+g.Count()+"   ·   fingerprints "+g.Select(x=>x.Source.SourceFingerprint).Distinct(StringComparer.OrdinalIgnoreCase).Count()+"   ·   "+String.Join(", ",g.Select(x=>ExpeditionKernel.Short(x.Source.SourceFingerprint)).Distinct().ToArray()))).ToList();OpenCollection(owner,"SOURCE FINGERPRINT RADAR · "+m.Title,rows,"Same source identity can recur with a different captured fingerprint.");}); }
        private static void DriftRadar(Window owner) { WithMission(owner,delegate(ExpeditionMission m){List<object> rows=m.Steps.Where(x=>x.Source!=null).GroupBy(x=>(x.Civilization??"")+"|"+(x.Source.SourceId??""),StringComparer.OrdinalIgnoreCase).Where(g=>g.Select(x=>x.Source.SourceFingerprint).Distinct(StringComparer.OrdinalIgnoreCase).Count()>1).Select(g=>(object)("DRIFT   ·   "+g.Key+"   ·   "+String.Join(" → ",g.OrderBy(x=>x.Sequence).Select(x=>ExpeditionKernel.Short(x.Source.SourceFingerprint)).ToArray()))).ToList();OpenCollection(owner,"UPSTREAM DRIFT RADAR · "+m.Title,rows,"Drift means the retained source snapshot changed; it does not itself explain why.");}); }
        private static void MissionImpact(Window owner) { WithMission(owner,delegate(ExpeditionMission m){ExpeditionStep s=Choose<ExpeditionStep>(owner,"MISSION IMPACT · SOURCE STEP",m.Steps.OrderByDescending(x=>x.Sequence).ToList());if(s==null)return;List<object> rows=new List<object>{s};rows.AddRange(m.Findings.Where(x=>x.SourceStepIds.Contains(s.Id)||x.StepId==s.Id).Cast<object>());rows.AddRange(m.Artifacts.Where(x=>x.StepId==s.Id).Cast<object>());rows.AddRange(m.Checkpoints.Where(x=>x.StepId==s.Id).Cast<object>());rows.AddRange(m.Questions.Where(x=>x.BranchId==s.BranchId&&x.CreatedUtc.CompareTo(s.EnteredUtc)>=0).Cast<object>());OpenCollection(owner,"MISSION IMPACT · "+s.Id,rows,"Explicit worldline consequence only; no semantic edge is invented.");}); }
        private static void MissionGraph(Window owner) { WithMission(owner,delegate(ExpeditionMission m){StringBuilder b=new StringBuilder();b.AppendLine("MISSION "+m.Id+"  fp "+ExpeditionKernel.Fingerprint(m));foreach(ExpeditionBranch br in m.Branches){b.AppendLine();b.AppendLine("BRANCH "+br.Name+" ["+br.Id+"] parent="+(br.ParentBranchId??"∅")+" fork="+(br.ForkStepId??"∅"));foreach(ExpeditionStep s in m.Steps.Where(x=>x.BranchId==br.Id).OrderBy(x=>x.Sequence)){b.AppendLine("  STEP "+s.Sequence+" "+s.Id+" <- "+(s.ParentStepId??"∅")+" :: "+s.Civilization+" :: "+(s.Source==null?"∅":s.Source.SourceId)+" fp "+(s.Source==null?"∅":ExpeditionKernel.Short(s.Source.SourceFingerprint)));foreach(ExpeditionFinding f in m.Findings.Where(x=>x.StepId==s.Id))b.AppendLine("    FIND "+f.Id+" :: "+f.Text);foreach(ExpeditionCheckpoint c in m.Checkpoints.Where(x=>x.StepId==s.Id))b.AppendLine("    CHECKPOINT "+c.Id+" :: "+c.Name);}}TextView(owner,"MISSION WORLDLINE GRAPH",b.ToString());}); }
        private static void CrossTrace(Window owner) { WithMission(owner,delegate(ExpeditionMission m){string q=Prompt(owner,"CROSS-SYSTEM TRACE","Search token","");if(String.IsNullOrWhiteSpace(q))return;string t=q.Trim();List<object> rows=new List<object>();rows.AddRange(m.Steps.Where(x=>Contains(x.Civilization,t)||Contains(x.Route,t)||(x.Source!=null&&(Contains(x.Source.SourceId,t)||Contains(x.Source.SourceFingerprint,t)||Contains(x.Source.Label,t)))).Cast<object>());rows.AddRange(m.Findings.Where(x=>Contains(x.Text,t)).Cast<object>());rows.AddRange(m.Questions.Where(x=>Contains(x.Text,t)).Cast<object>());rows.AddRange(m.Artifacts.Where(x=>Contains(x.Label,t)||Contains(x.SourceId,t)||Contains(x.SourceFingerprint,t)||Contains(x.Note,t)).Cast<object>());OpenCollection(owner,"CROSS-SYSTEM TRACE · "+t,rows,"Searches retained expedition evidence only.");}); }
        private static void HandoffMatrix(Window owner) { WithMission(owner,delegate(ExpeditionMission m){Dictionary<string,int> counts=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);foreach(ExpeditionBranch b in m.Branches){List<ExpeditionStep> xs=m.Steps.Where(x=>x.BranchId==b.Id).OrderBy(x=>x.Sequence).ToList();for(int i=1;i<xs.Count;i++){string k=xs[i-1].Civilization+" → "+xs[i].Civilization;counts[k]=counts.ContainsKey(k)?counts[k]+1:1;}}OpenCollection(owner,"CIVILIZATION HAND-OFF MATRIX · "+m.Title,counts.OrderByDescending(x=>x.Value).ThenBy(x=>x.Key).Select(x=>(object)(x.Value.ToString("000",CultureInfo.InvariantCulture)+"   ·   "+x.Key)).ToList(),"Directed transitions along retained branch trails.");}); }
        private static void WindowConstellation(Window owner, DeepSystemsContext ctx) { List<string> routes=DeepSystems.ExpeditionWindowRoutes();OpenCollection(owner,"WINDOW CONSTELLATION SNAPSHOT",routes.Cast<object>().ToList(),"These routes can be frozen into the next expedition checkpoint."); }
        private static void SessionContinuity(Window owner) { WithMission(owner,delegate(ExpeditionMission m){List<object> rows=new List<object>{m};foreach(ExpeditionBranch b in m.Branches)rows.Add(b);rows.Add("LATEST CHECKPOINTS");rows.AddRange(m.Checkpoints.OrderByDescending(x=>x.CreatedUtc).Take(20).Cast<object>());rows.Add("ACTIVE STEP");rows.Add(ActiveStep(m)??(object)"∅");OpenCollection(owner,"SESSION CONTINUITY · "+m.Title,rows,"The answer to 'where was I?' is persisted state, not memory.");}); }
        private static void CreateCheckpoint(Window owner, DeepSystemsContext ctx, string prefix) { WithMission(owner,delegate(ExpeditionMission m){ExpeditionBranch b=ActiveBranch(m);ExpeditionStep s=ActiveStep(m);string name=Prompt(owner,prefix+" CHECKPOINT","Name",prefix.ToLowerInvariant()+"-"+(m.Checkpoints.Count+1));if(String.IsNullOrWhiteSpace(name))return;string note=Prompt(owner,prefix+" CHECKPOINT","Resume note",s==null?"":(s.NextQuestion??s.FindingSummary??s.Intent));ExpeditionCheckpoint c=new ExpeditionCheckpoint{Id=ExpeditionKernel.NewId("CP"),MissionId=m.Id,BranchId=b==null?m.ActiveBranchId:b.Id,StepId=s==null?null:s.Id,Name=name,Note=note,MissionFingerprint=ExpeditionKernel.Fingerprint(m),SourceFingerprint=s==null||s.Source==null?null:s.Source.SourceFingerprint,WindowRoutes=DeepSystems.ExpeditionWindowRoutes()};c.CertificateHash=ExpeditionKernel.HashText(c.Id+"|"+c.MissionId+"|"+c.BranchId+"|"+c.StepId+"|"+c.MissionFingerprint+"|"+c.SourceFingerprint+"|"+String.Join("\n",c.WindowRoutes.ToArray()));m.Checkpoints.Insert(0,c);Touch(m);Save(ctx);AppendLedger(ctx,"CHECKPOINT",m,b,s,name);}); }
        private static void SealMission(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){List<ExpeditionValidationFinding> findings=ExpeditionKernel.Validate(m);if(findings.Any(x=>Eq(x.Severity,"ERROR"))){OpenCollection(owner,"MISSION SEAL REFUSED",findings.Cast<object>().ToList(),"Structural errors must be repaired before sealing.");return;}ExpeditionSeal s=ExpeditionKernel.Seal(m);m.Seals.Insert(0,s);Touch(m);Save(ctx);AppendLedger(ctx,"MISSION_SEAL",m,ActiveBranch(m),ActiveStep(m),s.CertificateHash);OpenCollection(owner,"MISSION SEALED",new List<object>{s},"Seal binds the mission graph identity; it is not an external truth certificate.");}); }
        private static void ExportMission(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){string fp=ExpeditionKernel.Fingerprint(m);string dir=Path.Combine(ctx.DataRoot,"deep-systems","expeditions");Directory.CreateDirectory(dir);string stem=SafeName(m.Title)+"-"+ExpeditionKernel.Short(fp);string jsonPath=Path.Combine(dir,stem+".json"),mdPath=Path.Combine(dir,stem+".md");File.WriteAllText(jsonPath,Json.Serialize(m),new UTF8Encoding(false));File.WriteAllText(mdPath,RenderMission(m),new UTF8Encoding(false));AppendLedger(ctx,"EXPORT",m,ActiveBranch(m),ActiveStep(m),jsonPath);MessageBox.Show("Expedition capsule written locally:\n\n"+jsonPath+"\n"+mdPath,"YOMI · EXPEDITION EXPORT",MessageBoxButton.OK,MessageBoxImage.Information);}); }
        private static void MissionAutopsy(Window owner, DeepSystemsContext ctx) { WithMission(owner,delegate(ExpeditionMission m){List<object> rows=new List<object>();rows.AddRange(ExpeditionKernel.Validate(m).Cast<object>());List<ExpeditionLedgerRecord> ledger=ReadLedger(ctx);rows.Add("LEDGER   ·   "+(VerifyLedger(ledger)?"VALID":"INVALID"));rows.AddRange(ledger.OrderByDescending(x=>x.Sequence).Take(256).Cast<object>());rows.Add("MISSION ROOT   ·   "+ExpeditionKernel.Fingerprint(m));OpenCollection(owner,"MISSION AUTOPSY · "+m.Title,rows,"Structural audit only. It does not certify the truth of findings.");}); }

        private static void Resume(ExpeditionMission m, ExpeditionCheckpoint c, Window owner, DeepSystemsContext ctx) { if(m==null||c==null)return;m.ActiveBranchId=c.BranchId;m.ActiveStepId=c.StepId;ExpeditionBranch b=m.Branches.FirstOrDefault(x=>x.Id==c.BranchId);if(b!=null)b.ActiveStepId=c.StepId;Touch(m);Save(ctx);AppendLedger(ctx,"RESUME",m,b,m.Steps.FirstOrDefault(x=>x.Id==c.StepId),c.Id);OpenResumeCapsule(owner,ctx,m,m.Steps.FirstOrDefault(x=>x.Id==c.StepId),c); }
        private static void OpenResumeCapsule(Window owner, DeepSystemsContext ctx, ExpeditionMission m, ExpeditionStep s, ExpeditionCheckpoint c) { if(s==null)return;Window w=W(owner,"YOMI · EXACT RESUME CAPSULE",1240,820);DockPanel root=Shell("EXACT RESUME CAPSULE",(c==null?"Current head":"Checkpoint "+c.Name)+" · branch "+s.BranchId+" · step "+s.Id+" · source fp "+(s.Source==null?"∅":ExpeditionKernel.Short(s.Source.SourceFingerprint)));WrapPanel tools=new WrapPanel{Margin=new Thickness(18,0,18,10)};SmallPortal(tools,"OPEN CAPTURED SOURCE",delegate{OpenSourceSnapshot(w,ctx,s);});SmallPortal(tools,"OPEN OWNING CIVILIZATION",delegate{OpenCivilization(s.Civilization,w,ctx);});SmallPortal(tools,"OPEN EXPEDITION COMMAND",delegate{Open(w,ctx);});SmallPortal(tools,"WORLD SPINE",delegate{WorldPassportSpine.CaptureAndOpen(w,ctx,m.Title+" · "+s.Id,"EXPEDITION_STEP","EXPΩ","expedition",s.Id,s,"","$mission/"+m.Id+"/step/"+s.Id);});DockPanel.SetDock(tools,Dock.Top);root.Children.Add(tools);List<object> rows=new List<object>{m,s,s.Source??(object)"NO SOURCE","RETAINED WINDOW ROUTES"};rows.AddRange((c==null?s.WindowRoutes:c.WindowRoutes).Cast<object>());rows.AddRange(m.Findings.Where(x=>x.StepId==s.Id).Cast<object>());OpenList(root,rows);w.Content=root;w.Show(); }
        private static void OpenSourceSnapshot(Window owner, DeepSystemsContext ctx, ExpeditionStep s) { if(s==null||s.Source==null)return;object value;try{value=Json.DeserializeObject(s.Source.SourceJson??"");}catch{value=s.Source.SourceJson;}DeepSystems.OpenExternalValue(owner,ctx,"EXPEDITION SOURCE · "+(s.Source.Label??s.Source.SourceId),value,"EXPΩ › RESUME › "+s.Civilization+" › "+s.Source.SourceId+" › "+ExpeditionKernel.Short(s.Source.SourceFingerprint)); }
        private static void OpenCivilization(string civilization, Window owner, DeepSystemsContext ctx)
        {
            string route = "atlas";
            if (Eq(civilization,"WORLD")) route="world";
            else if (Eq(civilization,"CIVILIZATION")) route="civilization";
            else if (Eq(civilization,"EPISTEMIC_LOGIC")) route="logic";
            else if (Eq(civilization,"VERIFICATION")) route="verification";
            else if (Eq(civilization,"STRATEGY")) route="strategy";
            else if (Eq(civilization,"SCIENTIFIC_DISCOVERY")) route="science";
            else if (Eq(civilization,"SYSTEMS_ENGINEERING")) route="engineering";
            else if (Eq(civilization,"CYBERNETIC_TWIN")) route="cybernetic";
            else if (Eq(civilization,"COMPLEX_SYSTEMS")) route="complex";
            else if (Eq(civilization,"OPERATIONS_RESEARCH")) route="or";
            else if (Eq(civilization,"ECONOMIC_CIVILIZATION")) route="economy";
            else if (Eq(civilization,"SPATIAL_CARTOGRAPHY")) route="spatial";
            else if (Eq(civilization,"DISTRIBUTED_SYSTEMS")) route="distributed";
            else if (Eq(civilization,"ADVERSARIAL_SECURITY")) route="security";
            else if (Eq(civilization,"DATA_FOUNDRY")) route="data";
            else if (Eq(civilization,"SOFTWARE_GENOME")) route="genome";
            else if (Eq(civilization,"LIVING_DOCUMENT")) route="documents";
            ExpeditionWorkspace.OpenRoute(owner,ctx,route,"EXPΩ civilization crossing");
        }

        private static void Touch(ExpeditionMission m) { if(m==null)return;m.UpdatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture);m.RootFingerprint=ExpeditionKernel.Fingerprint(m);TrimMission(m); }
        private static void TrimMission(ExpeditionMission m) { if(m.Steps.Count>MaxSteps)m.Steps=m.Steps.OrderByDescending(x=>x.Sequence).Take(MaxSteps).OrderBy(x=>x.Sequence).ToList();if(m.Findings.Count>MaxFindings)m.Findings=m.Findings.Take(MaxFindings).ToList();if(m.Questions.Count>MaxQuestions)m.Questions=m.Questions.Take(MaxQuestions).ToList();if(m.Artifacts.Count>MaxArtifacts)m.Artifacts=m.Artifacts.Take(MaxArtifacts).ToList();if(m.Checkpoints.Count>MaxCheckpoints)m.Checkpoints=m.Checkpoints.Take(MaxCheckpoints).ToList(); }
        private static ExpeditionMission ActiveMission() { if(Store==null||Store.Missions==null)return null;ExpeditionMission m=Store.Missions.FirstOrDefault(x=>x.Id==Store.ActiveMissionId);return m??Store.Missions.FirstOrDefault(); }
        private static ExpeditionBranch ActiveBranch(ExpeditionMission m) { return m==null?null:m.Branches.FirstOrDefault(x=>x.Id==m.ActiveBranchId)??m.Branches.FirstOrDefault(); }
        private static ExpeditionStep ActiveStep(ExpeditionMission m) { return m==null||String.IsNullOrWhiteSpace(m.ActiveStepId)?null:m.Steps.FirstOrDefault(x=>x.Id==m.ActiveStepId); }
        private static string CurrentQuestion(ExpeditionMission m, ExpeditionBranch b) { ExpeditionQuestion q=m.Questions.Where(x=>x.BranchId==b.Id&&Eq(x.Status,"OPEN")).LastOrDefault();return q==null?(b.Question??m.Question):q.Text; }
        private static void WithMission(Window owner, Action<ExpeditionMission> action) { ExpeditionMission m=ActiveMission();if(m==null){MessageBox.Show("No expedition exists yet. Create one from NEW EXPEDITION or enter from a civilization source.","YOMI · EXPΩ",MessageBoxButton.OK,MessageBoxImage.Information);return;}if(action!=null)action(m); }

        private static string StorePath(DeepSystemsContext ctx) { Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-grand-unified-expedition.json"); }
        private static string LedgerPath(DeepSystemsContext ctx) { Directory.CreateDirectory(ctx.StateRoot);return Path.Combine(ctx.StateRoot,"controller-grand-unified-expedition-ledger.jsonl"); }
        private static void Load(DeepSystemsContext ctx) { lock(Gate){if(Store!=null&&Eq(LoadedRoot,ctx.StateRoot))return;LoadedRoot=ctx.StateRoot;Store=null;string p=StorePath(ctx);if(File.Exists(p))try{Store=Json.Deserialize<ExpeditionCommandStore>(File.ReadAllText(p,Encoding.UTF8));}catch{PreserveCorrupt(p);}if(Store==null&&File.Exists(p+".previous"))try{Store=Json.Deserialize<ExpeditionCommandStore>(File.ReadAllText(p+".previous",Encoding.UTF8));}catch{}if(Store==null)Store=new ExpeditionCommandStore();Normalize();} }
        private static void Normalize() { if(Store==null)Store=new ExpeditionCommandStore();Store.Schema=1;if(Store.Missions==null)Store.Missions=new List<ExpeditionMission>();Store.Missions=Store.Missions.Where(x=>x!=null).Take(MaxMissions).ToList();foreach(ExpeditionMission m in Store.Missions)NormalizeMission(m);if(String.IsNullOrWhiteSpace(Store.ActiveMissionId)&&Store.Missions.Count>0)Store.ActiveMissionId=Store.Missions[0].Id; }
        private static void NormalizeMission(ExpeditionMission m) { if(m.Branches==null)m.Branches=new List<ExpeditionBranch>();if(m.Steps==null)m.Steps=new List<ExpeditionStep>();if(m.Findings==null)m.Findings=new List<ExpeditionFinding>();if(m.Questions==null)m.Questions=new List<ExpeditionQuestion>();if(m.Assumptions==null)m.Assumptions=new List<ExpeditionAssumption>();if(m.Contradictions==null)m.Contradictions=new List<ExpeditionContradiction>();if(m.Artifacts==null)m.Artifacts=new List<ExpeditionArtifact>();if(m.Checkpoints==null)m.Checkpoints=new List<ExpeditionCheckpoint>();if(m.Decisions==null)m.Decisions=new List<ExpeditionDecision>();if(m.Seals==null)m.Seals=new List<ExpeditionSeal>();if(m.Tags==null)m.Tags=new List<string>();foreach(ExpeditionStep s in m.Steps){if(s.WindowRoutes==null)s.WindowRoutes=new List<string>();if(s.FindingIds==null)s.FindingIds=new List<string>();if(s.ArtifactIds==null)s.ArtifactIds=new List<string>();}foreach(ExpeditionFinding f in m.Findings){if(f.SourceStepIds==null)f.SourceStepIds=new List<string>();if(f.Challenges==null)f.Challenges=new List<string>();}foreach(ExpeditionCheckpoint c in m.Checkpoints)if(c.WindowRoutes==null)c.WindowRoutes=new List<string>();TrimMission(m); }
        private static void Save(DeepSystemsContext ctx) { lock(Gate){Normalize();Store.Revision++;Store.UpdatedUtc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture);string p=StorePath(ctx),next=p+".next",prev=p+".previous";File.WriteAllText(next,Json.Serialize(Store),new UTF8Encoding(false));if(File.Exists(p))try{File.Copy(p,prev,true);}catch{}if(File.Exists(p))File.Delete(p);File.Move(next,p);} }
        private static void PreserveCorrupt(string p) { try{File.Copy(p,p+".corrupt-"+DateTime.UtcNow.ToString("yyyyMMddHHmmss",CultureInfo.InvariantCulture),true);}catch{} }
        private static void AppendLedger(DeepSystemsContext ctx,string ev,ExpeditionMission m,ExpeditionBranch b,ExpeditionStep s,string detail) { lock(Gate){List<ExpeditionLedgerRecord> old=ReadLedger(ctx);long seq=old.Count==0?1:old[old.Count-1].Sequence+1;string prev=old.Count==0?new string('0',64):old[old.Count-1].EntryHash;ExpeditionLedgerRecord r=new ExpeditionLedgerRecord{Schema=1,Sequence=seq,Utc=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture),Event=ev,MissionId=m==null?null:m.Id,BranchId=b==null?null:b.Id,StepId=s==null?null:s.Id,Detail=detail,MissionFingerprint=m==null?null:ExpeditionKernel.Fingerprint(m),PrevHash=prev};r.EntryHash=ExpeditionKernel.HashText(r.Schema+"|"+r.Sequence+"|"+r.Utc+"|"+r.Event+"|"+r.MissionId+"|"+r.BranchId+"|"+r.StepId+"|"+r.Detail+"|"+r.MissionFingerprint+"|"+r.PrevHash);File.AppendAllText(LedgerPath(ctx),Json.Serialize(r)+Environment.NewLine,new UTF8Encoding(false));} }
        private static List<ExpeditionLedgerRecord> ReadLedger(DeepSystemsContext ctx) { List<ExpeditionLedgerRecord> r=new List<ExpeditionLedgerRecord>();string p=LedgerPath(ctx);if(!File.Exists(p))return r;Queue<string> q=new Queue<string>();foreach(string line in File.ReadLines(p)){q.Enqueue(line);if(q.Count>MaxLedgerRead)q.Dequeue();}foreach(string line in q){if(String.IsNullOrWhiteSpace(line))continue;try{ExpeditionLedgerRecord x=Json.Deserialize<ExpeditionLedgerRecord>(line);if(x!=null)r.Add(x);}catch{}}return r; }
        private static bool VerifyLedger(List<ExpeditionLedgerRecord> xs) { if(xs==null||xs.Count==0)return true;for(int i=0;i<xs.Count;i++){ExpeditionLedgerRecord r=xs[i];if(i>0&&!Eq(r.PrevHash,xs[i-1].EntryHash))return false;string h=ExpeditionKernel.HashText(r.Schema+"|"+r.Sequence+"|"+r.Utc+"|"+r.Event+"|"+r.MissionId+"|"+r.BranchId+"|"+r.StepId+"|"+r.Detail+"|"+r.MissionFingerprint+"|"+r.PrevHash);if(!Eq(h,r.EntryHash))return false;}return true; }

        private static string SerializeBounded(object source) { string json;try{json=Json.Serialize(source);}catch{json=Json.Serialize(new Dictionary<string,object>{{"type",source==null?"null":source.GetType().FullName},{"text",source==null?"":source.ToString()},{"serialization_error",true}});}if(json.Length<=MaxSourceChars)return json;return Json.Serialize(new Dictionary<string,object>{{"type",source==null?"null":source.GetType().FullName},{"text",source==null?"":source.ToString()},{"original_chars",json.Length},{"capped",true},{"prefix_sha256",ExpeditionKernel.HashText(json)}}); }
        private static string ReadId(object source) { if(source==null)return "UNKNOWN";try{PropertyInfo p=source.GetType().GetProperty("Id",BindingFlags.Public|BindingFlags.Instance|BindingFlags.IgnoreCase);object v=p==null?null:p.GetValue(source,null);return v==null?source.GetType().Name:Convert.ToString(v,CultureInfo.InvariantCulture);}catch{return source.GetType().Name;} }
        private static string ReadLabel(object source) { if(source==null)return "UNKNOWN";foreach(string n in new[]{"Title","Name","Label","Id"})try{PropertyInfo p=source.GetType().GetProperty(n,BindingFlags.Public|BindingFlags.Instance|BindingFlags.IgnoreCase);object v=p==null?null:p.GetValue(source,null);if(v!=null&&!String.IsNullOrWhiteSpace(Convert.ToString(v,CultureInfo.InvariantCulture)))return Convert.ToString(v,CultureInfo.InvariantCulture);}catch{}return source.GetType().Name; }
        private static string RenderMission(ExpeditionMission m) { StringBuilder b=new StringBuilder();b.AppendLine("# "+(m.Title??"Expedition"));b.AppendLine();b.AppendLine("**Question:** "+m.Question);b.AppendLine();b.AppendLine("**Mission fingerprint:** `"+ExpeditionKernel.Fingerprint(m)+"`");b.AppendLine();foreach(ExpeditionBranch br in m.Branches){b.AppendLine("## Branch: "+br.Name);b.AppendLine();b.AppendLine("Question: "+br.Question);b.AppendLine();b.AppendLine("Hypothesis: "+br.Hypothesis);b.AppendLine();foreach(ExpeditionStep s in m.Steps.Where(x=>x.BranchId==br.Id).OrderBy(x=>x.Sequence)){b.AppendLine("### Step "+s.Sequence+" — "+s.Civilization);b.AppendLine();b.AppendLine("Source: "+(s.Source==null?"∅":(s.Source.Label+" (`"+s.Source.SourceFingerprint+"`)")));b.AppendLine();foreach(ExpeditionFinding f in m.Findings.Where(x=>x.StepId==s.Id)){b.AppendLine("- Finding: "+f.Text+" (confidence "+f.Confidence.ToString("P0",CultureInfo.InvariantCulture)+")");}b.AppendLine();}}b.AppendLine("## Open questions");b.AppendLine();foreach(ExpeditionQuestion q in m.Questions.Where(x=>Eq(x.Status,"OPEN")))b.AppendLine("- "+q.Text);b.AppendLine();b.AppendLine("## Contradictions");b.AppendLine();foreach(ExpeditionContradiction c in m.Contradictions)b.AppendLine("- ["+c.Status+"] "+c.Description);return b.ToString(); }
        private static string SafeName(string s) { if(String.IsNullOrWhiteSpace(s))return "expedition";StringBuilder b=new StringBuilder();foreach(char c in s)b.Append(Char.IsLetterOrDigit(c)?c:'-');string x=b.ToString().Trim('-');while(x.Contains("--"))x=x.Replace("--","-");return x.Length>80?x.Substring(0,80):x; }
        private static bool Eq(string a,string b) { return String.Equals(a,b,StringComparison.OrdinalIgnoreCase); }
        private static bool Contains(string a,string b) { return !String.IsNullOrWhiteSpace(a)&&!String.IsNullOrWhiteSpace(b)&&a.IndexOf(b,StringComparison.OrdinalIgnoreCase)>=0; }

        private static T Choose<T>(Window owner,string title,IList<T> items) where T:class { if(items==null||items.Count==0)return null;Window w=W(owner,"YOMI · "+title,1040,720);DockPanel root=Shell(title,"Double-click to select.");ListBox list=List();list.ItemsSource=items;T selected=null;list.MouseDoubleClick+=delegate{selected=list.SelectedItem as T;w.DialogResult=selected!=null;w.Close();};root.Children.Add(list);w.Content=root;bool? r=w.ShowDialog();return r==true?selected:null; }
        private static Window W(Window owner,string title,double width,double height) { return new Window{Title=title,Width=width,Height=height,Background=Bg,Foreground=Text,WindowStartupLocation=owner==null?WindowStartupLocation.CenterScreen:WindowStartupLocation.CenterOwner,Owner=owner}; }
        private static DockPanel Shell(string title,string subtitle) { DockPanel root=new DockPanel{Background=Bg};StackPanel head=new StackPanel{Margin=new Thickness(20,18,20,10)};head.Children.Add(new TextBlock{Text=title,Foreground=Text,FontSize=25,FontWeight=FontWeights.Bold});head.Children.Add(new TextBlock{Text=subtitle??"",Foreground=Muted,FontSize=13,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,5,0,0)});DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);return root; }
        private static void Portal(WrapPanel panel,string badge,string title,string detail,RoutedEventHandler click) { Button b=new Button{Width=285,MinHeight=118,Margin=new Thickness(7),Padding=new Thickness(14),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),HorizontalContentAlignment=HorizontalAlignment.Stretch};StackPanel p=new StackPanel();p.Children.Add(new TextBlock{Text=badge+"   "+title,Foreground=Accent,FontWeight=FontWeights.Bold,FontSize=13,TextWrapping=TextWrapping.Wrap});p.Children.Add(new TextBlock{Text=detail,Foreground=Muted,FontSize=12,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,7,0,0)});b.Content=p;b.Click+=click;panel.Children.Add(b); }
        private static void SmallPortal(Panel p,string title,RoutedEventHandler click) { Button b=new Button{Content=title,Margin=new Thickness(5),Padding=new Thickness(11,7,11,7),Background=Raised,Foreground=Accent,BorderBrush=Border};b.Click+=click;p.Children.Add(b); }
        private static ListBox List() { return new ListBox{Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,BorderThickness=new Thickness(1),FontFamily=new FontFamily("Consolas"),FontSize=12}; }
        private static void OpenList(DockPanel root,IList<object> items) { ListBox list=List();list.ItemsSource=items??new List<object>();root.Children.Add(list); }
        private static void OpenCollection(Window owner,string title,IList<object> items,string note) { Window w=W(owner,"YOMI · "+title,1360,840);DockPanel root=Shell(title,note+"   ·   "+(items==null?0:items.Count)+" retained rows");OpenList(root,items);w.Content=root;w.Show(); }
        private static void TextView(Window owner,string title,string text) { Window w=W(owner,"YOMI · "+title,1380,880);DockPanel root=Shell(title,"Read-only mission representation.");TextBox box=new TextBox{Text=text??"",Margin=new Thickness(18),Background=Surface,Foreground=Text,BorderBrush=Border,FontFamily=new FontFamily("Consolas"),FontSize=13,IsReadOnly=true,AcceptsReturn=true,AcceptsTab=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto};root.Children.Add(box);w.Content=root;w.Show(); }
        private static string Prompt(Window owner,string title,string label,string initial) { Window w=W(owner,"YOMI · "+title,780,310);DockPanel root=Shell(title,label);TextBox box=new TextBox{Text=initial??"",Margin=new Thickness(20,6,20,10),Padding=new Thickness(8),Background=Surface,Foreground=Text,BorderBrush=Border,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=90,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};DockPanel.SetDock(box,Dock.Top);root.Children.Add(box);StackPanel buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(20)};Button ok=new Button{Content="COMMIT",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Green,BorderBrush=Border};Button cancel=new Button{Content="CANCEL",Padding=new Thickness(18,7,18,7),Margin=new Thickness(6),Background=Raised,Foreground=Muted,BorderBrush=Border};string value=null;ok.Click+=delegate{value=box.Text;w.DialogResult=true;w.Close();};cancel.Click+=delegate{w.DialogResult=false;w.Close();};buttons.Children.Add(cancel);buttons.Children.Add(ok);root.Children.Add(buttons);w.Content=root;bool? r=w.ShowDialog();return r==true?value:null; }
        private static Brush B(string hex) { return (Brush)new BrushConverter().ConvertFromString(hex); }
    }
}
